### ISSUE TITLE
magit over tramp keeps asking for passphrase as if ssh-agent weren't there

### ISSUE THREAD

**Issue by zhaojiangbin** [magit/magit#4111] opened 2020-05-12 19:57 UTC
I am using magit over tramp for some git repos. In the remote host (Ubuntu 18.04), I have set up ssh-agent and added a passphrase-protected key. When I do fetch, pull and push, magit should ask me for the passphrase only on the first time.

Instead, magit asks for the passphrase every time I do fetch, pull and push, as if the ssh-agent weren't set up in the remote host.

In comparison, using git on the remote command line works as expected: it only asks for the passphrase for thte first time, until the key expired from the ssh-agent. The ssh-agent is using a lifetime of 1 hour.

When not over tramp, magit works as expected. For example, I also have ssh-agent and passphrase-protected keys set up in my laptop. Magit does not ask me for passphrase over and over when I do fetch/pull/push in git repos that cloned from the same origins.

For what it's worth, I ran the following commands in my laptop:
```
$ ssh remote-host sh -c "export | grep SSH"
export SSH_CLIENT="10.x.x.x 49921 22"
export SSH_CONNECTION="10.x.x.15 49921 10.x.x.7 22"
$ ssh remote-host sh -l -c "export | grep SSH"
export SSH_AUTH_SOCK="/run/user/1000/ssh-agent.socket"
export SSH_CLIENT="10.x.x.15 49904 22"
export SSH_CONNECTION="10.x.x.15 49904 10.x.x.7 22"
```
Could it be that magit somehow missed the SSH_AUTH_SOCK env variable in its remote git processes?

To reproduce the issue, need two machines: a desktop/laptop where you run Emacs and magit from, and a Linux machine, ideally running a recent Ubuntu version such as 18.04, as the remote host where the git clone is.

Also need a GitHub account, or a Git server that allows you to upload SSH keys for password-less logins.

1. In the Linux machine as the remote host, 

  1.1. Set up ssh-agent, create an SSH key pair with a non-empty passphrase. Make sure the ssh-agent is using relative long lifetime (with the -t option), such as an hour at least for testing.

  1.2. Upload the public SSH key to the github account. Or copy the pub key to the Git server using the `ssh-copy-id` command.

  1.3. Clone a repo from github or the Git server over SSH.

  1.4. On command line, run `git fetch` in the repo a few times within, say, 5 minutes. You should be asked for the passphrase on the first time, and only on the first time.

2. In the desktop/laptop, start Emacs with magit,

  2.1. Visit a file remotely in the git repo clone in 1.3. above.

  2.2. Run `magit-status` to bring up the magit-status buffer.

  2.3. In that buffer, press <kbd>f u</kbd> to fetch from origin. Repeat a few times in a row. 

  2.4. Magit asks for the passprase every time. <-- reproduced here

Output from `magit-version`:

```Magit 20200501.2225, Git 2.26.2, Emacs 27.0.90, darwin```

**Comment by tarsius** [comment] 2020-05-12 20:34
Probably a duplicate of #4076.

**Comment by zhaojiangbin** [comment] 2020-05-14 18:33
It turns out that using 'ssh or 'scp as the tramp method does not have this problem, in my tests so far. 

I have the default method changed to 'scpx which was causing the issue. Also tried 'sshx and it didn't work either. Didn't bother with other methods.

What's interesting though, the tramp doc says that both 'sshx and 'scpx open the connections with the "`-l`" switch:
> scpx is useful to avoid login shell questions. It is similar in performance to scp. scpx uses ‘`ssh -t -t host -l user /bin/sh`’ to open a connection. 

> Works like ssh but without the extra authentication prompts. sshx uses '`ssh -t -t host -l user /bin/sh`’ to open a connection with a “standard” login shell.

And I have symlinked `/bin/sh` to bash in my remote host.

Now I have a workaround so feel free to close the issue if you don't think there is much that magit can do or is worth doing.

**Comment by tarsius** [comment] 2020-05-24 10:06
Closing. But I have marked this as something to think about again, eventually.

**Closed** 2020-05-24 10:06 UTC
Labels: .
