### ISSUE TITLE
Can't apply/discard hunk with BOM (Byte Order Mark)

### ISSUE THREAD

**Issue by kostafey** [magit/magit#2832] opened 2016-10-20 14:45 UTC
Magit 20161019.2021, Git 2.10.0.windows.1, Emacs 25.1.1, windows-nt
1. `M-x magit-status`
2. Select hunk, <kbd>k y</kbd>

Here is shorted trace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  set-buffer(nil)
  (save-current-buffer (set-buffer command-buf) (magit-mode-get-buffer (quote magit-status-mode)))
  (let ((it (save-current-buffer (set-buffer command-buf) (magit-mode-get-buffer (quote magit-status-mode))))) (if it (progn (save-current-buffer (set-buffer it) (setq magit-this-error msg)))))
  (if magit-process-raise-error (signal (quote magit-git-error) (list (format "%s (in %s)" msg default-dir))) (let ((it (save-current-buffer (set-buffer command-buf) (magit-mode-get-buffer (quote magit-status-mode))))) (if it (progn (save-current-buffer (set-buffer it) (setq magit-this-error msg))))) (message "%s ... [%s buffer %s for details]" msg (let ((key (and (buffer-live-p command-buf) (save-current-buffer (set-buffer command-buf) (car ...))))) (if key (format "Hit %s to see" (key-description key)) "See")) (buffer-name process-buf)))
  (let ((msg (or (and (buffer-live-p process-buf) (save-current-buffer (set-buffer process-buf) (save-excursion (goto-char ...) (let ... ...)))) "Git failed"))) (if magit-process-raise-error (signal (quote magit-git-error) (list (format "%s (in %s)" msg default-dir))) (let ((it (save-current-buffer (set-buffer command-buf) (magit-mode-get-buffer (quote magit-status-mode))))) (if it (progn (save-current-buffer (set-buffer it) (setq magit-this-error msg))))) (message "%s ... [%s buffer %s for details]" msg (let ((key (and (buffer-live-p command-buf) (save-current-buffer ... ...)))) (if key (format "Hit %s to see" (key-description key)) "See")) (buffer-name process-buf))))
  (if (= arg 0) nil (let ((msg (or (and (buffer-live-p process-buf) (save-current-buffer (set-buffer process-buf) (save-excursion ... ...))) "Git failed"))) (if magit-process-raise-error (signal (quote magit-git-error) (list (format "%s (in %s)" msg default-dir))) (let ((it (save-current-buffer (set-buffer command-buf) (magit-mode-get-buffer ...)))) (if it (progn (save-current-buffer (set-buffer it) (setq magit-this-error msg))))) (message "%s ... [%s buffer %s for details]" msg (let ((key (and ... ...))) (if key (format "Hit %s to see" (key-description key)) "See")) (buffer-name process-buf)))))
  magit-process-finish(1 #<buffer *magit-process: project-jsp> nil "d:/workspace/project-jsp/" [cl-struct-magit-section process nil #<marker (moves after insertion) at 13356 in *magit-process: project-jsp> nil])
  (let* ((process-environment (append (magit-cygwin-env-vars) process-environment)) (default-process-coding-system (magit--process-coding-system)) (flat-args (magit-process-git-arguments args)) (--dash-source-117-- (magit-process-setup magit-git-executable flat-args)) (process-buf (car-safe (prog1 --dash-source-117-- (setq --dash-source-117-- (cdr --dash-source-117--))))) (section --dash-source-117--) (inhibit-read-only t)) (magit-process-finish (apply (function call-process-region) (point-min) (point-max) magit-git-executable nil process-buf nil flat-args) process-buf nil default-directory section))
  (if (file-remote-p default-directory) (progn (magit-start-git (current-buffer) args) (while (and magit-this-process (eq (process-status magit-this-process) (quote run))) (sleep-for 0.005))) (run-hooks (quote magit-pre-call-git-hook)) (let* ((process-environment (append (magit-cygwin-env-vars) process-environment)) (default-process-coding-system (magit--process-coding-system)) (flat-args (magit-process-git-arguments args)) (--dash-source-117-- (magit-process-setup magit-git-executable flat-args)) (process-buf (car-safe (prog1 --dash-source-117-- (setq --dash-source-117-- (cdr --dash-source-117--))))) (section --dash-source-117--) (inhibit-read-only t)) (magit-process-finish (apply (function call-process-region) (point-min) (point-max) magit-git-executable nil process-buf nil flat-args) process-buf nil default-directory section)))
  magit-run-git-with-input("apply" ("--reverse") "-p0" nil "--ignore-space-change" "-")
  magit-apply-patch([cl-struct-magit-section file "folder/file.jsp" #<marker (moves after insertion) at 284 in *magit: project-jsp> #<marker at 332 in *magit: project-jsp> #<marker at 776 in *magit: project-jsp> nil nil nil nil "diff --git  
  magit-apply-hunk([cl-struct-magit-section hunk (nil "-3,7" "+3,6") #<marker (moves after insertion) at 332 in *magit: project-jsp> #<marker at 348 in *magit: project-jsp> #<marker at 571 in *magit: project-jsp> nil nil nil nil nil nil [cl-struct-magit-section file ] nil] "--reverse")
  funcall(magit-apply-hunk [cl-struct-magit-section hunk (nil "-3,7" "+3,6") #<marker (moves after insertion) at 332 in *magit: project-jsp> #<marker at 348 in *magit: project-jsp> #<marker at 571 in *magit: project-jsp> nil nil nil nil nil nil [cl-struct-magit-section file  [cl-struct-magit-section file "folder/file.jsp" #<marker (moves after insertion) at 1267 in *magit: project-jsp> #<marker at 1307 in *magit: project-jsp> #<marker at 6351 in *magit: project-jsp> t nil nil nil "diff --... ] nil] "--reverse")
  (if (eq (magit-diff-type section) (quote unstaged)) (funcall apply section "--reverse") (if (magit-anything-unstaged-p nil (if (eq (progn nil (or (and ...) (signal ... ...)) (aref section 1)) (quote file)) (progn nil (or (and (memq ... cl-struct-magit-section-tags)) (signal (quote wrong-type-argument) (list ... section))) (aref section 2)) (magit-section-parent-value section))) (progn (let ((inhibit-magit-refresh t)) (funcall apply section "--reverse" "--cached") (funcall apply section "--reverse" "--reject")) (magit-refresh)) (funcall apply section "--reverse" "--index")))
  magit-discard-apply([cl-struct-magit-section hunk (nil "-3,7" "+3,6") ] magit-apply-hunk)
  (progn (magit-discard-apply section (quote magit-apply-hunk)))
  (if (magit-confirm (quote discard) "Discard hunk") (progn (magit-discard-apply section (quote magit-apply-hunk))))
  magit-discard-hunk([cl-struct-magit-section hunk (nil "-3,7" "+3,6") #<marker (moves after insertion) at 332 in *magit: project-jsp> #<marker at 348 in *magit: project-jsp> #<marker at 571 in *magit: project-jsp> nil nil nil nil nil nil [cl-struct-magit-section file "folder/file.jsp" #<marker (moves after insertion) at 284 in *magit: project-jsp> #<marker at 332 in *magit: project-jsp> #<marker at 776 in *magit: project-jsp> nil nil nil nil "diff --git folder/file2.jsp folder/file3.jsp\nindex 9b218b0..b883d70 100644\n---...........................] nil])
  (let nil (magit-discard-hunk it))
  (if (null x) (let nil (magit-discard-hunk it)) nil)
  (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunk it)) nil))
  (cond ((eq x (quote region)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-region it)) nil))) ((eq x (quote hunk)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunk it)) nil))) ((eq x (quote hunks)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunks it)) nil))) ((eq x (quote file)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-file it)) nil))) ((eq x (quote files)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-files it)) nil))) ((eq x (quote list)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-files it)) nil))) (t nil))
  (let* ((x (car x))) (cond ((eq x (quote region)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-region it)) nil))) ((eq x (quote hunk)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunk it)) nil))) ((eq x (quote hunks)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunks it)) nil))) ((eq x (quote file)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-file it)) nil))) ((eq x (quote files)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-files it)) nil))) ((eq x (quote list)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-files it)) nil))) (t nil)))
  (if (consp x) (let* ((x (car x))) (cond ((eq x (quote region)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-region it)) nil))) ((eq x (quote hunk)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunk it)) nil))) ((eq x (quote hunks)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-hunks it)) nil))) ((eq x (quote file)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-file it)) nil))) ((eq x (quote files)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-files it)) nil))) ((eq x (quote list)) (let* ((x (cdr x))) (if (null x) (let nil (magit-discard-files it)) nil))) (t nil))) nil)
  (let* ((x (cdr val))) (if (consp x) (let* ((x (car x))) (cond ((eq x (quote region)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote hunk)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote hunks)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote file)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote files)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote list)) (let* ((x ...)) (if (null x) (let nil ...) nil))) (t nil))) nil))
  (cond ((eq x (quote committed)) (let* ((x (cdr val))) (if (consp x) (let* ((x (cdr x))) (if (null x) (let nil (user-error "Cannot discard committed changes")) nil)) nil))) ((eq x (quote undefined)) (let* ((x (cdr val))) (if (consp x) (let* ((x (cdr x))) (if (null x) (let nil (user-error "Cannot discard this change")) nil)) nil))) (t (let* ((x (cdr val))) (if (consp x) (let* ((x (car x))) (cond ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) (t nil))) nil))))
  (let* ((x (car val))) (cond ((eq x (quote committed)) (let* ((x (cdr val))) (if (consp x) (let* ((x ...)) (if (null x) (let nil ...) nil)) nil))) ((eq x (quote undefined)) (let* ((x (cdr val))) (if (consp x) (let* ((x ...)) (if (null x) (let nil ...) nil)) nil))) (t (let* ((x (cdr val))) (if (consp x) (let* ((x ...)) (cond (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (t nil))) nil)))))
  (if (consp val) (let* ((x (car val))) (cond ((eq x (quote committed)) (let* ((x (cdr val))) (if (consp x) (let* (...) (if ... ... nil)) nil))) ((eq x (quote undefined)) (let* ((x (cdr val))) (if (consp x) (let* (...) (if ... ... nil)) nil))) (t (let* ((x (cdr val))) (if (consp x) (let* (...) (cond ... ... ... ... ... ... ...)) nil))))) nil)
  (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x (car val))) (cond ((eq x (quote committed)) (let* ((x ...)) (if (consp x) (let* ... ...) nil))) ((eq x (quote undefined)) (let* ((x ...)) (if (consp x) (let* ... ...) nil))) (t (let* ((x ...)) (if (consp x) (let* ... ...) nil))))) nil))
  (progn (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x (car val))) (cond ((eq x (quote committed)) (let* (...) (if ... ... nil))) ((eq x (quote undefined)) (let* (...) (if ... ... nil))) (t (let* (...) (if ... ... nil))))) nil)))
  (if it (progn (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x (car val))) (cond ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) (t (let* ... ...)))) nil))))
  (let ((it (magit-apply--get-selection))) (if it (progn (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x ...)) (cond (... ...) (... ...) (t ...))) nil)))))
  magit-discard()
  funcall-interactively(magit-discard)
  call-interactively(magit-discard nil nil)
  command-execute(magit-discard)
```

`magit-process.el:`

``` lisp
835 (with-current-buffer command-buf
836                      (magit-mode-get-buffer 'magit-status-mode))
```

fails for nil `command-buf`.

I can't reproduce it for small diffs.

**Comment by tarsius** [comment] 2016-10-20 16:39
The recent "do it in the correct buffer" fixes seem to need some additional tweaking.

**Comment by kyleam** [comment] 2016-10-21 01:24
@kostafey Can you point to a public repo and give an example of a
change that triggers the error for you?  I've tried to reproduce this
(on a GNU/Linux system, Emacs 25.1.1) by deleting all of Org mode's
lisp/org.el, which is over 25k lines.  I can discard that change
without an error.  Perhaps this is platform-specific.

**Comment by kostafey** [comment] 2016-10-21 08:13
@kyleam, I've found a relatively small case - [Switcheroo](https://github.com/kvakulo/Switcheroo). 

`1`. `git clone https://github.com/kvakulo/Switcheroo.git`
`2`. Open `Switcheroo/Core/AppWindow.cs` file.
`3`. Remove the first line. Here is s diff:

```diff
-﻿/*
- * Switcheroo - The incremental-search task switcher for Windows.
+﻿ * Switcheroo - The incremental-search task switcher for Windows.
  * http://www.switcheroo.io/
  * Copyright 2009, 2010 James Sulak
  * Copyright 2014 Regin Larsen
```

`4`. `M-x magit-status`, select hunk, <kbd>k y</kbd>.

Result: `magit-run-git-with-input: Wrong type argument: stringp, nil`

**Comment by tarsius** [comment] 2016-10-21 11:35
I don't know why the required buffer didn't exist anymore in your case, but I have the process code even more forgiving with regards to that. Please confirm that you no longer get this error.

**Comment by kostafey** [comment] 2016-10-21 12:21
I've updated `magit-process.el` according to the last commit. But behavior still unexpected.

`*messages*`:
```
Discard hunk? (y or n) y
@@@ CCC [cl-struct-magit-section hunk (nil -1,5 +1,4) #<marker (moves after insertion) at 182 in *magit: Switcheroo> #<marker at 198 in *magit: Switcheroo> #<marker at 437 in *magit: Switcheroo> nil nil nil nil nil nil [cl-struct-magit-section file Core/AppWindow.cs #<marker (moves after insertion) at 153 in *magit: Switcheroo> #<marker at 182 in *magit: Switcheroo> #<marker at 437 in *magit: Switcheroo> nil nil nil nil diff --git Core/AppWindow.cs Core/AppWindow.cs
index 1566644..5a739dd 100644
--- Core/AppWindow.cs
+++ Core/AppWindow.cs
 nil [cl-struct-magit-section unstaged nil #<marker (moves after insertion) at 132 in *magit: Switcheroo> #<marker at 153 in *magit: Switcheroo> #<marker at 438 in *magit: Switcheroo> nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker (moves after insertion) at 1 in *magit: Switcheroo> nil #<marker at 438 in *magit: Switcheroo> nil nil nil nil nil nil nil ([cl-struct-magit-section branch master #<marker (moves after insertion) at 1 in *magit: Switcheroo> #<marker at 54 in *magit: Switcheroo> #<marker at 132 in *magit: Switcheroo> t nil nil nil nil nil #3 ([cl-struct-magit-section branch origin/master #<marker (moves after insertion) at 54 in *magit: Switcheroo> nil #<marker at 114 in *magit: Switcheroo> t nil nil nil nil nil #5 nil] [cl-struct-magit-section tag v0.9.2 #<marker (moves after insertion) at 114 in *magit: Switcheroo> nil #<marker at 131 in *magit: Switcheroo> t nil nil nil nil nil #5 nil])] #2)] (#1)] (#0)] nil]
@@@ CCC [cl-struct-magit-section hunk (nil -1,5 +1,4) #<marker (moves after insertion) at 182 in *magit: Switcheroo> #<marker at 198 in *magit: Switcheroo> #<marker at 437 in *magit: Switcheroo> nil nil nil nil nil nil [cl-struct-magit-section file Core/AppWindow.cs #<marker (moves after insertion) at 153 in *magit: Switcheroo> #<marker at 182 in *magit: Switcheroo> #<marker at 437 in *magit: Switcheroo> nil nil nil nil diff --git Core/AppWindow.cs Core/AppWindow.cs
index 1566644..5a739dd 100644
--- Core/AppWindow.cs
+++ Core/AppWindow.cs
 nil [cl-struct-magit-section unstaged nil #<marker (moves after insertion) at 132 in *magit: Switcheroo> #<marker at 153 in *magit: Switcheroo> #<marker at 438 in *magit: Switcheroo> nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker (moves after insertion) at 1 in *magit: Switcheroo> nil #<marker at 438 in *magit: Switcheroo> nil nil nil nil nil nil nil ([cl-struct-magit-section branch master #<marker (moves after insertion) at 1 in *magit: Switcheroo> #<marker at 54 in *magit: Switcheroo> #<marker at 132 in *magit: Switcheroo> t nil nil nil nil nil #3 ([cl-struct-magit-section branch origin/master #<marker (moves after insertion) at 54 in *magit: Switcheroo> nil #<marker at 114 in *magit: Switcheroo> t nil nil nil nil nil #5 nil] [cl-struct-magit-section tag v0.9.2 #<marker (moves after insertion) at 114 in *magit: Switcheroo> nil #<marker at 131 in *magit: Switcheroo> t nil nil nil nil nil #5 nil])] #2)] (#1)] (#0)] nil]
Core/AppWindow.cs: patch does not apply ... [See buffer *magit-process: Switcheroo for details]
```

`*magit-process: Switcheroo`:
```
  1 C:/Program Files/Git/mingw64/libexec/git-core/git … apply --reverse -p0 --ignore-space-change -
error: patch failed: Core/AppWindow.cs:1
error: Core/AppWindow.cs: patch does not apply
```

**Comment by kyleam** [comment] 2016-10-21 13:25
@kostafey Thanks for the specific example.  No luck reproducing it on
my end.

**Comment by kostafey** [comment] 2016-10-21 13:41
@tarsius, is there any ideas I can provide some more debug information?

**Comment by tarsius** [comment] 2016-10-21 13:41
"Patch does not apply" when discarding is an expected issue. This can happen if you stage a change, modify the same area again, save, and then try to discard the staged change. In such a case you should *unstage* instead.

The error you posted earlier is about some buffer no longer existing but some code trying to use that buffer. That shouldn't happen and my change above made sure that we don't do that in a few additional places.

**Comment by tarsius** [comment] 2016-10-21 13:42
Make sure that you are really using the latest fix before trying to reproduce the error.

**Comment by kostafey** [comment] 2016-10-21 13:53
> This can happen if you stage a change, modify the same area again, save, and then try to discard the staged change. In such a case you should unstage instead.

It's definitely unstaged:

`*magit: Switcheroo`:
```diff
Unstaged changes (1)
modified   Core/AppWindow.cs
@@ -1,5 +1,4 @@
-﻿/*
- * Switcheroo - The incremental-search task switcher for Windows.
+﻿ * Switcheroo - The incremental-search task switcher for Windows.
  * http://www.switcheroo.io/
  * Copyright 2009, 2010 James Sulak
  * Copyright 2014 Regin Larsen
```

> Make sure that you are really using the latest fix before trying to reproduce the error.

I've used `magit` directly from git (commit `9986334ed20dc85a60e7dd2b4f8083b82c7522da`)

**Comment by tarsius** [comment] 2016-10-21 14:04
I still think we are talking about two completely unrelated issues here. Could you please try to reproduce the initial issue. Then, after you have hopefully confirmed that that no longer is an issued, we can move on to the second issue. The following is about that second issue:

> It's definitely unstaged:

The output you posted does not show whether there also are staged changes. I'm going to assume there are not.

The diff shows that the " *Swicheroo - The incremental-search task switcher for Windows." line is modified, but without showing any changes. This could be because of trailing whitespace being added or removed. Or there could be an issue with line-end encoding, which would explain why the patch does not apply.

**Comment by kostafey** [comment] 2016-10-21 14:18
> I still think we are talking about two completely unrelated issues here. Could you please try to reproduce the initial issue.

Yes, I can't reproduce the initial issue with last magit.

> The output you posted does not show whether there also are staged changes. I'm going to assume there are not.

Yes. There are no any more changes. One unstaged change is alone.

> Or there could be an issue with line-end encoding, which would explain why the patch does not apply.

Looks like it's the exact reason.

**Comment by npostavs** [comment] 2016-10-21 22:45
Actually, it looks like the problem is that there is a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of this file.

**Comment by tarsius** [comment] 2016-10-31 20:26
So, is there anything we can do about that?

**Comment by npostavs** [comment] 2016-10-31 22:22
It seems to work when I change `magit--process-coding-system` to return a utf8 encoding in the `cdr` (i.e., the one used to encode the data sent to git. I guess Emacs puts the BOM back when encoding as utf8? Although I wasn't able to confirm that.)

Maybe we can save the encoding used to decode the diff and re-encode with it when applying? Or maybe save the raw diff data somehow?

**Comment by tarsius** [comment] 2016-11-08 22:21
> Maybe we can save the encoding used to decode the diff and re-encode with it when applying? Or maybe save the raw diff data somehow?

Both seem like reasonable suggestions, and we definitely have to address this at some point, but it seems that this isn't a common issue, so we can let it rest it a bit until the underlying code is ready for such a change.

I plan to do the diff parsing in separate hidden buffers and also use those buffers as a cache. If we want to somehow remember the encoding before that has been implemented, then we should add an additional struct slot, because the value slot is already overloaded too much for diffs.

**Comment by tarsius** [comment] 2017-11-03 14:28
I cannot reproduce this and we have not ever heard from anybody who has a similar issue. I am assuming that this is due to some local coding system misconfiguration and close this.

**Closed by tarsius** 2017-11-03 14:28 UTC
Labels: bug, encoding

**Comment by npostavs** [comment] 2017-11-03 14:34
> I cannot reproduce this

It's been a while since I looked at this, but I suspect it wouldn't show up under GNU/Linux where typically the default encoding is utf8.

**Comment by tarsius** [comment] 2017-11-03 14:38
What is the default on Windoof? Isn't defaulting to utf8 the only sensible thing to do in this day and age, at least in the west? I am fine with telling users who have this issue to use utf8 are live it it.

**Comment by npostavs** [comment] 2017-11-03 18:18
> Isn't defaulting to utf8 the only sensible thing to do in this day and age, at least in the west?

Yes, but nobody said MS-Windows does the sensible thing :/ 

I checked this out a bit more closely, it looks Emacs converts the BOM character to a space with the normal `undecided-unix` value in the cdr of `default-process-coding-system`. When I change to `utf-8-unix` it's okay. On the other hand, doing that gives the problems in #3111, I think.

I tested with the redefinition of `magit-apply-patch`:
```elisp
(defun magit-apply-patch (section:s args patch)
  (let* ((files (if (atom section:s)
                    (list (magit-section-value section:s))
                  (mapcar 'magit-section-value section:s)))
         (command (symbol-name this-command))
         (command (if (and command (string-match "^magit-\\([^-]+\\)" command))
                      (match-string 1 command)
                    "apply"))
         ;; uncomment next line to make it work:
         ;;(default-process-coding-system '(undecided-dos . utf-8-unix))
         )
    (with-current-buffer (get-buffer-create "*patch test*")
      (erase-buffer)
      (setq buffer-file-coding-system 'utf-8)
      (insert patch)
      (magit-run-git-with-input
       "apply" args "-p0"
       (unless (magit-diff-context-p) "--unidiff-zero")
       "--ignore-space-change" "-")
      (call-process-region (point-min) (point-max)
                           "C:/msys64/usr/bin/xxd.exe" t '(t t) t "-"))))
```

Which gave me the following in `*patch test*` when it failed:
```
00000000: 6469 6666 202d 2d67 6974 2043 6f72 652f  diff --git Core/
[...]
00000070: 696e 646f 772e 6373 0a40 4020 2d31 2c32  indow.cs.@@ -1,2
00000080: 202b 3120 4040 0a2d 202f 2a0a 2d20 2a20   +1 @@.- /*.- * 
[...]
```
and this when I changed to use the `utf-8-unix` encoding:
```
00000000: 6469 6666 202d 2d67 6974 2043 6f72 652f  diff --git Core/
[...]
00000070: 696e 646f 772e 6373 0a40 4020 2d31 2c32  indow.cs.@@ -1,2
00000080: 202b 3120 4040 0a2d efbb bf2f 2a0a 2d20   +1 @@.-.../*.- 
[...]
```

I note that 
```elisp
(let ((encoded (encode-coding-string "\ufeff" 'undecided-unix))
      (hex ""))
  (dotimes (i (length encoded))
    (setq hex (format "%s%02X" hex (aref encoded i))))
  hex) ;=> "EFBBBF"
```
so I'm not sure why Emacs loses the BOM when talking to processes.

**Comment by tarsius** [comment] 2017-11-05 22:20
@npostavs Thanks a lot for looking into issues like these!

(And feel free to reopen them if you think that there still is something that can/should be done on Magit's side.)

**Comment by npostavs** [comment] 2017-11-07 17:10
> (And feel free to reopen them if you think that there still is something that can/should be done on Magit's side.)

Things clicked after my latest q/a with Eli, I think I can see what magit can do to work around the not-so-great encoding situation on Windows now.

@kostafey please try the patch in #3250.

**Comment by tarsius** [comment] 2017-11-17 10:55
@kostafey Please check whether this fix works for you.
