### ISSUE TITLE
git lfs push doesn't work inside magit

### ISSUE THREAD

**Issue by bgvianyc** [magit/magit#2413] opened 2015-11-28 02:06 UTC
Currently pushing inside of magit fails on repo's that utilize git-lfs. This could be partially emacs related as pushing does not work from the eshell either.

**Comment by npostavs** [comment] 2015-11-28 02:21
> does not work from the eshell either.

Are you on OSX by any chance? Does Emacs use the same git version as what's used from the shell?

**Comment by bgvianyc** [comment] 2015-11-28 02:29
No, this is being run on a ubuntu 14.04 machine.

**Comment by tarsius** [comment] 2015-11-28 11:28
What about the second question?

**Comment by tarsius** [comment] 2015-11-28 11:56
I've just given git-lfs a spin and it seems to work just fine (and I see no reason why it wouldn't just work™). In what way does pushing fail for you? Are there any error messages (try <kbd>$</kbd>).

**Comment by tarsius** [comment] 2015-11-28 12:24
Hm. Just discovered that "works" might be the wrong term. It appears that `git-lfs` for me just doesn't do anything at all. So it's no wonder that pushing worked, after all it just pushed those binary files as usual, because they were tracked as usual. Maybe that's the issue you are having?

I also cannot read the documentation (e.g. to figure out if I am doing something wrong) because of https://github.com/github/git-lfs/issues/719. These are the commands I ran:

```
git init testibus
cd testibus
cp /foobar/image.png .
git lfs track '*.png'
git add image.png
git commit -m init
```

after that `git lfs ls-files` shows no output.

**Comment by tarsius** [comment] 2015-11-28 12:42
Aha "Basic tutorials miss[es] key point about `git lfs init`" https://github.com/github/git-lfs/issues/719. When the introductory misses an essential step *and* the manpages are empty, then that of course makes it kinda hard to figure out how to use this thing... (To be fair, it should have been obvious to me that some setup would be required, then again how should a *beginner* know that?!)

**Comment by tarsius** [comment] 2015-11-28 12:44
Anyway, now that I succeeded adding a binary file using lfs I was able to reproduce your issue:

```
git … push -v origin master:refs/heads/master
Pushing to git@github.com:tarsius/foo.git
panic: runtime error: makeslice: len out of range

goroutine 66 [running]:
strings.Repeat(0x8ff5f0, 0x1, 0xffffffffffffffd8, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:464 +0x5f
github.com/github/git-lfs/lfs.(*ProgressMeter).update(0xc82025e000)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/progress_meter.go:140 +0x7c1
github.com/github/git-lfs/lfs.(*ProgressMeter).writer(0xc82025e000)
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/progress_meter.go:106 +0x30
created by github.com/github/git-lfs/lfs.(*ProgressMeter).Start
	/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/progress_meter.go:57 +0x60

... many more lines ...
```

I am inclined to blame that on `git-lfs`.

**Comment by tarsius** [comment] 2015-11-28 12:46
I succeeded pushing on the command line, which revealed that a spinner is used, maybe that blows up when no spinner can be used (because no pty). Maybe it can be told not to use a spinner, but without documentation I cannot figure that out.

**Comment by bgvianyc** [comment] 2015-11-28 12:52
Yes, emacs does use the same git version 2.6.3

**Comment by tarsius** [comment] 2015-12-04 14:46
I have experimented some more.

```
git init /tmp/lfs-test
cd /tmpf/lfs-test
git remote add origin git@github.com:me/lfs-test.git
git lfs install
git lfs track '*.png'
cp /path/to/image.png .
git add image.png
git commit -m msg
```

After that setup, this succeeds:

```
setsid sh -c "tty; git push origin master" < /dev/null > log 2>&1
```

and so does

```lisp
(let ((default-directory "/tmp/lfs-test/")
      (process-connection-type nil)) ; use pipe
  (with-current-buffer (get-buffer-create "*git-lfs*")
    (erase-buffer)
    (pop-to-buffer (current-buffer))
    (start-process "git-lfs" (current-buffer) "git" "push")))
```

but this does not

```lisp
(let ((default-directory "/tmp/lfs-test/")
      (process-connection-type t)) ; use pty
  (with-current-buffer (get-buffer-create "*git-lfs*")
    (erase-buffer)
    (pop-to-buffer (current-buffer))
    (start-process "git-lfs" (current-buffer) "git" "push")))
```

But that's essentially what Magit does. We do need to use a pty so that we can read passwords from the user.

**Comment by tarsius** [comment] 2015-12-04 14:48
Could you please ask the `git-lfs` maintainers for help.

**Comment by bgvianyc** [comment] 2015-12-04 19:31
try building from this branch and see if this solves the issue: https://github.com/github/git-lfs/pull/883

**Comment by tarsius** [comment] 2015-12-04 20:12
That sounds promising indeed.

**Comment by tarsius** [comment] 2015-12-06 23:47
Until such a fix is installed you can just set `magit-process-connection-type` to nil. But that means that Git will no longer be able to ask you for a password or passphrase. You'll have to either make sure that an `ssh-agent` is running and knows about the relevant keys, and that Emacs knows about the `ssh-agent`. Or you could use [git-gui--askpass](https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows#git-gui--askpass).

**Closed by tarsius** 2015-12-06 23:47 UTC
Labels: bug upstream
