### ISSUE TITLE
error installing magit lisp nesting exceeds max-lisp-eval-depth

### ISSUE THREAD

**Issue by kirk86** [magit/magit#3980] opened 2019-10-06 16:12 UTC
Today I received this error when installing magit

![image](https://user-images.githubusercontent.com/2902390/66271966-cec20300-e85b-11e9-801e-308c8b44a4db.png)

What  I don't understand is why is trying to install helm or helm-org since I don't use them or explicitly installed them. 

This emacs config only has use-package and installs magit nothing else at the moment. I don't understand which pkg is bringing helm as dependency?

Any ideas what's going wrong here?

**Comment by tarsius** [comment] 2019-10-06 17:04
I don't know what's going on. I suspect `package.el` somehow got into a wacky state. I recommend you remove the `elpa` repository, remove all `:ensure t` from your init file, restart Emacs, and then *manually* (using `package-install`) install the desired packages.

**Comment by kirk86** [comment] 2019-10-06 17:30
@tarsius Is it common to have `package.el` be such wacky, that would prevent me for building a config that is shareable and usable across devices.

> I recommend you remove the `elpa` repository, remove all `:ensure t` from your init file, remove `init.elc`, restart

That's what I previously did but had on `ini.el` only 
```
(use-package magit
 :ensure t
  :bind ("C-x g" . magit-status))
```
BTW this only happens with the magit package once I comment the magit package code above everything else works as it should, no problems what so ever.

**Comment by npostavs** [comment] 2019-10-06 17:50
I guess it will be fixed by this (when the change propagates to MELPA):
https://github.com/emacs-helm/helm/pull/2205

Similar reports:

https://emacs.stackexchange.com/questions/52995/installing-helm-projectile-results-in-mapc-lisp-nesting-exceeds-max-lisp-eval
https://old.reddit.com/r/emacs/comments/de602o/cant_install_or_upgrade_packages/

**Comment by tarsius** [comment] 2019-10-06 18:14
In particular https://lists.gnu.org/r/help-gnu-emacs/2019-10/msg00025.html. In other words this has nothing to do with magit but is caused by a bug in async and circular dependencies of helm.

**Closed by tarsius** 2019-10-06 18:14 UTC
Labels: invalid
