### ISSUE TITLE
Emacs hangs on staging chunks over Tramp 

### ISSUE THREAD

**Issue by impaktor** [magit/magit#4720] opened 2022-07-05 07:10 UTC
I've noticed this a long time (+1 year, ever since I started relying on tramp), on several computers, and emacs versions.

In M-x magit-status, I select the chunks I want to stage, of a file, minibuffer will say "Git finished" after a few seconds, but then I must C-g C-g C-g C-g to get emacs responsive again, and re-enter magit-status to stage next chunk.

- I rarely stage whole file, but when I do this, it works (usually/always(?), I believe.
- I just tried staging a subset of a chunk (C-spc), worked the first time, but not the second, in which case it freezes on "git finished" message. 
- My version:
`Magit 20220625.1219 [>= 3.3.0-git], Git 2.30.2, Emacs 27.1, gnu/linux`

I just tried reproducing this on a "clean" emacs (emacs -Q with magit), and I could stage 2 chunks, but when I try to stage a single line in a third chunk emacs freezes for minutes (I gave up and did C-g after a while). Doesn't look like emacs is using 100% CPU, so there's something else causing it to lock up.

**Comment by kyleam** [comment] 2022-07-06 02:00
Hmm, it certainly isn't zippy on my end, but I'm not able to trigger a hang when staging region hunks (tried five stage operations in a row).

**Comment by impaktor** [comment] 2022-07-06 19:03
Is there some code I could run in the background to monitor things to help debug?
I guess not, since Emacs doesn't multithread, and debug-on-error doesn't help, since it doesn't throw an error.

**Comment by tarsius** [comment] 2022-09-14 16:55
Try to use the profiler or debug statements to see where the hang happens.

**Comment by impaktor** [comment] 2022-11-15 12:39
Sorry for silence, I have not forgotten, more a question of me not knowing exactly what to do to further diagnose this. I've been running the emacs profiler for an hour or two today. Result below. (I did a lot of magit today, picking chunks and files for stageing which is very slow. Also I note just tab compleation in terminal (outside of emacs) on e.g. git branch name can take seconds, so maybe it's my git that's slow and not magit? (Often when stageing chunks I get "git finished" in mini-buffer, yet it keeps hanging for a long time and when I C-g to abort I see in mini-buffer: `error in process sentinel: Quit: ""`).

```
- command-execute                                              571538  86%
 - call-interactively                                          571483  86%
  - funcall-interactively                                      555432  83%
   + magit-discard                                             299647  45%
   + counsel-find-file                                         138882  20%
   + ivy-switch-buffer                                          31150   4%
   + magit-status                                               19231   2%
   + save-buffer                                                19200   2%
   + magit-stage                                                11157   1%
   + with-editor-finish                                          8596   1%
   + magit-commit-create                                         5963   0%
   + avy-goto-line                                               5036   0%
   + markdown-electric-backquote                                 2900   0%
   + counsel-M-x                                                 2733   0%
   + magit-stash-drop                                            1829   0%
   + magit-next-line                                              928   0%
   + isearch-printing-char                                        903   0%
   + magit-previous-line                                          812   0%
   + isearch-repeat-forward                                       704   0%
   + previous-line                                                690   0%
   + next-line                                                    675   0%
   + scroll-down-command                                          586   0%
   + undo-tree-visualize-undo                                     487   0%
   + magit-file-rename                                            476   0%
   + magit-stash-show                                             395   0%
   + undo-tree-visualize-redo                                     300   0%
   + self-insert-command                                          262   0%
   + scroll-up-command                                            240   0%
   + isearch-forward                                              225   0%
   + magit-diff-visit-file                                        206   0%
   + open-line                                                    131   0%
     recenter-top-bottom                                          129   0%
   + org-self-insert-command                                      119   0%
   + kill-region                                                  116   0%
   + magit-section-toggle                                         107   0%
   + yank                                                          75   0%
   + undo-tree-visualize                                           64   0%
   + ibuffer-other-window                                          56   0%
   + isearch-repeat-backward                                       46   0%
   + kill-ring-save                                                46   0%
   + magit-commit                                                  34   0%
   + isearch-yank-word-or-char                                     28   0%
   + jao-toggle-selective-display                                  27   0%
   + kill-line                                                     22   0%
   + org-yank                                                      22   0%
   + move-end-of-line                                              19   0%
   + handle-focus-out                                              15   0%
   + org-cycle                                                     14   0%
   + backward-kill-word                                            11   0%
   + kill-word                                                     10   0%
   + org-kill-line                                                 10   0%
   + isearch-delete-char                                            9   0%
   + handle-focus-in                                                9   0%
   + backward-page                                                  9   0%
   + org-return                                                     7   0%
   + org-open-line                                                  6   0%
   + set-mark-command                                               6   0%
   + markdown-outdent-or-delete                                     4   0%
   + other-window                                                   3   0%
   + magit-copy-buffer-revision                                     3   0%
   + yank-pop                                                       3   0%
   + org-delete-backward-char                                       3   0%
   + newline-and-indent                                             2   0%
     delete-backward-char                                           2   0%
   + kill-buffer                                                    2   0%
   + delete-rectangle                                               1   0%
   + undo-tree-undo                                                 1   0%
  - byte-code                                                   14023   2%
   + read-file-name                                              5403   0%
   + magit-read-stash                                            3634   0%
   + magit-toplevel                                              2256   0%
   + magit-read-file                                             2095   0%
   + read-number                                                  577   0%
   + magit-file-at-point                                           52   0%
   + magit-diff-arguments                                           5   0%
   + expand-file-name                                               1   0%
  - ivy-completing-read                                          2020   0%
   - ivy-read                                                    2020   0%
    + read-from-minibuffer                                         69   0%
    + ivy--reset-state                                              3   0%
    if                                                              2   0%
- ...                                                           25861   3%
   Automatic GC                                                 25817   3%
 + counsel-emacs-url-p                                             33   0%
 + magit-list-refs                                                  8   0%
 - tramp-handle-file-in-directory-p                                 2   0%
  - tramp-equal-remote                                              2   0%
   - file-remote-p                                                  2   0%
    - tramp-file-name-handler                                       2   0%
     - apply                                                        2   0%
      - tramp-sh-file-name-handler                                  2   0%
       - apply                                                      2   0%
        - tramp-handle-file-remote-p                                2   0%
         - expand-file-name                                         2   0%
          - tramp-file-name-handler                                 2   0%
           - tramp-find-foreign-file-name-handler                   2   0%
            - tramp-smb-file-name-p                                 1   0%
             + and                                                  1   0%
            - tramp-ftp-file-name-p                                 1   0%
             + and                                                  1   0%
 - #<compiled 0x1fffee8bb275>                                       1   0%
  - transient-format                                                1   0%
   + apply                                                          1   0%
+ flycheck-perform-deferred-syntax-check                        12129   1%
+ flycheck-handle-signal                                        11170   1%
+ timer-event-handler                                           10183   1%
+ erc-server-filter-function                                     8546   1%
+ redisplay_internal (C function)                                5947   0%
+ #<lambda 0x25dd9bd69cea4>                                      5838   0%
+ #<compiled 0x1fec1afcb1e1>                                     4988   0%
+ beacon--post-command                                           1574   0%
+ #<lambda 0x25dd9bd69cea4>                                      1419   0%
+ jit-lock--antiblink-post-command                                673   0%
+ djcb-set-cursor-according-to-mode                               639   0%
+ company-post-command                                            629   0%
+ magit-section-post-command-hook                                 597   0%
+ gui-set-selection                                                89   0%
  mouse-fixup-help-message                                         41   0%
+ yas-maybe-expand-abbrev-key-filter                               36   0%
+ beacon--vanish                                                   26   0%
```

**Comment by koen-vg** [comment] 2023-02-03 10:21
Ah right, I see that I missed this issue somehow, that's silly. Although the behaviour I'm seeing seems slightly different, in that:
(a) Magit hangs *every time* I try to stage a hunk,
(b) Even after quitting, the hunk is still not staged. I don't see any way of staging any hunks currently.

Should I also give the profiler a go to see where things might be going wrong? Other advice?

I'm using up-to-date master branch versions of magit and emacs. Would it be useful at all to attempt bisecting the issue to see where it was introduced? For me it seems to have been introduced relatively recently.

To complicate matters further, I can only reproduce the issue on my desktop, whereas I cannot on my laptop, even though the emacs and magit versions are the same. Only difference is that I use pgtk-emacs on the laptop. Operating systems are also different, using Debian and Fedora respectively.

**Comment by impaktor** [comment] 2023-02-03 10:43
@koen-vg Yeah, sounds like a different bug. I'd suggest opening a new issue, and both profiler and bisect sounds like useful things to try.

**Comment by koen-vg** [comment] 2023-02-03 10:52
Well I'll see what I can do. I already opened a new issue (https://github.com/magit/magit/issues/4870) which was closed as a duplicate of this one.

Small update: I did try with both the X and pgtk builds of emacs on the same machine where I get this problem, and at least that doesn't seem to change anything (the bug happens in both).

**Comment by tarsius** [comment] 2023-02-03 11:10
> Other advice?

Try to reproduce it without Magit. Write some code that is very close to what Magit would do, but which stands on its own. Then maybe even turn that into a test for Tramp. It is probably an issue in Tramp. If you make it easy for him to reproduce the issue, then it might become easier for him to fix it. Actually, before writing a new Tramp test, run the existing tests and see if any, expected or not, failures could be related to this.

**Comment by koen-vg** [comment] 2023-02-03 11:55
That's useful advice, thanks! I will try to give that a shot.

**Comment by Phundrak** [comment] 2023-02-22 13:59
I am currently experiencing this issue too, I tried reverting to previous commits, thinking it may have been a bug introduced in a somewhat recent one, but that is evidently not the case as Magit still hangs while running a version from last November, and I’m sure it was running fine at that time. I strongly doubt we’ll be able to find anything using a git bisect on Magit.

My guess is this is actually an Emacs 30.0.50 bug or change in its behaviour, since both koen-vg (as per the description of his original issue) and I are on master. My current build of Emacs dates from February 15th, I’ll see if the problem solved itself with newer versions as soon as I can (i.e. when straight's issue 1053 is fixed).

**Comment by Phundrak** [comment] 2023-02-22 14:32
I could upgrade Emacs to commit https://github.com/emacs-mirror/emacs/commit/8d8464bd5a98598e7a6fe63370545c7f07574926 (the commit before straight breaks, [savannah version of the link](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8d8464bd5a98598e7a6fe63370545c7f07574926)) and the issue with Magit seems to no longer be here, I can stage chunks again over Tramp (in my case, using yadm [as instructed in their documentation](https://github.com/TheLocehiliosan/yadm/blob/master/yadm.md?plain=1#L119))

**Comment by aarnej** [comment] 2023-02-25 18:29
I did some bisecting and I think the Emacs commit that broke Magit staging/reversing over Tramp is https://github.com/emacs-mirror/emacs/commit/8c6a4639318f09720cda295e6a93677153046d84

I'm still in the process of understanding what that commit actually does but it is not very long so an expert might be able to figure out why Magit over Tramp would break because of it.

The test I used when bisecting was: 
1. View a commit in Magit from a repo over Tramp
2. Try to reverse a hunk from a file in the commit (not the whole file) with the key "v". 

It got stuck on every commit after the afore mentioned one.

**Comment by benjaminor** [comment] 2023-03-10 07:58
I've experienced the same issue, it's caused by using
`(tramp-send-command
				 v "stty -icrnl -icanon min 1 time 0")` for non-Darwin remote hosts in the commit @aarnej  references:

> I did some bisecting and I think the Emacs commit that broke Magit staging/reversing over Tramp is [emacs-mirror/emacs@8c6a463](https://github.com/emacs-mirror/emacs/commit/8c6a4639318f09720cda295e6a93677153046d84)

If this function changed in the commit, `tramp-sh-handle-make-process` uses `(tramp-send-command
				 v "stty -icrnl")` as before for non-Darwin hosts, it works again.

**Comment by tarsius** [comment] 2023-03-10 10:05
Thanks for the information; it should help others with the same issue, who happen to stumble over this thread.

I would [still](https://github.com/magit/magit/issues/4720#issuecomment-1415722186) encourage you to bring that to the attention of Tramp's maintainer.

**Comment by benjaminor** [comment] 2023-03-10 10:44
Opened upstream bug to address this: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62093

**Comment by Mr-Dispatch** [comment] 2023-04-04 08:47
The referenced upstream issue is now stuck on "I'm not a magit user, can someone give me the commands to reproduce it", so if anyone can...

**Comment by smcgivern** [comment] 2023-04-18 11:32
Thanks for filing the upstream report! I was able to work around this (in a terrible way) by just replacing `tramp-sh-handle-make-process` with the [old version](https://github.com/emacs-mirror/emacs/blob/0820a81ec7a1dcd421b3eec345a38d8405ee00a0/lisp/net/tramp-sh.el#L2808-L3067), using `(advice-add ... :around ...)` and ignoring the original functio entirely.

**Comment by DerickEddington** [comment] 2023-06-23 23:21
Here is my simpler hack-around:
https://github.com/DerickEddington/dotfiles/blob/fd40e7690fd4c49c5055eee34ce13a100e5beded/.emacs.d/init/tramp.el#L7-L19

**Comment by sugitach** [comment] 2023-09-01 07:50
I started using emacs30 and encountered the same problem.
I applied DerickEddington's patch, which worked for a linux host (ubuntu20.04) but not for a remote machine on MacOS 13.5.

**Comment by DerickEddington** [comment] 2023-09-03 19:17
Maybe it didn't work with MacOS because TRAMP handles Darwin specially:
https://git.savannah.gnu.org/cgit/tramp.git/tree/lisp/tramp-sh.el?id=afe72c55225d411eec4694065eace6a16b9c0526#n3091

That different string argument to `tramp-send-command` would prevent my hack from adjusting the argument (to remove the `"-icanon min 1 time 0"` part) as needed for this issue.

My hack could easily be modified to also detect that slightly different string used with Darwin (`"stty -icanon min 1 time 0"`) and replace it with: `"stty"`.  @sugitach  

I didn't try to address this because a comment above seemed to imply that it's only non-Darwin hosts that need a workaround, and I've not tried with MacOS hosts.  If I remember correctly, I've used it with Ubuntu, NixOS, a few other Linux distros, Solaris (OpenIndiana) 10 & 11, and FreeBSD 12 & 13.

**Comment by sugitach** [comment] 2023-09-08 02:15
@DerickEddington Thanks a lot.

Maybe I'm hot with this one. I think it would be smarter if so replacing with a regular expression.
```
(defun my--tramp-send-command--workaround-stty-icanon-bug (conn-vec orig-command &rest args)
  "See: https://github.com/magit/magit/issues/4720"
  (let ((command
         (cond (string= "stty -icrnl -icanon min 1 time 0" orig-command) "stty -icrnl")
               (string= "stty -icanon min 1 time 0" orig-command) "stty")
               (t orig-command))))
    (append (list conn-vec command) args)))
```

**Comment by tusharhero** [comment] 2023-12-22 13:16
> Here is my simpler hack-around: https://github.com/DerickEddington/dotfiles/blob/fd40e7690fd4c49c5055eee34ce13a100e5beded/.emacs.d/init/tramp.el#L7-L19

Thank you. It is working for me.

**Comment by prashantvithani** [comment] 2023-12-29 16:20
There's an update to the bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62093

It seems the new variable `tramp-pipe-stty-settings` was added in the recent commit https://github.com/emacs-mirror/emacs/commit/2a1a7a8524c0307c09c91e89816b2b2b8bfb85bc. Setting it to empty string solves it.

```elisp
(setq tramp-pipe-stty-settings "")
```

**Comment by tarsius** [comment] 2024-01-02 14:06
I've now pushed a fix for this issue. For it to be effective, you have to update to tramp >= 2.6.2.

Thanks to everyone involved in fixing this!

Please let me know if you find any issues with this fix.

**Closed by tarsius** 2024-01-02 14:06 UTC
Labels: bug unconfirmed, area: tramp

**Comment by impaktor** [comment] 2024-01-02 14:33
I suspect there were many unrelated things mentioned in this issue, but I'm not using Tramp atm, so I can't verify if the issue is still there, but either way, thanks for looking into it and for the fine work done on magit.

If I encounter it again, I'll open a new issue and reference this one.

**Comment by lckarssen** [comment] 2024-01-10 11:10
Thanks for the fix! :pray: 

I hadn't used Magit over Tramp in a while, but got bitten by this bug today. After upgrading Magit and Tramp, all is fine.
