### ISSUE TITLE
Bad file descriptor error when creating stash

### ISSUE THREAD

**Issue by bjpbakker** [magit/magit#2633] opened 2016-05-02 22:07 UTC
When creating a stash I got the following error.

```
magit-stash-create: Cannot create temporary name for prefix: bad file descriptor, index.magit.
```

When debugging the issue I found that a macro `magit-with-temp-index` is used that calls `make-temp-name` with a relative file prefix. According to the docs of `make-temp-name` the given prefix should be an absolute file name.

The offending line is at: https://github.com/magit/magit/blob/50a7f49b8f9e9f42f02aa3b2304f5c9e75267885/lisp/magit-git.el#L1165

Stashing works again when I rewrite this to

```
(make-temp-name (magit-git-dir "index.magit."))
```

As I'm unsure if that would impact working with remote repositories, I didn't file a PR. Please let me know if you'd like me to.

**Comment by kyleam** [comment] 2016-05-02 22:28
Duplicate of #2624.

There is currently an open [Emacs bug][url] on this.

> According to the docs of make-temp-name the given prefix should be
> an absolute file name.

True.  Moving the git directory expansion inside the `make-temp-name`
seems appropriate, but based on that bug report, I don't think
`make-temp-name` is expected to fail like this even if a full path
isn't passed.  It seems to be specific to the trailing period and
perhaps OS X.

Are you on OS X?

[url]: http://lists.gnu.org/archive/html/bug-gnu-emacs/2016-04/msg00837.html

**Comment by bjpbakker** [comment] 2016-05-02 22:36
Yes I'm on OS X. I am on Emacs 24.5 through, not on 25.

To me the trailing dot seems not to be a problem. When passing in an absolute filename with a trailing dot `make-temp-name` returns a temp file name with that prefix (including the dot).

E.g. `(make-temp-name "/tmp/index.magit.")` returns `"/tmp/index.magit.70601hrO"`

Also `(make-temp-name "magit")` gets the bad file descriptor error.

**Comment by kyleam** [comment] 2016-05-02 22:54
> To me the trailing dot seems not to be a problem.

Interesting.

@jwiegley, is the trailing dot necessary to trigger your error?

**Comment by jwiegley** [comment] 2016-05-02 22:58
Both `/tmp/magit` and `/tmp/magit.` work fine.  Without `/tmp/`, both give the bad descriptor error.

**Comment by kyleam** [comment] 2016-05-02 23:50
> Both /tmp/magit and /tmp/magit. work fine. Without /tmp/, both give
> the bad descriptor error.

OK, thanks.

@bjpbakker, I think your suggestion to move `magit-git-dir` inside the
`make-temp-name` call would work fine for remote files.  That doesn't
explain why `make-temp-name` only seems to signal an error on OS X,
but it does seem like the appropriate thing to do anyway based on
`make-temp-name`'s docstring.

**Comment by bjpbakker** [comment] 2016-05-03 08:23
@kyleam thanks for helping out. I suppose you don't want a PR for this one change :)

**Comment by kyleam** [comment] 2016-05-03 16:11
> I suppose you don't want a PR for this one change :)

Sure, please open a PR.  Single changes often involve a lot of
debugging, so it's nice to give you credit for that.  Plus, the commit
message for this one should explain the motivation since it's not as
straightforward as "magit is calling this function wrong and seeing
the expected error".

**Closed** 2016-05-04 02:27 UTC
