### ISSUE TITLE
Commit limit "Trace line evolution" not resettable

### ISSUE THREAD

**Issue by theldoria** [magit/magit#3800] opened 2019-03-22 07:12 UTC
I set a trace limit in the log transient and viewed the log. Btw, that's a very nice view 👍  :-).
Key sequence so far: `l`, `-L` + file + `150`, `l`

Then I unset the trace limit (`-L`) and the transient does not show the limit. But the log is still using the limit. Reopening the transient shows the limit again.
Key sequence: `l`, `-L`, `l`

A limit to a specific author, on the other hand, works well.

> Magit 20190311.1451, Git 2.21.0.windows.1, Emacs 25.3.1, windows-nt

**Comment by tarsius** [comment] 2019-03-22 12:06
I am afraid I don't understand your description of the problem; in particular the second paragraph. Is its second sentence misplaced?

1. Show a trace log. `l -L foo RET 1-2 RET`.
2. Enter log transient again `l`.
3. Disable `-L` argument by pressing `-L`. It appears to me that you might expect the log to be updated at this point but it isn't and that is the intended behavior.
4. Replace the log with the selected arguments using `l`. The log is recreated and the lack of the `-L` argument is being taken into account as expected.

By the way, to change the log arguments of the log being shown in the current buffer you should use `L ... g` instead.

Also you can create a log that uses `-L` more easily by selecting text in a file-visiting buffer and then pressing `C-c M-g l`. Or you could use `C-c M-g t` (without a region).

**Comment by theldoria** [comment] 2019-03-23 17:21
> * Show a trace log. `l -L foo RET 1-2 RET`.
> * Enter log transient again `l`.
> * Disable `-L` argument by pressing `-L`. It appears to me that you might expect the log to be updated 

at this point but it isn't and that is the intended behavior.
The transient does SHOW the removement of `-L` the in the transient, but...
> * Replace the log with the selected arguments using `l`. The log is recreated and the lack of the `-L` argument is being taken into account as expected.

The log is still with the old `-L`.
Reopening the log transient shows the `-L` option again.

You see, the `-L` option somehow got persistent and completely unremovable.

I now tried to reproduce the issue with my Linux box (with identical configuration), but the problem is not present there. It exists, however, on my Windows box. I am going to try to find a way to narrow it more down to the origin of the issue.

> By the way, to change the log arguments of the log being shown in the current buffer you should use L ... g instead.

Nice to know...

> Also you can create a log that uses -L more easily by selecting text in a file-visiting buffer and then pressing C-c M-g l. Or you could use C-c M-g t (without a region).

Cool :-)

**Comment by theldoria** [comment] 2019-03-25 08:57
On Windows the issue occurs also with `-Q`, so I guess it's not my configuration.

I also realized that you can set new `-L` options (other region or file), but you can not reset them.

I can not easily dig deeper without your aid, since I do not yet understand good enough how `transient` works. I tried to understand `magit-log:-L`, but I need more for that.
What are my debug options from here? I am going to invest more time, if there is nothing trivial.

**Comment by tarsius** [comment] 2019-03-25 11:28
Wait I bit before you invest too much time. I'll try to finish my work on #3750 this week and that's likely to affect this issue.

**Comment by tarsius** [comment] 2019-04-18 16:50
I have completely refactored this and merged the result into `master` yesterday. Please try to reproduce the issues again.

**Comment by tarsius** [comment] 2019-04-24 12:25
Please let us know if you can still reproduce this.

**Closed by tarsius** 2019-04-24 12:25 UTC
Labels: needinfo
