### ISSUE TITLE
Add `--follow-tags` support to push window

### ISSUE THREAD

**Issue by samangh** [magit/magit#3533] opened 2018-08-01 19:56 UTC
I would love have an additional swicth for the `--follow-tags` and `--no-follow-tags` arguments to be added to the push pop up.

This command essentialy pushes any new tags associated with a commit. According to the [git-push documentation](https://git-scm.com/docs/git-push#git-push---follow-tags):

> Push all the refs that would be pushed without this option, and also push annotated tags in `refs/tags` that are missing from the remote but are pointing at commit-ish that are reachable from the refs being pushed.

This would save me from having to push twice after every release (i.e. once for the commit, and once for the tag).

**Comment by kyleam** [comment] 2018-08-01 20:17
This is a duplicate of gh-2919.  The [wiki] shows how you can add this to the push popup.  You could also set `push.followTags`.

[wiki]: https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands#add-argument---follow-tags

**Closed by kyleam** 2018-08-01 20:17 UTC

**Comment by samangh** [comment] 2018-08-01 20:28
I see. Thanks for the quick reply. I just noticed #2941, which sounds very useful.

Keep up the good work, magit is indispensable to my daily routine :-).
