### ISSUE TITLE
magit-stash cannot read tree <hash>

### ISSUE THREAD

**Issue by thepickle** [magit/magit#2534] opened 2016-02-01 19:23 UTC
When I try to stash (`zz` from the `magit-status` buffer) in a dirty working tree, it fails

My mini-buffer says something like
`Cannot read tree 0f1721ce2fa0db315de1d592e8d96daa4f63a232`

This will also happen, when trying to revert (no-commit) a previous commit in the log history (v from `magit-log`)

**Comment by npostavs** [comment] 2016-02-02 18:11
Works for me. Can you post output from `M-x magit-version`, and also OS version.

Maybe it only happens in certain repositories?

**Comment by thepickle** [comment] 2016-02-02 19:22
Windows 7 Enterprise
Magit 20160130.649, Git 1.9.5.msysgit.1, Emacs 24.5.1
I should also note I have cygwin binaries in my path.  I'll try it without that & comment again.

**Comment by thepickle** [comment] 2016-02-02 19:25
It works if I remove the cygwin path from PATH.
Will this still be fixed?

**Comment by npostavs** [comment] 2016-02-02 19:45
Ah, interesting, confirmed. Also with `Git 2.7.0.windows.1`.

**Comment by thepickle** [comment] 2016-02-02 19:48
Yes, I should've mentioned that I tried `git-for-windows 2.x` with the same result.

**Comment by npostavs** [comment] 2016-02-02 20:02
> interesting

Well, maybe it's not that interesting. The problem is simply that when magit sees `mount` in the path, it assumes you're using cygwin (or msys2) git, and sets up `magit-cygwin-mount-points` to translate back and forth between git and native paths, but since it you're not using cygwin git, when magit hands git a cygwinized path, it gets confused.

So basically, we need a smarter way to check whether cygwin (or msys2) git is being used than just calling `mount`.

https://github.com/magit/magit/blob/2.5.0/lisp/magit-git.el#L565

**Comment by thepickle** [comment] 2016-02-02 20:14
Very interesting indeed..
Does cygwin git not have a specialized version, akin to `git version 1.9.5.msysgit.1`

**Comment by npostavs** [comment] 2016-02-02 20:53
Should be fixed now.

**Closed** 2016-02-02 20:52 UTC
Labels: bug windows

**Comment by thepickle** [comment] 2016-02-02 21:48
Thank you kind sir.  Is there a way to build magit locally into my .emacs.d (on Windows) ??  I could patch it manually, but there must be a better way... :)

**Comment by npostavs** [comment] 2016-02-03 08:00
> is there a way to build magit locally into my .emacs.d (on Windows) ??

You can git clone the magit repository onto your local machine. You might want to look at quelpa or el-get to help manage it (i.e. handle byte compilation, autoloading, load-path, and updating) semi-automatically.

**Comment by thepickle** [comment] 2016-02-05 01:37
I know this will make the next melpa release, but what is your release schedule?  Magit seems to load faster as an elpa installed package.

**Comment by npostavs** [comment] 2016-02-05 08:06
> I know this will make the next melpa release

melpa doesn't have releases, it just takes snapshots every so often (I think it's around 6 hours?), the fix should already be in the latest melpa snapshot by now.

> Magit seems to load faster as an elpa installed package.

That doesn't really make sense, maybe you didn't compile? Or you didn't create autoloads?

**Comment by thepickle** [comment] 2016-02-05 12:22
I'm no emacs-expert, but I'm learning (slowly) :)
By 'load faster', I mean that it takes longer to startup emacs itself..

- Does `(require 'magit)` load the whole thing in one go? (maybe this is why)
- Do I need to put `(require 'magit)` line in .emacs in either the [elpa](http://magit.vc/manual/magit/Installing-from-an-Elpa-archive.html#Installing-from-an-Elpa-archive) or [git](http://magit.vc/manual/magit/Installing-from-the-Git-repository.html#Installing-from-the-Git-repository) repository case?
- Does the presence of `(require 'magit)` affect my ability to add custom `magit-log-popup` switches, since I have to do that for `--first-parent` switch..  See #2538 

Sorry that we're getting off-subject here, I just don't know how else to contact u guys, and you've already been super helpful :)

**Comment by npostavs** [comment] 2016-02-05 12:59
> Does `(require 'magit)` load the whole thing in one go? (maybe this is why)

Yes, if you haven't created `magit-autoloads.el`, but running `make` should do this for you. With `magit-autoloads.el` created, then a few loads are deferred. See https://github.com/magit/magit/blob/2.5.0/lisp/magit.el#L2944-L2955

You may be better off doing `(load "magit-autoloads")`, which I think is what elpa ends up doing for you when you activate the package.

> Does the presence of `(require 'magit)` affect my ability to add custom magit-log-popup switches, since I have to do that for `--first-parent` switch

You should either `(require 'magit)` before calling `magit-define-popup-switch`, or else do `(with-eval-after-load 'magit (magit-define-popup-switch ...))`; the 2nd alternative is better to minimize initial startup time.

> Sorry that we're getting off-subject here, I just don't know how else to contact u guys, and you've already been super helpful :)

It's okay, threads tend to drift. Other channels are listed in README.md:

>  <a href="https://groups.google.com/forum/?fromgroups#!forum/magit"><b>mailing list</b></a> |
>  <a href="http://emacs.stackexchange.com/questions/tagged/magit"><b>forum</b></a> |
>  <a href="https://gitter.im/magit/magit"><b>chat</b></a> |
