### ISSUE TITLE
Stashes of the index can only be restored inconveniently

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2397] opened 2015-11-16 11:22 UTC
Hello,

I created a stash of only the index (via z i or z I).  Such a stash can seemingly be applied only very inconveniently: when I pop or apply it, the changes are tried to be applied to the worktree.  Seems I can only use M-x magit-reset-index (a command that is not even bound to a key and thus hard to discover), but the stash is not offered as a candidate.  It works however to paste the stash name into the minibuffer and confirm.

I wonder if this could be made working more intuitively.

Thanks, Michael.

**Comment by kyleam** [comment] 2015-11-17 00:43
Hi Michael,

I think it should work as you expect.  If I stash staged changes with zi
and then pop with zp in the status buffer, the changes are applied to
the index.  Are there other steps I should do to reproduce the issue?

**Comment by michael-heerdegen** [comment] 2015-11-17 13:47
You are right.  But it seems that this command is doing something different from what I expected.

Consider you have some changes, and all of them are staged.  Not hit z i.  Now, you have no changes at all (clean workspace).  But this means that this command changes the worktree!  Is this expected?  I would never have expected this from the docstrings, I thought index stashes would not have any effect on the worktree at all.

**Comment by tarsius** [comment] 2015-11-17 17:05
This is the intended behavior. The word *after* "save" (in symbol names and the action descriptions in the popup) refers to the changes which are being, i.e. either only the staged changes, only the unstaged changes, or both staged and unstaged changes (in which case no word follows "save").

"Save" or "stash" here means "to store changes in a stash and then remove them from the working tree and index (provided they are in the index)". There is also a "store in a stash and do *not* remove from working tree or index" variant. For that we use "snapshot" in the symbol names and action descriptions.

So the doc-strings of the various `magit-stash-save*` commands might be a bit sparse because they do not define what "to stash" means, but since for each "save" command there is a corresponding "snapshot" command, it should be fairly obvious that "save" *does* remove the stashed changes.

Of course the doc-strings could be improved, but I would want the changes to be fairly concise.

**Comment by michael-heerdegen** [comment] 2015-11-18 09:04
Jonas Bernoulli <notifications@github.com> writes:

> This is the intended behavior.

Ok, that answers my question.

> So the doc-strings of the various magit-stash-save* commands might be
> a bit sparse because they do not define what "to stash" means, but
> since for each "save" command there is a corresponding "snapshot"
> command, it should be fairly obvious that "save" does remove the
> stashed changes.

Of course.  But my question was not whether z i removes changes, but
from where - I thought only from the index.  And that is not so obvious.

> Of course the doc-strings could be improved, but I would want the
> changes to be fairly concise.

Ok, thanks.  Feel free to close when you think we are done.

**Comment by tarsius** [comment] 2015-11-18 09:29
I am closing, but am still hoping that someone improves the documentation.

**Closed by tarsius** 2015-11-18 09:29 UTC
Labels: 30 support

**Comment by michael-heerdegen** [comment] 2015-11-18 09:58
Jonas Bernoulli <notifications@github.com> writes:

> I am closing, but am still hoping that someone improves the
> documentation.

BTW, I wonder if z i is always well defined.  It applies the reversed
staged changes to the worktree.  If the worktree is changed too, it
could be possible that z i can fail, or do I miss something?

**Comment by tarsius** [comment] 2015-11-18 10:00
Yes, that's true. Probably should be mentioned in the documentation too :-)

**Comment by michael-heerdegen** [comment] 2015-11-18 12:16
Is this appropriate?

**Comment by tarsius** [comment] 2015-11-18 18:09
Yes. Thanks!
