### ISSUE TITLE
Emacsclient -t crashes when merging with auto-merge

### ISSUE THREAD

**Issue by tmccombs** [magit/magit#2288] opened 2015-09-24 22:04 UTC
If a merge a branch from the command line, and there is an auto-merge, then when git opens emacslcient -t for the commit message, emacsclient crashes and messes up my terminal. 

If I remove the git-commit package this doesn't happen.

This may be an interaction between magit and perspective. But I don't know how to debug it very well.

**Comment by tarsius** [comment] 2015-09-25 15:30
I think this is a duplicate of #2285, for which I just pushed a fix. Please check whether that fixes the issue for you. (It can take up to two hours until a change hits Melpa.)

**Comment by tarsius** [comment] 2015-09-25 18:39
If not, let me know.

**Closed by tarsius** 2015-09-25 18:39 UTC
Labels: 32 duplicate

**Comment by tmccombs** [comment] 2015-11-20 01:07
This still happens for me after updating magi.

I have been able to determine that it happens if and only if I have a magit status buffer open in another frame.
