### ISSUE TITLE
magit-section should support updating its DOM (or otherwise support asynchronous data sources)

### ISSUE THREAD

**Issue by sdevlin** [magit/magit#4208] opened 2020-09-04 19:22 UTC
I'm trying to apply the magit-section library to format the contents of a compilation log. Unfortunately, it seems that magit-section does not support updates to its DOM; instead, the way to make changes is to erase the buffer and render it from scratch.

While this works well in many cases, it is awkward when you want to display something before all the data is ready. In an asynchronous scenario (e.g. tailing a log file), you either need to erase and render the buffer many times or wait a long time (potentially minutes) for the subprocess to finish.

It would be great if magit-section had functions to mutate the DOM similar to HTML, e.g. to insert a new node between two existing ones or to delete a node. I _think_ this should just be a matter of patching up all the adjacent nodes' references correctly, but my familiarity with magit-section internals is limited.

As an alternative, my particular case would be satisfied if I could supply a callback function that could write new sections only to the end of the buffer. In other words, an asynchronous version of the `magit-wash-sequence` function. I'm not sure if this is easier or harder than the more general API to modify the DOM.

Thanks for a great package! I've used magit-section successfully in a few personal projects, and it's a joy to work with!

**Comment by tarsius** [comment] 2020-09-05 18:29
Yes but not now.

**Comment by tarsius** [comment] 2021-08-13 18:04
Closing as a duplicate of #2985.

**Closed by tarsius** 2021-08-13 18:04 UTC
Labels: duplicate
