### ISSUE TITLE
magit-wip-commit-worktree: Cannot read tree HEAD

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#3646] opened 2018-11-01 02:25 UTC
Hello,

using current Magit from Melpa.  I use (magit-wip-after-apply-mode) and (magit-wip-after-save-mode) in my setup.  Since some days, whenever I hit C-c C-c from the edit-the-commit-message buffer, i get an error "magit-wip-commit-worktree: Cannot read tree HEAD".

I hope it's easy to reproduce when you turn the wip modes on and try to commit something.

TIA, Michael.

**Comment by michael-heerdegen** [comment] 2018-11-01 03:17
I think that this seems to happen only when confirming the commit message with C-c C-c when rebasing, not for normal commits.

**Comment by npostavs** [comment] 2018-11-01 11:44
Sounds like #3631, but slightly different? (@tarsius I think you posted the same, but in the wrong thread).

**Comment by tarsius** [comment] 2018-11-01 12:09
This might be a duplicate of #3631 indeed. @michael-heerdegen please update and try again.

But I really did intend to make a connection with #2708.

https://github.com/magit/magit/issues/3496#issuecomment-429371003 might also be related.

I think the only proper way forward is to not only wait for the `emacsclient` to return but also its parent process, the thing that asked for a file to be edited. Currently we wait for 0.1 seconds and hope for the best. If the parent is `git commit` for example, then that usually is long enough, but for a huge commit we might have to wait longer and the only way to know for how long we have to wait, is to wait for the parent to finish.

During a rebase the situation is a bit different. Here we cannot just wait for the parent to finish (which by the way probably is `git commit`, not `git rebase`, even if the user actually typed `r r`). Doing that would avoid our `git commit` and that of `git rebase` to conflict with each other, but that would only mean that we no race with whatever `git rebase` does afterwards instead. (This issue and https://github.com/magit/magit/issues/2708#issuecomment-434909123 are manifestations of that I think.) The only solution I can see is to never call `magit-wip-merge-branch` during rebases.

**Comment by tarsius** [comment] 2018-11-01 12:14
I might revert cbc15d71788dbcf5368b23337ff1cfaf0ab4a85 from #3615 until is all sorted out.

**Comment by michael-heerdegen** [comment] 2018-11-02 00:05
Jonas Bernoulli <notifications@github.com> writes:

> I might revert cbc15d71788dbcf5368b23337ff1cfaf0ab4a85 from #3615
> until is all sorted out.

So, what should I try now, in which order?  Just update Magit (though, I
updated Magit every day form M-x list-packages)?  Or also (setq
magit-wip-merge-branch nil)?

Michael.

**Comment by tarsius** [comment] 2018-11-03 16:35
> So, what should I try now, in which order?

It is possible that this issue is just a duplicate of #3631. In that case this issue should go away after updating to a version which contains the fix.

But you mention that you update Magit regularly, which probably means that you already had that version installed at the time you opened this issue. So this is another issue as explained earlier, and as I said earlier, I think that in that case it is just another possible result of the regression that also led to the behavior you mentioned in the other issue.

I have just pushed a94bc130c72fb4d14b7093acc945a6b9a544a060, which should fix that.

The new instructions are: Wait for that to land on Melpa, update, and try if the issue really is gone.

**Comment by tarsius** [comment] 2018-11-03 21:53
> I have just pushed a94bc130c72fb4d14b7093acc945a6b9a544a060, which should fix that.

Well actually, that was broken. But now it should work.

**Closed** 2018-11-03 21:59 UTC

**Comment by michael-heerdegen** [comment] 2018-11-06 01:28
Jonas Bernoulli <notifications@github.com> writes:

> The new instructions are: Wait for that to land on Melpa, update, and
> try if the issue really is gone.

So far everything is good.  I did not get the error message like in the
subject again.

I also had no more problem with interactive rebasing, though I didn't
try very often.

Thanks,

Michael.
