### ISSUE TITLE
Magit clone does not seem to work

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2639] opened 2016-05-06 03:46 UTC
`magit-clone` invocation results in a message “not inside a Git repository” and no new directory appears.

**Comment by tarsius** [comment] 2016-05-06 12:08
We need more information to help you here. Similar issues have been reported before ([by you for example](https://github.com/magit/magit/issues/2488), but these issued are believed to be fixed.

**Comment by mrkkrp** [comment] 2016-05-06 12:11
I will investigate it when I have time. When I discovered this I was busy working.

**Comment by mrkkrp** [comment] 2016-05-06 15:30
Hmm, can't reproduce it anymore. I'm closing, will reopen if I run into this behavior again.

**Comment by tarsius** [comment] 2016-05-06 15:33
Maybe symlinks are involved?

**Comment by mrkkrp** [comment] 2016-05-06 15:36
No, everything as usual, I have no idea what happened. Sorry for annoyance, I just wanted to document this, so I opened an issue.

**Comment by mrkkrp** [comment] 2016-05-11 08:20
@tarsius, New info here. It seems to happen whan repo that is being cloned is private and I haven't entered (and cached) my GitHub password yet. Can you reprodue it now?

**Comment by npostavs** [comment] 2016-05-11 10:01
So the problem is that `magit-clone` doesn't catch the password prompt, right? I don't have a private repo to test with, but I think it should work if the clone is run asynchronously so that `magit-process-password-prompt` willl apply. See #2648.

**Comment by tarsius** [comment] 2016-05-13 17:33
Closing in favor of #2648.

**Closed by tarsius** 2016-05-13 17:33 UTC
Labels: bug
