### ISSUE TITLE
Expanded changes and errors using magit with a git-svn repo

### ISSUE THREAD

**Issue by luniki** [magit/magit#3266] opened 2017-11-16 11:27 UTC
After updating magit in the morning, the magit status buffer of a git-svn repo is all wrong. (Un-)Staged Change Diffs are all expanded and staging a hunk results in:

"Args out of range: #("git-svn" 0 7 (face magit-branch-remote)), 13, 20"

I am using

git-svn version 2.15.0 (svn 1.9.7)

With a git repo (not git-svn) everything works as usual, that is awesometastic ;-)

**Comment by tarsius** [comment] 2017-11-16 12:23
> (Un-)Staged Change Diffs are all expanded

That is probably the case because another error occurred while the buffer was being created - please verify.

> and staging a hunk results in:

Did you switch between Emacs 25 and 26 recently? Try recompiling `magit` and `magit-svn` the problem might be due to differences in how certain data is stored in these Emacs releases.

**Comment by luniki** [comment] 2017-11-16 18:16
You are right. The expanded changes occurred after this error:

    let: Args out of range: #("git-svn" 0 7 (face magit-branch-remote)), 13, 20

I am still on Emacs 25.3.2. But I recently upgraded subversion (and thus libsvn-perl) via ppa:dominik-stadler/subversion-1.9

Re-installing magit does not solve these problems.

BUT I experience no problems at all using magit with a git repo...

**Comment by luniki** [comment] 2017-11-16 18:20
BTW I am not using magit-svn

**Comment by tarsius** [comment] 2017-11-16 18:40
Please `M-x toggle-debug-on-error` and then post the full backtrace.

**Comment by luniki** [comment] 2017-11-16 20:39
Here it is:

[magit-error.txt](https://github.com/magit/magit/files/1480169/magit-error.txt)

**Comment by luniki** [comment] 2017-11-16 20:40
Here it is:

[magit-error.txt](https://github.com/magit/magit/files/1480171/magit-error.txt)

**Comment by tarsius** [comment] 2017-11-16 21:10
```
Debugger entered--Lisp error: (args-out-of-range #("git-svn" 0 7 (face magit-branch-remote)) 13 20)
  match-string(1 #("git-svn" 0 7 (face magit-branch-remote)))
  #[257 "\300\301\"\210\302\303\"\302\304\"\211\305\232?\205,\0\306P\307\310\311\312\"\"\232\203+\0\313\314\315#\202,\0\207" [string-match "\\`\\([^/]*\\)/\\(.*\\)\\'" match-string 1 2 "HEAD" "refs/remotes/" magit-git-string "symbolic-ref" format "refs/remotes/%s/HEAD" propertize face magit-branch-remote-head] 9 "\n\n(fn NAME)"](#("git-svn" 0 7 (face magit-branch-remote)))
  -keep(#[257 "\300\301\"\210\302\303\"\302\304\"\211\305\232?\205,\0\306P\307\310\311\312\"\"\232\203+\0\313\314\315#\202,\0\207" [string-match "\\`\\([^/]*\\)/\\(.*\\)\\'" match-string 1 2 "HEAD" "refs/remotes/" magit-git-string "symbolic-ref" format "refs/remotes/%s/HEAD" propertize face magit-branch-remote-head] 9 "\n\n(fn NAME)"] (#("git-svn" 0 7 (face magit-branch-remote))))
  magit-format-ref-labels(" (HEAD -> refs/heads/master, refs/remotes/git-svn)")
  magit-log-wash-rev(log 7)
  apply(magit-log-wash-rev (log 7))
  #[128 "\302\300\303\301\"\"\207" [magit-log-wash-rev (log 7) apply append] 6 "\n\n(fn &rest ARGS2)"]()
  magit-wash-sequence(#[128 "\302\300\303\301\"\"\207" [magit-log-wash-rev (log 7) apply append] 6 "\n\n(fn &rest ARGS2)"])
  magit-log-wash-log(log ("log" "--format=%h%d%x00%x00%aN%x00%at%x00%s" "--decorate=full" "-10" "-n256" "--use-mailmap" "--no-prefix" "--"))
  apply(magit-log-wash-log (log ("log" "--format=%h%d%x00%x00%aN%x00%at%x00%s" "--decorate=full" "-10" "-n256" "--use-mailmap" "--no-prefix" "--")))
  #[128 "\302\300\303\301\"\"\207" [magit-log-wash-log (log) apply append] 6 "\n\n(fn &rest ARGS2)"](("log" "--format=%h%d%x00%x00%aN%x00%at%x00%s" "--decorate=full" "-10" "-n256" "--use-mailmap" "--no-prefix" "--"))
  magit-git-wash(#[128 "\302\300\303\301\"\"\207" [magit-log-wash-log (log) apply append] 6 "\n\n(fn &rest ARGS2)"] "log" "--format=%h%d%x00%x00%aN%x00%at%x00%s" ("--decorate=full" "-10" "-n256") "--use-mailmap" "--no-prefix" nil "--" nil)
  magit-insert-log(nil ("-10" "-n256" "--decorate"))
  magit-insert-recent-commits(nil)
  magit-insert-unpushed-to-upstream-or-recent()
  run-hooks(magit-status-sections-hook)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup-internal(magit-status-mode nil)
  magit-mode-setup(magit-status-mode)
  magit-status-internal("/home/luniki/Projects/studip/dashboard/app/controllers/")
  #[512 "\211\206\0\302\211BC\203H\0\303!\304\305!!\262\211\203(\0\306\"\203(\0\307!\202C\0\310\2036\0\311\312#\202:\0\311\313\"!\205C\0\314\315!\262\202K\0\307	!)\207" [magit--refresh-cache default-directory 0 magit-toplevel file-name-as-directory expand-file-name file-equal-p magit-status-internal y-or-n-p format "%s is a repository.  Create another in %s? " "Create repository in %s? " nil magit-init] 8 ("/home/luniki/.emacs.d/elpa/magit-20171116.649/magit-status.elc" . 4889) (byte-code "\302\211BC	\204\0\303 ?\205\0\304\305	!\306Y!)D\207" [magit--refresh-cache current-prefix-arg 0 magit-toplevel magit-read-repository prefix-numeric-value 16] 3)](nil ((31 . 26) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD~")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD") . "a0d7811f") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD~10")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "@{upstream}")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "refs/stash")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--is-bare-repository") . "false") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "BISECT_LOG") . "/home/luniki/Projects/studip/dashboard/.git/BISECT_LOG") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "REVERT_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/REVERT_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "CHERRY_PICK_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/CHERRY_PICK_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/applying") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/applying") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/onto") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/onto") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-merge") . "/home/luniki/Projects/studip/dashboard/.git/rebase-merge") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "MERGE_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/MERGE_HEAD") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--git-dir") . ".git") (("/home/luniki/Projects/studip/dashboard/" "describe" "--contains" "HEAD")) (("/home/luniki/Projects/studip/dashboard/" "describe" "--long" "--tags")) ((config "/home/luniki/Projects/studip/dashboard/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("magit.hidecampaign" ("true") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "svn-remote.svn.url" ("svn://develop.studip.de/studip/dev-branches/step317-widgets-renewal") "svn-remote.svn.fetch" (":refs/remotes/git-svn") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/home/luniki/Projects/studip/dashboard/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "show" "--no-patch" "--format=%h %s" "master^{commit}" "--") . "a0d7811f fix migration, re #7698") (("/home/luniki/Projects/studip/dashboard/" "symbolic-ref" "--short" "HEAD") . "master") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD") . "a0d7811fe7186b593a8c2457e1bb07a920fd5121") (("/home/luniki/Projects/studip/dashboard/app/controllers/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-cdup") . "") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-cdup") . "../../") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard")))
  ad-Advice-magit-status(#[512 "\211\206\0\302\211BC\203H\0\303!\304\305!!\262\211\203(\0\306\"\203(\0\307!\202C\0\310\2036\0\311\312#\202:\0\311\313\"!\205C\0\314\315!\262\202K\0\307	!)\207" [magit--refresh-cache default-directory 0 magit-toplevel file-name-as-directory expand-file-name file-equal-p magit-status-internal y-or-n-p format "%s is a repository.  Create another in %s? " "Create repository in %s? " nil magit-init] 8 ("/home/luniki/.emacs.d/elpa/magit-20171116.649/magit-status.elc" . 4889) (byte-code "\302\211BC	\204\0\303 ?\205\0\304\305	!\306Y!)D\207" [magit--refresh-cache current-prefix-arg 0 magit-toplevel magit-read-repository prefix-numeric-value 16] 3)] nil ((31 . 26) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD~")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD") . "a0d7811f") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD~10")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "@{upstream}")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "refs/stash")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--is-bare-repository") . "false") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "BISECT_LOG") . "/home/luniki/Projects/studip/dashboard/.git/BISECT_LOG") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "REVERT_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/REVERT_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "CHERRY_PICK_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/CHERRY_PICK_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/applying") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/applying") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/onto") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/onto") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-merge") . "/home/luniki/Projects/studip/dashboard/.git/rebase-merge") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "MERGE_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/MERGE_HEAD") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--git-dir") . ".git") (("/home/luniki/Projects/studip/dashboard/" "describe" "--contains" "HEAD")) (("/home/luniki/Projects/studip/dashboard/" "describe" "--long" "--tags")) ((config "/home/luniki/Projects/studip/dashboard/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("magit.hidecampaign" ("true") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "svn-remote.svn.url" ("svn://develop.studip.de/studip/dev-branches/step317-widgets-renewal") "svn-remote.svn.fetch" (":refs/remotes/git-svn") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/home/luniki/Projects/studip/dashboard/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "show" "--no-patch" "--format=%h %s" "master^{commit}" "--") . "a0d7811f fix migration, re #7698") (("/home/luniki/Projects/studip/dashboard/" "symbolic-ref" "--short" "HEAD") . "master") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD") . "a0d7811fe7186b593a8c2457e1bb07a920fd5121") (("/home/luniki/Projects/studip/dashboard/app/controllers/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-cdup") . "") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-cdup") . "../../") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard")))
  apply(ad-Advice-magit-status #[512 "\211\206\0\302\211BC\203H\0\303!\304\305!!\262\211\203(\0\306\"\203(\0\307!\202C\0\310\2036\0\311\312#\202:\0\311\313\"!\205C\0\314\315!\262\202K\0\307	!)\207" [magit--refresh-cache default-directory 0 magit-toplevel file-name-as-directory expand-file-name file-equal-p magit-status-internal y-or-n-p format "%s is a repository.  Create another in %s? " "Create repository in %s? " nil magit-init] 8 ("/home/luniki/.emacs.d/elpa/magit-20171116.649/magit-status.elc" . 4889) (byte-code "\302\211BC	\204\0\303 ?\205\0\304\305	!\306Y!)D\207" [magit--refresh-cache current-prefix-arg 0 magit-toplevel magit-read-repository prefix-numeric-value 16] 3)] (nil ((31 . 26) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD~")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD") . "a0d7811f") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD~10")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "@{upstream}")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "refs/stash")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--is-bare-repository") . "false") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "BISECT_LOG") . "/home/luniki/Projects/studip/dashboard/.git/BISECT_LOG") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "REVERT_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/REVERT_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "CHERRY_PICK_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/CHERRY_PICK_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/applying") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/applying") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/onto") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/onto") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-merge") . "/home/luniki/Projects/studip/dashboard/.git/rebase-merge") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "MERGE_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/MERGE_HEAD") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--git-dir") . ".git") (("/home/luniki/Projects/studip/dashboard/" "describe" "--contains" "HEAD")) (("/home/luniki/Projects/studip/dashboard/" "describe" "--long" "--tags")) ((config "/home/luniki/Projects/studip/dashboard/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("magit.hidecampaign" ("true") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "svn-remote.svn.url" ("svn://develop.studip.de/studip/dev-branches/step317-widgets-renewal") "svn-remote.svn.fetch" (":refs/remotes/git-svn") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/home/luniki/Projects/studip/dashboard/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "show" "--no-patch" "--format=%h %s" "master^{commit}" "--") . "a0d7811f fix migration, re #7698") (("/home/luniki/Projects/studip/dashboard/" "symbolic-ref" "--short" "HEAD") . "master") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD") . "a0d7811fe7186b593a8c2457e1bb07a920fd5121") (("/home/luniki/Projects/studip/dashboard/app/controllers/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-cdup") . "") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-cdup") . "../../") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard"))))
  magit-status(nil ((31 . 26) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD~")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD") . "a0d7811f") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD~10")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "@{upstream}")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "refs/stash")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--is-bare-repository") . "false") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "BISECT_LOG") . "/home/luniki/Projects/studip/dashboard/.git/BISECT_LOG") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "REVERT_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/REVERT_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "CHERRY_PICK_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/CHERRY_PICK_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/applying") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/applying") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/onto") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/onto") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-merge") . "/home/luniki/Projects/studip/dashboard/.git/rebase-merge") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "MERGE_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/MERGE_HEAD") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--git-dir") . ".git") (("/home/luniki/Projects/studip/dashboard/" "describe" "--contains" "HEAD")) (("/home/luniki/Projects/studip/dashboard/" "describe" "--long" "--tags")) ((config "/home/luniki/Projects/studip/dashboard/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("magit.hidecampaign" ("true") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "svn-remote.svn.url" ("svn://develop.studip.de/studip/dev-branches/step317-widgets-renewal") "svn-remote.svn.fetch" (":refs/remotes/git-svn") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/home/luniki/Projects/studip/dashboard/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "show" "--no-patch" "--format=%h %s" "master^{commit}" "--") . "a0d7811f fix migration, re #7698") (("/home/luniki/Projects/studip/dashboard/" "symbolic-ref" "--short" "HEAD") . "master") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD") . "a0d7811fe7186b593a8c2457e1bb07a920fd5121") (("/home/luniki/Projects/studip/dashboard/app/controllers/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-cdup") . "") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-cdup") . "../../") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard")))
  funcall-interactively(magit-status nil ((31 . 26) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD~")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--short" "HEAD") . "a0d7811f") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD~10")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "@{upstream}")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "refs/stash")) (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--is-bare-repository") . "false") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "BISECT_LOG") . "/home/luniki/Projects/studip/dashboard/.git/BISECT_LOG") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "REVERT_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/REVERT_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "CHERRY_PICK_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/CHERRY_PICK_HEAD") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/applying") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/applying") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-apply/onto") . "/home/luniki/Projects/studip/dashboard/.git/rebase-apply/onto") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "rebase-merge") . "/home/luniki/Projects/studip/dashboard/.git/rebase-merge") (("/home/luniki/Projects/studip/dashboard/" magit-git-dir "MERGE_HEAD") . "/home/luniki/Projects/studip/dashboard/.git/MERGE_HEAD") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--git-dir") . ".git") (("/home/luniki/Projects/studip/dashboard/" "describe" "--contains" "HEAD")) (("/home/luniki/Projects/studip/dashboard/" "describe" "--long" "--tags")) ((config "/home/luniki/Projects/studip/dashboard/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("magit.hidecampaign" ("true") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "svn-remote.svn.url" ("svn://develop.studip.de/studip/dev-branches/step317-widgets-renewal") "svn-remote.svn.fetch" (":refs/remotes/git-svn") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/home/luniki/Projects/studip/dashboard/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "show" "--no-patch" "--format=%h %s" "master^{commit}" "--") . "a0d7811f fix migration, re #7698") (("/home/luniki/Projects/studip/dashboard/" "symbolic-ref" "--short" "HEAD") . "master") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--verify" "HEAD") . "a0d7811fe7186b593a8c2457e1bb07a920fd5121") (("/home/luniki/Projects/studip/dashboard/app/controllers/" . magit-toplevel) . "/home/luniki/Projects/studip/dashboard/") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard") (("/home/luniki/Projects/studip/dashboard/" "rev-parse" "--show-cdup") . "") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-cdup") . "../../") (("/home/luniki/Projects/studip/dashboard/app/controllers/" "rev-parse" "--show-toplevel") . "/home/luniki/Projects/studip/dashboard")))
  #<subr call-interactively>(magit-status nil nil)
  apply(#<subr call-interactively> magit-status (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> magit-status nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (magit-status nil nil))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

**Comment by tarsius** [comment] 2017-11-16 21:16
And the output of `git show-ref`.

**Comment by luniki** [comment] 2017-11-16 22:41
$ git show-ref
a0d7811fe7186b593a8c2457e1bb07a920fd5121 refs/heads/master
a0d7811fe7186b593a8c2457e1bb07a920fd5121 refs/remotes/git-svn

**Comment by luniki** [comment] 2017-11-16 22:42
I removed my .emacs.d and reinstalled magit via melpa. The problem is still the same.

**Comment by tarsius** [comment] 2017-11-17 10:52
I've pushed a fix for this recent regression.

**Closed** 2017-11-17 10:51 UTC

**Comment by luniki** [comment] 2017-11-17 13:41
Thank you!
