### ISSUE TITLE
Add --mainline to the revert popup

### ISSUE THREAD

**Issue by tarsius** [magit/magit#3018] opened 2017-03-06 21:36 UTC
Like in the cherry-pick popup.

**Comment by tarsius** [comment] 2017-04-16 11:57
I have done this on https://github.com/magit/magit/compare/3018?expand=1. However it does not seem to work, not even on the command line.

```
$ git version
git version 2.12.2
$ cd ~/.emacs.d/lib/magit
$ git revert --mainline=2 495d7255
On branch 3018
Your branch is ahead of 'master' by 1 commit.
nothing to commit, working tree clean
$ git status     # ^ why same output?
On branch 3018
Your branch is ahead of 'master' by 1 commit.
nothing to commit, working tree clean
```

Am I doing something wrong?

**Comment by tarsius** [comment] 2017-04-16 12:00
@raxod502 Could you please look into this?

**Comment by raxod502** [comment] 2017-04-16 16:36
@tarsius I think this is the expected behavior. If you revert a merge commit, you're reverting all the commits which were merged in, but not already present in the main development history.

The history around `495d7255 ` looks like:

```
*   495d7255 Merge branch 'np/cmd-shell' [#3034]
|\
| * 6fc510e1 Update release notes
| * d04fc7fd magit-shell-command-verbose-prompt: new option
| * 514401ef Update documentation of magit-shell-command and related commands
| * b1b7798f magit-shell-command-topdir: return only the read command
| * affa62d3 magit-process-insert-section: hide shell in header
| * b3c02666 magit-process-insert-section: shell-quote arguments in header
| * 8b76cce7 magit-shell-command: cosmetics
| * 062836fa magit-git-command: use a shell
|/
*   9c003a93 Merge branch 'km/ref-completion-sort' [#3029]
```

The normal thing to do for your example would be `git revert --mainline=1 495d7255`, which is the default. This will revert commits `062836fa` through `495d7255`. If you do `git revert --mainline=2 495d7255`, then you're pretending that the right-hand branch is the main development history. So if you try to undo the merge of the left-hand branch into the right-hand branch, there's nothing to undo—all the commits in that branch are already included in the main development history, even before the merge.

Thus `--mainline=1` will do what you probably expected, and `--mainline=2` is a no-op.

**Comment by tarsius** [comment] 2017-04-16 19:20
Doh! "mainline" really says it all ;-)

**Comment by tarsius** [comment] 2017-04-17 21:05
I've pushed the commit.

**Closed** 2017-04-17 21:05 UTC
Labels: feature request
