### ISSUE TITLE
regression: "push implicitly" disappeared

### ISSUE THREAD

**Issue by glyph** [magit/magit#2445] opened 2015-12-20 00:51 UTC
I have several git repositories set up in an idiom like this: https://glyph.twistedmatrix.com/2014/09/actually-distributed.html

i.e. I have `remote.<remote>.push` configured to point at an alternate destination point in the upstream repository.

When I could do `P i` in magit, this was perfect; the implicit push always did the right thing.

But I just upgraded, and now I'm back to switching to the terminal to do `git push` again, since it's very annoying to have to carefully type `+refs/remotes/hostname/branchname` every time I want to push.

Please put `P i` back.  Thanks!

**Comment by glyph** [comment] 2015-12-20 00:53
It looks like the offending change was #2424, which unfortunately did a bunch of useful stuff at the same time.

**Comment by johnmastro** [comment] 2015-12-20 01:08
See also #2444, where it may make its return (albeit likely not in the popup by default)

**Comment by glyph** [comment] 2015-12-20 01:12
Thanks for the pointer.  Personally, I think it should be in the popup but with a [molly-guard](https://en.wiktionary.org/wiki/molly-guard) on it that requires you to confirm you understand why it's dangerous.  A *lot* of people use `git` on the command line by just typing `git push` and so having some way to replicate the behavior they're familiar with would be good.

**Comment by johnmastro** [comment] 2015-12-20 02:45
Indeed, the motto of the upcoming release (2.4) is "deal with the fact that everyone has a different opinion on how branching and pushing should work" (per [the roadmap](https://github.com/magit/magit/issues/2180)).

**Comment by npostavs** [comment] 2015-12-20 03:08
> the offending change was #2414, which unfortunately did a bunch of useful stuff at the same time.

I guess the particular change in question is isolated in 632faf3fdb6d9193508fbdc553762062a7565e7c. Closing, as I think further comments should go to #2444 (and see also commit message of b007e964d1947e16e95682e93a39b6e87ecbab51)

**Closed by npostavs** 2015-12-20 03:08 UTC

**Comment by tarsius** [comment] 2015-12-20 12:39
> I have several git repositories set up in an idiom like this

Interesting.

I will restore the command but probably not the binding. And I will probably also tune back the remarks about it not being dangerous. Unfortunately the description of `git push` without additional arguments in the `git-push` manpage is very short. It doesn't mention any of the relevant variables which completely change what it does. I am listing the ones I am aware of in `magit-push-implicitly`s doc-string, but was careful to not to claim that list is complete. Already I have to add on I forgot about `remote.<name>.push`.

**Comment by tarsius** [comment] 2015-12-20 14:30
@glyph I have tried you're approach and don't think `magit-push-implicitly` would support it or ever did. Though I might have missed some crucial step. What Magit version did you use before updating to one that did not support your workflow? Did you press <kbd>P i</kbd> to push or something else? <kbd>P Q</kbd>?

```shell
 $ git init a
Initialized empty Git repository in /home/jonas/tmp/y/a/.git/
$ cd a
$ echo 1 > file
$ git add file
$ git commit -m 1
[master (root-commit) 2df48e8] 1
 1 file changed, 1 insertion(+)
 create mode 100644 file
$ cd ..
$ git clone --origin a a b
Cloning into 'b'...
done.
$ cd a
$ git remote add b ../b
$ git config remote.b.push '+refs/heads/*:refs/remotes/a/*'
$ cd ../b
$ git config remote.a.push '+refs/heads/*:refs/remotes/b/*'
$ cd ../a
$ echo 2 > file
$ git commit -m 2 -a
[master ace39af] 2
 1 file changed, 1 insertion(+), 1 deletion(-)
```

After that I cannot push without any arguments:

```shell
$ git push
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>

```

The remote has to be specified:

```shell
$ git push b
Counting objects: 3, done.
Writing objects: 100% (3/3), 231 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../b
   2df48e8..ace39af  master -> a/master
```

The configuration looks like this:

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "b"]
        url = ../b
        fetch = +refs/heads/*:refs/remotes/b/*
        push = +refs/heads/*:refs/remotes/a/*
```


But there is not Magit command which does `git push <remote>`. And I am under the impression that there never was a command that did. I checked v1.4, v2.1, and v2.3.

The problem appears to be that Magit always provides the refspec explicitly when pushing. I made that change a long time ago (before v1.4) to fix a bug. It is sometimes necessary to specify the full refspec (including the *full* ref on the receiving side) to *create* a new branch/ref on the receiving end.

But back to the command line. In order to be able to just `git push` I had set the push-remote or upstream.

```shell
$ git config branch.master.pushRemote b       # or
$ git branch --set-upstream-to=b/master
Branch master set up to track remote branch master from b.
```

There's one change related to the use of full refspecs in v2.4 though, a full refspec is now used in cases where that is probably not necessary. (I made that change to address the "probably" part.) Reverting that like so:

```diff
diff --git a/lisp/magit-remote.el b/lisp/magit-remote.el
index 3731dc2..e6043da 100644
--- a/lisp/magit-remote.el
+++ b/lisp/magit-remote.el
@@ -287,8 +287,10 @@ (defun magit-git-push (branch target args)
   (-let [(remote . target)
          (magit-split-branch-name target)]
     (magit-run-git-async-no-revert "push" "-v" args remote
-                                   (format "%s:refs/heads/%s"
-                                           branch target))))
+                                   (if (equal branch target)
+                                       branch
+                                     (format "%s:refs/heads/%s"
+                                             branch target)))))
 
 ;;;###autoload
 (defun magit-push-current-to-pushremote (args &optional push-remote)
```

Allows the use of <kbd>P u</kbd> or <kbd>P p</kbd> to push to a non-standard ref on the receiving end again (depending on whether you have setup the upstream or push-remote).

But there's another problem. Git itself seems to be confused by `remote.<name>.push`. Even after pushing recent commits in "Unpushed to <remote-which-we-already-pushed-to>". In the case of the upstream, this cannot be Magit's fault, because we use `@{upstream}`, so it is Git's responsibility to figure out what tracking ref it has to check.

But I think the problem is not that Git doesn't check the correct ref, the problem is that it does not update the remote tracking ref on pushing when `remote.<name>.push` is set. This appears to operate on a different level - it isn't aware that it has to update a remote tracking ref. Instead it pushes according to some explicit refspec (the fact that this refspec is defined in configuration, not on the command line, does not seem to change that interpretation).

Even if we can somehow address this, another problem remains. You can only push to one remote by using `git push`, but since you have used three repositories in your example, I assume you want to be able to push to >= two remotes. For that you need `git push b; git push c`, but in Magit the semantics used for the push target is different from that used in Git. Git `push to REMOTE like so LOCAL-BRANCH[:REMOTE-BRANCH]`, Magit `push LOCAL-BRANCH to REMOTE[/REMOTE-BRANCH]`. So if `b` where the upstream/push-remote then you would have to type <kbd>P u/p c RET master</kbd> to push to `c`.

I am sympathetic to your goal. But my current understanding is that setting `remote.<name>.push` is not a suitable way of accomplishing what you want. Git itself does not appear to consistently interpret that variable the same way you do, even though it does what you want in the most important situation (when you push).

What about a dedicated command (implemented as a shell script as well as elisp command) which distributes the current branch to all remotes (or a subset) by explicitly calling `git push` with the appropriate refspecs instead of relying on `remote.<name>.push`?

**Comment by glyph** [comment] 2015-12-22 01:15
@tarsius:

> @glyph I have tried you're approach and don't think magit-push-implicitly would support it or ever did. Though I might have missed some crucial step. What Magit version did you use before updating to one that did not support your workflow? Did you press P i to push or something else? P Q?

I pushed <kbd>P i</kbd>.  It looks like `20151019.443` was a version that supported this.

**Comment by glyph** [comment] 2015-12-22 01:15
> But there's another problem. Git itself seems to be "confused" by remote.<name>.push. Even after pushing recent commits continue to appear in Unpushed to <remote-which-we-already-pushed-to>. In the case of the upstream, this cannot be Magit's fault, because we use @{upstream}, so it is Git's responsibility to figure out what tracking ref it has to check. (Actually Git is doing the right thing, in my opinion, it's just not what would be required by your use-case.)

Indeed, git is doing the right thing.  And in fact I want to see those revisions as "unpushed" because the remote side has not integrated them.

**Comment by glyph** [comment] 2015-12-22 01:17
> After that I cannot push without any arguments:

Yes, this is expected.  I have both `remote=...` and `merge = refs/heads/master` set in my local branch configuration.

**Comment by glyph** [comment] 2015-12-22 01:22
> What about a dedicated command (implemented as a shell script as well as elisp command) which distributes the current branch (or all branches, or a subset) to all remotes (or a subset) by explicitly calling git push with the appropriate refspecs instead of relying on remote.<name>.push?

The problem I see with this is that there's nowhere to put the relevant refspec in the configuration.  Or at least, I haven't found one; I hope I'm wrong, and you can correct me :).  I do *not* want the "remote remote" refspec to be "upstream" since "upstream" (i.e. `merge=`) is the place I want to *pull* revisions from; I explicitly want to *push* them somewhere else.  I want to specify this using git configuration, because I sometimes pair program with people who are uncomfortable with using magit and I'd like the command-line to continue to work for those folks.

**Comment by tarsius** [comment] 2015-12-22 01:29
I'll respond tomorrow. Meanwhile please give ccb03166b1030fbe6b2e70415b291b2831ca6cfc (from https://github.com/magit/magit/tree/jb/push-tweaks) a try.

**Comment by glyph** [comment] 2015-12-22 01:37
> I'll respond tomorrow. Meanwhile please give ccb0316 (from https://github.com/magit/magit/tree/jb/push-tweaks) a try.

Sure, take your time.  And happy holidays :).

I've never installed magit except from melpa, though, so I'm not sure how to install that branch properly.

**Comment by npostavs** [comment] 2015-12-22 01:52
> I've never installed magit except from melpa, though, so I'm not sure how to install that branch properly

See http://magit.vc/manual/magit/Installing-from-the-Git-repository.html

**Comment by glyph** [comment] 2015-12-22 02:00
Thanks; I'll try to look at it.

BTW: please do not recommend that people install from `git://` URLs; you should always prefer `https://`, as `git://` is unauthenticated and it makes it easy for attackers to inject malware.

**Comment by weissjeffm** [comment] 2016-02-22 11:31
I'm having a similar issue trying to push to a gerrit repository - the push refspec is `HEAD:refs/for/master`, but there's no way to specify to magit, that I can find. It will only do `refs/heads/master`.

**Comment by tarsius** [comment] 2016-02-23 10:06
I've added a new command `magit-push-refspecs` on <kbd>p r</kbd>, see 8290fabbfc4dc6482dc4b4a860a8f57995921324.

But also checkout https://github.com/terranpro/magit-gerrit which probably offers a more convenient command. Something like this might also work:

```lisp
(defun magit-push-for-master (args)
  (interactive (list (magit-push-arguments)))
  (-if-let (upstream (magit-get-upstream-remote "master"))
      (progn (run-hooks 'magit-credential-hook)
             (magit-run-git-async "push" "-v" args upstream
                                  "HEAD:refs/for/master"))
    (user-error "No upstream is configured for master")))

(magit-define-popup-action 'magit-push-popup
  ?M "for master" 'magit-push-for-master)
```

And maybe also the following generalized variant. Though I don't actually know whether that's something one would actually want to do when using Gerrit.

```lisp
(defun magit-push-for-branch (branch args)
  (interactive (list (magit-read-local-branch "Push HEAD to be integrated into branch")
                     (magit-push-arguments)))
  (-if-let (upstream (magit-get-upstream-remote branch))
      (progn (run-hooks 'magit-credential-hook)
             (magit-run-git-async "push" "-v" args upstream
                                  (concat "HEAD:refs/for/" branch)))
    (user-error "No upstream is configured for %s" branch)))

(magit-define-popup-action 'magit-push-popup
  ?O "for branch" 'magit-push-for-branch)
```
