### ISSUE TITLE
.git/index.lock is unexpectedly held by some process of unknown origin

### ISSUE THREAD

**Issue by bgamari** [magit/magit#2212] opened 2015-08-27 12:18 UTC
`git` commands such as `rebase` and `amend` run outside of magit tend to fail `emacs` has a file open in the same repository. The following error is produced,

```
git cherry-pick 1779ba85bea9db64257bb80e25fb6998bcc758e4
fatal: Unable to create '/opt/exp/ghc/ghc-landing/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

Yet looking in `.git` after the failure shows no such file. I believe that emacs is refreshing the file when it sees a change, which then causes magit to poke at the git repo, taking the lockfile and triggering the failure. The fact that  it is much harder to reproduce the issue when the `git` process in question is run in `strace` tends to support this hypothesis.

Ideally magit would have a hold-off time between seeing a change and refreshing its status to make it more likely that the repo is idle before poking at it.

**Comment by tarsius** [comment] 2015-08-27 12:47
Magit itself doesn't care about `.git/index.lock`. It's Git which is complaining about the lock, but you are aware of that. But Magit also does not "refresh" that file at all.

> Yet looking in `.git` after the failure shows no such file.

The process started by Magit failed because of the lock file. And the other process then finished normally and which causes the removal of the lock file.

> I believe that emacs is refreshing the file when it sees a change,

Emacs doesn't "refresh files", it does "revert file-visiting buffers" that have changed on disk, provided that `auto-revert-mode` is enabled. That only affects buffers which are actually being visited in a buffer.

Magit also provides a mechanism to do such reverts (see option `magit-revert-buffers`), but that only affects buffers that visit files in the working tree (unlike `.git/index.lock`). And again a buffer of course has to actually exist to be reverted.

> which then causes magit to poke at the git repo, taking the lockfile and triggering the failure.

As explained above I believe there is nothing that automatically triggers any file-visiting buffers to be reverted or Magit buffers to be refreshed.

I believe you are over thinking this. This is what I think is happening. A git process is running (presumably started outside of Magit) and then, while that process is still running, you do something in Magit which starts another git process which cannot run while another process is running. Git notices that and errors out. Seems like everything is behaving as intended.

**Comment by bgamari** [comment] 2015-08-27 14:02
> I believe you are over thinking this. This is what I think is happening. A git process is running (presumably started outside of Magit) and then, while that process is still running, you do something in Magit which starts another git process which cannot run while another process is running. Git notices that and errors out. Seems like everything is behaving as intended.

I should have been more explicit in my original message: I don't touch magit during this entire process. It appears to be emacs that is launching `git` processes unprovoked.

**Comment by tarsius** [comment] 2015-08-27 14:25
Do you use `magit-filenotify`? Can you reproduce with `emacs -Q` .... -l magit`?

**Comment by tarsius** [comment] 2015-08-29 16:22
There are two possibilities: an earlier git instance crashed, or there is indeed a git instance running which holds the lock.

In the second case the question is who started that instance and whether doing so is appropriate. It might be something completely unrelated to Emacs and Magit, in which case everything inside Emacs is behaving as expected. If something inside Emacs is doing it, then it might be Magit or it might be another package, for example VC or an extension to Magit.

While it is possible that Magit somewhere starts an asynchronous process when it should use a synchronous process, but I doubt it. In any case that process should be mentioned in the process log buffer, because all asynchronous git processes invoked by Magit get logged there. I also doubt that Magit is to blame, because then I would likely have heard about this before.

I think it is more likely that some other package is starting git and that that invocation holds the lock.

**Comment by bgamari** [comment] 2015-08-29 16:53
Sorry, I will attempt to reproduce this with `emacs -Q ` but this requires that I restart my development emacs session which is a bit painful. I'll give you an update when I get a chance to do this.

I am quite certain that this is not due to a crashed git process. If it were I would be able to observe the stale `.git/index.lock` after the failure.

That being said, I am fairly certain that the culprit here is emacs. Whether it's magit or a related package I can't yet say. I use spacemacs so it's entirely possible that it's a another package.

The hint of the process log is a good one. I'll check this.

**Comment by bgamari** [comment] 2015-09-03 09:19
@tarsius unfortunately I'm using spacemacs, so things seem to fail miserably when `emacs` is launched with `-Q`. In an effort to identify where these `git` calls are coming from I tried hooking `call-process`,

```
(fset 'real-call-process 'call-process)
(defun call-process (prog &optional infile dest displ &rest args)
       (message "call-proces %s" prog)
       (backtrace)
       (real-call-process prog infile dest displ args))
```

This resulted in,
```
nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil ((((((((...)))))))))
  real-call-process("git" nil (t nil) nil (((((((("ls-files" "-c" "-z" "--" "rts/Libdw.h")))))))))
  real-call-process("git" nil (t nil) nil ((((((("ls-files" "-c" "-z" "--" "rts/Libdw.h"))))))))
  real-call-process("git" nil (t nil) nil (((((("ls-files" "-c" "-z" "--" "rts/Libdw.h")))))))
  real-call-process("git" nil (t nil) nil ((((("ls-files" "-c" "-z" "--" "rts/Libdw.h"))))))
  real-call-process("git" nil (t nil) nil (((("ls-files" "-c" "-z" "--" "rts/Libdw.h")))))
  real-call-process("git" nil (t nil) nil ((("ls-files" "-c" "-z" "--" "rts/Libdw.h"))))
  real-call-process("git" nil (t nil) nil (("ls-files" "-c" "-z" "--" "rts/Libdw.h")))
  real-call-process("git" nil (t nil) nil ("ls-files" "-c" "-z" "--" "rts/Libdw.h"))
  call-process("git" nil (t nil) nil "ls-files" "-c" "-z" "--" "rts/Libdw.h")
  apply(call-process "git" nil (t nil) nil ("ls-files" "-c" "-z" "--" "rts/Libdw.h"))
  process-file("git" nil (t nil) nil "ls-files" "-c" "-z" "--" "rts/Libdw.h")
  apply(process-file "git" nil (t nil) nil "ls-files" ("-c" "-z" "--" "rts/Libdw.h"))
  vc-git--call((t nil) "ls-files" "-c" "-z" "--" "rts/Libdw.h")
  apply(vc-git--call (t nil) "ls-files" ("-c" "-z" "--" "rts/Libdw.h"))
  vc-git--out-ok("ls-files" "-c" "-z" "--" "rts/Libdw.h")
  vc-git-registered("/opt/exp/ghc/ghc-dwarf/rts/Libdw.h")
  apply(vc-git-registered "/opt/exp/ghc/ghc-dwarf/rts/Libdw.h")
  vc-call-backend(Git registered "/opt/exp/ghc/ghc-dwarf/rts/Libdw.h")
  ;; A couple frames of garbage
  vc-registered("/opt/exp/ghc/ghc-dwarf/rts/Libdw.h")
  vc-backend("/opt/exp/ghc/ghc-dwarf/rts/Libdw.h")
  vc-find-file-hook()
  auto-revert-handler()
  auto-revert-notify-handler(((6 . "Libdw.h") attribute-changed "/opt/exp/ghc/ghc-dwarf/rts/Libdw.h"))
  file-notify-callback((6 (attrib) "Libdw.h" 0))
  file-notify-handle-event((file-notify (6 (attrib) "Libdw.h" 0) file-notify-callback))
  funcall-interactively(file-notify-handle-event (file-notify (6 (attrib) "Libdw.h" 0) file-notify-callback))
  call-interactively(file-notify-handle-event nil [(file-notify (6 (attrib) "Libdw.h" 0) file-notify-callback)])
  command-execute(file-notify-handle-event nil [(file-notify (6 (attrib) "Libdw.h" 0) file-notify-callback)] t)
```

This seems to pretty clearly indicate that the problem is `vc`, not `magit`. I'll close this issue and bring it up with the `vc` folks (do you know who this might be?)

@tarsius thanks for your help!

**Comment by mgalgs** [comment] 2015-09-09 00:44
I'm no longer been able to reproduce the "Instant Fixup" hang I mentioned in #2214 after removing `vc`'s `find-file-hook`:

```elisp
(remove-hook 'find-file-hooks 'vc-find-file-hook)
```

**Comment by bgamari** [comment] 2016-02-05 10:08
This is a `vc` or `autorevert` issue. I reported it as [emacs #21559](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21559).

**Comment by Alexander-Shukaev** [comment] 2016-12-10 16:47
The issue continues and is more severe now with latest Magit regardless of the VC feature (see #2708).

**Comment by tarsius** [comment] 2016-12-10 17:09
Closing again in favor or #2708, which I also just reopened.

**Closed by tarsius** 2016-12-10 17:09 UTC
Labels: bug emacs
