### ISSUE TITLE
with-editor version problem

### ISSUE THREAD

**Issue by chylli** [magit/magit#2497] opened 2016-01-18 04:05 UTC
When I update spacemacs packages I got this error:
```
--> installing package: magit@git... [1/9]
An error occurred while installing magit (error: (error Need package `with-editor-20160118', but only 20160117.1513 is available))
--> installing package: git-commit@git... [9/9]
An error occurred while installing git-commit (error: (error Need package `with-editor-20160118', but only 20160117.1513 is available))
```

**Comment by robbyoconnor** [comment] 2016-01-18 04:16
I too am getting this issue too

**Comment by kyleam** [comment] 2016-01-18 04:18
It hasn't gotten around to be updated yet.  See #2202 and #2496.

**Comment by kyleam** [comment] 2016-01-18 05:10
Sorry, I should have looked a bit more closely.  I think there is a timezone discrepancy.  It seems that while the with-editor dependency was marked as 201601**18**, which matched the commit date, MELPA considered the build as 201601**17**.  (I think MELPA's timezone may be PST.)

**Comment by robbyoconnor** [comment] 2016-01-18 05:18
:+1:

**Comment by darth10** [comment] 2016-01-18 05:25
+1. Got this error today

**Comment by ad1217** [comment] 2016-01-18 06:42
This issue seems to still exist in `git-commit.el`.

**Comment by chylli** [comment] 2016-01-18 06:53
--> installing package: magit@git... [1/6]
An error occurred while installing magit (error: (error Need package `with-editor-20160118', but only 20160117.1513 is being installed))
--> installing package: evil-magit@git... [3/6]
An error occurred while installing evil-magit (error: (error Need package `with-editor-20160118', but only 20160117.1513 is being installed))
--> installing package: git-commit@git... [4/6]
An error occurred while installing git-commit (error: (error Need package `with-editor-20160118', but only 20160117.1513 is available))
--> installing package: linum-relative@spacemacs... [6/6]

**Comment by kyleam** [comment] 2016-01-18 07:15
> This issue seems to still exist in git-commit.el.

Doh, should be fixed now.  I'm not sure how long it will take to be updated on MELPA. 

(@tarsius: Sorry for spreading this across more than one commit.)

**Comment by zot** [comment] 2016-01-18 09:23
Opened a melpa issue about rejecting versions with bad dependencies: https://github.com/milkypostman/melpa/issues/3502

**Comment by robbyoconnor** [comment] 2016-01-18 09:34
@zot it's pretty bad

**Comment by robbyoconnor** [comment] 2016-01-18 09:34
This should automate :|

**Comment by zot** [comment] 2016-01-18 10:04
I'm (sort of) sure it's melpa's intention to automate this -- I think that's part of what they mean by curated.  Now that the issue is there, hopefully they'll be able to fix it.

**Comment by young40** [comment] 2016-01-18 10:05
got this issue, too

**Comment by robbyoconnor** [comment] 2016-01-18 10:19
You and hundreds of others @young40

**Comment by zot** [comment] 2016-01-18 10:22
Gotta wait another 3 hours, I think: https://melpa.org/#/ says "Current build started: an hour ago, last took 4 hours" and clicking on git-commit shows the bad dependency.

**Comment by mrkkrp** [comment] 2016-01-18 10:57
MELPA maintainers should be able to selectively restart the build for Magit.

**Comment by robbyoconnor** [comment] 2016-01-18 11:30
We can close this now -- it works.

**Comment by young40** [comment] 2016-01-18 11:48
it works now for me.

**Comment by darth10** [comment] 2016-01-18 12:52
`magit-20160117.2129` works fine! This can be closed.

**Comment by tarsius** [comment] 2016-01-18 14:05
@kyleam Thanks for the fix.

**Closed by tarsius** 2016-01-18 14:05 UTC
Labels: fly

**Comment by milkypostman** [comment] 2016-01-18 17:54
Just as a side note: you should never depend on version numbers from MELPA. Package requires should use the stable version numbers defined by the other package.

**Comment by tarsius** [comment] 2016-01-18 18:50
@milkypostman I am afraid I have to disagree. /cc @purcell 

Given two packages `foo` and `bar`, the later depending on the former, we might get into this situation.

1. `bar-2` depends on `foo-1`
2. The Melpa snapshot "versions" are `bar-20160102` and `foo-20160101`.
3. A user installs `bar-20160102` bringing in `>= foo-1`, which is satisfied by `foo-20160101`.
4. A big change is made to `foo`. It is released as `foo-3` and known as `foo-20160103` on Melpa.
5. `bar` is adjusted to take advantage of the cool additions in `foo-3`. That adjustment is incompatible with `foo-1`, so the **dependency is bumped from `foo-1` to `foo-3`**. The result is released as `bar-4` and known as `bar-20160104` on Melpa.
6. A user who previously had `bar-20160102` installed, updates to `bar-20160104`
7. `bar-20160104` depends on `foo-3`. **Since `20160101 > 3` the dependency on `>= foo-3` is satisfied**.
8. However `bar-4` / **`bar-20160104` is not compatible with `foo-1`**.
9. The user reports the issue "function foo-new-feature is undefined" in `bar`s issue tracker, and is told to install `foo-20160103`.
10. ~~`magit`~~ `bar` is very popular, half a dozen duplicates about the same issue are being opened.

The only proper fix I can see for this issue, is to implement https://github.com/milkypostman/melpa/issues/2955.

**Comment by tarsius** [comment] 2016-01-18 19:00
By the way the tagged, stable Magit releases do **not** depend on snapshots. When I created a release, then I "increase" the minimal version required from e.g. `20160101` to `2.0`, and create a tag (from which Melpa will create the Melpa-stable package), then I create the release tag, then I change the minimal version again, this time from `2.0` to `20160102`, and then finally I push the two (or more commits) as well as the tag).

That's quite a hack, but I have no other choice. For the most part I have automated this, see the make targets `bump-version` and `melpa-post-release`.

**Comment by milkypostman** [comment] 2016-01-18 21:29
@tarsius your example is a user malfunction. why would you not also update `foo` when updating `bar`? I guess that we can make this more clear. If you update one package you should update all packages. 

MELPA has always been intended to replace using `git pull` for all your packages in which case you are supposed to update all packages. Thus, if you update any package you should update them all.

**Comment by vyp** [comment] 2016-01-19 06:04
Emacs has no way of loading two separate versions of the same library/package, so I think it has to be done the way @milkypostman says. i.e. no partial upgrades for best results.

Maybe the solution is to separated `with-editor`, `git-commit` etc into different repositories and make new releases (i.e. git tags) whenever needed (meaning you wouldn't need to rely on snapshot version numbers). But I'm guessing there's a good reason to have them in the same repository.

**Comment by tarsius** [comment] 2016-01-20 01:03
> Emacs has no way of loading two separate versions of the same library/package,

I believe that in 25.1 `package.el` does some unload voodoo, which is supposed to prevent packages from being build with old versions of dependencies still in effect. I am not sure that is going to work perfectly reliable though. It doesn't matter though, Magit already uses `async` to ensure (reliabley) that `package.el` doesn't use outdated versions.

> so I think it has to be done the way @milkypostman says. i.e. no partial upgrades for best results.

Many users don't know about that.

> (meaning you wouldn't need to rely on snapshot version numbers)

`19700101` would still be larger than `2.4.0`, or `7682` (which we would be at if I created a release for each and every commit).

@milkypostman @purcell If magit and its internal dependencies were build in quick succession, then that would avoid the "magit becomes unavailable for a few ours after every release" issue. I don't really understand how builds happen, but maybe this would work:

```diff
diff --git a/scripts/parallel_build_all b/scripts/parallel_build_all
index 18e9c11..c6cfb43 100755
--- a/scripts/parallel_build_all
+++ b/scripts/parallel_build_all
@@ -18,9 +18,21 @@ function build_all {
     # grep --files-with-match wiki recipes/* | xargs make -j1 &
     make SLEEP=2 -j1 $(grep --files-with-match wiki recipes/*) &
     # grep --files-without-match wiki recipes/* | xargs make -j4 &
-    make -j4 $(grep --files-without-match wiki $(find recipes/ -type f -not -name python-info -and -not -name python3-info | sort)) &
+    make -j4 $(grep --files-without-match wiki $(find recipes/ -type f \
+      -not -name python-info -and \
+      -not -name python3-info -and \
+      -not -name with-editor -and \
+      -not -name git-commit -and \
+      -not -name magit-popup -and \
+      -not -name magit | sort)) &
     wait
 
+    # These packages have to be build in quick succession.
+    make recipes/with-editor
+    make recipes/git-commit
+    make recipes/magit-popup
+    make recipes/magit
+
     # python-info and python3-info are too big to run while other are
     # running. Running these separately should speed up other builds and
     # make this package actually build.
```

**Comment by hello-code** [comment] 2016-01-20 03:25
I met this issue too.
The solution is : Wait ! - Wait one hour or two hours.

**Comment by purcell** [comment] 2016-01-22 22:56
Ideally we'd try to resolve and build dependencies recursively, but that would imply a `make`-style build, and generating the dependency rules would first involve updating all the repositories. So the general solution to this would be to build in several passes: first update all the repos, then analyse dependencies which we might be responsible for building, and then build everything using the dependencies to inform the order. That'd be a lot of work.

But in general, if multiple separate packages are always released in exact lock-step with the same versions and hard interdependencies, then maybe they aren't separate packages after all.

**Comment by vyp** [comment] 2016-01-23 12:30
> I believe that in 25.1 package.el does some unload voodoo, which is supposed to prevent packages from being build with old versions of dependencies still in effect. [...]

@tarsius Are you saying that two packages that rely on different versions of the same library can each load their preferred version of that library? I thought that would be impossible simply because that's the way emacs lisp itself works. If that's really what you're saying, I can see this being a pretty huge feature with regards to emacs packages, even if the lack of it so far hasn't really caused too much problems. (But I don't think it really helps with the issue here though does it?)

> `19700101` would still be larger than `2.4.0`, or `7682` (which we would be at if I created a release for each and every commit).

Yeah, you're right. :/

> But in general, if multiple separate packages are always released in exact lock-step with the same versions and hard interdependencies, then maybe they aren't separate packages after all.

@purcell Yeah but the async and dash dependencies in magit use snapshot version numbers, but of course they can be used completely separately from magit (i.e. they *are* indeed separate packages).

**Comment by tarsius** [comment] 2016-01-27 18:07
> So the general solution to this would be to build in several passes ... That'd be a lot of work.

That would be the best approach ... and I understand :-)

> But in general, if multiple separate packages are always released in exact lock-step with the same versions and hard interdependencies, then maybe they aren't separate packages after all.

"In general" yes, and to some extend this also applies here. But for each of these packages there is another package on Melpa which depends on it directly. Which suggests that providing these libraries as separate packages is of value to at least some people. Also I have made this libraries available as separate packages because I was asked to do so.

* I will probably move `with-editor.el` to a separate repository. Now that it is pretty much "done", that shouldn't cause much additional work. But while it was still under development that was not an option.

* I would prefer to distribute `git-commit` a part of `magit`, but for historic reasons I cannot do that.

* Despite its name, `magit-popup` is a general purpose library.

The reason the version numbers go up for all packages at the same time is that *Melpa* used to make it impossible to not do so. Now that Melpa supports `:version-regexp` I could, and probably will, stop bumping all packages when Magit's version increases.

In any case, I know now how I can prevent issues like this for future releases (even if I should stick to bumping all versions at the same time). So there is no need for you to do anything.

> Are you saying that two packages that rely on different versions of the same library can each load their preferred version of that library?

No, the voodoo only (tries to) prevent new code being compiled with old macro definitions still in place. I.e. it prevents old code leaking into new byte-code files which are supposed to contain new versions of the code.

**Comment by vyp** [comment] 2016-01-28 06:14
> No, the voodoo only (tries to) prevent new code being compiled with old macro definitions still in place. I.e. it prevents old code leaking into new byte-code files which are supposed to contain new versions of the code.

Ah I understand, that makes much more sense. Thank you.
