### ISSUE TITLE
Jump from a diff to a log of relevant commits

### ISSUE THREAD

**Issue by yurikhan** [magit/magit#2811] opened 2016-10-05 16:32 UTC
I am reading a diff between two revisions, say `A..B`, possibly limited to a single file.

Once in a while, I stumble on a hunk that I’d like to investigate in detail. I want to press a key or two and see the commit(s) that introduce the change I’m currently looking at.

Since that is kind of vague, let’s say I want the equivalent of <kbd>l =L</kbd> `file` <kbd>RET</kbd> `start,+lines` <kbd>RET l</kbd> `range` <kbd>RET</kbd>, where `file`, `start` and `lines` are taken from the current hunk and `range` is the current diff’s range. The log should not be limited to the file, even if the diff was.

If point is in a file section but not in a hunk section, fall back to the log of all commits in range touching the file.

**Comment by tarsius** [comment] 2016-10-09 19:38
Duplicate of #2588.

**Closed by tarsius** 2016-10-09 19:38 UTC
Labels: duplicate
