### ISSUE TITLE
Refining hunks can be slow because smerge-refine-subst is inefficient

### ISSUE THREAD

**Issue by yyr** [magit/magit#1581] opened 2014-10-28 03:33 UTC
This issue was originally titled *args-out-of-range and other errors with latest next branch.* but we then went on mainly discussing the performance issue which was also mentioned.

It was then changed to *Highlighting of diffs sometimes takes a long time* and later to what you see above.

----

Press n on magit-status buffer I get this backtrace.

```
Debugger entered--Lisp error: (args-out-of-range [cl-struct-magit-section branch "master" #<marker (moves after insertion) at 1 in *magit: ~/.emacs.d/*> #<marker at 58 in *magit: ~/.emacs.d/*> #<marker at 144 in *magit: ~/.emacs.d/*> nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: ~/.emacs.d/*> nil nil nil nil nil nil nil (#1)] ([cl-struct-magit-section branch "origin/master" #<marker (moves after insertion) at 58 in *magit: ~/.emacs.d/*> nil #<marker at 122 in *magit: ~/.emacs.d/*> nil nil nil nil #1 nil] [cl-struct-magit-section tag "v0.4" #<marker (moves after insertion) at 122 in *magit: ~/.emacs.d/*> nil #<marker at 143 in *magit: ~/.emacs.d/*> nil nil nil nil #1 nil])] 12)
  magit-section-forward()
  call-interactively(magit-section-forward nil nil)
  command-execute(magit-section-forward)
```

There are other problems I see, may or may not be related. this is in my from *messages* buffer

magit-section-ident: Wrong type argument: arrayp, ([cl-struct-magit-section branch "master" #<marker (moves after insertion) at 1 in *magit: ~/.emacs.d/*> #<marker at 58 in *magit: ~/.emacs.d/*> #<marker at 144 in *magit: ~/.emacs.d/*> nil nil nil nil ...])

Another one also from *messages* buffer 

```
Error in post-command-hook (magit-section-update-highlight): (wrong-type-argument arrayp ([cl-struct-magit-section branch "origin/master" #<marker (moves after insertion) at 58 in *magit: ~/.emacs.d/*> nil #<marker at 122 in *magit: ~/.emacs.d/*> nil nil nil nil [cl-struct-magit-section branch "master" #<marker (moves after insertion) at 1 in *magit: ~/.emacs.d/*> #<marker at 58 in *magit: ~/.emacs.d/*> #<marker at 144 in *magit: ~/.emacs.d/*> nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: ~/.emacs.d/*> nil nil nil nil nil nil nil (#3)] #1] nil] [cl-struct-magit-section tag "v0.4" #<marker (moves after insertion) at 122 in *magit: ~/.emacs.d/*> nil #<marker at 143 in *magit: ~/.emacs.d/*> nil nil nil nil [cl-struct-magit-section branch "master" #<marker (moves after insertion) at 1 in *magit: ~/.emacs.d/*> #<marker at 58 in *magit: ~/.emacs.d/*> #<marker at 144 in *magit: ~/.emacs.d/*> nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: ~/.emacs.d/*> nil nil nil nil nil nil nil (#3)] #1] nil]))
```

Thanks.
PS: I started to feel, I am bothering you with these reports may be. I think that you have already know about these issues and in the middle of fixing them. do you want me to stay away from next branch for a while?

**Comment by uu1101** [comment] 2015-03-05 09:53
More input on this issue.

As shown in previous profile, most time is spent in `smerge-refine-subst`, invoked by `magit-diff-refine-hunk`.  The former procedure creates two temporary files, runs `diff`on them and marks the result with properties.  What has not been clear to me up to now is that this whole procedure _is invoked on each key press_. Creating and diffing the files on each cursor movement is probably what causes the "sluginess" and "disk trashing".  Please, see the following backtrace:

~~~
magit-diff-refine-hunk [2 times]
  backtrace()
  magit-diff-refine-hunk([cl-struct-magit-section hunk (nil "-2,6" "+2,10") ...)
  magit-diff-paint-hunk([cl-struct-magit-section hunk (nil "-2,6" "+2,10") ...)
  magit-diff-highlight-recursive([cl-struct-magit-section hunk (nil "-2,6" "+2,10") ...)
  magit-diff-highlight([cl-struct-magit-section hunk (nil "-2,6" "+2,10") ...)
  run-hook-with-args-until-success(magit-diff-highlight [cl-struct-magit-section hunk (nil "-2,6" "+2,10") ...)
  magit-section-update-highlight()
~~~

It seems to me that it would suffice to refine the hunk once, when it is created.  Would it be possible to avoid refining the hook when moving the cursor?

Thank you,
uu1101.

**Comment by Silex** [comment] 2015-03-05 10:12
I second this. When using `D` on diff hunks it seems to recompute the diff on each movements when moving inside a hunk.

**Comment by tarsius** [comment] 2015-03-05 13:19
> it seems to recompute the diff on each movements when moving inside a hunk

I don't think that's correct, hunks (like any section) are only repainted when point moves into the section from outside the section. Not when moving within. And when `magit-diff-refine-hunk` is `t`, then refining is part of the repaint step (see `magit-diff-paint-hunk`).

Besides a boolean, the value of `magit-diff-refine-hunk` can also be `all`, in which case all hunks are repainted at refresh time, instead of the hunks which later become the current section, due to movement. I assume "only refine the current hunk" was originally implemented as an alternative to "refine all hunks on each refresh" because the latter is to slow. Sadly it now looks like the former is also to slow. You might want to try setting it to `all`, this will make refreshing slower (e.g. after staging hunk) but movement faster.

Looks like another case where a workaround was added instead of fixing the issue:

> `smerge-refine-subst` ... procedure creates two temporary files, runs diff on them and marks the result with properties.

That sounds awful. Maybe it's time to implement a substitute for that function. (For smerge itself it might not matter if this is a bit slow, but here it does apparently. Also smerge might not have another choice but to write to disk, because it can't  use git, but we can).

There are two potential bottlenecks in `smerge-refine-subst`: it needs to write two files to disk and the result of comparing these two files is parsed in elisp. (It would be useful if someone figured out which is the real bottleneck by splitting that function in two, each of which handles one of the bottlenecks, before profiling).

Running an external command seems unavoidable but can we avoid writing two files to be read by that command by using `git diff` instead of `diff`? It seems not, at least not be writing a completely new parser. Given this diff:

```diff
diff --git a/magit.el b/magit.el
index 5ea25fd..56041b2 100644
--- a/magit.el
+++ b/magit.el
@@ -1,6 +1,6 @@
-;;; magit.el --- control Git from Emacs
+;;; MAGIT.el --- control Git from Emacs
 
-;; Copyright (C) 2008-2015  The Magit Project Developers
+;; COPYRIGHT (C) 2008-2015  The MAGIT Project Developers
 ;;
 ;; For a full list of contributors, see the AUTHORS.md file
 ;; at the top-level directory of this distribution and at
```

`diff -awd -ad magit.el.\~HEAD\~ magit.el` produces

```diff
1c1
< ;;; magit.el --- control Git from Emacs
---
> ;;; MAGIT.el --- control Git from Emacs
3c3
< ;; Copyright (C) 2008-2015  The Magit Project Developers
---
> ;; COPYRIGHT (C) 2008-2015  The MAGIT Project Developers
```

and `git diff --word-diff=porcelain` produces

```diff
diff --git a/magit.el b/magit.el
index 5ea25fd..56041b2 100644
--- a/magit.el
+++ b/magit.el
@@ -1,6 +1,6 @@
 ;;; 
-magit.el
+MAGIT.el
  --- control Git from Emacs
~
 
~
 ;; 
-Copyright
+COPYRIGHT
  (C) 2008-2015  The 
-Magit
+MAGIT
  Project Developers
~
 ;;
~
 ;; For a full list of contributors, see the AUTHORS.md file
~
 ;; at the top-level directory of this distribution and at
~
```

This differs in two ways: the format is generally different and one is per-line while the other is per-word. Per-word, seems like an advantage, we have to do less in elisp. But clearly we cannot just adapt the parsing code in `smerge-refine-subst` a little to deal with the output form git instead of diff. If it were only for the first difference, maybe we could.

So let's assume we go with `git --diff --word-diff=porcelain`; how would we hook that into existing Magit code?

I can see two general approaches.

1. Keep using regular `git diff` to generate the diffs to be displayed in Magit buffers. And then use `git diff` again, this time with `--word-diff=porcelain`, when refining hunk(s). This is basically the same as what we do now, except that we use git to produce the word diff. It also has the same problem; we still have to produce the word diff for each hunk individually. But now that might not be such a big problem because we don't write files to disk, and because hopefully our parsing will also be faster. 

  We could also cache the word diff, but that could turn out to be complicated, especially because a buffer may contain multiple diffs. Also we could maybe do the same if we stayed with `diff` anyway.

2. When hunk refinement is turned on (we would lose the ability to only refine the current hunk) use `git diff --word-diff=porcelain` up front. When parsing it convert it into what would have gotten without the argument, and convert the difference into refinement overlays. This way refinement would not be a separate step.

But either way (or another) this is going to be a lot of work.

So what can we do before the release? Not much I am afraid. There might be other reasons why diff might be slow at times, but this issue (by now) is about it being slow because of `smerge-refine-subst` specifically. I have changed the title accordingly. For other problems that cause the parsing/highlighting/painting of diffs to be slow open new issues. These other issues, if any, might or might not be addressed before the release.

But *this* issue is about slowness in an *optional* feature and the slowness is due to code *outside* of Magit, is *not* a regression (correct me if I am wrong), and fixing it would require *replacing* it with a different implementation (which would be a lot of work). Therefor I postpone this until after the release.

**Comment by uu1101** [comment] 2015-03-06 06:33
>> it seems to recompute the diff on each movements when moving inside a hunk
>
> I don't think that's correct, hunks (like any section) are only repainted when
> point moves into the section from outside the section. Not when moving
> within. And when `magit-diff-refine-hunk` is `t`, then refining is part of the
> repaint step (see `magit-diff-paint-hunk`).

With due respect, I disagree.  It *really* looks like it is updating:
setting a trace on `magit-section-update-highlight` (which is hooked to
`post-command-hook`), can confirm it.  This function then runs the hooks
in `magit-section-highlight-hook`, which finally invoke
`magit-diff-paint-hunk`.

For example, when adding the following line to the top of
`magit-section-update-highlight`:

~~~
      (message "magit-section-update-highlight: %s" (current-time))
~~~

One can see the messages in the minibuffer while moving in a hunk.

>> `smerge-refine-subst` ... procedure creates two temporary files, runs diff on
>> them and marks the result with properties.
>
> That sounds awful. Maybe it's time to implement a substitute ...
>
> ...
>
> But either way (or another) this is going to be a lot of work.
>
> So what can we do before the release? Not much I am afraid. There might be other reasons why diff might be slow at times, but this issue (by now) is about it being slow because of `smerge-refine-subst` specifically. I have changed the title accordingly. For other problems that cause the parsing/highlighting/painting of diffs to be slow open new issues. These other issues, if any, might or might not be addressed before the release.
>
> But *this* issue is about slowness in an *optional* feature and the slowness is due to code *outside* of Magit, is *not* a regression (correct me if I am wrong), and fixing it would require *replacing* it with a different implementation (which would be a lot of work). Therefor I postpone this until after the release. 

Sure, there is no urgent need here: note that the three or four
participants on this issue have not had enough impact to make the effort
to the search for the root cause for some months (that is my case, at
least).  And now we have the 'disable hunk refining' workaround.  Just
wanted to provide more input and highlight what I think the root cause
might be.

Best regards,
uu1101

**Comment by tarsius** [comment] 2015-03-06 11:08
> With due respect, I disagree. It *really* looks like it is updating: setting a trace on `magit-section-update-highlight` (which is hooked to `post-command-hook`), can confirm it. This function then runs the hooks in `magit-section-highlight-hook`, which finally invoke `magit-diff-paint-hunk`.

Indeed that seems to be the case and has to be fixed now. The reason `magit-section-update-highlight` does not abort when moving within the same section is that when the region is active/activated/deactivated then the highlighting really has to be updated, *especially* for hunks.

I will look into how to determine whether an update actually is required and/or how to at least avoid updating the refinement.

**Comment by tarsius** [comment] 2015-03-06 11:17
Does anyone know how to reliably determine whether the last command deactivated the mark?

**Comment by tarsius** [comment] 2015-03-06 12:06
I think this sentence is to clever for me to determine the intended meaning without any doubts:

> Sure, there is no urgent need here: note that the three or four participants on this issue have not had enough impact to make the effort to the search for the root cause for some months (that is my case, at least).

You could be saying that this indeed is not urgent. Or it could be sarcasm telling me that I should not further delay working on this. But then you go on explicitly including yourself among those who failed to determine the root cause in such a long time.

Anyway you have just provided *another* root cause: the refinement happening needlessly. The "other" root cause which was already known is that refinement is to slow. It was this second cause which I have decided not to work on until after the release.

The refinement happening needlessly (which was already brought up before, and which I did not believe initially) changes the picture. I will attempt to address this now, but this is far from trivial. So if this turns in major work, I might end up having to delay working on that too.

Coupling refinement with "washing" (which is part of the initial parsing) instead of "painting" (which is part of the un-/highlighting), as suggested above (in the "use word diff up front" approach) would also bypass the "refinement happens needlessly" problem.

The separation of washing and painting is only relevant for hunks and other diff related sections. It is necessary here because when the region is active we here do not actually use the region overlay, instead we create several overlays and/or ranges with text properties, both within the region, to communicate additional information. Only when the region is invalid as a magit selection (either "multiple file or hunk sections which are a valid selection" or "hunk internal region") does the region look as it would in other buffers.

That's all quite complicated and to not further complicate matters, I at some point decided that unhighlighting and then right away hightlighting the same section again is acceptable. Previously I had improved the performance of the highlighting - but forgot about the hunk refinement which is one case where the performance is *not* acceptable.

Completely reversing that design decision would be a lot of work. And if it turns out that this is what is required, then that won't happen before the release. But if I can find a way to just avoid needlessly unrefining and the right away refining again, then that could make it into the release.

**Comment by Silex** [comment] 2015-03-06 13:17
I confirm that now moving inside a diffed hunk doesn't seem to recompute the diffs all the time.

**Comment by tarsius** [comment] 2015-03-06 13:36
Please get the terminology right, i.e. use the terms that I use.

*Assuming that by "recompute diff" you actually mean "insert and wash diff":*

No it does not.

*Assuming that by "recompute diff" you actually mean "highlight diff/hunk":*

As I said changing that would not be easy.

*Assuming that by "recompute diff" you actually mean "refine hunk":*

Well of course, at some point the refinement has to happen and when you have chosen to only refine the current hunk then moving to another hunk means the latter now has to be refined.

It might be possible to avoid having to re-refine a hunk which has already been refined since the last refresh, by making these overlays invisible using the `invisible` overlay property. That would be less expensive but still not free and also yet more code.

Or instead of just giving the user the option to have either "only the current hunk" or "all hunks" refined, add a third mode which does refine hunks when they become current, but then *keep* the refinement when moving to another section. I.e. delayed refinement. But since refreshing would cause these refinements to be lost, that would likely be confusing and be reported as a bug.

**Comment by tarsius** [comment] 2015-03-06 13:37
No wait the `invisible` property makes the text invisible, not the overlay ineffective. So that won't work, but maybe there is something similar I cannot think of right now.

**Comment by uu1101** [comment] 2015-03-07 15:20
I am sorry for the confusion, it might be due to English not being my mother tongue.  I honestly meant that I do not consider this issue a blocker for the release; especially now that there is a workaround (disabling diff refinement).

To be clear, my view is that refining hunks via `smerge` being "heavyweight" is not a big deal, and at the moment don't see why should Magit optimize that now or in the future.  The issue is (was) performing it it needlessly.  With regards to that, I see three aspects to consider:
  * Hunks are re-refined when moving within a hunk.  You have fixed this, thanks!
  * Hunks are re-refined even when they are folded.  This means that moving to the "(unstaged)" heading computes the refinements for all hunks, even though they are not visible.  This one is vaguely annoying, but can be worked around.
  * Hunks are re-refined each time they are entered, even though the refinement could be "cached".  This would be nice-to-have.

I am writing this in a light-hearted spirit, with the intention of improving Magit, please take no offense from my words.  Thank you very much for the effort you put.

Best regards,
uu1101.

**Comment by tarsius** [comment] 2015-03-08 11:50
@uu1101 Don't worry, I figured it was all in good spirit.

> Hunks are re-refined even when they are folded. This means that moving to the "(unstaged)" heading computes the refinements for all hunks, even though they are not visible. This one is vaguely annoying, but can be worked around.

I might be able to do something about this but am not sure whether that will turn out to be simple enough to do it now.

**Comment by uu1101** [comment] 2015-03-08 20:52
Thinking a bit more about this, I wonder why should section highlight and hunk refinement go hand-in-hand.  That is, when I set `magit-diff-refine-hunk` to `t`, I want the hunk I am looking at to be refined, not on all hunks descendant of currently selected section.  The patch below refines hunks only when they are the current section; the disk churn is gone and the result is equally usable.

It seems that when `magit-diff-refine-hunk` is `all`, the refinement happens before, when washing, so this does not seem to interfere.

What do you think?

~~~{.patch}
diff --git i/magit-diff.el w/magit-diff.el
index f23f6d9..81c1dbd 100644
--- i/magit-diff.el
+++ w/magit-diff.el
@@ -1596,7 +1596,8 @@ of SECTION including SECTION and all of them are highlighted."
                                  'magit-diff-whitespace-warning)))))
 
 (defun magit-diff-refine-hunk (hunk)
-  (unless (magit-section-refined hunk)
+  (unless (or (magit-section-refined hunk)
+               (not (eq (magit-current-section) hunk)))
     (setf (magit-section-refined hunk) t)
     (save-excursion
       (goto-char (magit-section-start hunk))
}

**Comment by tarsius** [comment] 2015-04-02 13:24
@uu1101 That's a good suggestion and I almost forgot about it. Opening a new issue.

Uh wait this issue is still open... ah well already opened a new one :-/

**Comment by tarsius** [comment] 2015-04-29 18:39
Most of this should be addressed by now, see #1830.

Leaving the "`smerge-refine-subst` is inefficient" issue. That too is less relevant now that unnecessary refinement is being avoided. These things could be done additionally:

* Instead of unrefining a hunk when moving away, change the overlays to use an empty face. Avoids having to refine again later.
* Refine asynchronously.
* Actually figure out why it sometimes takes long.

I think all of that is unnecessary now. But let me know if you still see bad performance due to the refinement. Or if another issue mentioned above has not been addressed yet. I will then reopen this issue.

**Closed by tarsius** 2015-04-29 18:39 UTC
Labels: 10 feature request

**Comment by uu1101** [comment] 2015-04-30 06:55
Thank you very much.  I have not yet had time to review the changes, but will surely test it through the day. Again, thank you, have a good day!

**Comment by yyr** [comment] 2015-04-30 16:05
@tarsius Thanks for the work. I can see a lot of improvement in the performance. The basic navigation in my projects is *almost* instantaneous.

Thanks.

**Comment by uu1101** [comment] 2015-05-01 10:09
I have noticed a small regression when `magit-diff-refine-hunk` is set to `t`: when selecting a hunk region (in order to stage just some part of it) the non-refined highlight has its background removed, but the background for the refined part remains.

![screenshot from 2015-05-01 12 05 34](https://cloud.githubusercontent.com/assets/552356/7429025/7c237088-effa-11e4-86aa-e0f23a015b12.png)

It is no big deal, certainly not a blocker.  Just wanted to note it down. Thank you!

**Comment by tarsius** [comment] 2015-05-01 10:46
Actually it has been like this ever since I started removing the background outside the region. I don't see a simple way to prevent it and in some cases it might actually be helpful. So at least for now I leave it as is.

**Comment by uu1101** [comment] 2015-05-07 06:46
Sorry for the delay.

What I mean is that the refined background highlight (that of the word _SHOW_ in the screenshot) now remains even when outside the selected region, where before it was removed as well.  Compare with the following screenshot of 3eb8982:

![screenshot from 2015-05-07 08 39 48](https://cloud.githubusercontent.com/assets/552356/7509720/c0102a0e-f494-11e4-8e8a-f97ef9539813.png)

If you like, I can open a separate issue for this, as the performance issues that started this ticket are definitely over.

Again, thank you for your effort and for your spirit.

Best regards,
uu1101.

**Comment by tarsius** [comment] 2015-05-07 11:05
I just remembered I recently removed `'priority 2` from the relevant overlays. Putting that back should have fixed it, but it did not. So yes, better open a new issue
