### ISSUE TITLE
(wrong-type-argument transient-suffix [eieio-class-tag-- ...

### ISSUE THREAD

**Issue by vapniks** [magit/magit#4154] opened 2020-06-24 20:04 UTC
Hi, I'm using Magit 20200623.1341, Git 2.17.1, Emacs 25.2.2, gnu/linux
I get an error when I try to press the 'c' (commit) or 'P' (Push) keys in the magit buffer of a repo.
Here is the backtrace:
```
(wrong-type-argument transient-suffix [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil "-f" transient:magit-push:--force-with-lease t " %k %d (%v)" "Force with lease" nil nil nil nil nil nil nil nil nil "--force-with-lease" nil nil nil nil nil nil nil nil] object)
  signal(wrong-type-argument (transient-suffix [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil "-f" transient:magit-push:--force-with-lease t " %k %d (%v)" "Force with lease" nil nil nil nil nil nil nil nil nil "--force-with-lease" nil nil nil nil nil nil nil nil] object))
  transient--suffix-command([eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil "-f" transient:magit-push:--force-with-lease t " %k %d (%v)" "Force with lease" nil nil nil nil nil nil nil nil nil "--force-with-lease" nil nil nil nil nil nil nil nil])
  transient--make-transient-map()
  transient-setup(magit-push)
  magit-push()
  funcall-interactively(magit-push)
  call-interactively(magit-push nil nil)
  command-execute(magit-push)
```
I have tried reinstalling magit, and restarting emacs, but that didn't fix the problem.
I have noticed in my `*Packages*` buffer that `magit-circleci` and `magit-libgit` are incompatible with my version of emacs (they require emacs 25.3 & 26.1 respectively). Does that have something to do with the problem?

**Comment by tarsius** [comment] 2020-06-24 21:26
Duplicate of #4150 but lets talk here because this one comes with a backtrace.

Updating and/or recompiling `transient` should fix the issue.

I notice you both use Emacs 25 and I am guessing that both of you updated `magit` and/or `transient` while briefly trying out Emacs 26/27/28. Across those releases the internal representation of objects got changed once or twice, which obviously will lead to problems when switching Emacs versions.

**Comment by vapniks** [comment] 2020-06-24 23:39
As suggested, I recompiled `transient.el` and restarted emacs.
The problem now appears to have been fixed. Thankyou.

**Comment by xavierr** [comment] 2020-06-26 06:03
Same problem and same fix (recompile `transient.el` and started again emacs) worked for me. Thanks. I am using emacs 25.2.2

**Comment by sudeepdino008** [comment] 2020-06-28 11:12
How to recompile transient.el? It seems to be bundled with emacs

**Comment by jasaarim** [comment] 2020-07-06 08:32
I also ran into this: the first time starting the default Emacs on Ubuntu 18.04.4 (Emacs 25.2.2), [bootstapping straight.el](https://github.com/raxod502/straight.el#getting-started), and setting up Magit from Github with `(straight-use-package 'magit)`.

**Comment by lguez** [comment] 2020-07-19 09:20
Same problem, when I try to commit from Magit, I get the error:

Wrong type argument: transient-suffix, [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil ...

I am using Emacs 25.2.2 on Linux Mint 19.1. I have not been playing with any other version of Emacs. I have installed Magit version 20200713.2103 from Melpa (first time I try Magit).

**Comment by tarsius** [comment] 2020-07-19 09:31
Issues like this happen because one of these reasons.

- Some backward incompatible change in Emacs itself that requires that the byte-code is regenerated. I suggested that above but it appears that's not it in this case.

- Some backward incompatible change in one of the involved libraries itself, which is of a nature that causes the old now invalid incarnation of the think to leak into the byte-code generated from the new source, while the old version of the library has already been loaded.

  This seems to happen a lot when Eieio is involved. `package.el` should really use a separate `emacs` instance to prevent this sort of issue.

- If a macro is defined in one package and used in another package, then the package that uses it might have to be recompiled when the definition changes. This could be addressed by dumping dependencies, but it often gets overlooked.

**Closed** 2020-07-19 09:59 UTC

**Comment by jtongen1** [comment] 2020-07-20 14:07
for me, I tried uninstalling magit, git-commit, and transient, opening a new emacs process & re-installing magit, closing emacs, open a new one and re-test and that flow did not fix my issue.

After that I just deleted transient.elc and retested, and that did resolve the problem for me.

**Comment by matlupi** [comment] 2021-01-20 15:20
I have the same issue with emacs 27.1 and git 2.21.0

I see [above](https://github.com/magit/magit/issues/4154#issuecomment-649129460) that recompiling `transient.el` should help, however it is not indicated `HOW` to recompile the file.
@vapniks, could you elaborate on how you did it?

**Comment by mgarbade** [comment] 2022-07-25 13:18
> How to recompile transient.el? It seems to be bundled with emacs
> 

- Open emacs
- Ctrl - x, f (find file)
- ~/.emacs.d/elpa/transient-SOME_VERSION/transient.el
- now the file should open
- M-x `emacs-lisp-byte-compile` 
- press `ENTER`
- now transient.el should have recompiled

worked for me, I can finally use magit on WSL2 with Ubuntu 18.04 (which was a huge pain in the a** to get going)
