### ISSUE TITLE
Interactive rebase selects the latest commit when called from a file-visiting buffer

### ISSUE THREAD

**Issue by Zetagon** [magit/magit#4697] opened 2022-05-26 13:36 UTC
# Expected behaviour

Calling `magit-rebase-interactive` in a file-visiting buffer (or maybe just a non-magit buffer) via `M-x` or `magit-dispatch` should prompt for a commit.

# Observed behaviour

Instead of prompting a commit it selects the latest commit.

#   M-x magit-version RET
`Magit b4be194, Git 2.36.1, Emacs 28.1, gnu/linux`

# Probable cause

I digged around in the source and found that `magit-commit-at-point` will return the latest commit if the current buffer is visiting a file.  Not sure what the best way to fix this is, but the patch below seems to fix it.
```diff
 (defun magit-rebase-interactive (commit args)
   "Start an interactive rebase sequence."
-  (interactive (list (magit-commit-at-point)
+  (interactive (list (and magit-blame-mode (magit-commit-at-point))
                      (magit-rebase-arguments)))
   (magit-rebase-interactive-1 commit args
   ```

**Comment by kyleam** [comment] 2022-05-27 03:13
I agree with you that selecting a commit here is unexpected and undesirable, but your description seems a bit off:

> Instead of prompting a commit it selects the latest commit.

It looks to me like it's not necessarily the *latest* commit.  It's the commit that `git blame --porcelain`, called by `magit-current-blame-chunk`, reports for the line.

```
>  (defun magit-rebase-interactive (commit args)
>    "Start an interactive rebase sequence."
> -  (interactive (list (magit-commit-at-point)
> +  (interactive (list (and magit-blame-mode (magit-commit-at-point))
>                       (magit-rebase-arguments)))
>    (magit-rebase-interactive-1 commit args
```

I think this is the right idea, but this location is too aggressive.  There are modes besides `magit-blame-mode` in which `magit-commit-at-point` should return a commit (e.g., a log buffer).

Perhaps the best spot for that guard would be `magit-commit-at-point` (and `magit-branch-or-commit-at-point`), something like:

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 6c6630c7..26636fbd 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -1513,7 +1513,8 @@ (defun magit-remote-branch-at-point ()
 (defun magit-commit-at-point ()
   (or (magit-section-value-if 'commit)
       (magit-thing-at-point 'git-revision t)
-      (and-let* ((chunk (and (fboundp 'magit-current-blame-chunk)
+      (and-let* ((chunk (and (bound-and-true-p magit-blame-mode)
+                             (fboundp 'magit-current-blame-chunk)
                              (magit-current-blame-chunk 'addition t))))
         (oref chunk orig-rev))
       (and (derived-mode-p 'magit-stash-mode
@@ -1534,7 +1535,8 @@ (defun magit-branch-or-commit-at-point ()
                      (magit-ref-p (format "refs/pullreqs/%s"
                                           (oref (oref it value) number))))))
       (magit-thing-at-point 'git-revision t)
-      (and-let* ((chunk (and (fboundp 'magit-current-blame-chunk)
+      (and-let* ((chunk (and (bound-and-true-p magit-blame-mode)
+                             (fboundp 'magit-current-blame-chunk)
                              (magit-current-blame-chunk 'addition t))))
         (oref chunk orig-rev))
       (and magit-buffer-file-name
```

Another option would be making `magit-current-blame-chunk` itself check `magit-blame-mode`, but I think that'd break `magit-edit-line-commit` (and perhaps some other things).

**Comment by tarsius** [comment] 2022-05-27 10:43
The message of 40ad7a25cd isn't particularly helpful when trying to figure out what the intended scope of this changes was. But it is followed by bcadb58ef9, so I am pretty sure that was the intended use-case. In any case, not dwiming when we could, is better than automatically using a commit that we shouldn't use.

Kinda funny the role `magit-log-merged` plays here. To investigate this issue I used that command but it had a bug. And then it turns out that this issue was caused by a change made for the benefit of that command. :grinning:

**Comment by tarsius** [comment] 2022-05-27 10:51
I think I did not realize that `magit-current-blame-chunk` returns something even when `magit-blame-mode` is not turned on, so I am going with the proposed fix.

Kinda funny the role `magit-log-merged` plays here. To investigate this issue I used that command but it had a bug. And then it turns out that this issue was caused by a change made, at least in part, for the benefit of that command. (The commit that started to use `magit-current-blame-chunk` is followed by a commit that makes a minor tweak to `magit-log-merged` and picking up the current chunk is clearly beneficial for that command.) :grinning:

**Closed** 2022-05-27 10:55 UTC
Labels: fly
