### ISSUE TITLE
eol convention sometimes ignored

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2701] opened 2016-06-16 22:51 UTC
Hello,

magit-version => 20160614.1158

I'm working on a file that is encoded with utf-8-dos.  This one, to be precise: https://github.com/michael-heerdegen/hyper-german-trans/blob/master/language-de.cpp.

So, I'm on Debian using Unix style eol (end of line)  convention, and the file has the dos style eol convention.  Normally, this works transparently when working with Emacs, because it auto-detects the coding system.

But Magit has problems: if I hit E s, the ~HEAD~ buffer shows a ^M at each line's end (i.e. uses wrong coding), but ~{index} and the file itself don't.  As a result, it's nearly impossible to work with this (stage).

AFAIK the reason for the difference is that the index is opened as a file generated by git, so Emacs cares about encoding when opening it.

File version OTOH are got from git directly as a string (cat-file).  Dunno how much coding system aware Git is, anyway, Emacs receives the string with the "^M" chars in effect.

As a workaround, piping the string through `detect-coding-string` seems to help (fix the issue), but I'm not sure if it's the right thing to do.

There is a part number 2: magit-update-index must do the same thing in reverse: currently, we do
```
(with-temp-file index
            (insert-buffer-substring buffer))
```
which ignores eol convention as well, removing all ^M chars.  It seems that binding `coding-system-for-write` to `buffer-file-coding-system` (which is bound in the index buffer) fixes this.

But note I'm not sure if my fixes are correct as I don't know how many decodings and encodings are happening in the communication between Magit and Git.

More Magit commands may be concerned by this issue.

TIA, Michael.

**Comment by michael-heerdegen** [comment] 2016-06-17 23:10
I think VC's `vc-find-revision` and `vc-git-find-revision` and how they bind coding system variables may give you hints about what should be the right thing.

**Comment by npostavs** [comment] 2016-06-18 01:24
I'm not sure I understand the issue, but is it affected by `magit-process-ensure-unix-coding-system`? (cf #2587 and linked issues)

**Comment by michael-heerdegen** [comment] 2016-06-18 01:44
Noam Postavsky <notifications@github.com> writes:

> I'm not sure I understand the issue, but is it affected by
> magit-process-ensure-unix-coding-system? (cf #2587 and linked issues)

Seems related.  How can I try that stuff out?  Just use master (I use
the Melpa package ATM) - or do I need additional configuration?

**Comment by npostavs** [comment] 2016-06-18 01:48
That was merged a few months ago, so the Melpa package should have this option already.

**Comment by michael-heerdegen** [comment] 2016-06-18 02:00
Ah, I have it, yes.

My issue is essentially https://github.com/magit/magit/issues/2583, but unlike there, I'm  using Ediff to stage, not the status buffer.  The resulting problem seems to be analogue.

I will try to find out why magit-process-ensure-unix-line-ending -> t doesn't help in my case.  Maybe the solution for https://github.com/magit/magit/issues/2583 doesn't touch my scenario at all.

**Comment by michael-heerdegen** [comment] 2016-06-18 02:01
Or would you prefer that I instead create a step-by-step recipe?

**Comment by npostavs** [comment] 2016-06-18 02:11
Ah, actually, according to https://github.com/magit/magit/pull/2584#issuecomment-195706557 that's a Windows-only thing, so maybe it's not really so related.

This encoding stuff is tricky, so I think having a recipe from `emacs -Q` would be helpful for clarifying things.

**Comment by michael-heerdegen** [comment] 2016-06-18 02:27
Hhm, maybe it's the opposite?  Dunno, but if that issue was about editing unix style files under Windows, I must do it the other way round.

Anyway, staging and unstaging from the status buffer works as expected.

My issue is about staging with Ediff and is actually quite easy to reproduce: Try to stage something with E s for a file using dos eol convention on unix (you get a three windowed Ediff frame), and you'll see at least two problems:

1.  the ~HEAD~ version displayed as ediff buffer A shows CR chars at the end of each line (annoying, but not fatal)

2.  If you stage something: c b, your staged hunks will have CR chars removed. This is actually really bad.  For example, if you stage only one line from ediff, at the end you'll see that the staging area contains changes for every line of the file - the removed cr chars.

**Comment by npostavs** [comment] 2016-06-18 02:39
Can you remind how to add a CRLF file without git converting to LF

```
~/tmp/git1$ git add foo.crlf 
warning: CRLF will be replaced by LF in foo.crlf.
The file will have its original line endings in your working directory.
```

Or is this actually the case you're talking about?

**Comment by michael-heerdegen** [comment] 2016-06-18 02:58
Noam Postavsky <notifications@github.com> writes:

> Can you remind how to add a CRLF file without git converting to LF
>
> ~/tmp/git1$ git add foo.crlf 
> warning: CRLF will be replaced by LF in foo.crlf.
> The file will have its original line endings in your working directory.

I did it from Magit, with s over the new file, and c to commit.  But I
also don't get such a warning when running git:

bash-4.3:micha:test2$ git init
Initialized empty Git repository in /home/micha/Treasure/today/test2/.git/
bash-4.3:micha:test2$ git add ./language-de.cpp
bash-4.3:micha:test2$ git version
git version 2.8.1

> Or is this actually the case you're talking about?

No.

**Comment by npostavs** [comment] 2016-06-18 04:48
Ah, I have `core.autocrlf = input` set in my git config, I can reproduce the issue without that.

So your problem seems to be fixed with
```diff
modified   lisp/magit.el
@@ -1205,7 +1205,8 @@ (defun magit-find-file-noselect (rev file)
       (setq file (file-relative-name file topdir)))
     (or (magit-get-revision-buffer rev file)
         (with-current-buffer (magit-get-revision-buffer-create rev file)
-          (let ((inhibit-read-only t))
+          (let ((inhibit-read-only t)
+                (process-coding-system-alist '(("git" . undecided))))
             (erase-buffer)
             (magit-git-insert "cat-file" "-p" (concat rev ":" file)))
           (setq magit-buffer-revision  (magit-rev-format "%H" rev)
```

Which tells Emacs to guess the encoding of the file content received from git. But we should probably try to make the encoding match the buffers we compare against, rather than guessing from scratch each time.

**Comment by michael-heerdegen** [comment] 2016-06-18 23:05
Noam Postavsky <notifications@github.com> writes:

> So your problem seems to be fixed with
>
> modified   lisp/magit.el
> @@ -1205,7 +1205,8 @@ (defun magit-find-file-noselect (rev file)
>        (setq file (file-relative-name file topdir)))
>      (or (magit-get-revision-buffer rev file)
>          (with-current-buffer (magit-get-revision-buffer-create rev file)
> -          (let ((inhibit-read-only t))
> +          (let ((inhibit-read-only t)
> +                (process-coding-system-alist '(("git" . undecided))))
>              (erase-buffer)
>              (magit-git-insert "cat-file" "-p" (concat rev ":" file)))
>            (setq magit-buffer-revision  (magit-rev-format "%H" rev)


Thanks so far.  For me, only the first part is fixed: all three ediff
buffers now "look correct", i.e. have correct eol style.

But you probably also need to change `magit-update-index` as I
suggested: With your patch, when I stage only one hunk with Ediff,
still the whole file is changed wrt line endings (this had been my part
2).

> Which tells Emacs to guess the encoding of the file content received
> from git. But we should probably try to make the encoding match the
> buffers we compare against, rather than guessing from scratch each
> time.

Maybe it would be reasonable to ask the user when these methods come to
different conclusions, because it's undecidable what the user wants in
this case.

**Comment by npostavs** [comment] 2016-06-19 03:34
> But you probably also need to change `magit-update-index` as I suggested: With your patch, when I stage only one hunk with Ediff, still the whole file is changed wrt line endings (this had been my part 2).

Ah, yes, missed that.

>> Which tells Emacs to guess the encoding of the file content received
>  from git. But we should probably try to make the encoding match the
>  buffers we compare against, rather than guessing from scratch each
>  time.
>
> Maybe it would be reasonable to ask the user when these methods come to
> different conclusions, because it's undecidable what the user wants in
> this case.

I think the only time where the guess from scratch would give different results is when the user is changing the encoding of the file. In this case, letting Emacs guess each time would result in identical buffer contents even though the file has changed. Trying to stage from that would give wrong results, I think, so there's no point in offering that option.

**Comment by michael-heerdegen** [comment] 2016-06-19 14:29
Noam Postavsky <notifications@github.com> writes:

>  Maybe it would be reasonable to ask the user when these methods come to
>  different conclusions, because it's undecidable what the user wants in
>  this case.
>
> I think the only time where the guess from scratch would give
> different results is when the user is changing the encoding of the
> file.

Yes, that's what I meant.

> In this case, letting Emacs guess each time would result in identical
> buffer contents even though the file has changed. Trying to stage from
> that would give wrong results, I think, so there's no point in
> offering that option.

But isn't `magit-find-file-noselect' used also to check out prior
revisions from files?

I had in mind E r (ediff range).  If the user

  (1) made some changes
  (2) changed eol convention
  (3) made more changes

and wants to undo some of the changes made in (1) with E r, he doesn't
want to see changed eol style in that ediff.

**Comment by npostavs** [comment] 2016-06-19 14:40
Ah, that makes sense. Perhaps only `E s` should require same encoding.

>  wants to undo some of the changes made in (1) with E r,

How does one undo changes with `E r` though? It makes 2 read-only buffers.

**Comment by michael-heerdegen** [comment] 2016-06-19 14:43
Noam Postavsky <notifications@github.com> writes:

> How does one undo changes with E r though? It makes 2 read-only
> buffers.

When you enter only a single commit id, it ediffs against the opened
file whose buffer is just reused.

**Comment by npostavs** [comment] 2016-06-21 03:40
Please take a look at #2704.

**Comment by michael-heerdegen** [comment] 2016-06-22 00:08
Noam Postavsky <notifications@github.com> writes:

> Please take a look at #2704.

Looks reasonable... I'll test it for some days to see if it works as
intended, and report back.  Thanks so far!

**Comment by michael-heerdegen** [comment] 2016-06-26 14:03
Didn't find any problems, it worked as expected all the time.
Can we install the patch?

**Comment by npostavs** [comment] 2016-06-27 01:11
Ah, forgot to mention it here, but I changed the code a bit. Did you test the original or the new one? https://github.com/magit/magit/pull/2704#issuecomment-227731533

**Comment by michael-heerdegen** [comment] 2016-06-27 02:42
Noam Postavsky <notifications@github.com> writes:

> Ah, forgot to mention it here, but I changed the code a bit. Did you
> test the original or the new one?  #2704 (comment)

Seems I tested the old code.  Ok, will continue testing with fed2b0b3,
the current head of pull-request/2704/head.

**Comment by michael-heerdegen** [comment] 2016-07-05 18:45
It seems to work well as well.  I would say: let's merge!

**Comment by npostavs** [comment] 2016-07-07 01:59
> It seems to work well as well. I would say: let's merge!

It's done!

**Closed** 2016-07-07 01:59 UTC
Labels: bug
