### ISSUE TITLE
Modified file does not show up in status buffer

### ISSUE THREAD

**Issue by felipeochoa** [magit/magit#2879] opened 2016-12-01 17:27 UTC
I ran into this issue with a `.dot` file in my repository (on Windows 10). It's fairly straightforward to reproduce on my computer in a `-Q` Emacs session as follows:

1. `magit-init` a new repo
2. Create a single file `index.html.dot` in said repo with some well-formed, ASCII html content
3. Add and commit the file through magit's status buffer
4. Make some change to the file and save it
5. Go back to the status buffer and press `g`

Instead of seeing the modified file, magit takes a little longer to run (I think) and then continues to show an empty status buffer (i.e., the changes don't show up). Running `git status` (either through a shell or using `: status` from magit) shows that `index.html.dot` is modified as expected. You can go further and stage this file, but magit will still not show it in the status buffer.

Adding a `.gitattributes` file with `*.dot !diff` makes `index.html.dot` will finally reappear in magit.

One additional clue to the issue is that `git-diff` complains that `index.html.dot is not a Word Document.` and likewise for some similarly-named temp file.

Not knowing anything about magit's source, I imagine it's calling `git-diff` and then skipping the file on error. If that really is the case, then I'm fine adjudicating this issue to operator error -- I should have had that in my .gitattributes all along -- but at the very least magit should not be silent on the matter.

```
M-x magit-version RET
Magit 20161128.1456, Git 2.11.0.windows.1, Emacs 25.1.1, windows-nt
```

**Comment by npostavs** [comment] 2016-12-01 17:45
> One additional clue to the issue is that `git-diff` complains that `index.html.dot is not a Word Document.` and likewise for some similarly-named temp file.
> 
> Not knowing anything about magit's source, I imagine it's calling `git-diff` and then skipping the file on error. If that really is the case, then I'm fine adjudicating this issue to operator error -- I should have had that in my .gitattributes all along -- but at the very least magit should not be silent on the matter.
> 

Seems to be due to Git for Window's default gitattributes file (`C:/Git-2.x/mingw64/etc/gitattributes`)

```
*.doc	diff=astextplain
*.DOC	diff=astextplain
*.docx	diff=astextplain
*.DOCX	diff=astextplain
*.dot	diff=astextplain
*.DOT	diff=astextplain
*.pdf	diff=astextplain
*.PDF	diff=astextplain
*.rtf	diff=astextplain
*.RTF	diff=astextplain
```

**Comment by tarsius** [comment] 2016-12-02 18:28
It's a known issue that Magit silently ignores it when diff fails to produce any output. Fixing that will require some massive changes, but it's on my todo list.

In this specific case we have already figured out what the cause and fix are, so I am closing this.

**Closed by tarsius** 2016-12-02 18:28 UTC
Labels: support
