### ISSUE TITLE
Binding M-w in magit-mode breaks normal Emacs behavior

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#1958] opened 2015-07-03 07:01 UTC
I find it quite common to mark&copy text in my Magit to use elsewhere in Emacs.  Recently, it was rebound to some-long-function-I-can't-remember, which seems to only copy the current commit id.  I wouldn't mind this behavior being on a custom key, but rebinding M-w seems odd for a buffer that mostly contains text.  I know it's easy to change the binding back, which I've done, but I thought you might want to correct this bit of inconsistency.

**Comment by npostavs** [comment] 2015-07-03 09:13
See #1913. But yeah, I think you're right about this, though at the time it somehow didn't really occur to me that `M-w`'s default binding would be important.

**Comment by tshatrov** [comment] 2015-07-03 15:11
I just encountered this too, wanted to copy some stuff from a diff but neither C-w nor M-w work.

**Comment by tarsius** [comment] 2015-07-03 15:18
Yes, this was a last minute kludge and I intend to address this better. Suggestions welcome.

**Comment by jwiegley** [comment] 2015-07-04 05:57
I think `C-x C-w` might be nicely in scope for what you want: mode-specific functionality akin, but not equal to, a default binding.

**Comment by tshatrov** [comment] 2015-07-04 09:45
I believe extensions are recommended to use C-c prefix (mode-specific-map)

**Comment by tarsius** [comment] 2015-07-04 15:34
> @mgalgs said: Yes, I'm all about a proper fix but we need to do something right now since it leaves such a bad impression on the droves of people now jumping on the 2.1.0 release. I was envisioning reverting the keybinding immediately so that we could work on a proper fix with more calm.

The problem is that when we remove the `M-w` binding then, in revision and log buffers, we remove the only way to copy the value users are mostly to want to copy: the revision(s). But you are right, an "emergency" fix would make sense, but that involves finding another key, which we could use at least for the time being. What about `C-c C-w` and `C-c M-w`? Would it be okay to use those?

**Comment by mgalgs** [comment] 2015-07-04 15:48
> we remove the only way to copy the value users are mostly to want to copy: the revision(s).

Ah, I didn't even notice that the revision had moved up into the header line... Hmmm...  How about moving it out of the header line?  I often find myself needing to copy a different number of characters from the revision depending on what I'm using it for (might need the full 40 characters for some internal code review purposes, for example, or just a few characters if I'm just quickly sharing something with someone else).  Seems like the easiest way to accommodate all the different ways people would like to consume the revision is to just give it to them and let them copy it how they want.

I also just noticed that `M-w` resolves to a symbolic ref (like my branch name) rather than the sha1 of the commit, so even without my emergency fix there's currently no way for me to copy the sha1 of some patches.

So `C-c C-w` sounds great but I think we should consider moving the commit hash out of the header line.

**Comment by npostavs** [comment] 2015-07-04 19:05
+1 for `C-c C-w`.

> I also just noticed that M-w resolves to a symbolic ref (like my branch name) rather than the sha1 of the commit, so even without my emergency fix there's currently no way for me to copy the sha1 of some patches.

From the `*magit-rev: ...` buffer `magit-copy-buffer-thing-as-kill` (currently `M-w`) gives you the sha1. From the log buffer, `magit-copy-as-kill` (`C-w`) gives the sha1 of commit under point.

> we should consider moving the commit hash out of the header line.

I guess there was some reason for putting there to begin with? It does seem more straightforward to have it in the buffer rather than the header.

**Comment by jwiegley** [comment] 2015-07-04 20:37
I like `C-c C-w` as a binding too.

**Comment by tarsius** [comment] 2015-07-05 10:43
Instead of using new key bindings I have turned `magit-copy{,-buffer-thing}-as-kill` into variants of `kill-as-save`. When the region is *active*, then these commands now behave like `kill-as-kill`. Only if the region is not active they copy the thing at point or in the buffer. (Note that `kill-as-save` can copy non-active regions. We lose that ability, but I suspect most users only copy regions they can see.)

And in revision buffers `magit-copy-buffer-thing-as-kill` now copies the full hash. I too found things like `master~10` entirely useless in this context.

> How about moving it out of the header line?

I often found myself looking at scrolled log/diff/rev buffers and being unsure what is being displayed. Now that information is always visible. Putting it into the `header-line` *and* the buffer text might be an option, but I tend to think the second is not necessary, now that the full hash is copied in rev buffers.

----

On a related note, I recommend setting `x-select-enable-primary` to `t`.

----

I am closing this, but feel free to provide further suggestions. The naming issue I will take care of some other time (see #1586).

**Closed by tarsius** 2015-07-05 10:43 UTC

**Comment by npostavs** [comment] 2015-07-05 11:19
@tarsius: did you forget to push?

> Note that kill-as-save can copy non-active regions. We lose that ability, but I suspect most users only copy regions they can see.

I do use non active regions sometimes, but generally only as part of a larger editing sequence, so I guess it won't be a problem in magit buffers.

**Comment by tarsius** [comment] 2015-07-05 11:24
> did you forget to push?

Yep. Have done it now.

**Comment by basil-conto** [comment] 2018-01-30 20:12
`Magit 2.11.0-474-gf4bef01a, Git 2.15.1, Emacs 27.0.50, gnu/linux`

I'm seeing the following unexpected and inexplicable behaviour:

1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>g</kbd><kbd>y</kbd>
3. <kbd>C-SPC</kbd><kbd>M-f</kbd><kbd>M-w</kbd>
   - Region saved as kill, mark deactivated.
4. <kbd>C-SPC</kbd><kbd>C-n</kbd><kbd>M-w</kbd>
   - Region saved as kill, mark still active.

In other words, <kbd>M-w</kbd> deactivates the mark as expected in sections heads, but not in their body. The body happens to have a `keymap` property, but I don't see how that would be affecting `magit-copy-buffer-revision`/`copy-region-as-kill`.

This is at worst a really minor nuisance, but any ideas what could be causing it?

**Comment by tarsius** [comment] 2018-01-30 20:32
Please open a new issue for that.

This is caused by `magit-section-update-highlight` setting `deactivate-mark` to `nil`. I haven't investigated further yet.
