### ISSUE TITLE
Add option to decouple confirmation and completion

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#2916] opened 2017-01-02 20:18 UTC
Hi Jonas,

Other than removing `P P` and `F F` (which I restored with a local patch), I've been extremely happy with Magit v2.9; great work!

Two key bindings I'm wondering about, and why they behave differently than so many others:

- `k` almost everywhere prompts y/n to kill the thing or region at point.  On stashes, however, it prompts me with a list of all stashes, to select one.  Since my cursor is already on the stash I want to kill, why doesn't it just ask me y/n if I want to kill that stash?

- `E` on a merge conflicted file used to enter ediff to order to resolve the merge.  Now if I type `E E` on a `unmerged` line, it pops me into a 2-way diff.  I need to type `E m` to resolve a merge resolution, but instead of acting on the merge conflict line that I'm on, it prompts me with a list of all the merge conflicts in the project.

Request: Harmonize these bindings with the way that other aspects of Magit operate, so that `k` on a stash line will prompt to kill that stash, `E E` on a merge conflict line will resolve the merge, as would `E m`.

Thanks,
  John

**Comment by npostavs** [comment] 2017-01-02 20:51
> Now if I type `E E` on a unmerged line, it pops me into a 2-way diff.

I'm unable to reproduce this. I get a 3-way ediff session, same as what I get from `E m`.

**Comment by kyleam** [comment] 2017-01-02 21:02
Your feelings on `k`'s consistency appear consistent over time :)

https://github.com/magit/magit/issues/1858

**Comment by jwiegley** [comment] 2017-01-03 17:26
For example, right now I'm in the midst of a rebase and I see this:

```
Head:     dba308d Allow MIT LL URL to be null in config.
Tag:      mitll-integration-v0.3.0 (6)

Rebasing master onto dba308d65257385958d73bb83fba949d35defff0
pick 17cb58e Create the first variant with input from config.yaml
pick 8c228e6 Further work toward support known good inputs
join 58afd14 Changes to support a known good state
onto dba308d Allow MIT LL URL to be null in config.

Unstaged changes (1)
unmerged   src/Rings/Types.hs
@@@ -195,37 -189,19 +195,49 @@@ data RingsSettings = RingsSetting
        -- | The port for sending status updates and log messages.
      , _ringsTestPort :: !Network.PortNumber
        -- | The docker network that the application should attach to.
 -    , _ringsDockerNetwork :: Text
 +    , _ringsDockerNetwork :: !Text
        -- | The RPF file relative to the root of the application repository.
 -    , _ringsRpfFile :: Text
 +    , _ringsRpfFile :: !Text
        -- | The repair module to tell GenPatcher to use.
++<<<<<<< HEAD
 +    , _ringsRepairModule :: !Text
++||||||| merged common ancestors
++    , _ringsRepairModule :: Text
++      -- | The application repository
++    , _ringsAppRepository :: Text
++=======
+     , _ringsRepairModule :: Text
+       -- | Files within the project which represent known good data.
+     , _ringsRepairGoodFiles :: [Text]
+       -- | The application repository
+     , _ringsAppRepository :: Text
++>>>>>>> Changes to support a known good state
        -- | The names of events that indicate repair is necessary.
 -    , _ringsRepairEventNames :: [Text]
 +    , _ringsRepairEventNames :: ![Text]
        -- | The URL for talking to the comparator
      , _ringsComparatorBaseUrl :: !SC.BaseUrl
 +      -- | Hostname of the AMQP server
 +    , _ringsAmqpHostname :: !Network.HostName
 +      -- | Port for accessing the AMQP server
 +    , _ringsAmqpPort :: !Integer
 +      -- | Timeout for waiting for the AMQP server to come up (Nothing means
 +      --   wait forever)
 +    , _ringsAmqpWaitTimeout :: !(Maybe Integer)
 +      -- | AMQP Virtual host
 +    , _ringsAmqpVirtualHost :: !Text
 +      -- | AMQP Username
 +    , _ringsAmqpUsername :: !Text
 +      -- | AMQP Password
 +    , _ringsAmqpPassword :: !Text
 +      -- | Hostname of the application code repository
 +    , _ringsCodeRepoHostname :: !Network.HostName
 +      -- | Port for accessing the application code repository
 +    , _ringsCodeRepoPort :: !Integer
 +      -- | Path for accessing the application code repository
 +    , _ringsCodeRepoPath :: !Text
 +      -- | Timeout for waiting for the code repository to come up (Nothing means
 +      --   wait forever)
 +    , _ringsCodeRepoWaitTimeout :: !(Maybe Integer)
      } deriving (Show, Generic)
  
  makeLenses ''RingsSettings
@@@ -240,18 -216,10 +252,25 @@@ instance TextShow RingsSettings wher
          , "ringsDockerNetwork", showb (r ^. ringsDockerNetwork)
          , "ringsRpfFile", showb (r ^. ringsRpfFile)
          , "ringsRepairModule", showb (r ^. ringsRepairModule)
++<<<<<<< HEAD
++||||||| merged common ancestors
++        , "ringsAppRepository", showb (r ^. ringsAppRepository)
++=======
+         , "ringsRepairGoodFiles", showb (r ^. ringsRepairGoodFiles)
+         , "ringsAppRepository", showb (r ^. ringsAppRepository)
++>>>>>>> Changes to support a known good state
          , "ringsRepairEventNames", showb (r ^. ringsRepairEventNames)
          , "ringsComparatorBaseUrl", fromString $ SC.showBaseUrl (r ^. ringsComparatorBaseUrl)
 +        , "ringsAmqpHostname", showb (r ^. ringsAmqpHostname)
 +        , "ringsAmqpPort", fromString $ show (r ^. ringsAmqpPort)
 +        , "ringsAmqpWaitTimeout", showb (r ^. ringsAmqpWaitTimeout)
 +        , "ringsAmqpVirtualHost", showb (r ^. ringsAmqpVirtualHost)
 +        , "ringsAmqpUsername", showb (r ^. ringsAmqpUsername)
 +        , "ringsAmqpPassword", showb (r ^. ringsAmqpPassword)
 +        , "ringsCodeRepoHostname", showb (r ^. ringsCodeRepoHostname)
 +        , "ringsCodeRepoPort", fromString $ show (r ^. ringsCodeRepoPort)
 +        , "ringsCodeRepoPath", fromString $ show (r ^. ringsCodeRepoPath)
 +        , "ringsCodeRepoWaitTimeout", showb (r ^. ringsCodeRepoWaitTimeout)
          ]
  
  instance ToJSON RingsSettings where
@@@ -264,18 -232,10 +283,25 @@@
          , "ringsDockerNetwork" A..= (r ^. ringsDockerNetwork)
          , "ringsRpfFile" A..= (r ^. ringsRpfFile)
          , "ringsRepairModule" A..= (r ^. ringsRepairModule)
++<<<<<<< HEAD
++||||||| merged common ancestors
++        , "ringsAppRepository" A..= (r ^. ringsAppRepository)
++=======
+         , "ringsRepairGoodFiles" A..= (r ^. ringsRepairGoodFiles)
+         , "ringsAppRepository" A..= (r ^. ringsAppRepository)
++>>>>>>> Changes to support a known good state
          , "ringsRepairEventNames" A..= (r ^. ringsRepairEventNames)
          , "ringsComparatorBaseUrl" A..= SC.showBaseUrl (r ^. ringsComparatorBaseUrl)
 +        , "ringsAmqpHostname" A..= (r ^. ringsAmqpHostname)
 +        , "ringsAmqpPort" A..= show (r ^. ringsAmqpPort)
 +        , "ringsAmqpWaitTimeout" A..= (r ^. ringsAmqpWaitTimeout)
 +        , "ringsAmqpVirtualHost" A..= (r ^. ringsAmqpVirtualHost)
 +        , "ringsAmqpUsername" A..= (r ^. ringsAmqpUsername)
 +        , "ringsAmqpPassword" A..= (r ^. ringsAmqpPassword)
 +        , "ringsCodeRepoHostname" A..= (r ^. ringsCodeRepoHostname)
 +        , "ringsCodeRepoPort" A..= show (r ^. ringsCodeRepoPort)
 +        , "ringsCodeRepoPath" A..= show (r ^. ringsCodeRepoPath)
 +        , "ringsCodeRepoWaitTimeout" A..= (r ^. ringsCodeRepoWaitTimeout)
          ]
  
  instance FromJSON RingsSettings where
@@@ -292,6 -255,8 +318,13 @@@
              <*> (v .: "ringsDockerNetwork")
              <*> (v .: "ringsRpfFile")
              <*> (v .: "ringsRepairModule")
++<<<<<<< HEAD
++||||||| merged common ancestors
++            <*> (v .: "ringsAppRepository")
++=======
+             <*> (v .: "ringsRepairGoodFiles")
+             <*> (v .: "ringsAppRepository")
++>>>>>>> Changes to support a known good state
              <*> (v .: "ringsRepairEventNames")
              <*> (do
                      url <- v .: "ringsComparatorBaseUrl"

Staged changes (2)
modified   src/Rings/Listeners.hs
@@ -42,6 +42,7 @@ import Rings.Operations
     , VersionId
     , _ringsRpfFile
     , _ringsRepairModule
+    , _ringsRepairGoodFiles
     , ringsRepairEventNames
     , RingsSettings(RingsSettings)
     , codeRepoUrl
@@ -134,6 +135,7 @@ requestRepair chan input = do
     RingsSettings
         { _ringsRpfFile = rpf
         , _ringsRepairModule = repairModule
+        , _ringsRepairGoodFiles = repairGoodFiles
         } <- useRingsIO ringsSettings
     codeRepo <- useRingsIO $ ringsSettings.to codeRepoUrl
     let startRepairRequest = RepairRequest
@@ -142,7 +144,9 @@ requestRepair chan input = do
             , _startRepairBranch = "master"
             , _startRepairRpfFile = rpf
             , _startRepairModule = repairModule
-            , _startRepairTestArguments = [T.decodeUtf8 input]
+            , _startRepairTestArguments =
+                ["--good-files"] ++ repairGoodFiles ++
+                ["--bad-files", T.decodeUtf8 input]
             }
     liftIO $ AMQP.publishMsg chan "" "repair-control"
         (AMQP.newMsg { AMQP.msgBody = A.encode startRepairRequest })
unmerged   src/Rings/Types.hs
```

If I type `E E` on the `Unmerged` line, it pops me into a 2-way diff where the entire file is considered a single diff region.  If I type `E m` here, I get `There are no unresolved conflicts`.  The only way for me to resolve the conflict is to do it by hand.

**Comment by tarsius** [comment] 2017-01-03 18:00
What does `git diff-files --name-status` print?

**Comment by jwiegley** [comment] 2017-01-03 22:05
@tarsius Ah, problem solved, at least for `E m` (if not `E E`). I had a busted submodule `.git` file.

**Comment by tarsius** [comment] 2017-01-03 22:27
Yeah, that's one of those sharp edges of submodules; if you mess one up, then git can fail spectacularly in the super-repository.

**Comment by tarsius** [comment] 2017-01-04 12:26
So how about `k`?

**Comment by phil-s** [comment] 2017-01-04 22:06
@jwiegley , by default `k` on a stash doesn't display a list.

It does a completing-read for the stash to drop, with the stash-at-point as the default value, and therefore by default the prompt indicates the stash at point, and you type RET to drop it.

If you are seeing a list to select from, that makes me think you have some kind of completing-read add-on which automatically displays the list of completions?

**Comment by jwiegley** [comment] 2017-01-04 22:46
@phil-s You're right, I'm using Helm.  What I'm wondering is why it isn't just a y/n prompt, rather than a selection.  If I'd wanted to drop a different stash, I would have moved to that line...

**Comment by johnmastro** [comment] 2017-01-05 00:40
I think, when confirmation is desired for the operation anyway, it's nice to offer the list. It's a single key to confirm either way - just `RET` instead of `y`. Once your muscle memory catches up, you get more flexibility with no downside.

**Comment by danrharms** [comment] 2017-01-05 02:48
Would you ever use this flexibility though?  The selections that come up list only the stash number, not the description, so it would be error-prone, to say the least, to find another stash anyway. 

For my part, I find myself always doing a double-take when the completion menu comes up, to make sure the selected stash is the one I intended. It feels strange to have to select my desired stash twice in a row.

**Comment by tarsius** [comment] 2017-01-05 08:37
I'll probably add an option similar to `magit-no-confirm`, maybe `magit-no-alternatives`. Valid values would be `t` for "don't ever offer alternative targets instead of a yes-or-no prompt" or a list of symbols representing individual commands for which no alternatives should be offered.

For stashes I kinda agree. Here I too usually (always?) move to the stash I want to delete and then just confirm that using `RET`. But for e.g. branches that is not the case, among other reasons because multiple branches can point to the commit on the current line, so here I often have to select something other than the default. (The default should be improved, but that's a different issue.)

There are some complications I have to think about some more. E.g. the same command could be affected by both `magit-no-confirm` and `magit-no-alternatives`, which might be confusing.

**Comment by tarsius** [comment] 2017-10-19 16:10
Since 2.9.0 the option `magit-no-confirm-default` can be used to do this. Also see #2741.

**Comment by tarsius** [comment] 2017-10-23 18:56
Err, that's not actually true. But I have now started working on `magit-no-alternatives`.

**Comment by tarsius** [comment] 2017-10-29 13:57
Closing in favor of the pull request #3232, after all that has exactly the same title :wink: 

I'll try to get that in a review worthy state today and intend to merge it soon after.

**Closed by tarsius** 2017-10-29 13:57 UTC
Labels: feature request
