### ISSUE TITLE
Error in latest version. Popups are unusable! cl-etypecase failed: [eieio-class-tag--transient-column ...]

### ISSUE THREAD

**Issue by gjm** [magit/magit#3732] opened 2019-02-15 10:49 UTC
After latest update, in `magic-status` window, whenever I press "action" keys (like `c` for commit) I get this error:
```
cl-etypecase failed: [eieio-class-tag--transient-column 1 nil nil nil nil nil nil nil nil ([eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil -a transient:magit-commit:--all t  %k %d (%v) Stage all modified and deleted files --all -a nil nil nil nil nil nil nil] [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil -e transient:magit-commit:--allow-empty t  %k %d (%v) Allow empty commit --allow-empty unbound nil nil nil nil nil nil nil] [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil -v transient:magit-commit:--verbose t  %k %d (%v) Show diff of changes to be committed --verbose -v nil nil nil nil nil nil nil] [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil -n transient:magit-commit:--no-verify t  %k %d (%v) Disable hooks --no-verify -n nil nil nil nil nil nil nil] [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil -R transient:magit-commit:--reset-author t  %k %d (%v) Claim authorship and reset author date --reset-author unbound nil nil nil nil nil nil nil]
  [eieio-class-tag--transient-option 1 nil nil nil nil nil nil nil nil -A magit:--author t  %k %d (%v) Override the author --author= unbound nil nil nil nil magit-transient-read-person nil nil] [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil -s transient:magit-commit:--signoff t  %k %d (%v) Add Signed-off-by line --signoff -s nil nil nil nil nil nil nil] [eieio-class-tag--transient-option 1 nil nil nil nil nil nil nil nil -C magit-commit:--reuse-message t  %k %d (%v) Reuse commit message --reuse-message= -C nil nil nil magit-revision-history magit-read-reuse-message nil nil]) nil Arguments],
  (integer string list transient-group transient-suffix)
```
Also post the output of

  M-x magit-version RET

Magit 20190214.2056, Git 2.19.1, Emacs 25.2.2, gnu/linux

**Comment by ioreshnikov** [comment] 2019-02-15 10:50
Can confirm. Updated magit an hour ago and now my setup is broken.

**Comment by tarsius** [comment] 2019-02-15 12:45
Did the new `transient` dependency get installed? Did you try restarting Emacs?

**Comment by tarsius** [comment] 2019-02-15 12:54
I suspect what happened is this.

1. Magit is partially loaded. Somethings are only autoloaded because you haven't used any commands yet that would cause them to be properly loaded.
2. You update Magit, which also brings in `transient`.
3. You try to use a Magit command that you did not use before.
4. Emacs loads the relevant libraries.
5. Now some libraries of the old Magit version are loaded along with some libraries from the new Magit version. If a library has already been loaded before the update, then that is "already loaded", so the new version won't get loaded.
6. Magit/Emacs is in an inconsistent state. Some new code tries to use code that hasn't been loaded yet and won't ever get loaded because the old version of it is already loaded.

Restarting Emacs will *likely* fix this.

However, it is also possible that the old version has leaked into the byte-compiled files of the new version. Magit tries to prevent that by forcing `package.el` to use `async` to compile in a separate Emacs instance. But users can disable that or it might not always work reliably.

So simply restarting Emacs does not work, then you should also uninstall Magit, restart Emacs, and only then reinstall Magit.

Please report if simply restarting did the trick for you or if you had to reinstall.

**Comment by ioreshnikov** [comment] 2019-02-15 13:06
> Did the new `transient` dependency get installed? Did you try restarting Emacs?

Yes it did git installed. And yes, I did try restarting emacs. And after that failed I removed my dot emacs directory, cloned my configuration once again and installed all the dependencies on this brand new emacs config. It did not help. The upstream is broken.

**Comment by tarsius** [comment] 2019-02-15 13:22
I can reproduce this when

1. Installing using `package.el`.
2. *Not* removing the `*.elc` files.
3. Using Emacs 25.3 (instead of 26.1).

If I stop doing any one of these it works again. Okay this could be a tough one.

**Comment by tarsius** [comment] 2019-02-15 13:39
Hm that is weird. The error says that one of `(integer string list transient-group transient-suffix)` but it got a `transient-option`, but a `transient-option` is a (derives from) `transient-suffix`.

**Comment by ioreshnikov** [comment] 2019-02-15 13:41
@tarsius is it OK that both magit-popup and transient get installed automatically?

**Comment by tarsius** [comment] 2019-02-15 13:43
> is it OK that both magit-popup and transient get installed automatically?

Yes, assuming that some other package declares `magit-popup` as a dependency.

**Comment by ioreshnikov** [comment] 2019-02-15 13:45
@tarsius Ah, ok, it's required by docker.

**Comment by Silex** [comment] 2019-02-15 13:49
@ioreshnikov: yeah, I'll switch to transient when I have time, it looks awesome!

**Comment by JonHarder** [comment] 2019-02-15 13:56
As a short term work around, deleting `elpa/transient-VERISON/transient.elc` and restarting emacs makes it work again.

**Comment by tarsius** [comment] 2019-02-15 14:03
Thank you Github, but the message of 73a100d489b570832dfc9d2dd2e7c712fc6ebc1d says

> **Possibly** fix #3733 

I did this because I suspect it has something to do with the order in which the libraries are being compiled. And I will be gone for a few hours.

> As a short term work around, deleting `elpa/transient-VERISON/transient.elc` and restarting emacs makes it work again.

Thanks for figuring out that only that file has to be deleted. (Others take note.)

That probably means that my potential fix won't do the trick though.

**Comment by gjm** [comment] 2019-02-15 14:14
I had already tried restarting with no success. I tried uninstalling and
reinstalling again with no success.

The only workaround for me, right now, is this:
https://github.com/magit/magit/issues/3732#issuecomment-464058617

Atentamente,

Gonçalo Marrafa

**Comment by tarsius** [comment] 2019-02-15 18:59
https://github.com/magit/transient/commit/9183fe1ed2688fe41db2a367896b5375dbba2cd9 should fix this.

**Comment by tarsius** [comment] 2019-02-15 18:59
Github, chill out. I want some feedback before closing...

**Comment by jacott** [comment] 2019-02-15 21:42
Appears to work now for me

**Closed** 2019-02-17 23:57 UTC
Labels: bug, bug emacs
