### ISSUE TITLE
Staging/unstaging in magit-status causes cursor to jump to top of buffer

### ISSUE THREAD

**Issue by landshark666** [magit/magit#4727] opened 2022-07-19 19:23 UTC
Magit Version: Magit 20220706.148 [>= 3.3.0-git], Git 2.33.0, Emacs 26,3, gnu/linux
Magit Version: Magit 20220706.148 [>= 3.3.0-git], Git 2.33.0, Emacs 27.2, gnu/linux (different machine)

I deleted magit-* from my install directory and watched use-package reinstall fresh from Melpa upon emacs restart. The problem described below persisted.

When staging/unstaging anything in the `magit-status` buffer, the cursor always jumps to the top of the buffer.  I've tried it with hunks as well as full files. It always jumps to the top.

Previous versions left the cursor at the current point so it was easy to hit `s`, `s`, `s`, ... to stage multiple concurrent hunks/files.  Now I need to scroll down to the appropriate file/section after every stage command.

I verified launching via `--no-init` and manually loading the required Magit packages had no effect on the behavior; the cursor kept jumping to the top.

I dropped just the Magit package back to 20210512.1949 and the original behavior was restored (the only other version I had available).

**Comment by tarsius** [comment] 2022-07-19 20:25
Duplicate of #4695.

**Closed** 2022-07-19 20:25 UTC
Labels: duplicate
