### ISSUE TITLE
Checking out master from detached head state with unstaged changes

### ISSUE THREAD

**Issue by glinka** [magit/magit#2542] opened 2016-02-05 21:23 UTC
If I pull up the `magit-log` buffer, checkout a previous commit with `b b`, make a change to one of the tracked files so that there are unstaged changes listed when `magit-status` is called, then attempt to checkout `master` from `magit-log`, I get a `(No buffers need to be reverted)` message and nothing changes (`HEAD` is unmoved and files are unreverted). If I discard the unstaged changes and then try to checkout `master`, things revert as expected and `HEAD` moves to `master`.

Not a serious issue, but it could be handled more transparently with some error message explaining that unstaged changes must be resolved before a different commit can be checked out.

**Comment by kyleam** [comment] 2016-02-05 21:30
You should also see something like

     GitError! Your local changes to the following files would be overwritten by checkout:  [Type `$' for details]

at the very top highlighted in `font-lock-warning-face`.

**Comment by glinka** [comment] 2016-02-05 21:36
Perhaps it's local to my setup then, because while I do see this message in `magit-process`, that's the only place it seems to appear. When I switch to `magit-status` there's no warning.

**Comment by kyleam** [comment] 2016-02-05 21:42
What's your Magit version?

**Comment by kyleam** [comment] 2016-02-05 21:44
Sorry, re-reading your question, it seems you're in magit-log, not the status buffer, when checking out master.  Then the warning should be at the top of the log buffer.

**Comment by kyleam** [comment] 2016-02-05 21:48
OK, never mind.  Just tried in the log and the warning won't show up there, where as it would in, for example, magit-status or magit-refs.

**Comment by glinka** [comment] 2016-02-05 21:55
Ah, I see. Brilliant package by the way! If you still need it `magit-version` says

`Magit 20150908.1149, Git 2.7.0, Emacs 24.5.1`

**Comment by kyleam** [comment] 2016-02-05 22:10
Currently magit-insert-error-header is only shown in magit-status and
magit-refs buffers because magit-insert-error-header is wired up to
their section hooks.

@tarsius @npostavs Should we try to support the error header in all
Magit buffers?

**Comment by kyleam** [comment] 2016-02-05 22:43
> Magit 20150908.1149

I think your Magit version predates the GitError display in status and refs buffers.  That would have a MELPA tag starting with 20151204 or something close to that.  While upgrading won't address your particular case here, it will add GitError to status and refs buffers.

**Comment by tarsius** [comment] 2016-02-06 18:48
Closing because this is the expected behavior.

@glinka After you have updated to the most recent version, you might also want to set `auto-revert-verbose` to `nil`.

> Should we try to support the error header in all Magit buffers?

@kyleam That's fine with me. At least for the buffers which are created using a sections-hook, this should be easy to do.

**Closed by tarsius** 2016-02-06 18:48 UTC
