### ISSUE TITLE
Transient called with nil key

### ISSUE THREAD

**Issue by angrybacon** [magit/magit#4882] opened 2023-02-19 09:48 UTC
I've just reinstalled my system after getting a new macOS machine so everything is up to date and using Ventura 13.0.

### How to Reproduce

I've written below the minimum steps I could reproduce the error with, using `emacs -Q`.

```sh
rm -rf eln-cache/ elpa/
```

```elisp
(package-initialize)
(require 'use-package)
(setq-default
 use-package-always-defer t
 use-package-always-ensure t)
(use-package magit)
```

<kbd>M-x toggle-debug-on-error</kbd>, then hit <kbd>c</kbd> to trigger the commit transient

<details>
<summary>Backtrace</summary>

```raw
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  transient--exit-and-debug(error (wrong-type-argument stringp nil))
  transient--colorize-key(nil magit:--author)
  #f(compiled-function (obj) "Format OBJ's `key' for display and return the result." #<bytecode 0x9a50abae8a13c8f>)(#<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (obj) "Format OBJ's `key' for display and return the result." #<bytecode 0x9a50abae8a13c8f>) #<transient-option transient-option-457cf792>)
  #f(compiled-function (&rest args) #<bytecode 0x949c941ac6809ee>)(#<transient-option transient-option-457cf792>)
  #f(compiled-function (cl--cnm obj) #<bytecode -0x4dbf48ba4554c19>)(#f(compiled-function (&rest args) #<bytecode 0x949c941ac6809ee>) #<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode -0x4dbf48ba4554c19>) #f(compiled-function (&rest args) #<bytecode 0x949c941ac6809ee>) #<transient-option transient-option-457cf792>)
  #f(compiled-function (obj) #<bytecode 0x1d5ec8c8b813a21c>)(#<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (obj) #<bytecode 0x1d5ec8c8b813a21c>) #<transient-option transient-option-457cf792> nil)
  transient-format-key(#<transient-option transient-option-457cf792>)
  #f(compiled-function (obj) "Return a string generated using OBJ's `format'.\n%k is formatted using `transient-format-key'.\n%d is formatted using `transient-format-description'.\n%v is formatted using `transient-format-value'." #<bytecode 0x8ce441d7a93eb0c>)(#<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (obj) "Return a string generated using OBJ's `format'.\n%k is formatted using `transient-format-key'.\n%d is formatted using `transient-format-description'.\n%v is formatted using `transient-format-value'." #<bytecode 0x8ce441d7a93eb0c>) #<transient-option transient-option-457cf792>)
  #f(compiled-function (&rest args) #<bytecode 0x20d1f8445e57b57>)(#<transient-option transient-option-457cf792>)
  #f(compiled-function (cl--cnm obj) #<bytecode -0xf8a4e2d63b23ae9>)(#f(compiled-function (&rest args) #<bytecode 0x20d1f8445e57b57>) #<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode -0xf8a4e2d63b23ae9>) #f(compiled-function (&rest args) #<bytecode 0x20d1f8445e57b57>) #<transient-option transient-option-457cf792>)
  #f(compiled-function (obj) "When edit-mode is enabled, then prepend the level information.\nOptional support for popup buttons is also implemented here." #<bytecode 0x38e94a6dea80cd8>)(#<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (obj) "When edit-mode is enabled, then prepend the level information.\nOptional support for popup buttons is also implemented here." #<bytecode 0x38e94a6dea80cd8>) #<transient-option transient-option-457cf792>)
  #f(compiled-function (&rest args) #<bytecode 0x8d90228f1d0722>)(#<transient-option transient-option-457cf792>)
  #f(compiled-function (cl--cnm obj) #<bytecode -0x1f0712fe14db0a17>)(#f(compiled-function (&rest args) #<bytecode 0x8d90228f1d0722>) #<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode -0x1f0712fe14db0a17>) #f(compiled-function (&rest args) #<bytecode 0x8d90228f1d0722>) #<transient-option transient-option-457cf792>)
  #f(compiled-function (obj) "When reading user input for this infix, then highlight it." #<bytecode 0xb00e28c6268bfff>)(#<transient-option transient-option-457cf792>)
  apply(#f(compiled-function (obj) "When reading user input for this infix, then highlight it." #<bytecode 0xb00e28c6268bfff>) #<transient-option transient-option-457cf792> nil)
  transient-format(#<transient-option transient-option-457cf792>)
  #f(compiled-function (group) #<bytecode -0x14b719b33c41cf42>)(#<transient-column transient-column-4d5c6054>)
  apply(#f(compiled-function (group) #<bytecode -0x14b719b33c41cf42>) #<transient-column transient-column-4d5c6054>)
  #f(compiled-function (&rest args) #<bytecode -0x1e3445e7cda9a2ce>)(#<transient-column transient-column-4d5c6054>)
  #f(compiled-function (cl--cnm group) #<bytecode -0x4bf701a53492a1f>)(#f(compiled-function (&rest args) #<bytecode -0x1e3445e7cda9a2ce>) #<transient-column transient-column-4d5c6054>)
  apply(#f(compiled-function (cl--cnm group) #<bytecode -0x4bf701a53492a1f>) #f(compiled-function (&rest args) #<bytecode -0x1e3445e7cda9a2ce>) #<transient-column transient-column-4d5c6054>)
  #f(compiled-function (group) "Insert GROUP's description, if any." #<bytecode 0x63533ff84a39f8a>)(#<transient-column transient-column-4d5c6054>)
  apply(#f(compiled-function (group) "Insert GROUP's description, if any." #<bytecode 0x63533ff84a39f8a>) #<transient-column transient-column-4d5c6054> nil)
  transient--insert-group(#<transient-column transient-column-4d5c6054>)
  transient--insert-groups()
  transient--show()
  transient--redisplay()
  transient-setup(magit-commit)
  magit-commit()
  funcall-interactively(magit-commit)
  command-execute(magit-commit)
```
</details>

A similar issues also happens without the popup setting `transient-show-popup` to `nil`.

### System Details

<details>
<summary><kbd>M-x emacs-version</kbd></summary>

```raw
GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.1.0, NS appkit-2299.00 Version 13.0 (Build 22A380)) of 2023-02-18
```
</details>

<details>
<summary><kbd>M-x magit-debug-git-executable</kbd></summary>

```raw
magit-remote-git-executable: "git"
magit-git-executable: "/opt/homebrew/bin/git" (2.39.2)
exec-path: ("/Users/mathieu.marques/.nvm/versions/node/v18.14.1/bin" "/opt/homebrew/opt/coreutils/libexec/gnubin" "/usr/local/sbin" "/usr/local/opt/coreutils/libexec/gnubin" "/opt/homebrew/bin" "/opt/homebrew/sbin" "/Users/mathieu.marques/Scripts" "/usr/local/bin" "/System/Cryptexes/App/usr/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/homebrew/Cellar/emacs-plus@30/30.0.50/libexec/emacs/30.0.50/aarch64-apple-darwin22.1.0")
  /Users/mathieu.marques/.nvm/versions/node/v18.14.1/bin (t)
  /opt/homebrew/opt/coreutils/libexec/gnubin (t)
  /usr/local/sbin (nil)
  /usr/local/opt/coreutils/libexec/gnubin (nil)
  /opt/homebrew/bin (t)
    /opt/homebrew/bin/git (2.39.2)
  /opt/homebrew/sbin (t)
  /Users/mathieu.marques/Scripts (t)
  /usr/local/bin (t)
  /System/Cryptexes/App/usr/bin (t)
  /usr/bin (t)
    /usr/bin/git (2.39.2)
  /bin (t)
  /usr/sbin (t)
  /sbin (t)
  /opt/homebrew/Cellar/emacs-plus@30/30.0.50/libexec/emacs/30.0.50/aarch64-apple-darwin22.1.0 (t)
```
</details>

```sh
$ ls -l elpa/ 
total 0
drwxr-xr-x  4  128 Feb 19 11:05 archives
drwxr-xr-x 24  768 Feb 19 11:05 dash-2.19.1
drwxr-xr-x  7  224 Feb 19 11:06 git-commit-3.3.0
drwxr-xr-x 99 3.1K Feb 19 11:06 magit-3.3.0
drwxr-xr-x  9  288 Feb 19 11:05 magit-section-3.3.0
drwxr-xr-x 12  384 Feb 19 11:05 transient-0.3.7
drwxr-xr-x 13  416 Feb 19 11:05 with-editor-3.2.0
```

Feel free to escalate this to Transient if it's more relevant there

**Comment by tarsius** [comment] 2023-02-19 11:10
Duplicate of #4882.

**Closed** 2023-02-19 11:10 UTC
Labels: duplicate

**Comment by jumper047** [comment] 2023-02-19 12:53
Seems like issue still there - Emacs 29, just updated transient and got this backtrace while trying to display git log (`l`):
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  transient--exit-and-debug(error (wrong-type-argument stringp nil))
  transient--colorize-key(nil magit-log:-n)
  #f(compiled-function (obj) "Format OBJ's `key' for display and return the result." #<bytecode 0x9d08637f098e0cf>)(#<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (obj) "Format OBJ's `key' for display and return the result." #<bytecode 0x9d08637f098e0cf>) #<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (&rest args) #<bytecode 0x949c941ac5254ae>)(#<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (cl--cnm obj) #<bytecode -0x1dc853ed55536619>)(#f(compiled-function (&rest args) #<bytecode 0x949c941ac5254ae>) #<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode -0x1dc853ed55536619>) #f(compiled-function (&rest args) #<bytecode 0x949c941ac5254ae>) #<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (obj) #<bytecode 0x108aa60d340c261c>)(#<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (obj) #<bytecode 0x108aa60d340c261c>) #<transient-option transient-option-1563f8c51144> nil)
  transient-format-key(#<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (obj) "Return a string generated using OBJ's `format'.\n%k is formatted using `transient-format-key'.\n%d is formatted using `transient-format-description'.\n%v is formatted using `transient-format-value'." #<bytecode 0x624210cd980a6fc>)(#<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (obj) "Return a string generated using OBJ's `format'.\n%k is formatted using `transient-format-key'.\n%d is formatted using `transient-format-description'.\n%v is formatted using `transient-format-value'." #<bytecode 0x624210cd980a6fc>) #<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (&rest args) #<bytecode 0x20d1f8445fcdf97>)(#<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (cl--cnm obj) #<bytecode 0x193e7f792f0cfd17>)(#f(compiled-function (&rest args) #<bytecode 0x20d1f8445fcdf97>) #<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode 0x193e7f792f0cfd17>) #f(compiled-function (&rest args) #<bytecode 0x20d1f8445fcdf97>) #<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (obj) "When edit-mode is enabled, then prepend the level information.\nOptional support for popup buttons is also implemented here." #<bytecode -0x57eb9962c922728>)(#<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (obj) "When edit-mode is enabled, then prepend the level information.\nOptional support for popup buttons is also implemented here." #<bytecode -0x57eb9962c922728>) #<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (&rest args) #<bytecode 0x8d90228f1ff3e2>)(#<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (cl--cnm obj) #<bytecode 0x157df761552195eb>)(#f(compiled-function (&rest args) #<bytecode 0x8d90228f1ff3e2>) #<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode 0x157df761552195eb>) #f(compiled-function (&rest args) #<bytecode 0x8d90228f1ff3e2>) #<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (obj) "When reading user input for this infix, then highlight it." #<bytecode -0x17befb66e5f0cc01>)(#<transient-option transient-option-1563f8c51144>)
  apply(#f(compiled-function (obj) "When reading user input for this infix, then highlight it." #<bytecode -0x17befb66e5f0cc01>) #<transient-option transient-option-1563f8c51144> nil)
  transient-format(#<transient-option transient-option-1563f8c51144>)
  #f(compiled-function (group) #<bytecode -0x837ebf981944b7d>)(#<transient-column transient-column-1563f8c5110a>)
  apply(#f(compiled-function (group) #<bytecode -0x837ebf981944b7d>) #<transient-column transient-column-1563f8c5110a>)
  #f(compiled-function (&rest args) #<bytecode -0x1e3b1235c65f176a>)(#<transient-column transient-column-1563f8c5110a>)
  #f(compiled-function (cl--cnm group) #<bytecode -0x484279837cd66df>)(#f(compiled-function (&rest args) #<bytecode -0x1e3b1235c65f176a>) #<transient-column transient-column-1563f8c5110a>)
  apply(#f(compiled-function (cl--cnm group) #<bytecode -0x484279837cd66df>) #f(compiled-function (&rest args) #<bytecode -0x1e3b1235c65f176a>) #<transient-column transient-column-1563f8c5110a>)
  #f(compiled-function (group) "Insert GROUP's description, if any." #<bytecode -0x158c51d13bc8152f>)(#<transient-column transient-column-1563f8c5110a>)
  apply(#f(compiled-function (group) "Insert GROUP's description, if any." #<bytecode -0x158c51d13bc8152f>) #<transient-column transient-column-1563f8c5110a> nil)
  transient--insert-group(#<transient-column transient-column-1563f8c5110a>)
  #f(compiled-function () #<bytecode -0x1967a58e0f963284>)()
  apply(#f(compiled-function () #<bytecode -0x1967a58e0f963284>) nil)
  transient--insert-groups()
  transient--show()
  transient--redisplay()
  transient-setup(magit-log)
  magit-log()
  funcall-interactively(magit-log)
  call-interactively(magit-log nil nil)
  command-execute(magit-log)
```

**Comment by ssbb** [comment] 2023-02-19 13:00
@jumper047 make sure it actually updated (eg `package-list-packages` and then `/u`).

For me it wasn't updated because package.el thought `magit` depends on older version of `transient`. I had to manually remove (`package-delete`) magit, git-commit and transient and then re-install.

**Comment by tarsius** [comment] 2023-02-19 13:01
> just updated transient

Unfortunately it can take a few hours for a new snapshot to appear on Melpa. Also, what @ssbb said.

**Comment by jumper047** [comment] 2023-02-19 13:10
@tarsius @ssbb sorry for disturbance and thank you for your help! Deletion and reinstallation of the packages magit, transient and git-commit helps (not sure why it doesn't helps me earlier, maybe because I deleted only transient)
