### ISSUE TITLE
 Magit commit opens *Async Shell Command* window

### ISSUE THREAD

**Issue by 3rd3** [magit/magit#3077] opened 2017-05-18 08:33 UTC
Commit via `SPC g s c c` opens an empty *Async Shell Command* window near the bottom and puts the focus there. Is that intended? How can I change this behavior such that this window does not open or that the focus is set to the `COMMIT_EDIT_MSG` buffer?

`M-x magit-version RET`: Magit 20170425.638, Git 2.9.0, Emacs 25.2.1, darwin

I'm use Magit in Spacemacs.

**Comment by kyleam** [comment] 2017-05-18 14:10
I don't use spacemacs, so I don't know what that key sequence means.
But assuming it runs the command `magit-commit`, you should be placed
in the commit message buffer, and an async shell command buffer
shouldn't be displayed or created.  Do you see the same thing if you
run <kbd>M-x magit-commit</kbd>?

**Comment by kyleam** [comment] 2017-05-19 15:33
I'm closing this because there's not much we can do to investigate.
This is likely quite specific to your setup; if Magit were regularly
throwing users into an async shell buffer when they tried to commit,
we'd see a lot of reports.

Please reopen if you have more details about how to reproduce the
issue.

**Closed by kyleam** 2017-05-19 15:33 UTC
Labels: support
