### ISSUE TITLE
"blame parent commit" feature discoverability in blame mode

### ISSUE THREAD

**Issue by moy** [magit/magit#3389] opened 2018-03-02 16:31 UTC
When blaming a file, it's common to to find out that the last modification for the lines of interest was a minor one, and then it's very convenient to have an easy way to blame the parent commit of these lines. For example, in `git gui blame`, one can right-click on a line -> "blame parent commit".

It would be very cool to have a similar feature in Magit's blame-mode.

PS: Thanks a lot for your work on Magit! :-)

**Comment by tarsius** [comment] 2018-03-02 16:47
And in Magit you can just invoke `magit-blame` again, while blame information is already visible. You can do that using <kbd>b</kbd>.

You might also want to enable `global-magit-file-mode` and then see what is available on <kbd>C-c M-g</kbd>.

**Comment by moy** [comment] 2018-03-02 16:56
Ah, thanks!

I missed in in the documentation, but it is there: https://magit.vc/manual/magit/Blaming.html:

> If Magit-Blame mode is already turned on in the current buffer then blaming is done recursively, by visiting REVISION:FILE (using magit-find-file), where REVISION is the revision before the revision that added the current line or chunk of lines.

May I suggest a very minor doc improvement then: make sure the word "parent" appears somewhere in the explanations (I googled "magit blame parent commit" and searched the doc for the word "parent" without finding, such occurrence would have helped my during my search). For example `where REVISION is the parent of the revision that added the current line or chunk of lines.`.

Anyway, thanks for your quick answer and for the magi(ck|t) you're doing!

**Comment by tarsius** [comment] 2018-03-02 16:59
But blaming again does not necessarily find the parent commit. Like with humans the parents of a commit are only the direct ancestors.

**Comment by moy** [comment] 2018-03-02 17:09
I don't get it. The original text is "the revision before the revision", which to me is very much what "parent commit" is (well, strictly speaking the both your version and mine should state which parent it is in case of merge). Blame will then walk through history from that commit, but it'll start from the parent commit.

I just checked, on a file where RET in blame-mode shows a commit with `Parent:     23bee48`, running blame again opens a buffer `<filename>~23bee48`, i.e. it does blame against the parent.

**Comment by tarsius** [comment] 2018-03-02 17:22
Hm, seems you are right, I'll have to take another look.

**Comment by phil-s** [comment] 2018-03-07 04:03
I presume this is equivalent to <kbd>a</kbd> when using `vc-annotate` ?

**Comment by moy** [comment] 2018-03-07 16:41
> I presume this is equivalent to `a` when using vc-annotate ?

Yes, that's it.

**Comment by tarsius** [comment] 2018-03-29 01:49
More or less a duplicate of #3263.

**Closed by tarsius** 2018-03-29 01:49 UTC
Labels: documentation, duplicate, support

**Comment by moy** [comment] 2018-04-04 21:06
I don't understand. #3263 is about forward/reverse blame. My point with this issue is not, it's still the traditional blaming that goes backwards in time starting from the present. Just that it's convenient to have a way to continue towards the past after the first blame stops (the feature is there, just that I didn't find it and I think minor modifications of the doc could make it easier to find).

Did I miss anything?

**Comment by tarsius** [comment] 2018-04-04 21:36
Okay I did `/s/the revision before/a parent of/` now.

**Comment by moy** [comment] 2018-04-05 07:13
Perfect. Future me is happy because he'll find the feature right away :-).

Thanks (for this and your work on Magit in general!).
