### ISSUE TITLE
(void-function transient-prefix-object)

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#5064] opened 2023-12-09 22:44 UTC
On HEAD of main today:
Magit v3.3.0-841-g42e261d2, Transient 0.4.3, Git 2.42.1, Emacs 29.1, darwin
GNU Emacs 29.1 (build 1, aarch64-apple-darwin22.5.0, Carbon Version 169 AppKit 2299.6) of 2023-08-08

typing `b' causes backtrace even with emacs -Q, in seemingly any repo

```
Debugger entered--Lisp error: (void-function transient-prefix-object)
  apply(debug (error (void-function transient-prefix-object)))
  transient--exit-and-debug(error (void-function transient-prefix-object))
  (transient-prefix-object)
  (eieio-oref (transient-prefix-object) 'scope)
  (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope))
  (closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope)))()
  transient--do-suffix-p((closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope))) nil nil nil nil nil nil nil t)
  transient--use-suffix-p(#<transient-column transient-column-572a8e6c>)
  transient--init-group(nil [1 transient-column (:description "Variables" :if (closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope)))) ((1 transient-suffix (:key "d" :command magit-branch.<branch>.description)) (1 transient-suffix (:key "u" :command magit-branch.<branch>.merge/remote)) (1 transient-suffix (:key "r" :command magit-branch.<branch>.rebase)) (1 transient-suffix (:key "p" :command magit-branch.<branch>.pushRemote)))])
  transient--init-child(nil [1 transient-column (:description "Variables" :if (closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope)))) ((1 transient-suffix (:key "d" :command magit-branch.<branch>.description)) (1 transient-suffix (:key "u" :command magit-branch.<branch>.merge/remote)) (1 transient-suffix (:key "r" :command magit-branch.<branch>.rebase)) (1 transient-suffix (:key "p" :command magit-branch.<branch>.pushRemote)))])
  #f(compiled-function (c) #<bytecode -0x142f4544a7f7fbce>)([1 transient-column (:description "Variables" :if (closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope)))) ((1 transient-suffix (:key "d" :command magit-branch.<branch>.description)) (1 transient-suffix (:key "u" :command magit-branch.<branch>.merge/remote)) (1 transient-suffix (:key "r" :command magit-branch.<branch>.rebase)) (1 transient-suffix (:key "p" :command magit-branch.<branch>.pushRemote)))])
  mapcan(#f(compiled-function (c) #<bytecode -0x142f4544a7f7fbce>) ([1 transient-column (:description "Arguments") ((7 transient-switch (:key "-r" :description "Recurse submodules when checking out an existing b..." :argument "--recurse-submodules" :command transient:magit-branch:--recurse-submodules :if (closure (t) nil (magit-git-version>= "2.13")))))] [1 transient-column (:description "Variables" :if (closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope)))) ((1 transient-suffix (:key "d" :command magit-branch.<branch>.description)) (1 transient-suffix (:key "u" :command magit-branch.<branch>.merge/remote)) (1 transient-suffix (:key "r" :command magit-branch.<branch>.rebase)) (1 transient-suffix (:key "p" :command magit-branch.<branch>.pushRemote)))] [1 transient-columns nil ([1 transient-column (:description "Checkout") ((1 transient-suffix (:key "b" :description "branch/revision" :command magit-checkout)) (1 transient-suffix (:key "l" :description "local branch" :command magit-branch-checkout)) (6 transient-suffix (:key "o" :description "new orphan" :command magit-branch-orphan)))] [1 transient-column (:description "") ((1 transient-suffix (:key "c" :description "new branch" :command magit-branch-and-checkout)) (1 transient-suffix (:key "s" :description "new spin-off" :command magit-branch-spinoff)) (5 transient-suffix (:key "w" :description "new worktree" :command magit-worktree-checkout)))] [1 transient-column (:description "Create") ((1 transient-suffix (:key "n" :description "new branch" :command magit-branch-create)) (1 transient-suffix (:key "S" :description "new spin-out" :command magit-branch-spinout)) (5 transient-suffix (:key "W" :description "new worktree" :command magit-worktree-branch)))] [1 transient-column (:description "Do") ((1 transient-suffix (:key "C" :description "configure..." :command magit-branch-configure)) (1 transient-suffix (:key "m" :description "rename" :command magit-branch-rename)) (1 transient-suffix (:key "x" :description "reset" :command magit-branch-reset)) (1 transient-suffix (:key "k" :description "delete" :command magit-branch-delete)))] [1 transient-column (:description "") ((7 transient-suffix (:key "h" :description "shelve" :command magit-branch-shelve)) (7 transient-suffix (:key "H" :description "unshelve" :command magit-branch-unshelve)))])] [1 transient-columns (:hide #f(compiled-function () #<bytecode 0x173d9817c0f5065e>)) ([1 transient-column (:description "Value commands") ((1 transient-suffix (:key "C-x s  " :description "Set" :command transient-set)) (1 transient-suffix (:key "C-x C-s" :description "Save" :command transient-save)) (1 transient-suffix (:key "C-x C-k" :description "Reset" :command transient-reset)) (1 transient-suffix (:key "C-x p  " :description "Previous value" :command transient-history-prev)) (1 transient-suffix (:key "C-x n  " :description "Next value" :command transient-history-next)))] [1 transient-column (:description "Sticky commands") ((1 transient-suffix (:key "C-g" :description "Quit prefix or transient" :command transient-quit-one)) (1 transient-suffix (:key "C-q" :description "Quit transient stack" :command transient-quit-all)) (1 transient-suffix (:key "C-z" :description "Suspend transient stack" :command transient-suspend)))] [1 transient-column (:description "Customize") ((1 transient-suffix (:key "C-x t" :command transient-toggle-common :description #f(compiled-function () #<bytecode 0x1e0d3cc1cd32e9b5>))) (1 transient-suffix (:key "C-x l" :description "Show/hide suffixes" :command transient-set-level)))])]))
  cl-mapcan(#f(compiled-function (c) #<bytecode -0x142f4544a7f7fbce>) ([1 transient-column (:description "Arguments") ((7 transient-switch (:key "-r" :description "Recurse submodules when checking out an existing b..." :argument "--recurse-submodules" :command transient:magit-branch:--recurse-submodules :if (closure (t) nil (magit-git-version>= "2.13")))))] [1 transient-column (:description "Variables" :if (closure (t) nil (and magit-branch-direct-configure (eieio-oref (transient-prefix-object) 'scope)))) ((1 transient-suffix (:key "d" :command magit-branch.<branch>.description)) (1 transient-suffix (:key "u" :command magit-branch.<branch>.merge/remote)) (1 transient-suffix (:key "r" :command magit-branch.<branch>.rebase)) (1 transient-suffix (:key "p" :command magit-branch.<branch>.pushRemote)))] [1 transient-columns nil ([1 transient-column (:description "Checkout") ((1 transient-suffix (:key "b" :description "branch/revision" :command magit-checkout)) (1 transient-suffix (:key "l" :description "local branch" :command magit-branch-checkout)) (6 transient-suffix (:key "o" :description "new orphan" :command magit-branch-orphan)))] [1 transient-column (:description "") ((1 transient-suffix (:key "c" :description "new branch" :command magit-branch-and-checkout)) (1 transient-suffix (:key "s" :description "new spin-off" :command magit-branch-spinoff)) (5 transient-suffix (:key "w" :description "new worktree" :command magit-worktree-checkout)))] [1 transient-column (:description "Create") ((1 transient-suffix (:key "n" :description "new branch" :command magit-branch-create)) (1 transient-suffix (:key "S" :description "new spin-out" :command magit-branch-spinout)) (5 transient-suffix (:key "W" :description "new worktree" :command magit-worktree-branch)))] [1 transient-column (:description "Do") ((1 transient-suffix (:key "C" :description "configure..." :command magit-branch-configure)) (1 transient-suffix (:key "m" :description "rename" :command magit-branch-rename)) (1 transient-suffix (:key "x" :description "reset" :command magit-branch-reset)) (1 transient-suffix (:key "k" :description "delete" :command magit-branch-delete)))] [1 transient-column (:description "") ((7 transient-suffix (:key "h" :description "shelve" :command magit-branch-shelve)) (7 transient-suffix (:key "H" :description "unshelve" :command magit-branch-unshelve)))])] [1 transient-columns (:hide #f(compiled-function () #<bytecode 0x173d9817c0f5065e>)) ([1 transient-column (:description "Value commands") ((1 transient-suffix (:key "C-x s  " :description "Set" :command transient-set)) (1 transient-suffix (:key "C-x C-s" :description "Save" :command transient-save)) (1 transient-suffix (:key "C-x C-k" :description "Reset" :command transient-reset)) (1 transient-suffix (:key "C-x p  " :description "Previous value" :command transient-history-prev)) (1 transient-suffix (:key "C-x n  " :description "Next value" :command transient-history-next)))] [1 transient-column (:description "Sticky commands") ((1 transient-suffix (:key "C-g" :description "Quit prefix or transient" :command transient-quit-one)) (1 transient-suffix (:key "C-q" :description "Quit transient stack" :command transient-quit-all)) (1 transient-suffix (:key "C-z" :description "Suspend transient stack" :command transient-suspend)))] [1 transient-column (:description "Customize") ((1 transient-suffix (:key "C-x t" :command transient-toggle-common :description #f(compiled-function () #<bytecode 0x1e0d3cc1cd32e9b5>))) (1 transient-suffix (:key "C-x l" :description "Show/hide suffixes" :command transient-set-level)))])]))
  transient--init-suffixes(magit-branch)
  transient--init-objects(magit-branch nil (:scope "main"))
  transient-setup(magit-branch nil nil :scope "main")
  magit-branch("main")
  funcall-interactively(magit-branch "main")
  call-interactively(magit-branch nil nil)
  command-execute(magit-branch)
```

**Comment by tarsius** [comment] 2023-12-09 22:59
You have to update Transient. `transient-prefix-object` is a new function.

Duplicate of #5062 and a few others, I believe. Please use the search feature before opening issues.

**Closed** 2023-12-09 22:59 UTC
Labels: duplicate, support

**Comment by dpassen** [comment] 2023-12-10 01:25
Perhaps this change should be reconsidered. emacs-29.1 ships with transient 0.4.1 and upgrading built-ins is more complicated than external packages.

**Comment by tarsius** [comment] 2023-12-10 15:47
> Perhaps this change should be reconsidered.

What change? "Improving Transient, even though it is now part of Emacs"? :grin: 

> upgrading built-ins is more complicated than external packages.

That's very unfortunate and the result of a bad default. But it's easily fixed: `(setq package-install-upgrade-built-in t)`, basically.

We have the same issue with `seq` and I recently added a warning that informs users how to fix the issue. I've now done [the same](041f034c6d4974ff4370fc67a0eea9970665b3bc) for `transient`.

```elisp
⛔ Emergency (magit): Magit requires `transient' >= 0.5.0,
but due to bad defaults, Emacs' package manager, refuses to
upgrade this and other built-in packages to higher releases
from GNU Elpa.

To fix this, you have to add this to your init file:

  (setq package-install-upgrade-built-in t)

Then evaluate that expression by placing the cursor after it
and typing C-d d.

Once you have done that, you have to explicitly upgrade `transient':

  M-x package-upgrade transient RET

Then you also must make sure the updated version is loaded,
by evaluating this form:

  (progn (unload-feature 'transient t) (require 'transient))

If you don't use the `package' package manager but still get
this warning, then your chosen package manager likely has a
similar defect.
```
