### ISSUE TITLE
Magit faces not honoring theme in client server mode

### ISSUE THREAD

**Issue by memeplex** [magit/magit#3526] opened 2018-07-26 23:38 UTC
#  (1) what behavior you expected

I'm using doom tomorrow night theme. I expect magit face colors to follow this theme.

#  (2) what behavior you observed

When I simply run `emacs` the colors for magit faces are fine. When I run `emacs --daemon` and `emacsclient -c` instead the colors are wrong and I have to `load-theme` explicitly afterwards in order to fix them.

I don't think this is doom culprit since from a cursory inspection of its code it's just setting magit faces in the usual way. Nevertheless I've reported it at their tracker. You can see some screenshots there too. https://github.com/hlissner/emacs-doom-themes/issues/210

#  (3) and how we can reproduce the issue.

Install doom themes. Enable tomorrow night (probably this happens with other themes too). Start an emacs daemon. Run emacsclient against that daemon. See some diff using magit, in particular it's quite obvious that the unhighlighted colors aren't from the theme. Repeat for standalone emacs and compare.

#  M-x magit-version RET

Magit 20180725.1504, Git 2.18.0, Emacs 26.1.50, gnu/linux

**Comment by tarsius** [comment] 2018-07-26 23:45
I think neither Magit nor Doom is to plain. Rather `emacs --daemon` loads Emacs with the assumption that you will connect to it in a terminal and when you later connect to it and create an X11 window, then those assumptions are not correct anymore. There are probably ways to make things work better but because I don't use `emacs --daemon` and almost never use `emacsclient` I do not know them.

In any case I very much doubt that Magit is to blame, so I am closing this.

**Closed by tarsius** 2018-07-26 23:45 UTC

**Comment by tarsius** [comment] 2018-07-26 23:46
But I would appreciate it if you could add a link here to the solution once it has been found, so that I know a little more something like this comes up again.

**Comment by memeplex** [comment] 2018-07-26 23:53
Ok, thanks for the hint. I tried loading the theme on an after frame
creation hook, which should have worked according to your suggestion, but
it didn't. Maybe I did something wrong, I will try again and let you know
of any advance.

**Comment by memeplex** [comment] 2018-07-26 23:56
Btw, every other color is ok in client/server mode AFAICS, event most magit colors. The colors that aren't working are computed on the fly by the theme (darkening other base colors). Maybe if emacs is assuming that it's running on a terminal and this terminal is not 24 bit color, then the computation could be throwing colors that the underlying terminal barely can approximate.

**Comment by memeplex** [comment] 2018-07-27 00:04
Here are some workarounds:

1. `emacsclient -c --eval "(load-theme 'doom-tomorrow-night)"`

2. (I was missing the `select-frame` part the first time, I'm still unsure why it's needed though):

```elisp
(add-hook 'after-make-frame-functions
          (lambda (frame)
            (select-frame frame)
            (load-theme 'doom-tomorrow-night)))
```

I assume this could be improved to only load the theme one time.

**Comment by madscientist** [comment] 2018-07-27 12:54
Just a note: it's not the case that `emacs --daemon` expects clients to run in a terminal.  I have `emacs --daemon` set to start in my GNOME login session startup so it's always running, and when I use Emacs on my desktop I use emacsclient to open an X window and when I log in from home I use emacsclient to open in an xterm (over ssh).  It's the only way I use Emacs, in all my environments.

I don't use themes and Magit works great in both X and terminal modes so I can't comment on the specific problem.

**Comment by npostavs** [comment] 2018-07-27 18:14
> Just a note: it's not the case that `emacs --daemon` expects clients to run in a terminal.

The problem is likely some config code somewhere that doesn't expect both graphical and terminal clients in the same session. E.g., it checks `display-graphic-p` only once on startup, instead of per-display/frame.

**Comment by memeplex** [comment] 2018-07-27 18:22
Indeed I was searching for display-xxx-p tonight and found nothing related
in the theme. Does magit do some display conditional initialization to its
faces? It's really weird, perhaps I should report this to emacs bug
tracker, at least to get some clarification on the issue.

**Comment by npostavs** [comment] 2018-07-27 18:29
Based on what you've posted so far, I don't see anything that would point to an Emacs bug. You said something about colour blending, perhaps that implicitly uses a fixed colour value for the face (and hence locks in the terminal colour for a face when starting as daemon)?

**Comment by memeplex** [comment] 2018-07-27 18:58
On Fri, Jul 27, 2018, 3:29 PM Noam Postavsky <notifications@github.com>
wrote:

> Based on what you've posted so far, I don't see anything that would point
> to an Emacs bug. You said something about colour blending, perhaps that
>
Yes, but after a closer inspection this color bending is just
(unconditionally to the device type) computing a rgb value from others.
Except that emacs store the closer available color for the face instead of
the passed one, which I don't think, I'm unable to understand what the
daemon environment has to do.

>
>

**Comment by memeplex** [comment] 2018-07-27 23:39
I've been doing some debugging and it seems to be that, indeed, the result of `doom-blend` depends on the current frame/terminal type:

1. `doom-tomorrow-night.el` defines

```
   (violet     '("#b294bb" "#b294bb" "brightmagenta"))
   (bg         '("#1d1f21" nil       nil            ))
```

2. `doom-themes-common` defines

```
   magit-diff-hunk-heading   :background (doom-blend violet bg 0.3)
```

3. `doom-themes` defines the function `doom-blend (color1 color2 alpha)`

4. After `load-theme` in the daemon  `magit-diff-hunk-heading` has background color `#4c004c`

5. After `load-theme` in a frame `magit-diff-hunk-heading` has background color `#49424f`

6. Now, let's eval the following expression in different environments

```
(let ((violet     '("#b294bb" "#b294bb" "brightmagenta"))
      (bg         '("#1d1f21" nil       nil            )))
  (doom-blend violet bg 0.3))
```
   * eval in x frame --> #49424f 
   * eval in TERM=xterm-24bit --> #49424f
   * eval in TERM=xterm --> #440044
   * eval in TERM=xterm-256color --> #483c48
   * eval in daemon --> #4c004c

7. For the colors above `doom-blend` is essentially doing:

```
(doom-name-to-rgb "#b294bb") -> (x1, x2, x3)
(doom-name-to-rgb "#1d1f21") -> (y1, y2, y2)
    ---> sum(alpha x (x1, x2, x3), (1- alpha) x (y1, y2, y3))
```

8. The difference that you can see in point 6 is due to `doom-name-to-rgb` returning different vectors in different environments.

9. `doom-name-to-rgb` is defined as:

```
(defun doom-name-to-rgb (color &optional frame)
  "Retrieves the hexidecimal string repesented the named COLOR (e.g. \"red\")
for FRAME (defaults to the current frame)."
  (cl-loop for x in (color-values color frame)
           collect (/ x (float (car (color-values "#ffffff"))))))
```

10. So ultimately the difference must come from `color-values`. Its documentation states that it:

```
Returns a description of the color named COLOR on frame FRAME.
```

So it clearly depends on the type of frame.

Now, the missing part of this puzzle is in which kind of terminal or display the daemon runs. Notice that the color computed for the daemon is not only different from the color computed inside a frame but also from 16 color, 256 color and 24 bit terminals.

**Comment by memeplex** [comment] 2018-07-27 23:53
Now I would say this IS a bug in doom themes, because by calling `color-values` it is prematurely setting a display-dependent color which should have been done by emacs "display abstraction layer" as a last step. The theme should set exact colors and let emacs map them to the different display types.
