### ISSUE TITLE
Lisp error: (void-variable git-commit-mode-map)

### ISSUE THREAD

**Issue by avatar-lavventura** [magit/magit#5227] opened 2024-09-17 09:42 UTC
The error I am receiving with the newest version (`magit-4.1.0`). I was not getting this error on the previous versions of magit. This error accout due to `(require 'magit)` line.

```lisp
Debugger entered--Lisp error: (void-variable git-commit-mode-map)
  (keymap-set git-commit-mode-map "C-c C-d" #'magit-diff-while-committing)
  eval-buffer(#<buffer  *load*-640754> nil "/home/alper/.emacs.d/elpa/magit-4.1.0/magit-diff.e..." nil t)  ; Reading at buffer position 48816
  load-with-code-conversion("/home/alper/.emacs.d/elpa/magit-4.1.0/magit-diff.e..." "/home/alper/.emacs.d/elpa/magit-4.1.0/magit-diff.e..." nil t)
  require(magit-diff)
  eval-buffer(#<buffer  *load*-415629> nil "/home/alper/.emacs.d/elpa/magit-4.1.0/magit.el" nil t)  ; Reading at buffer position 2463
  load-with-code-conversion("/home/alper/.emacs.d/elpa/magit-4.1.0/magit.el" "/home/alper/.emacs.d/elpa/magit-4.1.0/magit.el" nil t)
  require(magit)
  eval-buffer(#<buffer  *load*> nil "/home/alper/.emacs" nil t)  ; Reading at buffer position 79624
  load-with-code-conversion("/home/alper/.emacs" "/home/alper/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x14ff173d550b42c2>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cdc35>) t)
  command-line()
  normal-top-level()
```

Error message on the `.emacs` file for `(require 'magit)`: `Symbol’s value as variable is void: git-commit-mode-map`

**Comment by tarsius** [comment] 2024-09-17 14:15
Duplicate of #5225.

**Closed** 2024-09-17 14:15 UTC
Labels: duplicate
