### ISSUE TITLE
Installing magit from elpa gets "Package 'graphql-0' is unavailable"

### ISSUE THREAD

**Issue by Atman50** [magit/magit#3580] opened 2018-09-11 19:16 UTC
Used to work until very recently.

started emacs -q (windows)

Added ("melpa" . "https://melpa.org/packages/") to package-archives

M-x list-packages

Selected magit 20180903.2339

Tried to install.

Got output of:

```
Install package ‘magit-20180903.2339’? (y or n) y
Package menu: Operation started [Installing 1]
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
cond: Package ‘graphql-0’ is unavailable
```

Not sure if this externally imposed because of a missing graphql-0 package...

I tried installing graphql-mode 20180303.2358 and then tried to install magit. Still failed the same way.

I looked and didn't see anyone else having this issue.

BTW this is emacs 27.0.50: GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32) of 2018-03-26 - this has not changed for a while and magit was working fine until just recently....

**Comment by vermiculus** [comment] 2018-09-11 19:37
Duplicate of #3581 (I already commented on that one; sorry!)

**Closed** 2018-09-13 12:27 UTC
Labels: duplicate
