### ISSUE TITLE
magit-diff-mode should have diff-apply-hunk keybinding

### ISSUE THREAD

**Issue by doublep** [magit/magit#1903] opened 2015-06-19 14:54 UTC
It's useful to be able to go around full diff and selectively _revert_ hunks you find are bad (e.g. forgotten debug-only changes) before making a commit. I used to use `C-u C-c C-a` for this (`diff-apply-hunk` with prefix argument), but this is not bound in magit-diff-mode.

**Comment by tarsius** [comment] 2015-06-19 15:47
> I used to use `C-u C-c C-a` for this

In in magit it's simply `k` for un-/staged changes and `v` for changes that have already been committed. See http://magit.vc/manual/next/magit/Applying.html#Applying. That's the manual of the upcoming `2.1.0` (which will be releases in less than two weeks), but in `1.4.0` it works similarly.

In the future please use one of the intended support channels (see https://github.com/magit/magit#getting-help) and only open a feature request once you have confirmed that the reason why you cannot find some feature is because it doesn't exist yet. If you need more help figuring out how to use this feature then use the Emacs Stackexchange site for that.

**Closed by tarsius** 2015-06-19 15:47 UTC
Labels: 30 support

**Comment by doublep** [comment] 2015-06-19 15:53
You misunderstood. I wanted to revert certain hunks from a diff only, not commits or all changes to a file. Let's say in three classes I made 5 changes in each. Before commiting this changeset I review it. And during this review I find that 1 of 3x5 changes is wrong and should not be commited. I want to just revert that one hunk and still commit all three files.

**Comment by tarsius** [comment] 2015-06-19 15:59
> I wanted to revert certain hunks [...]

What you are describing is called "unstaging".

> And during this review I find that 1 of 3x5 changes is wrong and should not be commited.

Assuming you have already staged everything, go the the "Staged changes" in the status buffer. Then press `M-4` to show all hunks. Move to the change that should be not committed and press `u` to unstage it. Note that magit's stage (`s`), unstage (`u`), and other "apply variants" can act on hunks, or even the region, not just on complete files.

**Comment by doublep** [comment] 2015-06-19 16:01
Oh, indeed. Sorry for problems then.
