### ISSUE TITLE
Document how interactive rebasing works in practise a bit better

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2593] opened 2016-03-20 15:01 UTC
Hi,

I think the documentation (info manual) could be made a bit more newbie friendly in that regard.  I think it covers most things and there is nothing wrong with it, but OTOH, I think it is still not sufficient for someone who does it for the first time.  In particular:

1. When there are conflicts, explain what the typical workflow in Magit is: resolve with E m (provide a link to Emerge: some people will use this for the first time!).  Tell what quitting Emerge does.  How do I proceed?  (Do I have to commit or does this happen automatically?  How? Extend?)  How do I continue then?  (r r: say that!)
Just some quick notes will be sufficient.  I know that the wiki covers these things, but the very basic stuff should be covered by the manual, too.

2.  It seems that when I create a commit with the same commit message as the next commit to be applied, that commit will be replaced (the line then shows "gone").  Is that something special?  Please document that feature in a short note.

Just my opinion, of course.  But when I learned interactive rebasing with Magit, I needed to try things sometimes (which is not good since rebasing is complex and laborious per se enough, and you can really mess up your stuff).  And I needed to make some notes and I needed them later.  That's not good; after having done rebasing a few times, the manual should be enough to refresh your mind.

TIA,

Michael.

**Comment by aptly-io** [comment] 2016-03-26 21:14
Agree completely! 

1. A commit presents the squash action and next fails due to an error telling there are uncommitted files. Of course those files I like to comit+squash with an earlier commit. That's why action squash is presented in the GUI right?

2. Trying then to first simply commit and then rebase-to-squash made me lose all commits (T_T).
I advise git casual squashers, like me, not to use magit's interface but use the command line (if avail for your OS):

`git rebase -i HEAD~5 `
then being dropped in an editor where you rewrite the several presented `pick <hash>` lines into your preferred order and use action `squash` instead of `pick` seems like a piece of cake in comparison to magit's current GUI ...

**Comment by kyleam** [comment] 2016-03-27 00:23
> 1. A commit presents the squash action and next fails due to an error
> telling there are uncommitted files. Of course those files I like to
> comit+squash with an earlier commit.

I don't understand your description.  magit-commit-squash depends on
there being "uncommitted" files.  If you keep getting an error, please
report it in a separate issue, with steps to reproduce it.

> That's why action squash is presented in the GUI right?

magit-commit-squash ("c s") creates a commit like "c c", but instead of
opening up the editor for you to write the message, it allows you to
pick a commit to squash when rebasing later (naming the new commit as
"!squash \<old-commit subject>").

> 2. Trying then to first simply commit and then rebase-to-squash made
> me lose all commits (T_T).

That shouldn't happen, but if you made commits, you can retrieve them
from the reflog.

> I advise git casual squashers, like me, not to use magit's interface but use the command line (if avail for your OS):
>
> `git rebase -i HEAD~5 `
> then being dropped in an editor where you rewrite the several
> presented `pick <hash>` lines into your preferred order and use action
> `squash` instead of `pick` seems like a piece of cake in comparison to
> magit's current GUI ...

Documentation suggestions and detailed error reports are very
appreciated, but this comment isn't helpful.

**Comment by npostavs** [comment] 2016-03-27 01:10
> When there are conflicts, explain what the typical workflow in Magit is: resolve with E m (provide a link to Emerge

I've just been opening the file and resolving by hand (sometimes using `smerge-mode` to help a bit).

> It seems that when I create a commit with the same commit message as the next commit to be applied, that commit will be replaced (the line then shows "gone"). Is that something special? Please document that feature in a short note.

This is documented under "Rebase sequence log" but it might not be obvious that there is something useful in this section (I don't see an explanation of what a "sequence log" is).

> And I needed to make some notes and I needed them later.

Perhaps these notes could be the basis of some new documentation?

**Comment by michael-heerdegen** [comment] 2016-03-28 02:04
Noam Postavsky <notifications@github.com> writes:

> This is documented under "Rebase sequence log" but it might not be
> obvious that there is something useful in this section (I don't see an
> explanation of what a "sequence log" is).

Yes, we should try to find a better name.

And "is documented under" - do you mean what is said about the "same
patch id"?  I wondered what is meant by that.

> Perhaps these notes could be the basis of some new documentation?

Well, I mainly wrote down to use E m in case of conflict, and what to do
afterwards.  And I'm still not sure what is correct in some situations
(for example I had some trouble when conflicts while rebasing involved
merge commits), so I will not be able to provide a patch, but I can make
suggestions and ask questions.

**Comment by npostavs** [comment] 2016-03-28 02:24
> And "is documented under" - do you mean what is said about the "same patch id"? I wondered what is meant by that.

https://git-scm.com/docs/git-patch-id

> A "patch ID" is nothing but a sum of SHA-1 of the file diffs associated with a patch, with whitespace and line numbers ignored. As such, it’s "reasonably stable", but at the same time also reasonably unique, i.e., two patches that have the same "patch ID" are almost guaranteed to be the same thing.

---

> I mainly wrote down to use E m in case of conflict, and what to do afterwards. And I'm still not sure what is correct in some situations (for example I had some trouble when conflicts while rebasing involved merge commits)

Hmm, I'm not sure it makes sense to document the details conflict resolution using some other tool in the magit manual. Surely a link to the emerge section in the Emacs manual should suffice? From (ma)git's point of view, the only thing to do is resolve the conflict *somehow*, and mark it as resolved by staging the file.

**Comment by michael-heerdegen** [comment] 2016-03-28 23:25
Noam Postavsky <notifications@github.com> writes:

>  And "is documented under" - do you mean what is said about the "same
>  patch id"?  I wondered what is meant by that.
>
> https://git-scm.com/docs/git-patch-id

I originally wrote this:

 It seems that when I create a commit with the same commit message as
 the next commit to be applied, that commit will be replaced (the line
 then shows "gone"). Is that something special? Please document that
 feature in a short note.

Is what I wrote there true at all?  I could not reproduce this, and the
chapter (info "(magit) Rebase sequence log") doesn't say something about
this.

Seems "gone" is independent from the commit message, even if I add a
commit in between that has the same subject line like the following
to-be-applied commit (but with different patch id; that's what I
originally meant, maybe you had misunderstood?).

> Hmm, I'm not sure it makes sense to document the details conflict
> resolution using some other tool in the magit manual.

Agreed.

> Surely a link to the emerge section in the Emacs manual should
> suffice? From (ma)git's point of view, the only thing to do is resolve
> the conflict somehow, and mark it as resolved by staging the file.

That's all not trivial information for the newbie: it's not trivially
clear that resolving can be done from outside Magit (are git operations
involved in "resolving" and how can should there be performed with
Magit?), and/or how it can be done from within Emacs.

The main thing that confuses me is that I don't know what the state
"unresolved conflicts" is characterized.  Under the "staged" and
"unstaged" section I only see "unmerged", diffing commands fail there.
What does that mean?

And what does "resolve" mean (technically!)?

As far as I can conclude, it seems that when git tries to apply a change
that leads to a conflict, it stops the current operations and inserts
special markers into the files, and the git commands then find these
markers and behave specially.  But apart from that, there is no meta
data describing the conflict state, and if I remove the markers from the
files in any way, the "conflict state" is just gone, correct?  So, any
further operation will just be business as usual, e.g. resuming
rebasing, right?


If that's correct, we could explain this similarly in two or three
sentences, so any reader will be able to piece things together
him/herself.  Plus, say that "unmerged" just means files in worktree or
index respectively include merge markers, if that's correct.

**Comment by kyleam** [comment] 2016-03-29 00:30
> it's not trivially clear that resolving can be done from outside Magit
> (are git operations involved in "resolving" and how can should there
> be performed with Magit?), and/or how it can be done from within
> Emacs.

It maps directly to git rebase.  Quoting "man git-rebase":

```
In case of conflict, git rebase will stop at the first problematic commit and leave
conflict markers in the tree. You can use git diff to locate the markers (<<<<<<) and
make edits to resolve the conflict. For each file you edit, you need to tell Git that
the conflict has been resolved, typically this would be done with

    git add <filename>
```    

To do this from Magit, you resolve the conflict in any manner you
prefer, and then stage the file.

```
After resolving the conflict manually and updating the index with the desired
resolution, you can continue the rebasing process with

    git rebase --continue
```

From Magit, "rr".

```
Alternatively, you can undo the git rebase with

    git rebase --abort
```

From Magit, "ra".

**Comment by npostavs** [comment] 2016-03-29 01:20
> I originally wrote this:
>> It seems that when I create a commit with the same commit message as the next commit to be applied, that commit will be replaced (the line then shows "gone"). Is that something special? Please document that feature in a short note.
>
> Is what I wrote there true at all? I could not reproduce this, and the chapter (info "(magit) Rebase sequence log") doesn't say something about this.

No, the commit message has no effect. Only the actual diffs matter. I think the documentation about this is OK (providing you know what "tree" and "patch-id" are).

> That's all not trivial information for the newbie: it's not trivially clear that resolving can be done from outside Magit (are git operations involved in "resolving" and how can should there be performed with Magit?), and/or how it can be done from within Emacs.

Generally, the current docs assume the reader already has a thorough understanding of the corresponding git concepts, terminology, and procedures.

**Comment by michael-heerdegen** [comment] 2016-03-29 03:06
Noam Postavsky <notifications@github.com> writes:

>  That's all not trivial information for the newbie: it's not trivially
>  clear that resolving can be done from outside Magit (are git
>  operations involved in "resolving" and how can should there be
>  performed with Magit?), and/or how it can be done from within Emacs.
>
> Generally, the current docs assume the reader already has a thorough
> understanding of the corresponding git concepts, terminology, and
> procedures.

Rightly - in general, but...

FWIW, this was, in summary, the only larger issue about Magit that was
unclear to me after having read the docs I mentioned.

Rebasing is a complex procedure, the documentation of git itself is bad,
and Magit claims to be a complete git porcelain.  Given that, I think
adding two sentences could IMHO be justified.

The git manual page of git-rebase just tells me what I should "typically
do", I should "typically git add".  Pro Git is more a tutorial than a
reference.  Expect users coming to Magit having some defects and holes
in their mental models.  A tiny bit of redundancy doesn't harm, I
think.  Lots of people learn git by using Magit...etc...that were all my
arguments ;-) sorry for the long text.

BTW, I didn't need to stage anything when resolving a conflict in my
test now.  I just edited the file, and after that, Magit showed that
this version had already been staged.  Why is that?

**Comment by tarsius** [comment] 2016-03-29 08:56
> Generally, the current docs assume the reader already has a thorough understanding of the corresponding git concepts, terminology, and procedures.

I would have liked to seed the manual on such things by simply copying from the Git documentation but due the use of incompatible licenses that was not possible. And writing in-depth documentation from scratch for all features would have been too much work for one person.

I am not against explaining more of these things in the manual and we can do so by concentrating on the things users actually ask us about. But it will take time and since there always is Git's documentation, it isn't a priority.

> Rebasing is a complex procedure, the documentation of git itself is bad, and Magit claims to be a complete git porcelain. Given that, I think adding two sentences could IMHO be justified.

I suspect it might be a bit more work. But let us hear those to sentences ;-)

> A tiny bit of redundancy doesn't harm, I think. Lots of people learn git by using Magit

I agree and am happy that Magit can help users learning Git, but both Git and Magit have many features that need to be documented. Currently most of the manual was written by me. But my time is limited and I therefore of opted to in most cases not explain shared concepts/features in the Magit documentation.

We (as in "not just me") can improve that gradually, but it will take time and we (as in "the maintainers") won't always instantly improve the particular part of the manual a user encourages to improve.

> BTW, I didn't need to stage anything when resolving a conflict in my test now. I just edited the file, and after that, Magit showed that this version had already been staged. Why is that?

If you visit an unmerged file by typing `RET` in a Magit buffer, then that automatically turns on `smerge-mode`, which in turn notices when the last conflict was removed and in response stages the file.

**Comment by tarsius** [comment] 2016-05-08 11:21
I've added a new section on conflict resolution and improved the sections on rebasing.

**Closed by tarsius** 2016-05-08 11:21 UTC
Labels: feature request

**Comment by michael-heerdegen** [comment] 2016-06-03 22:39
Hi,

> I've added a new section on conflict resolution and improved the
> sections on rebasing.

My comment comes late, but here it is:

Your additions to the manual are great, it reads very well.  Thanks for
your work!
