### ISSUE TITLE
Magit hangs on staging hunk over tramp

### ISSUE THREAD

**Issue by koen-vg** [magit/magit#4870] opened 2023-02-03 10:07 UTC
# Bug description
1. Open magit on a remote (tramp) repository.
2. Attempt staging a single hunk.
3. The message "Tramp: Opening connection git for <host> using ssh...done" is issued.
4. Magit hangs.
5. I can quit (`C-g`) to regain control, but the hunk is still not staged.

When I `toggle-debug-on-quit` first and interrupt magit after it hangs, I get the following backtrace:
````
Debugger entered--Lisp error: (quit)
  magit-run-git-with-input("apply" ("--cached") "-p0" nil "--ignore-space-change" "-")
  magit-apply-patch(#<magit-file-section "[redacted]" [file unstaged status] 5177-[5207-]8165> ("--cached") "diff --git workflow/Snakefile workflow/Snakefile\ni...")
  magit-apply-hunk(#<magit-hunk-section (nil (349 6) (349 13)) [hunk file unstaged status] 5207-[5258-]5550> "--cached")
  magit-stage(nil)
  funcall-interactively(magit-stage nil)
  command-execute(magit-stage)
````
Meanwhile, there's still an open magit process whose buffer reads `run git … apply --cached -p0 --ignore-space-change -`. On the host in question, I can see a process `1399114 git --no-pager --literal-pathspecs -c core.preloadindex=true -c log.showSignature=false -c color.ui=false -c color.diff=false apply --cached -p0 --ignore-space-change -`.

I'm a little bit stuck on how to proceed in debugging this, but please let me know if there's anything I could do.

My first thought was that might be related somehow to https://github.com/magit/magit/issues/3624 and https://github.com/magit/magit/commit/2286a6397485f815de70e8105eda90fd0caed4e7, but both the local and remote hosts are linux machines. 

# Emacs and magit versions
Output of `magit-version`: `Magit v3.3.0-507-g679ded80, Git 2.30.2, Emacs 30.0.50, gnu/linux`

**Comment by tarsius** [comment] 2023-02-03 10:13
Duplicate of #4720.

**Closed** 2023-02-03 10:13 UTC
Labels: duplicate
