### ISSUE TITLE
How to start magit-revision-mode with all sections collapsed?

### ISSUE THREAD

**Issue by hisnawi** [magit/magit#3370] opened 2018-02-10 02:08 UTC
I usually like to get the big picture of which files changed in a commit before opening each file to see individual changes.

So in magit-log when clicking a commit it always opens with all files expanded and I have to always hit shift-tab to close them.

Is there a way to always start magit-revision-mode with magit-section-cycle-global enabled/activated?

I tried both:

```
    (add-hook 'magit-revision-mode-hook 'magit-section-cycle-global)
    (add-hook 'magit-revision-mode-hook (lambda () (magit-section-cycle-global)))
```

**Comment by tarsius** [comment] 2018-02-10 13:17
Duplicate of https://www.reddit.com/r/emacs/comments/7wfbl8/how_to_start_magitrevisionmode_with_all_sections/.

**Closed by tarsius** 2018-02-10 13:17 UTC
