### ISSUE TITLE
Toggle unmodified parts

### ISSUE THREAD

**Issue by stevium** [magit/magit#4327] opened 2021-02-21 20:42 UTC
Currently it's not possible to expand unmodified sections within a magit buffer:

![image](https://user-images.githubusercontent.com/15067828/108636800-ee28f280-7487-11eb-8970-0ff6057a7e74.png)

Having only a possibility to toggle modified areas is sometimes a limiting factor.

When scrolling through changes it would be very useful to toggle hidden contents as well, without the need to actually `visit` a file.

And if one needs to make a change on an unchanged line, one could land on it directly, instead of visiting modified parts and preforming additional navigation.

**Comment by tarsius** [comment] 2021-02-21 20:55
I do not intend to implement that.

**Comment by stevium** [comment] 2021-02-21 21:06
Is there any chance that you would welcome a PR on this? Or you just do not see a benefit to having this implemented? Thanks!

**Comment by tarsius** [comment] 2021-02-21 21:54
Are you aware that you can show more context using `D - U ...`? It will add more context to all hunks though, not just the one you clicked on.

> Is there any chance that you would welcome a PR on this? Or you just do not see a benefit to having this implemented?

The problem is that we no longer would just insert and then "wash" `git diff ...` output. We would have to go back and add more text. A naive implementation would also lose the extra text as soon as the buffer is refreshed.

I probably would not merge an implementation of this but you could still give it a try, if only to see how easy/hard it is to do. Who knows, maybe I'll change my mind.

**Comment by stevium** [comment] 2021-02-21 23:02
`D - U ...` is a great option for having more content expanded if configured with a large enough number. But at the same time it might feel a bit overwhelming if you are interested only in certain sections of a file and want to keep smaller hunks.

I was thinking maybe to have it more granular, with some concept of `nested unchanged hunks`, where each expansion would uncover more nested content, until you reach the center.

But in any case, thank you for your consideration. I would sure love to give it a try if I could find some time, to experiment with it and see how far I get with the prototype.

**Comment by tarsius** [comment] 2021-02-27 16:14
If you some up with a simple implementation, then there is a good chance that I would add it, but no guarantees.

I don't understand the "nested unchanged hunks" idea but that does not sound like something simple.

I think it should work pretty much exactly like in the Github web interface. Click to "show more lines above/below here" and the extra lines should be added to the existing hunk. It would probably be okay to not merge two sibling sections once there are no more lines "in between", but there should be no overlap, ever.

Adding lines should be done without recreating the complete buffer content. However when the buffer is refreshed, then these additional lines should not just disappear again. So we would have to remember which hunks get how many lines added to them. It will be a challenge to maintain the "identity" of hunks, when staging/applying/... preceding hunks.

**Comment by tarsius** [comment] 2021-02-27 16:15
I am closing this because I won't be working on it.

**Closed by tarsius** 2021-02-27 16:15 UTC
Labels: wontadd
