### ISSUE TITLE
Selecting lines of code in Magit diff buffers does not scroll the window horizontally

### ISSUE THREAD

**Issue by danielmartin** [magit/magit#4175] opened 2020-07-27 17:47 UTC
**Magit version:** Magit 20200723.236, Git 2.25.0, Emacs 26.3, darwin

**Steps to reproduce the problem:**

1. Open, for example, any git stash in Magit to display its diff in its own window.
2. Reduce the width of the diff window so that long lines are not displayed in full (note that the stash buffer has `truncate-lines` set to `t`).
3. Place the point in any of those long lines in the diff. Press C-a and C-e. You see the point going to the first and last character in the line, and the window scrolls horizontally. Now press C-a and start a region with C-SPC. Now press C-e.

**Actual Results:**

The line is selected, but you don't see the position of the point, so it makes selecting things harder.

**Expected Results:**

The window scrolls so you can see how the region is growing. That helps when selecting text because you can be more precise.

If you open a regular Emacs `text-mode` buffer and activate `toggle-truncate-lines`, this problem is not reproducible. It also does not happen in the file headings of Magit diff buffers.

**Comment by tarsius** [comment] 2020-07-27 18:48
I can reproduce but because this is a particularly complicated area that requires an hour of mediation before any progress can be attempted I will probably not try to fix this any time soon.

**Comment by tarsius** [comment] 2021-08-13 17:56
This is a duplicate of #2758. (Or maybe this is a new variant that hasn't explicitly been mentioned there. I did not re-read the whole thing.)

This is triggered by the newline character of the `before-string` in `magit-diff-highlight-hunk-region-using-overlays`.

As mentioned in the manual these issues are due to limitations of Emacs and I don't intend to do anything about it:

>  magit-diff-highlight-hunk-region-using-overlays and
>  magit-diff-highlight-hunk-region-using-underline emphasize the
>  region by placing delimiting horizontal lines before and after it.
>  Both of these functions have glitches which cannot be fixed due to
>  limitations of Emacs' display engine.  For more information see
>  https://github.com/magit/magit/issues/2758 ff.

**Closed** 2021-08-13 17:56 UTC
Labels: duplicate
