### ISSUE TITLE
magit2.1 tramp and centos6

### ISSUE THREAD

**Issue by baron42bba** [magit/magit#1978] opened 2015-07-05 12:03 UTC
Just a hint for those of us using magit via tramp on centos6:
The defaults for magit-git-global-arguments "--literal-pathspecs" and "-c" "core.preloadindex=true" don't work there. After removing these via customise-group all works like a charm.

Thank you for the great work!

Thinking about this: would be nice to have some kind of switch for these arguments for different systems. if local use these, if hostname x is in the path or tramp in general use these arguments. Or maybe a pre-run test git --version ?

Anyway just wanted to have it documented for other users fighting with the upgrade.

**Comment by tarsius** [comment] 2015-07-05 12:36
> The defaults for magit-git-global-arguments "--literal-pathspecs" and "-c" "core.preloadindex=true" don't work there. After removing these via customise-group all works like a charm.

What doesn't work?

> [remove] "--literal-pathspecs"

That will cause breakage if there are any filenames with special characters.

> Or maybe a pre-run test git --version ?

So the issue is due to the use of an old Git version and not due to the use of Centos?

**Comment by baron42bba** [comment] 2015-07-05 13:03
It's with git version 1.7.1 which is current for centos6. git-1.7.1-3.el6_4.1.x86_64
As these parameters are not known by that version of git git just throws an error and isn't delivering the output expected by magit. This causes magit to not even find the git repository.  So magit isn't working at all. After removing these - for git 1.7.1 unknown - arguments it's working again and finds the git repository.

**Comment by tarsius** [comment] 2015-07-05 13:31
You can do that of course, but you will run into issues in unexpected places, without a way to figure out what's going on. Magit requires Git v1.9.4. Most things also work with older versions but there's no list of what doesn't work, which I could point you too. At startup Magit checks that the local Git version is recent enough. But it does not check that remote versions are too.

So it would be better to just install a newer version on the remote, see http://magit.vc/manual/magit/I-am-using-a-Git-release-older-than-194.html.

----

I am closing this. That of course makes it less likely that others see it, on the other hand the issue tracker isn't the proper place for tips and tricks. (There is a wiki page for that.) But thanks anyway.

**Closed by tarsius** 2015-07-05 13:31 UTC
