### ISSUE TITLE
Debugger entered--Lisp error: (void-function keymap-lookup)

### ISSUE THREAD

**Issue by bradclawsie** [magit/magit#4878] opened 2023-02-15 01:12 UTC
emacs 28.2

no previous state (erased .emacs.d to test)

installed from melpa - magit-20230213.2018

3.3.0 from nongnu does not have this issue

**Comment by kyleam** [comment] 2023-02-15 02:19
> void-function keymap-lookup

I see this too.  `keymap-lookup` is defined by compat for Emacs versions before 29, so in general using it is fine.  However, I think the problem is that it's used in `magit-maybe-define-global-key-bindings`, and that can be triggered before compat is loaded because `magit-autoloads.el` includes

```elisp
(if after-init-time
    (magit-maybe-define-global-key-bindings)
  (add-hook 'after-init-hook #'magit-maybe-define-global-key-bindings t))
```

https://github.com/magit/magit/blob/deb10e984e16201182b0569f7df7d30ec3b8afa9/lisp/magit.el#L305-L320

@bradclawsie, you should be able to temporarily work around this by arranging `(require 'compat)` to be called before `magit-autoloads.el` gets loaded.

**Comment by PalaceChan** [comment] 2023-02-15 04:32
not sure if related but i also updated today emacs 28.2 and when i try to do magit-file-dispatch my messages shows

```
Turning on magit-auto-revert-mode...done
defvar: Symbol’s function definition is void: define-keymap
```
still trying to minimally repro (adding `(require 'compat)` before my `use-package` for magit isnt sufficing

**Comment by metayan** [comment] 2023-02-15 06:56
Putting
```
(require 'compat)
```
immediately after package initialisation at the beginning of `.emacs` made `magit` work for me.
Thanks for the tip, @kyleam .

**Comment by radrow** [comment] 2023-02-15 10:02
For me requiring compat didn't change anything.

**Comment by tarsius** [comment] 2023-02-15 10:58
I've pushed a fix. (I couldn't really test it because my 28.2 broke over night and I am out the door now.)

**Comment by bradclawsie** [comment] 2023-02-15 16:18
fwiw the most recent update has fixed this for me, @tarsius - thank you and if you are also confident that this issue is addressed, feel free to close with my gratitude

**Comment by PalaceChan** [comment] 2023-02-16 03:43
fixed my issue too and another similar error i was getting with orgit!

**Closed** 2023-02-21 13:24 UTC
Labels: bug
