### ISSUE TITLE
6401ba9343 breaks emacs <27.1

### ISSUE THREAD

**Issue by bgutter** [magit/magit#4010] opened 2019-12-08 02:45 UTC
1. **What behavior you expected**

No crash when magit is installed/enabled.

2. **what behavior you observed**

Crash; see backtrace.

3. **and how we can reproduce the issue.**

Install magit on current stable Emacs (26.3), then open a file.

**Please include a backtrace in your report.**

```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  executable-find("git" t)
  magit-turn-on-auto-revert-mode-if-desired()
  magit-auto-revert-mode-enable-in-buffers()
  run-hooks(change-major-mode-after-body-hook after-change-major-mode-hook)
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1( <SNIP> )
  <SNIP>
  my:find-buffer()
  funcall-interactively(my:find-buffer)
  call-interactively(my:find-buffer nil nil)
  command-execute(my:find-buffer)
```

**Also post the output of: M-x magit-version RET**
`
Magit 20191207.2321, Git 2.23.0, Emacs 26.3, gnu/linux
`
**Before reporting a defect please try to reproduce it using an Emacs instance...**

Confirmed -- issue still occurs.

Also, I <3 this package.

**Comment by bgutter** [comment] 2019-12-08 02:50
See also #3684

**Comment by Silex** [comment] 2019-12-08 09:56
Duplicate of #4011

**Closed** 2019-12-08 11:54 UTC
