### ISSUE TITLE
Empty interactive rebase not working

### ISSUE THREAD

**Issue by Alizter** [magit/magit#4865] opened 2023-01-30 14:29 UTC
When doing an interactive rebase with magit, sometimes I use it to remove commits. When the todo list is empty the rebase fails. My workaround for the moment is to add a break after the kill and then continue manually. Is this a git bug or could magit also handle this case?

**Comment by kyleam** [comment] 2023-01-31 02:18
> My workaround for the moment is to add a break after the kill and then continue manually

You can also insert a noop with `z` (`git-rebase-noop`) (see #2991).  Or do a hard reset if you know upfront that you don't want any of the commits. 

> Is this a git bug

It's Git's intended behavior.  If you look in the process buffer, you'll see "error: nothing to do" (because all the items of the todo list have been dropped).

> or could magit also handle this case?

In my view we shouldn't diverge from Git's behavior.

(Transferring to a discussion because this is a feature request.)

**Closed as completed** 2023-01-31 02:18 UTC
Labels: moved
