### ISSUE TITLE
Feature Request: Pruning Deleted Branches by Branch Name

### ISSUE THREAD

**Issue by sangwoo-joh** [magit/magit#4435] opened 2021-07-09 06:58 UTC
Hi. Thanks for this great tool! I literally use magit every day in my life, and this is one of the key applications in emacs!

I suggest improving (or maybe add a new option?) for pruning deleted branches: delete by branch name.

As I use only "Allow squash merging" and "Automatically delete head branches" in GitHub repository settings, the current `-p` option in the `Fetch` operation misses the local branches.

For example, assuming there is a `develop` branch, and I work on the `feature` branch which is check-outed from the `develop` branch. After some commits are pushed to the `feature` branch, the code review is finally completed. After I **squash & merge** the `feature` branch into the `develop` branch, GitHub automatically deletes the `feature` branch. Since I want to apply this removal into my local repository, I call magit's Fetch operation with `-p` (Prune delete branches) option, but it is not working. I think this is because magit is deleting the branch by its commit hash, not by the branch name.
So I hope one of the two:
 - Either improve the current `-p` option to find and delete the deleted branches by name,
 - Or, add a new option in the Fetch operation to find and delete the deleted branches by name.

Since I'm a big fan of magit, if this feature seems reasonable, I hope I would find a way to contribute this feature.
Thank you!

**Comment by alphapapa** [comment] 2021-07-09 07:14
This is not so much a Magit operation as it is a Git one.  The `-p` option calls `git fetch -p`.    Its man page says:

       -p, --prune
           After fetching, remove any remote-tracking references that no longer exist on the remote. Tags are not subject to
           pruning if they are fetched only because of the default tag auto-following or due to a --tags option. However, if tags
           are fetched due to an explicit refspec (either on the command line or in the remote configuration, for example if the
           remote was cloned with the --mirror option), then they are also subject to pruning.

You can learn this by pressing `? -p` in the fetch dispatcher.

But Magit also has these commands:

‘M p’     (‘magit-remote-prune’)

     This command removes stale remote-tracking branches for a remote
     read in the minibuffer.

‘M P’     (‘magit-remote-prune-refspecs’)

     This command removes stale refspecs for a remote read in the
     minibuffer.

     A refspec is stale if there no longer exists at least one branch on
     the remote that would be fetched due to that refspec.  A stale
     refspec is problematic because its existence causes Git to refuse
     to fetch according to the remaining non-stale refspecs.

     If only stale refspecs remain, then this command offers to either
     delete the remote or to replace the stale refspecs with the default
     refspec ("+refs/heads/*:refs/remotes/REMOTE/*").

     This command also removes the remote-tracking branches that were
     created due to the now stale refspecs.  Other stale branches are
     not removed.

You could learn about these by searching the Magit info manual.

**Comment by sangwoo-joh** [comment] 2021-07-09 07:32
@alphapapa wow, thanks for the excellent explanation!

I know there are `M p` and `M P`, but neither of them worked as I expected.

And, even though it is not supported by Git, is there any chance to support this feature by Magit? I apologize if this is a rude question.

**Comment by alphapapa** [comment] 2021-07-09 08:30
> I know there are M p and M P, but neither of them worked as I expected

As with any software problem, it will be hard to discuss this issue unless you speak in terms of reproducible, step-by-step examples, showing what you wanted to happen and what actually happened.  (Although Jonas may be so many steps ahead of us that he already knows the answer, but I'm trying to save him the trouble.)

> And, even though it is not supported by Git, is there any chance to support this feature by Magit? I apologize if this is a rude question.

Please note that I am not a Magit maintainer.

Anyway, I suspect that if you learn more about these features, you may find that they can already do what you want, but something else is preventing them from working as you want.

**Comment by tarsius** [comment] 2021-07-09 10:01
"Remote-tracking branches" are *local* references (e.g. `refs/remotes/origin/foobar`) of remote branches "as the exist on the remote". Collectively the refs in `refs/remotes/origin/*` provide a cached view into what branches exist on `origin`. It's only a cache, so it may come outdated and `git pull --prune` is how it is updated.

If you worked on `foobar` locally, then you did so by creating a "real" local branch, its ref being `refs/heads/foobar`. `git remote --prune` knows nothing about that.

Theoretically Magit could spy on the output of `git fetch --prune` and use some heuristics (name, push-target configuration etc.) to determine whether some related local branch should be deleted when a remote-tracking ref is being deleted. But that heuristic would fail sometimes and then it would silently destroy local branches that are still relevant. I think doing this would be too dangerous.

**Comment by alphapapa** [comment] 2021-07-09 11:28
Jonas seems better at parsing English than I am.  :)  Now I understand what @sangwoo-joh was asking for.

And yes, I agree, that would be too dangerous.  I try to use consistent prefixes for branch names so that from time to time I can use `magit-show-refs` to look for obsolete branches and they appear grouped together.

BTW, am I correct in that, were one to not squash before merging, git would be able to detect that these branches have been merged into `master` and they could be more easily and automatically removed?  (ISTR being prompted for something like this...)

Also, I recently discovered an alternative to squash-and-merge, but now I've forgotten the details, and I think the comment that mentioned it is in a browser tab somewhere...  Anyway, it was a way to preserve the original commits from the branch while keeping a linear, sans-merge commit graph.  Maybe something like a shared-parent fast-forward after rebasing...?  Seemed like one of those things that's not widely known but would be widely appreciated if it were.

**Comment by sangwoo-joh** [comment] 2021-07-10 04:29
@tarsius Thanks for the clarification! I understand that it is dangerous, so I thought it would be nice if another option (with warnings of course!) could support this feature. Currently, I just use a shell script for this, but since I'm living in Magit world, I just wanted to have it in the system.
Maybe I will have my own. Thanks!

**Comment by sangwoo-joh** [comment] 2021-07-10 04:32
@alphapapa 

> BTW, am I correct in that, were one to not squash before merging, git would be able to detect that these branches have been merged into `master` and they could be more easily and automatically removed?  (ISTR being prompted for something like this...)

Yes, if I just merge (not with squash), then local Git would automatically detect and delete the branch! But I prefer to squash & merge because this shows what a pull request does cleanly.

**Comment by alphapapa** [comment] 2021-07-10 08:32
BTW, I found the thing I was talking about: the workflow is to rebase and then force a merge commit.  It's mentioned here: https://news.ycombinator.com/item?id=27723435

**Comment by tarsius** [comment] 2021-07-12 20:43
> rebase and then force a merge commit

Highly recommend.

Also, if a pull-request is involved, then push to the feature branch after rebasing and before merging.

In practice I often skip creating a pull-request and/or doing the non-ff merge.

**Comment by tarsius** [comment] 2021-07-12 20:44
> Maybe I should make my own.

Happy hacking :grinning:

**Closed by tarsius** 2021-07-12 20:44 UTC
Labels: wontadd
