### ISSUE TITLE
Amend commit is too slow

### ISSUE THREAD

**Issue by dajva** [magit/magit#3603] opened 2018-09-27 09:41 UTC
Doing a magit amend takes a very long time on some (large?) repositories. I see a very long delay before the commit message buffer shows up.
To reproduce, checkout a large repository, for instance the Chromium code base which I tested this on. Open a magit status buffer in that repository and run the amend command. I suspect that this might be more related to number of branches than size of repository but that does not really matter for this report.

M-x magit-version RET
Magit 2.13.0, Git 2.18.0, Emacs 25.3.2, gnu/linux

I have identified this delay to come from `magit-commit-amend-assert` which runs a git command like this as I understand it:
`/usr/bin/git --no-pager --literal-pathspecs -c core.preloadindex=true -c log.showSignature=false branch --remote --contains`

Running this particular command takes close to 8 minutes in the chromium repository on my setup. I see the benefit of the amend-assert functionality but would be great if this could be turned off in some way.

Thanks for a great package.

**Comment by tarsius** [comment] 2018-09-27 10:51
This should be fixed by 76998b5e03cf6df390dba55546bbd3b3fc6eeaed, which isn't included in 2.13.0.  Please try the `master` branch.

Duplicate of #3519.

**Closed** 2018-09-27 10:52 UTC
Labels: duplicate

**Comment by dajva** [comment] 2018-09-27 13:13
Thanks, I'll try that
