### ISSUE TITLE
"Instant Fixup" occasionally fails with "Unable to create index.lock: File exists."

### ISSUE THREAD

**Issue by mgalgs** [magit/magit#2214] opened 2015-08-27 17:58 UTC
I've noticed that the "Instant Fixup" commit action occasionally fails with:

    fatal: Unable to create '/path/to/repo/kernel/.git/index.lock': File exists.

    If no other git process is currently running, this probably means a
    git process crashed in this repository earlier. Make sure no other git
    process is running and remove the file manually to continue.

    Could not apply 1105a9373f21f951c63de6e49bb8cd78b4adf291... fixup! iommu/arm-smmu: Implement .reg_read and .reg_write

The symptom looks similar to #2212 but the cause is different since I'm not doing anything with `git` outside of magit.

Here's the full "Instant Fixup" session (`commit` + `rebase -i`) from my `*magit-process*` buffer:

      0 git … commit --no-edit --fixup=7269a7aae25e --
    [detached HEAD 1105a9373f21] fixup! iommu/arm-smmu: Implement .reg_read and .reg_write
     1 file changed, 2 insertions(+), 2 deletions(-)

      1 git … rebase -i 7269a7aae25e^ --autosquash --autostash
    fatal: Unable to create '/path/to/repo/kernel/.git/index.lock': File exists.

    If no other git process is currently running, this probably means a
    git process crashed in this repository earlier. Make sure no other git
    process is running and remove the file manually to continue.

    Could not apply 1105a9373f21f951c63de6e49bb8cd78b4adf291... fixup! iommu/arm-smmu: Implement .reg_read and .reg_write

Is anything happening asynchronously during an "Instant Fixup"?  I wonder why the `index.lock` is still hanging around...

**Comment by mgalgs** [comment] 2015-08-27 18:00
I've only seen this while doing an "Instant Fixup".  I've never seen it during any other action.

**Comment by tarsius** [comment] 2015-08-29 16:24
I am closing this as a duplicate of #2212 because I think the cause *is* the same, we just have a very vague idea of what it is. If that turns out to be wrong, then we can of course reopen this.

In the output above I see nothing that indicates that an asynchronous git process started by magit is holding the lock.

**Closed by tarsius** 2015-08-29 16:24 UTC
Labels: 01 unconfirmed
