### ISSUE TITLE
How to prevent a bunch of open magit buffers after a commit?

### ISSUE THREAD

**Issue by kaushalmodi** [magit/magit#2124] opened 2015-07-28 22:58 UTC
I have noticed that at the end of a committing session, I have these buffers remaining open:

- magit process (even when there were no error during stage, commit, push, etc steps)
- magit diff (while this diff is useful when writing commit logs, I believe it shouldn't stay open after a commit is done)

Is this behavior expected? If so how can I fix it?

Also, probably related, at times after I finish committing by hitting `C-c C-c` in the commit log buffer, the magit status buffer gets buried. And then I need to `C-x b` to the status buffer to proceed with pushing.

**Comment by tarsius** [comment] 2015-07-29 15:22
> Is this behavior expected? If so how can I fix it?

Yes, that's the expected behavior. I recommend you don't change it.

* Running any command creates the process buffer, not just committing. It's like `*Messages*`. You might not always need it but when you need to check what you just did, then you'll be glad you can do it.

* The diff buffer contains state. (The diff arguments which should be used to show diffs in the diff buffer when inside this repository.) If you delete the buffer, then the state is gone. (There currently are some issues with how this state is used, but they will have been addressed once #2119 has been merged.)

**Comment by manuel-uberti** [comment] 2015-07-31 09:09
I'm not sure if this can help, but this is what I have in my setup:
```
(defun custom/kill-buffers (regexp)
  "Kill buffers matching REGEXP without asking for confirmation."
  (interactive "sKill buffers matching this regular expression: ")
  (cl-letf (((symbol-function 'kill-buffer-ask)
	     (lambda (buffer) (kill-buffer buffer))))
    (kill-matching-buffers regexp)))

(defun magit-quit-session ()
    "Restore previous window configuration and cleanup buffers."
    (interactive)
    (custom/kill-buffers "^\\*magit")
    (jump-to-register :magit-fullscreen))

(bind-key "q" #'magit-quit-session magit-status-mode-map)
```
With this code, after I am done with commits I just press ```q``` to close all the open Magit buffers.

**Comment by manuel-uberti** [comment] 2015-07-31 09:12
I am not sure whether this could be useful, but this is how I do it:
```
(defadvice magit-status (around magit-fullscreen activate)
    "Turn fullscreen on for magit-status."
     (window-configuration-to-register :magit-fullscreen)
     ad-do-it
     (delete-other-windows))

(defun magit-quit-session ()
    "Restore previous window configuration and cleanup buffers."
     (interactive)
     (custom/kill-buffers "^\\*magit")
     (jump-to-register :magit-fullscreen))

(bind-key "q" #'magit-quit-session magit-status-mode-map)
```
And this is the ```custom/kill-buffers``` function:
```
(defun custom/kill-buffers (regexp)
  "Kill buffers matching REGEXP without asking for confirmation."
  (interactive "sKill buffers matching this regular expression: ")
  (cl-letf (((symbol-function 'kill-buffer-ask)
	     (lambda (buffer) (kill-buffer buffer))))
    (kill-matching-buffers regexp)))
```

**Closed** 2015-07-31 16:11 UTC
Labels: 30 support

**Comment by kaushalmodi** [comment] 2015-07-31 16:14
Thanks @tarsius.

@manuel-uberti I might do something like what you did if there are still a lot of magit buffers lying around after the recently merged PR https://github.com/magit/magit/pull/2119.

**Comment by tarsius** [comment] 2015-07-31 16:16
> I might do something like what you did if there are still a lot of magit buffers lying around after the recently merged PR https://github.com/magit/magit/pull/2119.

These changes don't make it less (or more) likely that buffers stay alive. They most make it more desirable to keep the buffers alive.

**Comment by mmahmoudian** [comment] 2023-03-27 16:16
@tarsius since you have moved away your webite/blog, the link above is broken, and I could not find it by substituting `manuel-uberti.github.io` -> `emacsair.me`

Also if you don't mind me adding to the discussion, I like that Magit keep some buffers for further review, but I think it has merit to have a function to remove all magit buffers that are not locked. I think the `helpful` package has a function for this matter as well.

**Comment by tarsius** [comment] 2023-03-27 19:15
> @tarsius since you have moved away your webite/blog, the link above is broken, and I could not find it by substituting `manuel-uberti.github.io` -> `emacsair.me`

:grin: It appears you interpreted

> @manuel-uberti posted a followup

as

> Hey @manuel-uberti, take note, that I posted a followup

but it was meant as

> The person whose name is Manuel Uberti, posted a followup

For obvious reasons I did restore the post from his blog on my blog, when he deleted his blog.

----

> Also if you don't mind me adding to the discussion, I like that Magit keep some buffers for further review, but I think it has merit to have a function to remove all magit buffers that are not locked. I think the `helpful` package has a function for this matter as well.

`magit-mode-bury-buffer` with two prefix arguments kills all Magit buffers belonging to the current repository. I just had a look at the implementation and docstring, and decided that it needs a bit of tweaking, but basically it should already do what you want.

**Comment by tarsius** [comment] 2023-03-29 17:16
Link updated.

> I still would suggest adding a function similar to `mu-magit-kill-buffers`  to magit.

I cannot find a function by that name on this page or on the the blog post, so I am not sure what you are suggesting.

> I went through the existing keybindings and it seems these are not bound to anything magit related: `n`,`N`,`p`,`R`,`x`.

I'm afraid real estate is more scarce, see https://github.com/magit/magit/wiki/Plugin-Dispatch-Key-Registry.

> After some thinking I came up with C-q for default binding for this function. It is by default bound to `quoted-inser` from `simple.el` which is completely useless in `magit-status-mode` . This is just a suggestion from a relatively new and n00b Emacs user :)

Please do that in your personal configuration, for now at least.

I'm unsure whether `magit-kill-all-repository-buffers` and a key binding for that should be added, and will sleep over it a few times.

**Comment by tarsius** [comment] 2023-03-29 17:38
Ah right, he posted to links. I only followed the second.

**Comment by brc** [comment] 2024-04-09 22:02
@manuel-uberti's post is now at:
https://manueluberti.eu/posts/2018-02-17-magit-bury-buffer/

_( Where will Manuel's blog post be next summer? Celebrate this thread's decennial to find out! )_
