### ISSUE TITLE
magit-blame bails out on a buffer of a file with executable flag

### ISSUE THREAD

**Issue by kprav33n** [magit/magit#2295] opened 2015-09-26 04:17 UTC
When I run `magit-blame` on a buffer that is version controlled, I get the following error message:

```
user-error: Buffer isn't visiting a tracked file
```

I'm able to successfully run `vc-annotate` on the same buffer. Here are the version details:

```
Magit 20150918.541, Git 2.3.8 (Apple Git-58), Emacs 24.5.1
```

Please let me know if I should provide any additional details. Any tips on how to troubleshoot this issue?

**Comment by kyleam** [comment] 2015-09-26 04:38
I'm not having any luck reproducing it, but magit-file-relative-name
must be returning nil on your system.  Do you see this on with any
tracked file?  You could debug that function with eval-defun (C-u
C-M-x), call magit-blame, and report back what's causing the nil return
value.

**Comment by kprav33n** [comment] 2015-09-26 07:27
Thank you @kyleam for promptly looking at the issue. I can confirm that `magit-file-relative-name` is returning `nil`. This is not happening with all files in my repo. There are some files where `magit-blame` is successful. On those files, `magit-file-relative-name` is returning `non nil`. 

One more thing that I found after your reply is that for the failing buffer: there are multiple files in the git repo with the same name but different path. I'm not sure if that makes a difference.

**Comment by kyleam** [comment] 2015-09-26 15:25
> I can confirm that `magit-file-relative-name` is returning `nil`. This
> is not happening with all files in my repo.

Can you debug magit-file-relative-name and see what is behind that?

> One more thing that I found after your reply is that for the failing
> buffer: there are multiple files in the git repo with the same name
> but different path.

Are the ones with the same base names the ones that are failing for you?
I've tried to test this, and it works fine on my end.

Is this a public repo?  If not, can you reproduce it in a public repo so
that we can test with the same repo/files that are failing on your end?

**Comment by kprav33n** [comment] 2015-09-26 17:10
Unfortunately the issue is seen only on a repo that is not on githup, or public. I'm not able to reproduce in a new repo that I tried creating for this purpose.

Looks like the problem is arising from the macro `magit--with-safe-default-directory`. I tried evaluating the following expression from two different buffers in my git repo. 

```elisp
(magit--with-safe-default-directory buffer-file-name default-directory)
```

For the file that I can successfully blame, I get the parent directory of that file.

```
repo/foo/bar.cc -> repo/foo/
```

For the file that fails with blame, I get the file appended with a slash. This seems to be the culprit.

```
repo/car/jazz.cc -> repo/car/jazz.cc/
```

I'm not very familiar with macros. I'll debug this macro more, and update.

**Comment by kyleam** [comment] 2015-09-26 18:06
Thanks for the update.  I wonder what's different about the problematic
files.

While I don't think it will help your issue, you may want to update to
the latest version from MELPA.  There have been changes to
magit--with-safe-default-directory since your version.  These were
related to Windows and tramp, so they're not likely to affect you, but
you might as well be debugging the current version of
magit--with-safe-default-directory.

**Comment by kprav33n** [comment] 2015-09-26 19:17
I figured out the root cause. This happens for the file that has executable bit set on it. For those files, the following returns `t`.

```elisp
(file-accessible-directory-p buffer-file-name)
```

This might be a bug with Emacs itself. Try creating a file, set executable permission for everyone, and evaluate the above expression from it's buffer. It is surprising for this to return `t` while the file is actually not a directory.

**Comment by kprav33n** [comment] 2015-09-26 19:37
One more update. This is not a bug with Emacs `file-accessible-directory-p`. When invoking Emacs without the init file, the `file-accessible-directory-p` returns `nil`. However, when I load it with my configuration it returns `t` for the same file. I'm using [Spacemacs](https://github.com/syl20bnr/spacemacs) stock configuration. I'll attempt to turn off layer by layer and see which layer is introducing this issue. Once I get to the bottom of the issue, I'll add notes and close the issue. Please keep it open until then.

**Comment by kyleam** [comment] 2015-09-26 19:46
Thanks for the update.  Glad you're making progress in tracking it down.

**Comment by kprav33n** [comment] 2015-09-26 21:40
@kyleam Thanks for all the pointers. After spending about an hour, I'm completely lost now. The behavior of `(file-accessible-directory-p buffer-file-name)` is not consistent.If I run the same expression over and over in the same buffer, I get `t` sometimes and `nil` sometimes. Out of three times I ran, I got these in my `*Messages*` buffer.

```
nil [2 times]
t
```

I turned off all layers except magit. I also see difference in behavior for terminal (`-nw`) vs UI mode. I'm not able to reproduce this issue in terminal mode. I'm seeing this only in UI mode. I'm able to do `magit-blame` consistently in terminal model for the problematic buffer.

I found [this public repo](https://github.com/simonwagner/mergepbx) to reproduce the issue. The file is `src/mergepbx.py` as it has executable permission.

Here is a screen capture of how `magit-blame` doesn't work in UI mode, but works in terminal mode using the same Emacs.

[![Screen Capture](http://img.youtube.com/vi/PDo7tKFQgDc/0.jpg)](https://www.youtube.com/watch?v=PDo7tKFQgDc)

 I'm out of ideas on what to try.

**Comment by kyleam** [comment] 2015-09-27 04:24
Even though you said it only happened when using Spacemacs, I tried
with the mergepbx.py file you mentioned, looping over
`(file-accessible-directory-p buffer-file-name)` 100 times, and the
expected value, nil, was returned all times.

While this is showing up for you when using magit-blame, the issue
seems to be with file-accessible-directory-p when using Spacemacs.
I'm going to close this because I don't think there is anything to be
done on Magit's end, but feel free to post any further details or
progress.  I'm too am out of ideas of what you could try next, but
perhaps it's worth asking the Spacemacs developers if they can
reproduce the file-accessible-directory-p issue you're seeing.

**Closed by kyleam** 2015-09-27 04:24 UTC

**Comment by syl20bnr** [comment] 2015-09-27 05:07
It would be suprising that Spacemacs is the cause of this, this is a low level function and I don't see any settings that could compromise it.

@kprav33n Seems to me it is OS/Emacs build related, what is your OS and emacs build ? Same question for @kyleam

**Comment by kprav33n** [comment] 2015-09-27 05:26
@syl20bnr Thanks for jumping in. I just confirmed that this issue is not related to Spacemacs. I just tried it with bare minimal Emacs configuration with magit to reproduce the issue. Here are the version details:

OS Version:
```
$ uname -a
Darwin PRAVEEK6-M-3059 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

Emacs Version:
```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2015-04-10 on builder10-9.porkrind.org
```

Magit Version:
```
Magit 20150925.821, Git 2.3.8 (Apple Git-58), Emacs 24.5.1
```

Here is the screen capture of the issue with Vanilla Emacs. Can I reopen the issue?

[![Screen Capture](http://img.youtube.com/vi/3nVkhcieirE/0.jpg)](https://youtu.be/3nVkhcieirE)

**Comment by kyleam** [comment] 2015-09-27 05:35
> It would be suprising that Spacemacs is the cause of this, this is a
> low level function and I don't see any settings that could compromise
> it.

Agreed, but since @kprav33n reported that he only saw the issue when
using Spacemacs and not emacs -Q, I thought it'd be worth asking.

**Comment by syl20bnr** [comment] 2015-09-27 05:42
Mmmmhh seems that it is an Emacs bug.
@kprav33n could you test with the emacs-mac homebrew formula as well ?

> $ brew tap railwaycat/emacsmacport
$ brew install emacs-mac --with-spacemacs-icon

**Comment by kyleam** [comment] 2015-09-27 05:44
> Can I reopen the issue?

The issue is with how file-accessible-directory-p is behaving, so I don't think there is something to be done on magit's end.

**Comment by syl20bnr** [comment] 2015-09-27 05:59
Indeed. Open or not I would be a good thing to use this issue to track the bug upstream.
@kprav33n if you open a bug for Emacs, can you post the link here ?

**Comment by kprav33n** [comment] 2015-09-27 06:09
@kyleam @syl20bnr I also installed emacs-mac using brew. I face the exact issue with that as well. I'm not sure if Emacs folks will accept this as a valid bug. But, let me file it anyway. I'll restrict the scope of the upstream bug to `file-accessible-directory-p` to avoid pushing the issue back to magit/spacemacs.

**Comment by kyleam** [comment] 2015-09-27 06:25
@syl20bnr:
> if you open a bug for Emacs, can you post the link here ?

@kprav33n Yes, please do.  But marking it as closed, I didn't mean to suggest that you shouldn't follow up at all here.

Thanks for your nice work debugging this.  It will be very helpful to anyone else that encounters this.

**Comment by kprav33n** [comment] 2015-09-27 22:15
Filed an [upstream bug](http://lists.gnu.org/archive/html/bug-gnu-emacs/2015-09/msg00937.html).

> Your message is being forwarded to the package maintainers and other
interested parties for their attention; they will reply in due course.

> Your message has been sent to the package maintainer(s):
 bug-gnu-emacs@gnu.org

> If you wish to submit further information on this problem, please
send it to 21573@debbugs.gnu.org.

**Comment by rothmichaels** [comment] 2016-01-12 21:44
I experienced this issue also, using Emacs.app from MacPorts 

Version: `GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)`

**Comment by patefacio** [comment] 2016-03-10 23:29
I got the same error but for reasons unrelated to file permissionsand wanted to leave a record of the cause. For me I was seeing this error when trying to do a magit-status, or magit-blame on a file I knew was in git. The problem was at some point using magit I must have accidentally git inited a folder under my original git repo that was a parent to the file missing.

my_git_repo/path1/path2/file_in_question

my_git_repo has a .git folder and in magit I see file_in_question.
But somehow path2 also had a .git folder - no submodules - just a mistake.
Then doing magit-status on the file said it was not tracked. 
So, if you get this message, check upwards from the file to where you expect the correct .git folder.
If you find extra .git folders on the way, likely you did a magit-status on something and were too quick to hit a keystroke and unintentionally initialized a new empty repo.

**Comment by tarsius** [comment] 2016-03-26 09:58
According to http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21573#17 the bug isn't in Emacs either but in Apples code.

**Comment by tarsius** [comment] 2016-03-28 16:03
Could those for whom `(file-accessible-directory-p file)` sometimes returns incorrect results check whether `(and (file-directory-p file) (file-accessible-directory-p file))` always returns the correct result in those same situations.

**Comment by bitti** [comment] 2016-03-28 18:23
I can only a qualitative check, because it's somewhat difficult to reproduce it reliable (sometimes I have to open emacs with `-Q` and open the file in Python mode). But for my case the latter expression seems to work:

    (file-accessible-directory-p "/tmp/hello.py")
    t
    
    (and (file-directory-p "/tmp/hello.py") (file-accessible-directory-p "/tmp/hello.py"))
    nil
    
    (file-accessible-directory-p "/tmp")
    t
    
    (and (file-directory-p "/tmp") (file-accessible-directory-p "/tmp"))
    t

**Comment by sprajagopal** [comment] 2017-09-05 17:00
I have this issue too. Except it's weirder. I can't actually close emacs. Maybe it's calling magit-blame?!
I have no clue why though.

**Comment by tarsius** [comment] 2017-09-05 17:24
Without actually having reread everything above, I am guessing that your issue is something completely different because (a) we have added a work around for this issue (b) I don't see how `file-accessible-directory-p` could cause Emacs to "not actually close", and (c) or how attempting to close Emacs could cause `magit-blame` to be called.

You will have to provide much more precise information for us to have any change of figuring out what is going on.
