### ISSUE TITLE
No longer able to discard all changes to a file.

### ISSUE THREAD

**Issue by MacFarlaneBro** [magit/magit#3363] opened 2018-02-05 11:52 UTC
I have noticed that recently (the last month or so) I seem to have lost the ability to discard all changes to a file at once in the status page using 'k'. Instead I have to discard the changes to each  hunk within the file individually.

I'm not sure if this was an intentional change but it seems to be consistent across my devices and I was wondering if perhaps they key combination to discard a whole files changes has changed.

Magit: 20180118.1423
Git: 2.7.4
Emacs: 25.3.50.2
OS: Ubuntu

Thanks for all the great work!

**Comment by tarsius** [comment] 2018-02-05 12:29
I cannot reproduce that. Do you get a backtrace if you `M-x toggle-debug-on-error` first? Did you try with `make emacs-Q`, or if you are using `package.el` the command generated by `M-x magit-emacs-Q-command`?

**Comment by tarsius** [comment] 2018-02-05 16:12
Uh actually, that's expected, but I am not sure this always worked that way, let me check.

**Comment by tarsius** [comment] 2018-02-05 16:13
Are you *sure* you haven't been using `b k` in the past?

**Comment by tarsius** [comment] 2018-02-05 16:14
Waaaa, I need to take a break. To many issues on my head right now. Starting to confuse them with each other.

**Comment by weak-head** [comment] 2018-02-07 17:35
I'm having the similar behavior on Linux Mint 18.3 ('Abort' is shown as output), though on Ubuntu 17.04 and Windows 10 for the same repository, for the same file it works completely fine and 'k' discards the changes.

**Comment by MacFarlaneBro** [comment] 2018-02-07 17:42
Interesting, I was getting the same 'abort' message in the minibuffer, I forgot to mention that in my previous post.

**Comment by tarsius** [comment] 2018-02-07 20:54
That suggests that there might be a regression concerning the code that asks (or not) the user to confirm an action. How exactly do you "discard all changes" to a file of exactly what kind.

So far I am assuming that you discard a file by moving to

```
Unstaged changes (1)
[here]modified   lisp/magit.el
```

and then press `k` without an active region. When you do that are you asked `Discard unstaged changes in lisp/magit.el (y or n) ` and answer with `y`. Whether you are asked that question depends on the value of `magit-no-confirm`. I cannot reproduce the issue regardless of whether I choose to be asked this question or not.

**Comment by weak-head** [comment] 2018-02-08 04:07
Actually no special steps required, `k` doesn't work at all on my Linux Mint environment. Any possible way of calling discard doesn't work (e.g. `magit-discard`). On the other hand, there is no way how I can reproduce it on the other environments I have, so I feel that it is more environment specific.

Not sure if it would be much of help but when `k` is being pressed I have the following output:
1.  mini-buffer: `Abort`

2. 'Magit Process' buffer:

```  
0 git … checkout --
M	init.el
Your branch is up-to-date with 'origin/master'
```

3. Messages buffer: `user-error: Abort` 

Also `magit-no-confirm` is set to default and I'm not getting the question.

**Comment by tarsius** [comment] 2018-02-16 15:42
> I'm having the similar behavior on Linux Mint 18.3 ('Abort' is shown as output), though on Ubuntu 17.04 and Windows 10 for the same repository, for the same file it works completely fine and 'k' discards the changes.

Something must be different beside the OS. I don't see how that could make a difference in this case - especially since nothing weird like Windows or macOS is involved. Please try to find out what the actual difference is. Until you have found out what setting triggers this issue, I don't think I can fix it.

**Closed** 2018-02-25 01:05 UTC
Labels: unconfirmed
