### ISSUE TITLE
Commit with multiple frames using emacs-client

### ISSUE THREAD

**Issue by eflanigan00** [magit/magit#3127] opened 2017-07-13 17:14 UTC
magit commit will fail when I'm running emacs-client and having multiple frames open.
When I call `delete-other-frames` and commit everything works fine.
I'm using emacs 25.2 on RHEL 7

This is the error:
There was a problem with the editor '/path/emacsclient --socket-name=/tmp/emacs(large_number)/server'

I'm also using with-editor. I'm not sure if that is part of the problem or not.

**Comment by kyleam** [comment] 2017-07-13 19:40
Can you provide your versions for magit and with-editor?

My guess is that this is more of a with-editor issue than a magit one.
Either way, I think we're going to have a hard time reproducing it
because I'm sure that everyday many Magit users make commits while
having multiple frames open.

**Comment by eflanigan00** [comment] 2017-07-13 20:21
I understand. Both versions are fairly new, I've upgraded both within the last month.
I've seen this problem on and off for a while now.  It always occurs when I'm in the magit status window and type c-c

Is there some timeout thing in the code?
I'm running on a slow system and there is lots of network lag.

**Comment by kyleam** [comment] 2017-07-13 22:21
> Both versions are fairly new, I've upgraded both within the last month.

You can get Magit's version with `magit-version`.

For `with-editor`, the output of `with-editor-debug` should indicate
the version through with-editor.el's path, assuming you've installed
it from MELPA.  (Other information from its output might be useful as
well.)

> Is there some timeout thing in the code?
> I'm running on a slow system and there is lots of network lag.

So you're connecting to these repositories via tramp?  I don't think
with-editor has any timeouts itself.  Have you looked into
`tramp-connection-timeout`?

**Comment by eflanigan00** [comment] 2017-07-23 14:22
This is what I see. The first time I do magit-commit it hangs. I hit C-g. Then I run magit-commit a second time and I get the correct behavior. Something catches the editor on the first call.

**Comment by kyleam** [comment] 2017-07-23 14:52
> The first time I do magit-commit it hangs. I hit C-g.

If you don't hit C-g, do you get the error that you initially
reported?

> Then I run magit-commit a second time and I get the correct behavior.

Even with multiple frames open?

------------------------------------------------------------------------

Please respond to the requests/questions in my previous post.  That
information might not help, but, since we can't reproduce the issue,
we don't have much else to go on.

My best guess at this point is that you're hitting a tramp timeout and
that your issue is unrelated to having multiple frames open.

**Comment by eflanigan00** [comment] 2017-07-23 15:10
My apologies, I tried the following without any luck:

    (setq tramp-connection-timeout 180)
    (setq tramp-connection-min-time-diff 10)

If I don't hit C-g emacs just hangs there unresponsive.  I see the "Type C-c C-c to finish" message below but the screen never switches over to the COMMIT buffer.
I have waited more than 180 seconds and it doesn't ever come back.
When I hit $ it says there was a problem with the editor /.../emacsclient --socket-name=/tmp/emacs12345/server

I think you might be right about the timeout thing, but I know very little or nothing about tramp.
I'm working in a corporate RHEL 7 environment. I use putty->vncserver and VNC viewer to get a Linux desktop. On the RHEL system the files are in a group project area. I assume the underlying file structure is on a NAS of some sort but I don't know for sure.

**Comment by eflanigan00** [comment] 2017-07-23 15:17
1. So first attempt at magit commit emacs fails and hangs.
I then hit C-g.

2. I then execute magit-commit from the magit status screen again. The COMMIT_EDIT_MSG immediately pops up but the magit change information isn't on the other window. I get the same error "problem with the editor --socket".

3. The third time I hit magit-commit everything works perfectly. I get the COMMIT_EDITMSG in one window then the *magit-diff on the other window and I'm able to successfully commit. 

This happens even with multiple frames open.
I've been doing this for about a week and it is fairly consistent.
Sometimes I get lucky and I can commit the first time. More often that not it is the third try that always works without fail.

The more I see the behavior it seems like the original opening of the COMMIT_MSG buffer fails or is delayed.

Thank you for your comments and help!

**Comment by kyleam** [comment] 2017-07-23 16:11
> I think you might be right about the timeout thing, but I know very
> little or nothing about tramp. I'm working in a corporate RHEL 7
> environment. I use putty->vncserver and VNC viewer to get a Linux
> desktop.

Based on this information about your setup, I think my guess about a
tramp timeout is wrong.  If I understand correctly, it doesn't sound
like tramp should come into play.  The Emacs instance is running on
the virtual desktop, not your local machine, right?  So, from Emacs's
perspective, everything is local.

Can you provide the `magit-version` and `with-editor-debug` output?

**Comment by eflanigan00** [comment] 2017-07-23 16:12
I also have auto-revert question that sometimes pops up. I will try to disable auto revert and see.

**Comment by eflanigan00** [comment] 2017-07-23 16:20
Magit 20170702.1158, Git 2.9.4, Emacs 25.2.1, gnu/linux

    with-editor: /home/ed/.emacs.d/elpa/with-editor-20170702.742/with-editor.el
    emacs: /users/me/sys/src/emacs-25.2/src/emacs (25.2.1)
    system:
      system-type: gnu/linux
      system-configuration: x86_64-unknown-linux-gnu
      system-configuration-options:
    server:
      server-running-p: t
      server-process: #<process server>
      server-use-tcp: nil
      server-name: server
      server-socket-dir: /tmp/emacs1072254
        server
      server-auth-dir: ~/.emacs.d/server/
        server
    with-editor-emacsclient-executable:
    value:   /users/me/sys/src/emacs-25.2/lib-src/emacsclient (25.2)
     default: /users/me/sys/src/emacs-25.2/lib-src/emacsclient (25.2)
     funcall: /users/me/sys/src/emacs-25.2/lib-src/emacsclient (25.2)
    path: (long)
    exec-path: (long)
    with-editor-emacsclient-path:
        /projects/sys/src/git-2.9.4 (t)
        /projects/sys/src/Anaconda3-4.4.0/bin (t)
       /projects/sys/src/global-6.5.7/gtags/ (t)
       /users/me/sys/src/emacs-25.2/lib-src (t)
       /users/me/sys/src/emacs-25.2/lib-src/emacsclient (25.2)

**Comment by eflanigan00** [comment] 2017-07-23 16:23
I just saw there is a few changes in with-editor. I can also try to get the latest and see what happens.

**Comment by eflanigan00** [comment] 2017-07-23 16:25
And yes, as you describe emacs is local on the RHEL system.

**Comment by eflanigan00** [comment] 2017-07-26 22:40
Another observation: the commit seems more likely to be successful if I'm not in the magit status window and if I have a single window open.

**Comment by eflanigan00** [comment] 2017-07-30 14:49
error: There was a problem with the editor '/users/123456/irad_mbce_adps/sys/src/emacs-25.2/lib-src/emacsclient --socket-name=/tmp/emacs10123456/server'.
Please supply the message using either -m or -F option.

I wonder if it is unable to open the socket because it was previously opened by emacs earlier?

**Comment by stardiviner** [comment] 2017-08-06 00:16
I have similar error:
```
  0 git … apply --cached -p0 --ignore-space-change -
  1 git … commit --
Waiting for Emacs...
*ERROR*: Auth Error: "Token not found"
error: There was a problem with the editor '/usr/local/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```
As this issue suggest, I disabled `global-auto-revert-mode`, then the commit works fine.
But later, this error appears again, Then I disabled `magithub`, and restart Emacs again. The problem solved.

**Comment by tarsius** [comment] 2017-09-27 08:14
@stardiviner see #3154.

**Comment by tarsius** [comment] 2017-09-27 08:18
> Does the source code load the commit message first. Then split to the diff?

Yes.

Do you still have this issue?

**Comment by eflanigan00** [comment] 2017-09-28 03:12
> Do you still have this issue?

Let me update my package and try it over the next couple of days.

**Comment by eflanigan00** [comment] 2017-09-28 23:43
Unfortunately yes I still have the problem.

**Comment by eflanigan00** [comment] 2017-09-30 00:01
I did some testing with my init file. 
The problem occurs when I add mode-icons package.

I added this issue to mode-icons
https://github.com/ryuslash/mode-icons/issues/54

Maybe it is something about redrawing?

**Comment by kyleam** [comment] 2017-09-30 06:34
> The problem occurs when I add mode-icons package.

I loaded `mode-icons` and enabled `mode-icons-mode`.  Using
emacsclient and multiple frames, I made several commits but wasn't
able to trigger anything.

So you're only hitting this when you enable `mode-icons-mode`?  If you
run `emacs -Q` with just magit loaded (or `make emacs-Q` from the
magit repo), you're not able to trigger it?

**Comment by eflanigan00** [comment] 2017-09-30 17:42
I have a lengthy config file. When I comment out mode-icons everything runs perfectly fine.
But when I run with only magit, with-editor and mode-icons it also runs fine.
There is some interaction going on in my config.
I will try to figure out the combinations that cause this.

**Comment by tarsius** [comment] 2017-10-06 21:18
So this seems to be caused by some bad interaction in your configuration. I am closing this for now, but if you have some new information you need our help with (or found the cause or solution), then let us know.

**Closed by tarsius** 2017-10-06 21:18 UTC
Labels: needinfo
