### ISSUE TITLE
error when running magit-status

### ISSUE THREAD

**Issue by cognominal** [magit/magit#2502] opened 2016-01-19 03:35 UTC
Magit 20160117.805, Git 2.4.9 (Apple Git-60), Emacs 24.5.1

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil face magit-hash)
  #[0 "\305\306\307\"c\210\n\203\310\311\312\300\"\313\314#\315\261\210\310\300\313\316#\315\261\210\317\300!\2032\311\320\300\"\206-\321c\210\2029\310\322\313\323#c\210\324c\210\325\326!\210\327\301!\210\330\301\331H>\204S\332\333\334\335#\210\301\336H\337\"\210\301\331H>\204g\332\333\340\335#\210\301\211\341\342 I\262\343\305\344\301\331H>\204\200\332\333\345\335#\210\301\346H\"!\347!\205\215\211J\212\301\331H>\204\234\332\333\334\335#\210\301\336Hb\210`W\203\317\350`\335\"\206\257\351`\335\"\204\310\352`\335\301$\210\203\310\352`\353$\210\211b\266\202\241)\266\301\f=\203\334\354\301!\207\301\331H>\204\352\332\333\355\335#\210\301\356H\331H>\204\372\332\333\357\335#\210\301\331H>\204\332\333\355\335#\210\301\356H\211\360\301\331H>\204\332\333\355\335#\210\301\356H\331H>\204+\332\333\357\335#\210\301\331H>\2049\332\333\355\335#\210\301\356H\360H\301C\244I\207" ["cog/act-ast" [cl-struct-magit-section branch "cog/act-ast" #<marker at 57 in *magit: nqp> nil nil nil nil nil nil nil nil [cl-struct-magit-section branch "act-ast" #<marker at 1 in *magit: nqp> #<marker at 57 in *magit: nqp> nil nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: nqp> nil nil nil nil nil nil nil nil nil nil] nil] nil] magit-status-show-hashes-in-headers cl-struct-magit-section-tags magit-root-section format "%-10s" "Push: " propertize magit-rev-format "%h" face magit-hash 32 magit-branch-remote magit-rev-verify "%s" "" "is missing" font-lock-warning-face 10 run-hooks magit-insert-section-hook magit-insert-child-count set-marker-insertion-type 0 error "%s accessing a non-%s" magit-section-start magit-section 3 t magit-section-end 5 point-marker intern "magit-%s-section-map" magit-section-type 1 boundp next-single-property-change get-text-property put-text-property keymap magit-section-show magit-section-parent 12 magit-section-children 13] 9 "\n\n(fn)"]()
  funcall(#[0 "\305\306\307\"c\210\n\203\310\311\312\300\"\313\314#\315\261\210\310\300\313\316#\315\261\210\317\300!\2032\311\320\300\"\206-\321c\210\2029\310\322\313\323#c\210\324c\210\325\326!\210\327\301!\210\330\301\331H>\204S\332\333\334\335#\210\301\336H\337\"\210\301\331H>\204g\332\333\340\335#\210\301\211\341\342 I\262\343\305\344\301\331H>\204\200\332\333\345\335#\210\301\346H\"!\347!\205\215\211J\212\301\331H>\204\234\332\333\334\335#\210\301\336Hb\210`W\203\317\350`\335\"\206\257\351`\335\"\204\310\352`\335\301$\210\203\310\352`\353$\210\211b\266\202\241)\266\301\f=\203\334\354\301!\207\301\331H>\204\352\332\333\355\335#\210\301\356H\331H>\204\372\332\333\357\335#\210\301\331H>\204\332\333\355\335#\210\301\356H\211\360\301\331H>\204\332\333\355\335#\210\301\356H\331H>\204+\332\333\357\335#\210\301\331H>\2049\332\333\355\335#\210\301\356H\360H\301C\244I\207" ["cog/act-ast" [cl-struct-magit-section branch "cog/act-ast" #<marker at 57 in *magit: nqp> nil nil nil nil nil nil nil nil [cl-struct-magit-section branch "act-ast" #<marker at 1 in *magit: nqp> #<marker at 57 in *magit: nqp> nil nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: nqp> nil nil nil nil nil nil nil nil nil nil] nil] nil] magit-status-show-hashes-in-headers cl-struct-magit-section-tags magit-root-section format "%-10s" "Push: " propertize magit-rev-format "%h" face magit-hash 32 magit-branch-remote magit-rev-verify "%s" "" "is missing" font-lock-warning-face 10 run-hooks magit-insert-section-hook magit-insert-child-count set-marker-insertion-type 0 error "%s accessing a non-%s" magit-section-start magit-section 3 t magit-section-end 5 point-marker intern "magit-%s-section-map" magit-section-type 1 boundp next-single-property-change get-text-property put-text-property keymap magit-section-show magit-section-parent 12 magit-section-children 13] 9 "\n\n(fn)"])
  magit-insert-push-branch-header()
  funcall(magit-insert-push-branch-header)
  mapc(funcall (magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header))
  magit-insert-remaining-headers()
  run-hooks(magit-insert-section-hook)
  #[0 "\306\307\310\"c\210\f\203\311\301\312\313#\314\261\210\311\300\312\315#c\210\314\302\316\261\210\317\320!\210\321\303!\210\322\303\323H
>\2047\324\325\326\327#\210\303\330H\331\"\210\303\323H
>\204K\324\325\332\327#\210\303\211\333\334 I\262\335\306\336\303\323H
>\204d\324\325\337\327#\210\303\340H\"!\341!\205q\211J\212\303\323H
>\204\200\324\325\326\327#\210\303\330Hb\210`W\203\263\342`\327\"\206\223\343`\327\"\204\254\344`\327\303$\210\203\254\344`\345$\210\211b\266\202\205)\266\303+=\203\301\346\303!\207\303\323H
>\204\317\324\325\347\327#\210\303\350H\323H
>\204\337\324\325\351\327#\210\303\323H
>\204\355\324\325\347\327#\210\303\350H\211\352\303\323H
>\204\324\325\347\327#\210\303\350H\323H
>\204\324\325\351\327#\210\303\323H
>\204\324\325\347\327#\210\303\350H\352H\303C\244I\207" ["act-ast" "7c7ea34" "[js] Serialize MultiDimArray." [cl-struct-magit-section branch "act-ast" #<marker at 1 in *magit: nqp> #<marker at 57 in *magit: nqp> nil nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: nqp> nil nil nil nil nil nil nil nil nil nil] nil] magit-status-show-hashes-in-headers cl-struct-magit-section-tags format "%-10s" "Head: " propertize face magit-hash 32 magit-branch-local 10 run-hooks magit-insert-section-hook magit-insert-child-count set-marker-insertion-type 0 error "%s accessing a non-%s" magit-section-start magit-section 3 t magit-section-end 5 point-marker intern "magit-%s-section-map" magit-section-type 1 boundp next-single-property-change get-text-property put-text-property keymap magit-section-show magit-section-parent 12 magit-section-children 13 magit-root-section] 9 "\n\n(fn)"]()
  funcall(#[0 "\306\307\310\"c\210\f\203\311\301\312\313#\314\261\210\311\300\312\315#c\210\314\302\316\261\210\317\320!\210\321\303!\210\322\303\323H
>\2047\324\325\326\327#\210\303\330H\331\"\210\303\323H
>\204K\324\325\332\327#\210\303\211\333\334 I\262\335\306\336\303\323H
>\204d\324\325\337\327#\210\303\340H\"!\341!\205q\211J\212\303\323H
>\204\200\324\325\326\327#\210\303\330Hb\210`W\203\263\342`\327\"\206\223\343`\327\"\204\254\344`\327\303$\210\203\254\344`\345$\210\211b\266\202\205)\266\303+=\203\301\346\303!\207\303\323H
>\204\317\324\325\347\327#\210\303\350H\323H
>\204\337\324\325\351\327#\210\303\323H
>\204\355\324\325\347\327#\210\303\350H\211\352\303\323H
>\204\324\325\347\327#\210\303\350H\323H
>\204\324\325\351\327#\210\303\323H
>\204\324\325\347\327#\210\303\350H\352H\303C\244I\207" ["act-ast" "7c7ea34" "[js] Serialize MultiDimArray." [cl-struct-magit-section branch "act-ast" #<marker at 1 in *magit: nqp> #<marker at 57 in *magit: nqp> nil nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker at 1 in *magit: nqp> nil nil nil nil nil nil nil nil nil nil] nil] magit-status-show-hashes-in-headers cl-struct-magit-section-tags format "%-10s" "Head: " propertize face magit-hash 32 magit-branch-local 10 run-hooks magit-insert-section-hook magit-insert-child-count set-marker-insertion-type 0 error "%s accessing a non-%s" magit-section-start magit-section 3 t magit-section-end 5 point-marker intern "magit-%s-section-map" magit-section-type 1 boundp next-single-property-change get-text-property put-text-property keymap magit-section-show magit-section-parent 12 magit-section-children 13 magit-root-section] 9 "\n\n(fn)"])
  magit-insert-head-branch-header()
  magit-insert-headers((magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header))
  magit-insert-status-headers()
  run-hooks(magit-status-sections-hook)
  #[0 "\305\306	\"\203\307\301!\210\202\"\310\311!\210\312\313!\210\314\301\315N@!\307\302!\210)\307\316!\210\317\300!\210\320\300\321H>\2049\322\323\324\325#\210\300\326H\327\"\210\300\321H>\204M\322\323\330\325#\210\300\211\313\331 I\262\332\333\334\300\321H>\204f\322\323\335\325#\210\300\336H\"!\337!\205s\211J\212\300\321H>\204\202\322\323\324\325#\210\300\326Hb\210`W\203\265\340`\325\"\206\225\341`\325\"\204\256\342`\325\300$\210\203\256\342`\343$\210\211b\266\202\207)\266\300\f=\203\302\344\300!\207\300\321H>\204\320\322\323\345\325#\210\300\346H\321H>\204\340\322\323\347\325#\210\300\321H>\204\356\322\323\345\325#\210\300\346H\211\350\300\321H>\204\322\323\345\325#\210\300\346H\321H>\204\322\323\347\325#\210\300\321H>\204\322\323\345\325#\210\300\346H\350H\300C\244I\207" [[cl-struct-magit-section status nil #<marker at 1 in *magit: nqp> nil nil nil nil nil nil nil nil nil nil] magit-status-sections-hook magit-status-sections-hook-1 cl-struct-magit-section-tags magit-root-section -all-p functionp run-hooks message "`magit-status-sections-hook' contains entries that are no longer valid.\nUsing standard value instead.  Please re-configure" sit-for 5 eval standard-value magit-insert-section-hook magit-insert-child-count set-marker-insertion-type 0 error "%s accessing a non-%s" magit-section-start magit-section 3 t magit-section-end point-marker intern format "magit-%s-section-map" magit-section-type 1 boundp next-single-property-change get-text-property put-text-property keymap magit-section-show magit-section-parent 12 magit-section-children 13] 9 "\n\n(fn)"]()
  funcall(#[0 "\305\306	\"\203\307\301!\210\202\"\310\311!\210\312\313!\210\314\301\315N@!\307\302!\210)\307\316!\210\317\300!\210\320\300\321H>\2049\322\323\324\325#\210\300\326H\327\"\210\300\321H>\204M\322\323\330\325#\210\300\211\313\331 I\262\332\333\334\300\321H>\204f\322\323\335\325#\210\300\336H\"!\337!\205s\211J\212\300\321H>\204\202\322\323\324\325#\210\300\326Hb\210`W\203\265\340`\325\"\206\225\341`\325\"\204\256\342`\325\300$\210\203\256\342`\343$\210\211b\266\202\207)\266\300\f=\203\302\344\300!\207\300\321H>\204\320\322\323\345\325#\210\300\346H\321H>\204\340\322\323\347\325#\210\300\321H>\204\356\322\323\345\325#\210\300\346H\211\350\300\321H>\204\322\323\345\325#\210\300\346H\321H>\204\322\323\347\325#\210\300\321H>\204\322\323\345\325#\210\300\346H\350H\300C\244I\207" [[cl-struct-magit-section status nil #<marker at 1 in *magit: nqp> nil nil nil nil nil nil nil nil nil nil] magit-status-sections-hook magit-status-sections-hook-1 cl-struct-magit-section-tags magit-root-section -all-p functionp run-hooks message "`magit-status-sections-hook' contains entries that are no longer valid.\nUsing standard value instead.  Please re-configure" sit-for 5 eval standard-value magit-insert-section-hook magit-insert-child-count set-marker-insertion-type 0 error "%s accessing a non-%s" magit-section-start magit-section 3 t magit-section-end point-marker intern format "magit-%s-section-map" magit-section-type 1 boundp next-single-property-change get-text-property put-text-property keymap magit-section-show magit-section-parent 12 magit-section-children 13] 9 "\n\n(fn)"])
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup(magit-status-mode)
  magit-status-internal("/Users/cog/mine/nqp/")
  magit-status(nil)
  call-interactively(magit-status nil nil)
  command-execute(magit-status)

**Comment by kyleam** [comment] 2016-01-19 05:41
I'm not able to reproduce this on the same commit in the npq repo.
And looking at magit-insert-push-branch-header, which is throwing the
error, the nil case is checked, so I don't see how it is getting
through.

Perhaps something went wrong with the compilation.  I think it'd be
worth uninstalling and re-installing, making sure Magit isn't already
loaded.  You could also try stepping through
magit-insert-push-branch-header with C-u C-M-x.

**Comment by kyleam** [comment] 2016-01-19 05:43
[Also, note that you're getting the warning "magit-status-sections-hook contains entries that are no longer valid.  Using standard value instead. Please re-configure", although that shouldn't be related to this.]

**Comment by cognominal** [comment] 2016-01-19 07:20
For an unrelated reason, I had to restart emacs.
The problem disappeared.
I will post again if it appears again possibly with some relevant context
if I can find any.
thx for your support.

On Tuesday, January 19, 2016, Kyle Meyer <notifications@github.com> wrote:

> [Also, note that you're getting the warning "magit-status-sections-hook
> contains entries that are no longer valid. Using standard value instead.
> Please re-configure", although that shouldn't be related to this.]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/2502#issuecomment-172746936>.
>


-- 
cognominal stef

**Comment by kyleam** [comment] 2016-01-19 07:36
OK, closing.  Please re-open if it you see it again.

**Closed by kyleam** 2016-01-19 07:36 UTC

**Comment by cognominal** [comment] 2016-01-19 22:36
The problem is caused my ~/.git/config file which I did not paste so you had not all
the informations to solve the problem.
I am messing with remote branches and manually edit my ~/git/.config file
probably not in ways expected by magit and probably not in very standard ways.
I am not git expoert.
It seems not to cause any problem with regular git.
The first one works with magit. The second does not.
It seems that I can't arbitrarily rename remotes.
Thx for your support.

[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/cognominal/nqp
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master



[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "cog"]
	url = https://github.com/cognominal/nqp
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = cog
	merge = refs/heads/master

**Comment by kyleam** [comment] 2016-01-19 23:00
I tried your settings in the npq repo's ".git/config".  Even when
when the configuration lists a remote that doesn't exist, I can't
reproduce the error.

As I mentioned, I don't think a nil value should not be able to get
through to cause the error you're seeing, which makes me think
something went wrong with the installation/compilation.  Have you
tried to uninstall/re-install or step through
magit-insert-push-branch-header with C-u C-M-x?
