### ISSUE TITLE
Functions 'length=' and 'length>' void in Emacs 27

### ISSUE THREAD

**Issue by tenklo** [magit/magit#4730] opened 2022-07-21 13:28 UTC
Hi, thanks for the best git client!

### Short:
Commit `8842230bcafae287e56a8a4597aaa4539c3345d6` introduced the use of `length=` and `length>`, which are only available in Emacs 28(+).

### Long:
- expected behavior
   In Emacs 27 (and below for sure) be able to view git logs (and use multiple other functions)
- observed behavior
   Read
> Symbol’s function definition is void: length=

in the messages buffer

- steps to reproduce
   - use Emacs 27
   - magit-status
   - press `l l`

### Backtrace:

> Debugger entered--Lisp error: (void-function length=)
>   length=(nil 1)
>   magit-log-refresh-buffer()
>   apply(magit-log-refresh-buffer nil)
>   magit-refresh-buffer()
>   magit-setup-buffer-internal(magit-log-mode nil ((magit-buffer-revisions ("main")) (magit-buffer-log-args ("-n256" "--graph" "--decorate")) (magit-buffer-log-files nil)))
>   magit-log-setup-buffer(("main") ("-n256" "--graph" "--decorate") nil)
>   magit-log-current(("main") ("-n256" "--graph" "--decorate") nil)
>   funcall-interactively(magit-log-current ("main") ("-n256" "--graph" "--decorate") nil)
>   call-interactively(magit-log-current nil nil)
>   command-execute(magit-log-current)

### Versions:
`Magit v3.3.0-403-g80cdadb0, Git 2.34.3, Emacs 27.2, gnu/linux`

I get wanting to use the new and better functions, but in this case it is hurting backwards compatability :(

**Comment by kyleam** [comment] 2022-07-21 22:44
Magit depends on `compat`, and `compat` provides those functions.  Perhaps this is a setup/installation issue?  Do you have `compat` installed?

**Comment by paddy-hack** [comment] 2022-07-25 06:59
Just ran into the same myself.  
```
Magit v3.3.0-408-g765069ad, Git 2.35.1, Emacs 27.1, gnu/linux
```
Reverting `compat` to `cc1924fd8b3f9b75b26bf93f084ea938c06f9615` fixes it for me.  
Using `664be609c968a8ffac14a4d62560e87f692e7d68` introduces the breakage.

I have no clue how all of this combines to work but I have a hunch that removing
``` Makefile
compat.el:     compat-macs.el
```
from `compat`'s `Makefile` has something to do with this.

**Comment by paddy-hack** [comment] 2022-07-25 23:53
FTR, the SHAs above are from https://github.com/emacs-straight/compat.git.

**Comment by vallon** [comment] 2022-07-28 13:04
Experiencing the same problem in emacs 26.1.  Using emacs-straight/compat.git.  compat sha 27728fa with magit sha 765069ad gives "Sym func def is void: length=", but checkout out compat sha 664be60 and purging straight build/compat fixes the error.

The emacs-straight/compat git repo is a filesystem mirror of the compat dev repo https://sr.ht/~pkal/compat/, but not a git mirror, so the shas don't line up.

**Comment by tarsius** [comment] 2022-07-28 13:56
It would be best to report this upstream at https://lists.sr.ht/~pkal/compat-devel. I believe this is a transitional issue, i.e., if one succeed in re-compiling the latest version of `compat` and after that all packages that depend on it, then the issue would be no more.

Somewhere I saw someone mention that they used `straight`'s "recompile everything" command and that that did not fix the issue for them. (But I cannot find that comment anymore.) I can see two potential causes for that. (1) That command does not actually succeed in recompiling everything, *while ensuring that no old code, that is already loaded when the recompilation happens, leaks into the new byte-code or native-code*, or (2) something pins `compat` to a faulty version.

*I am on a prolonged mental health break, else I would have responded to this earlier. But since so far apparently no body bothered asking `compat`'s author for help, I'll do that now.*

@phikal Could you please have a look at this and work with the affected users to figure out why things stay broken for them.

@raxod502 Are you sure `straight`'s recompilation command does not leak old loaded code? E.g., you might ensure that the byte-code is sound, while failing to wipe `eln` files.

@hlissner You are already aware of this issue, but I am mentioning you in case `doom` pins `compat` to a faulty commit and you need to do something about that.

@minad @astoff @seagle0128 You also use `compat` for one of your packages. Mentioning you in case you are not aware of the issue, or are aware but are struggling with this mystery issue on your own, or would be interested in helping with this issue and making `compat` updates less fragile.

In hindsight it might have been better not to go all in on `compat` so quickly. On the other hand this is a chicken&egg problem; had I not started to use `compat` in `magit`, fewer users would be affected by these issues and it would have taken longer to address them. Wanting to use `compat` myself was only part of what caused me to do it early on; I also wanted to make it easier for other package maintainers to justify doing the same.

Here are some off the issues I have seen about this:
- https://github.com/doomemacs/doomemacs/issues/6583
- https://github.com/doomemacs/doomemacs/issues/6591

**Comment by minad** [comment] 2022-07-28 14:17
@tarsius

> I believe this is a transitional issue, i.e., if one succeed in re-compiling the latest version of compat and after that all packages that depend on it, then the issue would be no more.

As far as I know recompile everything should solve all issues. This may require deleting all packages and reinstalling them if the package manager is not doing the right thing by default. 
Reporting compat-related upstream is the way to go, such that @phikal has a chance to improve the robustness of updates.

> In hindsight it might have been better not to go all in on compat so quickly. On the other hand this is a chicken&egg problem; had I not started to use compat in magit, fewer users would be affected by these issues and it would have taken longer to address them. Wanting to use compat myself was only part of what caused me to do it early on; I also wanted to make it easier for other package maintainers to justify doing the same.

I think you did alright with requiring Compat early on. I have only one minor criticism regarding your approach - you required Compat for all your packages even if no compatibility code was needed at all. See for example the commit https://github.com/tarsius/hl-todo/commit/317cff80394ec2dc25fc2c7aae296369c3e9638b. I disagree with this sledgehammer method. However I understand that you did this to reduce the maintenance efforts in the future.

Regarding the robustness of Compat - I advised @phikal early on to keep things simple and to be aware of the impact of his package. While Philip's work seems to be quite thorough and well-thought out, it seems that even greater care is necessary in the future. There is still some uncertainty about the future development of Compat, e.g., using advices to override certain functions. I can only repeat the comments I've made earlier on the Compat mailing list. The package should be kept simple and intrusive approaches are better avoided in Compat. This means no advices, no unexpected overrides, no unexpected autoloads, etc.

Finally I have to make comment about the harassment-like behavior of some users and the way issues are reported. For my projects reports like https://github.com/magit/magit/issues/4698 would be unacceptable and I would block the responsible user from commenting again.

**Comment by minad** [comment] 2022-07-28 15:53
@phikal You should give up on the belief that Emacs package managers respect stable versions. ;) Maybe with https://github.com/melpa/melpa/issues/8135 the situation will get better since then one could potentially abolish MELPA(-unstable) in favor of MELPA-devel and more people would rely on stable versions.

I wonder how [fe923d8e](https://git.sr.ht/~pkal/compat/commit/fe923d8ef905dfdc1ca2a78147f5a7d28426d093) can cause this issue. What is the issue with the version check?

**Comment by seagle0128** [comment] 2022-07-28 16:11
Interesting! I am keeping on my eyes. So far no such issue is reported to [doom-modeline](https://github.com/seagle0128/doom-modeline). Thanks for letting me know!

**Comment by minad** [comment] 2022-07-28 16:38
> That might help out with MELPA, but officially I am only publishing new
releases on GNU ELPA.  If a package manager insinuates that it handles
and supports ELPA, then I still think it is reasonable that it should
respect the way ELPA works.  The fact that commits are mangled is
already bad enough for reproducing bugs, but if that is ready done, then
the mirror should at least merge version bumps into single commits.  But
I guess that is an issue for another discussion...

I agree only partially here. The Straight ELPA mirror is obviously a bad idea, since it mangles the commits. I also don't see a reason why Straight is not pulling directly from the ELPA repository - maybe to reduce the load on the ELPA server and to profit from the better availability of the github mirror? However Straight is supposed to pull the development version, so that part is functioning correctly. FWIW I am thankful for the few straight users of my ELPA-only packages Vertico and Corfu since they report bugs earlier than the package.el users.

> The obvious mistake is that < is not a symmetric relation, and that
check only loaded compat-NM.el if NM was less than the current emacs
version.  We want the opposite. 

Uh, I see. The condition was reversed. Maybe test a change before pushing it? ;) For packages released on MELPA you will get bug reports almost immediately if you made a mistake. Your Compat package is affected in effectively the same way thanks to Straight.

**Comment by paddy-hack** [comment] 2022-07-31 23:59
FTR, I just ran `M-x straight-pull-all` and the issue has been fixed for me.  
I'm now using compat@2a9cf8b7bdb5bf2cf4ee73b2c586ec9d736cb4f6 (SHA from https://github.com/emacs-straight/compat.git).

**Comment by raxod502** [comment] 2022-09-03 17:45
Sorry for the delay here, just wanted to chime in since a couple questions were asked of me:

> @raxod502 Are you sure straight's recompilation command does not leak old loaded code? E.g., you might ensure that the byte-code is sound, while failing to wipe eln files.

No, I'm not confident of that. Historically, `straight.el` did not even try to achieve reproducible builds here, since it just did the default thing, which is to byte-compile in the same Emacs process, which by default is affected by whatever else you have loaded, including previous versions of the same package. https://github.com/radian-software/straight.el/pull/657 by @progfolio largely solved this problem, but it's still possible that there is an edge case, especially around native compilation as you mentioned.

> the straight package manager appears to be tracking the git HEAD instead of using the latest commit that bumped the version number (which I would consider a bug)

This is actually a compromise to practicality that I made early on in the design of `straight.el`, since the dominant trend in the ecosystem at the time was to run the development versions of all packages. For example, MELPA Stable was available, but even the MELPA maintainers discouraged its use. There is a long-standing open issue about allowing users to opt in to running only tagged releases of their packages and dependencies, but neither I nor anybody else ever picked it up: https://github.com/radian-software/straight.el/issues/31.

> I also don't see a reason why Straight is not pulling directly from the ELPA repository - maybe to reduce the load on the ELPA server and to profit from the better availability of the github mirror?

The reason for this is explained here: https://github.com/radian-software/gnu-elpa-mirror#why

In summary:
* cloning GNU ELPA takes a long time and the server is often down
* you also have to clone the Emacs source repo as well, which takes even longer even if you use the GitHub mirror
* the GNU ELPA build scripts, at the time I created GNU ELPA Mirror, had outstanding bugs that needed to be patched before they would run successfully, requiring extensive local hacks to actually run the code properly
* the way that certain packages were set up in the GNU ELPA repository was very odd and hard to deal with locally, e.g. different unrelated packages would be stored in the same repository but on different branches

By creating a mirror, all of those problems were solved and it was possible to use all GNU ELPA packages out of the box, at the cost of losing accurate commit history. This was so successful that eventually the mirror was made the default, but it is still possible (though not recommended) to use upstream: `(setq straight-recipes-gnu-elpa-use-mirror nil)`.

**Comment by tarsius** [comment] 2022-09-13 08:54
Thanks for the feedback!

Closing since no user reported this issue in a while--it seems it really was a transitional issue. We might still have to instruct users to to do the reinstallation dance once in a while.

Speaking of which, @raxod502 @progfolio, I think it would be a good idea to add a "recompile everything cleanly" command to straight. Borg offers `make clean build` for that, and it only takes a few minutes even with a hundred packages, which is better than multiple people investigating half an hour here and there, investigating "impossible" issues.

**Closed by tarsius** 2022-09-13 08:54 UTC
Labels: invalid

**Comment by raxod502** [comment] 2022-09-14 01:00
Yeah, absolutely, I agree that such a feature is needed.

As a workaround until there is an explicit command added, one can `rm -rf ~/.emacs.d/straight/build` and restart Emacs. Everything will be built fully from scratch.
