### ISSUE TITLE
Creating new branches is difficult

### ISSUE THREAD

**Issue by jacksonrayhamilton** [magit/magit#2009] opened 2015-07-08 02:42 UTC
Since updating to `2.1.0`, I find creating new branches to be less convenient.

Firstly, when I'm creating branches, I'm almost always branching off HEAD, but now I have to hit RET to select the current branch. I imagine this change was to further generalize the command, but for me it's just annoying. I would appreciate an option to "assume that the current branch is the one to branch from;" or take that one step further and have an option that "assumes the current branch" in other cases too, e.g. setting upstream.

Also, when I create a new branch, I expect the upstream of `new-branch-name` to be `origin/new-branch-name`. That's what happens when I use `git checkout -b new-branch-name`. But since the update, the upstream is left at the previous branch.

This wouldn't be much of a deal, since the default branch to push to is still `origin/new-branch-name`. But after pushing, `magit-status` still reports the files as unpushed, because my upstream is e.g. `master`. And if I do want to set upstream manually, I can't do it until I've pushed at least once. When doing `magit-branch-set-upstream`, if I try to set upstream to `origin/new-branch-name` before having pushed once, I get an error that the branch doesn't exist. (Not that I want to go through the rigamarole of setting upstream; I would prefer to just have it set to what I expect it to be, automatically.)

**Comment by tee3** [comment] 2015-07-08 03:04
When you push your branch, you can choose to set upstream via `P -u P origin`.  I guess it is a couple more characters to type, but it is doable without the "rigamarole".  Does git do this by default?  I didn't think so, I believe you have to say `git push -u origin new-branch-name` to set the upstream when you first push a branch.

**Comment by jacksonrayhamilton** [comment] 2015-07-08 03:21
Actually I was wrong, `git checkout -b` doesn't seem to set the upstream.

@tee3, if I use the `-u` flag when pushing a branch created with `magit-branch-and-checkout`, it seems to be setting the upstream to `origin` (thus accomplishing nothing). Though the `-u` flag does do what I expect (which is to set upstream to `origin/my-branch-name`) for branches manually created with `git checkout -b`.

**Comment by tee3** [comment] 2015-07-08 03:56
@jacksonrayhamilton I'm not a maintainer, but I thought I might help answer the question.  I just tried what I described and it did what I expected.  Can you give the process below a try and see if it works for you?  The only question mark in my mind is how pushing to origin works since I have `ido` running and it may be completing something I'm not aware of, but I doubt it.  If it doesn't work how you expect. what would you expect?

I created a new branch from `master` via `b B master [RET] new-branch`, which will create a branch called `new-branch` with no upstream set.  I then made a commit to `new-branch` and pushed it to `origin` setting the upstream via `P -u P origin` (which defaults the name of the upstream branch to `origin/new-branch`).  I then committed another change to `new-branch` and did a push without trying to set upstream and the change was pushed properly to `origin/new-branch`.  Checking the upstream of `new-branch` also shows that upstream is `origin/new-branch`.

Hope it helps!

**Comment by npostavs** [comment] 2015-07-08 04:59
> Firstly, when I'm creating branches, I'm almost always branching off HEAD, but now I have to hit RET to select the current branch. I imagine this change was to further generalize the command, but for me it's just annoying.

Yeah, I find this a bit annoying too; sometimes I start typing the intended new branch name at the starting point prompt and then I end up hitting`C-g` when magit asks for the new branch name.


> The only question mark in my mind is how pushing to origin works since I have ido running and it may be completing something I'm not aware of ...
> I then made a commit to new-branch and pushed it to origin setting the upstream via P -u P origin (which defaults the name of the upstream branch to origin/new-branch).

If you're not using `ido`, you would have to type `P -u P origin/new-branch RET`, but there is completion so depending other existing names it might be more like `P -u P o/ne TAB RET`. Perhaps this can be improved by setting a default, similar to #1994.

Also see http://emacs.stackexchange.com/a/13784/5296 for the `advice` I use to press `-u` automatically.

**Comment by npostavs** [comment] 2015-07-08 12:09
> Perhaps this can be improved by setting a default

Thinking about something like this:

```elisp
(defun magit-push-current (branch remote &optional remote-branch args)
   "Push the current branch to its upstream branch.
 If the upstream isn't set, then read the remote branch."
   (interactive
   (let* ((branch (or (magit-get-current-branch)
                      (magit-read-local-branch "Push")))
          (remote (or (and (magit-branch-p branch)
                           (magit-get-remote-branch branch))
                      (magit-read-remote-branch (format "Push %s to" branch)
                                                nil (--when-let (magit-list-remotes)
                                                      (cons (car it) branch))
                                                branch))))
     (list branch (car remote) (cdr remote) (magit-push-arguments))))
   (magit-push branch remote remote-branch args))
```

This bypasses `magit-push-read-args`, which I'm finding difficult to follow/modify due to its use of 3 flags. I'm considering how to remove the flags without duplicating too much code.

**Comment by Silex** [comment] 2015-07-08 12:16
Maybe the binding `b C` could be used to create a new branch starting from HEAD and thus only asking fort the new branch name?

Anyway, imho the new branch/pull popups are superior to the old ones. Especially stuffs like "push other/elsewhere".

**Comment by tarsius** [comment] 2015-07-08 12:48
> Yeah, I find this a bit annoying too; sometimes I start typing the intended new branch name at the starting point prompt and then I end up hitting `C-g` when magit asks for the new branch name.

I have to admit that still happens to me to occasionally. Switching the order again, is something that should be considered in the long run. For now it might be enough to verify that the input can be resolved before accepting it when the user presses `RET`.

I would like to limit improvements to such minor tweaks for the time being. I intend to make big changes eventually (see #1485). But there is too much going on right now, for me to tackle this also. I especially want to avoid new commands or other features that are at risk of being replaced in a not so far away future. What we have now is better than what we had before. But that doesn't keep users from noticing those areas where some sub-feature works less well now, or at least differently. So I would like to avoid users getting used to features whose future is unclear.

But that shouldn't keep you from making suggestions. I just have no intention of merging/implementing them as they are coming in.

**Comment by jacksonrayhamilton** [comment] 2015-07-08 18:25
@tee3, indeed, I tried pushing a new branch with `-u` again and the upstream was correctly set to `origin/my-branch-name`. IDK what went wrong the first time, maybe I ran into a bug, or maybe I was just doing something wrong.

> Yeah, I find this a bit annoying too; sometimes I start typing the intended new branch name at the starting point prompt and then I end up hitting `C-g` when magit asks for the new branch name.

This has also happened to me, but I know it's because I have to retrain my muscles to a new sequence of commands. I am okay with retraining myself if it's for the better. In this case, the generalization of the command made it more complicated without being any more useful (to me).

**Comment by tarsius** [comment] 2015-07-08 19:14
The advantage of reading the starting point first and only then the new branch name, is that once you have entered e.g. "origin/some-feature" (with completion), you can just press `RET` to create a local branch named "some-feature". If we do it the other way around you have to type out "some-feature" character by character, and then you still have to select "origin/some-feature".

Sure there are compromises but they are more work to implement than just using this order.

**Comment by npostavs** [comment] 2015-07-08 20:22
> Maybe the binding b C could be used to create a new branch starting from HEAD and thus only asking for the new branch name?

```elisp
(defun magit-branch-HEAD-and-checkout (branch &optional args)
  "Create and checkout BRANCH at branch or revision START-POINT.
\n(git checkout [ARGS] -b BRANCH HEAD)."
  (interactive (list (magit-read-string "Branch name") (magit-branch-arguments)))
  (setq args (delete "--track" args))
  (magit-branch-and-checkout branch "HEAD" args))

(magit-define-popup-action 'magit-branch-popup ?C "Create @HEAD & checkout"
  'magit-branch-HEAD-and-checkout ?c)
```

> once you have entered e.g. "origin/some-feature" (with completion), you can just press RET on the second prompt to create a local branch named "some-feature".

I guess this makes sense, though it feels weird to set a non-existent branch as the upstream.

**Comment by tarsius** [comment] 2015-07-08 20:55
> I guess this makes sense, though it feels weird to set a non-existent branch as the upstream.

No, one selects an existing branch to be used as the upstream of a yet to be named and created branch. The order helps with the naming part (which is why I picked that order).

> it feels weird to set a non-existent branch as the upstream

Some users have asked for exactly that. And I think it makes sense if one is primarily concerned with pushing being as easy as possible. `some-feature` would normally be pushed to `my-fork/some-feature`. Personally I usually use `master` as upstream and push, with the help of ido, using `p e m s RET` (I might, or might not, have to type more than just `m s`, depending on what other remotes and branches exist).

When the upstream is `master` (or `origin/master`) then "Unpushed/Unpulled commits", in my opinion, displays more interesting information (the commits on the feature branch and the commits that happened since work on the feature began). But one cannot easily see whether one has pushed all commits yet. Then again, I usually know that - else I use `l b`.

With a "publish" branch this will be easier, as "Unpublished/??? commits" can be displayed *in addition* to the "~~Unpushed~~Unmerged/Unpulled commits".

**Comment by jacksonrayhamilton** [comment] 2015-07-08 22:14
> The advantage of reading the starting point first and only then the new branch name, is that once you have entered e.g. "origin/some-feature" (with completion), you can just press `RET` on the second prompt to create a local branch named "some-feature".

I don't understand, when I do `b B` and type `origin/some-feature`, firstly it's not possible to complete the name of a branch that doesn't exist yet. But even if I type that out, and then type `some-feature` for the name of the new branch, the following error appears in `*magit-process*`:

```
128 git … checkout -b some-feature origin/some-feature
fatal: Cannot update paths and switch to branch 'some-feature' at the same time.
Did you intend to checkout 'origin/some-feature' which can not be resolved as commit?
```

And I typically am switching to the new branches I create. But even if use plain old `b c` to create a new branch with the name `origin/some-feature`, I get this error:

```
128 git … branch some-feature origin/some-feature
fatal: Not a valid object name: 'origin/some-feature'.
```

Anyway, it's not the ordering that irks me. It's the fact that I need to type the starting branch at any point. I guess it took some muscle memory discombobulation for me to notice it.

@npostavs's feature does exactly what I want, so I guess I'll throw that into the init file for the time being. Unfortunately I will still have to choose the starting branch in other places, so a more general solution would be preferred.

**Comment by npostavs** [comment] 2015-07-09 04:10
> Some users have asked for exactly that. And I think it makes sense if one is primarily concerned with pushing being as easy as possible.

Right, this does sort of make sense, but looking at this again I don't understand your point about the order helping at all.

> No, one selects an existing branch to be used as the upstream of a yet to be named and created branch. The order helps with the naming part (which is why I picked that order).

I'm always branching off `master`, so entering `origin/master` first doesn't help me with entering `some-feature` afterwards. 

> Personally I usually use `master` as upstream

And it seems like the same applies to you??

**Comment by tarsius** [comment] 2015-07-09 09:43
Okay people. I am going to do something about this. Maybe not in `2.2.0`, which I hope to release within a week, but in `2.2.1` or `2.3.0`, which should follow soon too.

**Comment by bastianbeischer** [comment] 2015-07-10 09:48
There's also another thing which I found disturbing:

The --track option is on by default.

While this makes sense when creating a branch which starts with a remote tracking branches I don't think it makes sense to tracker other local branches (maybe its just me).

That's why I disabled the '--track' option. This actually makes branching behave exactly like I want:

When branching from a remote tracking branch, upstream is set, otherwise not.

But at the same time this is also confusing, because disabling --track is actually different from --no-track...

**Comment by tarsius** [comment] 2015-07-10 09:56
> I don't think it makes sense to tracker other local branches (maybe its just me).

I usually track the local `master` and others have mentioned that they do that too, I think.

I think it makes sense to default to "if the starting point is a branch, then track that".

> But at the same time this is also confusing, because disabling --track is actually different from --no-track

Which will be addressed in a far away future when I replace `magit-popup.el` with the yet to be written `transient.el`. :-)

**Comment by tarsius** [comment] 2015-07-10 22:03
I have added two new push command `magit-push-quickly` and `magit-push-implicitly`.

**Comment by tarsius** [comment] 2015-07-13 13:56
In refs buffers `RET` now checks out the branch at point again. You can also use `C-u RET` to just "focus" on the branch at point. The cherry commits that are shown when expanding a branch are then relative to that focused branch instead of `HEAD`.

**Comment by seh** [comment] 2015-07-14 00:19
I just tried it, but version 20150713.726 from MELPA doesn't have the change yet. However, per the patch, it _looks_ like it will do just what I expected it to do.
Thank you for listening to feedback and adjusting it to suit.

**Comment by tarsius** [comment] 2015-07-15 21:18
I have changed the default of `magit-branch-read-upstream-first` to `t`. See d4992d0e5709d70ae72ebc2646e8267805fde2d4.

**Comment by ryankask** [comment] 2015-07-16 16:55
I've been reading through this discussion but I'm not sure if this has been addressed.

Is it possible, when creating a new branch with `b B`, to not track the branch you choose to branch off of by default? (i.e. same behaviour when you do `git checkout -b mybranch`)

Thanks for your work on this amazing project.

**Comment by jacksonrayhamilton** [comment] 2015-07-16 17:11
@ryankask: `--track` is enabled by default, you can turn it off by default by adding the following to your init file:

```lisp
(setq magit-branch-arguments (remove "--track" magit-branch-arguments))
```

**Comment by ryankask** [comment] 2015-07-17 08:02
@jacksonrayhamilton Thanks!

**Comment by dangirsh** [comment] 2015-07-23 23:53
I'm using version 20150722.2133 from MELPA. 

My workflow often requires me to create a local branch that tracks some remote branch (generated by a bugtracker), then push only to that branch. The v1 behaviour was perfect for this: find the remote branch in the ref list, hit RET, accept some default prompts, done. Even with the changes from this ticket, I still can't achieve this as easily in v2: hitting RET on a remote branch leaves me in a detached state, which is useless to me.

But I'm not whining... I just wanted to post my solution here in case it helps someone else (with as stubborn muscle memory as me ;) )

```
(defun my-magit-branch-and-checkout-dwim ()
  (interactive)
  (let* ((ref (magit-section-value (magit-current-section)))
         (local-branch-name (mapconcat #'identity (cdr (split-string ref "/")) "/")))
    (magit-branch-and-checkout local-branch-name ref)
    (setcar magit-refresh-args local-branch-name)
    (magit-run-git "checkout" local-branch-name)
    (magit-refresh)))

(define-key magit-refs-mode-map (kbd "<return>") 'my-magit-branch-and-checkout-dwim)
```

**Comment by tarsius** [comment] 2015-07-24 00:32
@dangirsh see #2101.

**Comment by jacksonrayhamilton** [comment] 2015-08-01 18:41
After reading #2079 and re-reading your [earlier comment](https://github.com/magit/magit/issues/2009#issuecomment-119700102) I think some clarification is in order:

I understand what you mean now. If I pull and get new branches from remote, I can create local copies of them with `b c` or `b C`.

I'm not used to creating local versions of remote branches that way; when I used the git cli, I would just do `git checkout some-newly-pulled-feature` and it would automatically create and switch to a new branch based off `origin/some-newly-pulled-feature` with the name `some-newly-pulled-feature`.

With this realization, I support having the base branch come first. I don't even think an order-switching option is needed. I had gotten so used to typing `RET` twice to finish creating new branches that I did not even realize I was being *asked* which branch to base off of. The behavior I wanted was to *not* for the order to be switched back, but for an option to be added such that I didn't have to choose a base branch at all. Like with `git checkout` on newly-pulled remote branches and `git branch brach-namegit checkout -b` for creating new branches.

**Comment by jacksonrayhamilton** [comment] 2015-08-01 18:53
After re-reading your [earlier comment](https://github.com/magit/magit/issues/2009#issuecomment-119700102), #2079 and the [2.2.0 changelog](https://github.com/magit/magit/commit/6089956948922ccb4530ab0a5b8f67a11c721b4a#diff-ca223320437ba4af3eb1694be48af324R99), I think some clarification is in order:

I understand what you mean now. If I pull and get new branches from remote, I can create local copies of them with `b c` or `b C`.

I'm not used to creating local versions of remote branches that way; when I used the git cli, I would just do `git checkout newly-pulled-feature` and it would automatically create and switch to a new branch based off `origin/newly-pulled-feature` with the name `newly-pulled-feature`.

With this realization, I support having the base branch come first. I don't even think an order-switching option is needed. I had gotten so used to typing `RET` twice to finish creating new branches that I did not even realize I was being *asked* for a base branch.

The behavior I wanted was to *not* for the order to be switched back, but for an option to be added such that I didn't have to choose a base branch at all. (Like the behavior of `git checkout newly-pulled-branch-name`, or `git branch brach-name` or `git checkout -b branch-name` for creating new branches.)

I think this issue has ballooned and is laden with too much confusion, so I could create a new issue for the actual feature request.

**Comment by glasser** [comment] 2015-08-15 16:53
In my project, we all push our feature branches to the main repo.

So I am frequently trying to make a new local branch `glasser/feature` which branches off of `master` but whose upstream is `origin/glasser/feature`.

So I'd like to just be able to do `b B`, select `master`, type `glasser/feature`.  But that gives me an upstream of `master`, which is wrong. I'd rather it give me an upstream of `origin/glasser/feature`, or if that doesn't make sense because it doesn't exist, no upstream and I'm happy to hit `-u` when I first push.

Now, you've said above that I can fix that by removing `--track` from `magit-branch-arguments`.  BUT!  This leads to a different problem.  Let's say I want to check out some *existing* branch from the repo, where I don't have a local branch yet.  `b b` and selecting `origin/some-branch` will create a `some-branch` for me... but if I removed `--track` it won't be a tracking branch!

I think what I'd like is the ability to specify (globally or per repo) that I intend to treat this repo as a "matching" repo, kind of like the `push.default`'s matching setting.  So that when `magit` creates a new local branch, it tracks it if and only if the branch name matches the branch that it would be tracking.  So in the first case (make `glasser/feature` (which I'll note is a branch name, not a remote and branch name) from `master`) it would not track, and in the second case (make `some-branch` from `origin/some-branch`) it would track.

Yes, I know there are plenty of good reasons to make branches that track branches with non-matching names, but there are also lots of workflows that never want to do that.

**Comment by glasser** [comment] 2015-08-19 10:42
... second time accidentally pushing my unreviewed feature branch to origin/master by accident :(  Yeah, I'm going to stop using magit's branch creation commands.

**Comment by tarsius** [comment] 2015-08-19 11:00
> ... second time accidentally pushing my unreviewed feature branch to origin/master by accident :( Yeah, I'm going to stop using magit's branch creation commands.

@glasser The problem is not the commands that create branches. They might set an upstream that is different from what you want and it is inconvenient that you have to change the upstream. But branch-creation behaving differently from what you would want is not what is causing you to push to `master` (at least not the second time).

The upstream branch is displayed very prominently in the status buffer and, as you know, the upstream branch is what `PP` pushes to. You had time to "fix" the upstream or realize that `PP` would not be doing what you want.

Anyway:

> I think what I'd like is the ability to specify (globally or per repo) that I intend to treat this repo as a "matching" repo, kind of like the `push.default`'s matching setting.

Use `Pi`:

```lisp
(defun magit-push-implicitly (&optional args)
  "Push without explicitly specifing what to push.
This runs `git push -v'.  What is being pushed depends on various
Git variables as described in the `git-push(1)' and `git-config(1)'
manpages."
  (interactive (list (magit-push-arguments)))
  (magit-run-git-async-no-revert "push" "-v" args))
```

If expect that you will keep on pressing `PP` out of habit, then change the bindings as described [here](http://magit.vc/manual/magit-popup/Customizing-existing-popups.html).

Ps: I will start working on the publish remote thingy very soon.

**Comment by glasser** [comment] 2015-08-19 18:16
Sure, I can start using push-implicitly, but all that does is prevent my misconfiguration from hurting me, not prevent my misconfiguration from happening in the first place.

But I think there are a ton of people in the world who are used to doing these two operations at the command-line:

```
$ git checkout -b my-new-feature master
$ git checkout somebody-elses-feature-that-hasnt-been-checked-out-before
```

and the fact that there's no configuration for magit that allows you to run both of these common operations conveniently with the same semantics as git is surprising.

**Comment by omouse** [comment] 2015-10-21 16:47
At least there should be a gigantic warning on the magit homepage about this change. I've used magit for a while and have been used to the fact that pushing will automatically track to the new branch rather than to the branch that it was based off of.

I agree with @glasser that those two commands are the most commonly used on the command-line for creating branches. This change in magit is asking us to un-learn something we've used for years. I don't mind changing my habits but I don't see what this change has bought us.

**Comment by tarsius** [comment] 2015-10-21 18:54
[Jonas is getting upset](https://www.youtube.com/watch?feature=player_embedded&v=A66ierfTCUQ#t=573).

In a few days I will release `v2.3.0`. The slogan for the next release after that is "Deal with the fact that everyone has a different opinion on how branching and pushing should work." (see #2180). I have just written a longish reply, but since I was still nowhere near done after a thousand words, I discarded it and decided to instead work toward wrapping up `v2.3.0`, so that I would sooner be able to tackle `v2.4.0` which will address this issue. Still the above link to a video probably doesn't cut it, so here we go again:

I have heard you guys. Really I have. How many more times do I have to repeat that until you believe me? You don't like how the pushing works now. But repeating this over and over again, all while for the most part ignoring what I have said already, won't cause this to be addressed sooner - it will cause it to be addressed later (due to emotional stress).

Q: Fine but why don't you make some intermediate changes to keep me from shooting myself in the food?

The issue at hand is that users are confronted with an intermediate approach and are not satisfied with it. I should have gone all the way but haven't. Adding yet another intermediate approach is not going to help - if anything it's going to make matters worse.

I already have done that. I have changed <kbd>P P</kbd> to require that the user confirms the push target. As a result every user who agrees with me on what this command ought to be doing given the current implementation (push without requiring conformation) has to customize the option. Some of the users whom I forced to this for your benefit, got quite upset about that, causing them to write things like "Shut the fuck up Magit" in their init file before setting the option, and tweeting about what a stupid thing I have done.

Any user who changes the value of `magit-push-always-verify` without reading the documentation and then is surprised that <kbd>P P</kbd> doesn't do what he expected, has to blame himself and nobody else for that. I refuse to accept any blame here. Forcing everyone to opt-in to the intended behavior is as far as I could go in the short run. If you read "Please read this carefully or be prepared to be surprised" and then do not read it and end up being surprised, then that's your mistake.

Magit has many users, with mutually exclusive ideas not only on what is the *best* way to implement a certain feature but also on "this obviously is the one and only correct way of doing it, and it is wrong of you to also cater for users who disagree". In such a situation I have three options (a) do what users A tell me I should be doing, and get complains from users B, (b) do what users B tell me I should be doing, and get complains form users A, or (c) find a compromise and get complains from both users A and users B. (c) is most stressful because if I do that, I then get the most complains, but I do it anyway because I care for users A and users B, even if users A do not care about users B and vice versa.

**This is very frustrating and I can't take it anymore. For that reason I will lock this issue very soon** (I am giving @omouse a few hours to comment). **And if someone opens a new issue about this, then I will immediately close that, put a link to this post, and forgo commenting any further.**

Note that this doesn't mean that I don't care about your needs or that I won't try to take them into account. It just means that (a) this issue being brought up again and again stresses me out and (b) that as a result of that the solution to this issue is being *delayed*.

Once I have implemented the new and improved branching+pushing, I will *not* push it to `master` immediately. Instead I will push it to a feature branch and invite you to comment. I might then make further changes. But right now any further comment on this issue is counterproductive and not appreciated.

---

Here is the definition of `magit-push-always-verify`:

```lisp
(defcustom magit-push-always-verify 'nag
  "Whether certain commands require verification before pushing.

Starting with v2.1.0 some of the push commands are supposed to
push to the configured upstream branch without requiring user
confirmation or offering to push somewhere else.

This has taken a few users by surprise, and they suggested that
we force users to opt-in to this behavior.  Unfortunately adding
this option means that now other users will complain about us
needlessly forcing them to set an option.  But what can you do?
\(I am not making this up.  This has happened in the past and it
is very frustrating.)

You should set the value of this option to nil, causing all push
commands to behave as intended:

`PP' Push the current branch to its upstream branch, no questions
     asked.  If no upstream branch is configured or if that is
     another local branch, then prompt for the remote and branch
     to push to.

`Po' Push another local branch (not the current branch) to its
     upstream branch.  If no upstream branch is configured or if
     that is another local branch, then prompt for the remote and
     branch to push to.

`Pe' Push any local branch to any remote branch.  This command
     isn't affected by this option.  It always asks which branch
     should be pushed (defaulting to the current branch) and then
     where that should be pushed (defaulting to the upstream
     branch of the previously selected branch).

There are other push commands besides these.  You should read
their doc-strings instead of blindly trying them out and then
being surprised if it turns out that they do something different
from what you expected.  For example inside the push popup type
`?i' to learn what \"implicitly\" means here.  Or to learn about
all push commands at once, consult the manual.

While I have your attention, I would also like to warn you that
pushing will be further improved in a later release (probably
v2.3.0), and that you might be surprised by some of these
changes, unless you read the documentation.

Setting this option to t makes little sense.  If you consider
doing that, then you should probably just use `Pe' instead of
`PP' or `Po'."
  :package-version '(magit . "2.2.0")
  :group 'magit-commands
  :type '(choice (const :tag "require verification and mention this option" nag)
                 (const :tag "require verification" t)
                 (const :tag "don't require verification" nil)))
```

(Yes, the second to last paragraph has to be updated.)

**Comment by omouse** [comment] 2015-10-21 19:11
@tarsius sorry for commenting on this closed issue, I appreciate the work you've done and the way this is being handled, I just got bit by this issue for the first time ever today wasn't aware if there was a resolution or not.

Thanks for replying and explaining it, apologies if my comment stressed you out.

**Comment by tarsius** [comment] 2015-10-21 19:18
Well, it was the sum of it all, not just your comment. But thanks.

**Comment by tarsius** [comment] 2015-11-28 11:22
I have now implemented improved branch handling. Please give #2414 a spin and do comment (on the pr). Thanks for you patience.

**Closed by tarsius** 2015-11-28 11:22 UTC
Labels: 10 feature request, umbrella
