### ISSUE TITLE
magit does not split windows vertically if treemacs is active

### ISSUE THREAD

**Issue by tastytea** [magit/magit#4034] opened 2020-01-25 01:43 UTC
### Observed behavior

I have a frame with 3 windows. On the left is Treemacs, in the middle is a dedicated buffer with sourcecode and on the right is magit-status.

When I make a commit, the right window shows the diff. After I press `q`, this window shows the buffer with the commit message.

When I hide Treemacs and then make a commit, the right window is split vertically and shows the diff at the bottom and the commit message at the top.

### Expected behavior

I expected that the right window is always split vertically if it can't be split horizontally.

### How to reproduce

Provided that magit and treemacs are installed as packages, the behavior can be reproduced with this `init.el`:

``` elisp
(package-initialize)
(require 'magit)
(require 'treemacs)

(defun toggle-window-dedicated ()
  (interactive)
  (message
   (if (let (window (get-buffer-window (current-buffer)))
         (set-window-dedicated-p window (not (window-dedicated-p window))))
       "%s is dedicated."
     "%s is no longer dedicated.")
   (current-buffer)))
```

* Open Treemacs with **M-x** `treemacs`.
* Choose a file in a versioned directory.
* Dedicate buffer to window with **M-x** `toggle-window-dedicated`.
* Open magit with **M-x** `magit-status`.
* Amend the last commit with `c a`.
* *diff and commit message are not split.*
* Close Treemacs with **M-x** `treemacs`.
* Amend the last commit with `c a`.
* *diff and commit message are split.*

### Versions

**`magit-version`:** Magit 20200124.1129, Git 2.24.1, Emacs 27.0.50, gnu/linux  
**Same result with:** Magit 20200124.1129, Git 2.24.1, Emacs 26.3, gnu/linux  
**`treemacs-version`:** [Treemacs] v2.7-2020.01.25 @ 27.0.50

### Things I've tried

I've tried to influence the splitting behavior with this function:

``` elisp
(defun my/split-vertically ()
  (setq-local split-width-threshold nil)
  (setq-local split-height-threshold 0))
```

… that was called from `magit-pre-display-buffer-hook` and/or `git-commit-setup-hook`. No luck.

**Comment by phil-s** [comment] 2020-01-26 02:11
You possibly want to be looking at https://magit.vc/manual/magit/Switching-Buffers.html

That describes the `magit-display-buffer-function` user option, along with all of the standard values (functions) provided for it.

If you need custom behaviour, you can start with whichever function provides the closest match, and base a new custom function on that.

**Comment by kyleam** [comment] 2020-01-26 17:39
@tastytea Thanks for the detailed report and the steps to reproduce the behavior.

If you have a look at some of the `magit-display-buffer-function` implementations that @phil-s points to, you'll notice that `magit-display-buffer-traditional` (the default), as well as most of the other alternatives, will end up calling `(display-buffer BUFFER nil)` for the diff buffer.  So, for a vanilla user configuration, we're going down the display actions defined in `display-buffer-fallback-action`.

In most cases, `display-buffer--maybe-pop-up-frame-or-window` should pop up a window, but in the scenario you describe, it can't find an available window based on what `window-splittable-p` reports.  So the next relevant action is `display-buffer-use-some-window`.  That chooses the commit buffer window because the other windows are marked as dedicated.

Perhaps we should consider doing more on our end for this scenario, but Magit is very good about going through magit-display-buffer-traditional/display-buffer, so it ultimately gives you complete control for your specific situation.  Here's an example customization that should work for you:

```elisp
(defun my/magit-display-buffer (buffer)
  (if (and git-commit-mode
           (with-current-buffer buffer
             (derived-mode-p 'magit-diff-mode)))
      (display-buffer buffer '((display-buffer-pop-up-window
                                display-buffer-use-some-window
                                display-buffer-below-selected)
                               (inhibit-same-window . t)))
    (magit-display-buffer-traditional buffer)))

(setq magit-display-buffer-function #'my/magit-display-buffer)
```

In words: when we're not displaying a diff from the commit message buffer, behave the same as `magit-display-buffer-traditional`.  Otherwise, try to pop up a window or reuse a window (provided it is not the commit message window); if that fails, open up a window below and display it there.  Note that `display-buffer-below-selected` overrides `split-{height,width}-threshold`, so hopefully a window will be popped up even with layouts that would typically prevent it.

**Comment by tastytea** [comment] 2020-01-26 19:44
Thanks for your answers. @kyleam your code works beautifully.

I find it strange that a window with the same height is vertically splitable without Treemacs but not splitable with Treemacs. Do I understand it right that `window-splittable-p` from Emacs is at fault here? Or is it more likely that Treemacs is the source?

**Comment by kyleam** [comment] 2020-01-27 03:22
> I find it strange that a window with the same height is vertically splitable without Treemacs but not splitable with Treemacs. Do I understand it right that `window-splittable-p` from Emacs is at fault here?

That's a reasonable interpretation of my "[display-buffer-pop-up-window] can't find an available window based on what window-splittable-p reports", but I stated that poorly.  The decision isn't just based on what `window-splittable-p` reports.  For example, `display-buffer-pop-up-window`
chooses two windows (the largest and the least recently used) to pass in its two calls to `window--try-to-split-window`, which eventually calls `window-splittable-p`, so the layout can affect _which two_ windows are considered.  Plus, there's a fair amount of logic between the `window--try-to-split-window` call and the eventual call to `window-splittable-p`.

My guess is that which buffers are passed to `window--try-to-split-window` play a role in the differences you see when using treemacs vs when not.  When I try on my end, that's what it comes down to.

<details>
<summary>More details...</summary>

Due to the height of my screen, `window-splittable-p` always says that I can't split vertically with the default `split-height-threshold`.  When treemacs isn't loaded, `window--try-to-split-window` is passed the commit message buffer and that is successfully split because it triggers that last condition in `split-window-sensibly` that sets `split-height-threshold` to 0.  When treemacs is loaded, `window--try-to-split-window` is given only dedicated windows, and last condition in `split-window-sensibly` isn't triggered.

</details>

**Comment by kyleam** [comment] 2020-01-27 23:30
All right, in my view, this can be closed, but feel free to continue discussing.

**Closed by kyleam** 2020-01-27 23:30 UTC
Labels: support
