### ISSUE TITLE
magit does not automatically [prompt to] save buffers visiting TRAMP paths

### ISSUE THREAD

**Issue by CyberShadow** [magit/magit#4292] opened 2021-01-13 18:05 UTC
In 66df603ea9e9d0e4f504ec4ed2b79e4b92e11c45, `magit-save-repository-buffers` was changed to use `(magit-rev-parse-safe "--show-toplevel")` instead of `(magit-toplevel)`. However, in a remote TRAMP buffer, `(magit-rev-parse-safe "--show-toplevel")` evaluates to just the local path on the remote system, whereas `(magit-toplevel)` returns the full TRAMP path.

This did not seem to have immediately become an issue because the change was done to both sides of the comparison. I assume this worked at some point but I don't immediately see a change that would have introduced this. In any case, the problem occurs on this line:

https://github.com/magit/magit/blob/25f432551347468ce97b8b03987e59092e91f8f0/lisp/magit-mode.el#L1215

Here, `topdir` is `(magit-rev-parse-safe "--show-toplevel")`, i.e. the local path on the remote, while `(file-truename buffer-file-name)` will include the TRAMP prefix.

**Comment by tarsius** [comment] 2021-10-10 20:28
Yes but in 1ff422528de116069d043ff15e4a86e02d0327d1 from five years ago that was fixed, after it was reported in #2843. Subsequently the function was modified again and it looks like there were regressions, but it does not look like they reintroduced this particular bug.  Anyway, as of the current `master` (a little after v3.3.0) I cannot reproduce this issue.

**Comment by tarsius** [comment] 2021-10-10 20:55
Yes, this bug report was filled after the bug that you pointed at (66df603ea) was introduced *and* fixed. That does of course not rule out the possibility that another bug was later introduced that has the same symptoms. However if that is the case then **that** bug was not introduced in 66df603ea, because that has already been fixed in 1ff422528 -- both half a decade ago. So it seems that your report that 66df603ea introduced a currently existing bug is not correct.

But if you experience a bug as of today, then you don't have to point me to the commit that introduced it, so the point is moot. What is needed however are steps to reproduce the issue because as I said, I am unable to reproduce it.

**Comment by tarsius** [comment] 2021-10-10 21:14
So I can reproduce the problem but I am probably not in the right state of mind to fix it right now. :woozy_face:

**Closed** 2021-10-12 18:45 UTC
Labels: obsolete, area: tramp
