### ISSUE TITLE
Creation of new branches should track correctly

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1709] opened 2015-01-23 01:28 UTC
I've had an issue a few times where I created a new local branch, and had problems pushing it to the remote under the same name.  It defaults to the parent branch instead, and explicitly requires changing the upstream branch name in order to create a new branch when pushed to the remote.  I would think the default would be to push to a new branch, rather than pushing to the parent.

**Comment by tarsius** [comment] 2015-01-23 03:47
I have completely reworked pushing on the `next` branch. Before I did that I almost always pushed from the command line - I didn't feel I could trust the magit commands.

Now it feels much safer but doesn't exactly work as you suggest. When you create a branch and the starting point is another branch then that is automatically tracked. If a remote branch is upstream then push defaults to push there without offering another branch. But if not such upstream is configured then it will ask for a branch, not just push to something else. There also is an "elsewhere" variant and finally it's now much easier to change the upstream branch.

Give `next` a try.

**Comment by tarsius** [comment] 2015-01-23 03:51
And for support please give http://emacs.stackexchange.com a try.

**Comment by j-mckitrick** [comment] 2015-01-23 11:11
I've been using ```next``` for a few weeks now, and I like it.  I'm trying to provide some meaningful feedback before release.  :-)

**Comment by tarsius** [comment] 2015-01-23 16:36
Ow, kinda sounded like `master` to me. Let's have another look.

**Comment by tarsius** [comment] 2015-01-23 17:21
`p` pushes to what is configured for the current branch, and `e` allows you to push the same branch somewhere else. `o` allows pushing any branch anywhere.

"Push to some remote using the same branch name as locally" would be doable but one would always have to select the remote. Of course an option could be added that for each branch records the remote to push to. But it is a bit more complex than that.

The problem is that Git only supports one "branch that is related to the current one". I intend to fix that eventually, see #1485. That issue also mentions my `magit-push-remote` which also attempts to address this issue, but falls short of what it could be doing. (Also I haven't touched it in over a year and since it likely has bit rotten quite a bit I would strongly recommend against using it with Magit's `next` branch right now. But I will try to have a look soon and port it to `next`.)

**Comment by tarsius** [comment] 2015-01-23 17:37
Also see #1593.

**Comment by tarsius** [comment] 2015-01-23 20:48
Closing in favor or #1485.

**Closed by tarsius** 2015-01-23 20:48 UTC
Labels: 32 duplicate
