### ISSUE TITLE
when committing, diffs are blank if .git is a symlink

### ISSUE THREAD

**Issue by notestaff** [magit/magit#3599] opened 2018-09-25 19:46 UTC
I'm using git-annex with submodules: http://git-annex.branchable.com/submodules/
It replaces .git of a submodule with a symlink.
magit-status shows browseable differences, but when doing a commit, when writing a commit message, the differences are shown as blank.

**Comment by tarsius** [comment] 2018-09-25 20:06
> magit-status shows browseable differences, but when doing a commit, when writing a commit message, the differences are shown as blank.

Are you talking about doing those things inside the submodule or inside the superproject?

Anyway, that wiki page does not actually say *why* symlinks have to be used and that

> The conversion of .git file to .git symlink mostly won't bother git.

It also bothers tools like magit that assume that other tools don't mess with this.

I think this is a pretty minor issue. It could probably be fixed by teaching `magit-git-dir` and/or `magit-toplevel` about yet another edge-case, but that comes with a big risk of breaking other edge-cases and so I don't think this is worth the effort.

You should be able to show the diff by going to the status buffer and invoking the appropriate diff command from there. The problem is that the diff command is invoked with the `default-directory` of `COMMIT_EDITMSG` and due to the symlink magit doesn't find its way back to the working tree. Or something like that.

**Comment by tarsius** [comment] 2018-09-25 20:14
Actually it might be fairly easy to work around this issue by adjusting `magit--record-separated-gitdir`.

**Comment by kyleam** [comment] 2018-09-25 20:35
> Anyway, that wiki page does not actually say why symlinks have to be used

An annex file is a symlink to ".git/annex/objects/XXX", so if the gitdir isn't symlinked (or old-style, non-absorbed submodules aren't used) the annex file links don't point to the content.

**Closed** 2018-09-27 11:00 UTC
Labels: feature request
