### ISSUE TITLE
Document configuration to prevent COMMIT_EDITMSG from opening new frame

### ISSUE THREAD

**Issue by jfkw** [magit/magit#2172] opened 2015-08-14 15:58 UTC
After upgrading to magit 2.1 (previously on 1.x), I am unable prevent COMMIT_EDITMSG from popping up in a new frame. I can't find mention of this in the end-user documentation. Please consider adding a configuration option to prevent magit from using new frames anywhere.

An excerpt of magit 1.x configuration I used, which doesn't seem to have anything related to frames.
```
(defun magit-exit-commit-mode ()
  (interactive)
  (kill-buffer)
  (delete-window))
(eval-after-load "git-commit-mode"
  '(define-key git-commit-mode-map (kbd "C-c C-k") 'magit-exit-commit-mode))
;; close popup when commiting
(defadvice git-commit-commit (after delete-window activate)
  (delete-window)))
```

**Comment by tarsius** [comment] 2015-08-14 16:19
This shouldn't happen, please try to reproduce from `emacs -Q`.

**Comment by tarsius** [comment] 2015-08-14 19:06
> An excerpt of magit 1.x configuration I used

Why was that required? To close the buffer and create a commit use `C-c C-k` and close the buffer but abort the commit use `C-c C-k`.

**Comment by tarsius** [comment] 2015-08-19 11:15
Feel free to follow up, even now that I have closed this.

**Closed by tarsius** 2015-08-19 11:15 UTC
Labels: 30 support

**Comment by jfkw** [comment] 2015-08-19 17:11
I will, thanks. I normally use el-get, and I haven't yet had time to learn how to start emacs -Q adding minimal config to load magit and dash.

**Comment by jfkw** [comment] 2015-08-19 18:00
I did get emacs to run with minimal config, and the problem of a new COMMIT_EDITMSG frame does not manifest. OK to leave this closed, I'll check the list or StackOverflow for support on my specific config problem. For completeness:
```
emacs -Q -l ~/.emacs.d/magit-only.el
```
magit-only.el:
```
(add-to-list 'load-path "~/.emacs.d/el-get/dash")
(add-to-list 'load-path "~/.emacs.d/el-get/magit/lisp")
(require 'magit)

(with-eval-after-load 'info
  (info-initialize)
  (add-to-list 'Info-directory-list
               "~/.emacs.d/el-get/magit/Documentation/"))
```
I returned to my normal el-get config, and made sure magit customization was minimal:

init.el
```
(setq el-get-sources
      '((:name magit
               :after (progn
               (global-set-key (kbd "C-c g") 'magit-status)))
         ...
```
I next searched for frame and window related customization, in case they were interfering:
```
;; Don't ever change window configuration
(setq pop-up-windows nil)

;; ediff configuration
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
(setq ediff-split-window-function 'split-window-horizontally)

;; fullscreen mode mapped to key
(defun fullscreen ()
  (interactive)
  (set-frame-parameter nil 'fullscreen
    (if (frame-parameter nil 'fullscreen) nil 'fullboth)))

(global-set-key [f11] 'fullscreen)
```
I have yet to disable these one-by-one to see if that fixes the problem. I'll take those support requests to the appropriate venues. Thanks.

**Comment by jfkw** [comment] 2015-08-19 18:54
I have a reproducible case now that exhibits the unwanted new frame on COMMIT_EDITMSG, (setq pop-up-windows nil):

magit-only.el
```
(add-to-list 'load-path "~/.emacs.d/el-get/dash")
(add-to-list 'load-path "~/.emacs.d/el-get/magit/lisp")
(require 'magit)

(with-eval-after-load 'info
  (info-initialize)
  (add-to-list 'Info-directory-list
	       "~/.emacs.d/el-get/magit/Documentation/"))

(setq pop-up-windows nil)
```
Start with: 
```
emacs -Q -l ~/.emacs.d/magit-only.el

**Comment by jfkw** [comment] 2015-08-25 15:33
Updated title, have a reproducible case. OK to reopen this issue?

**Comment by tarsius** [comment] 2015-08-25 16:48
By setting `pop-up-windows` to `nil` you are disallowing elisp packages from creating new windows. If a package then needs to create a new window, it has no choice but to create a new frame instead. In this case Magit wants to show two buffers the diff buffer and the message buffer, but since the frame has only one window and you are not allowing Magit to create a new window it has to create a new frame.

Setting `pop-up-windows` to `nil` is a pretty hard-core setting and you should only do it if you understand the consequences and are willing to deal with them yourself. In this case you could either redefine `magit-commit-diff` to explicitly create a new window, or you could remove `commit` from `magit-diff-auto-show` so that the diff is not automatically shown when creating a commit.

**Comment by rootzlevel** [comment] 2015-09-17 15:14
The same happens to me, but I don't have `pop-up-windows` set to nil. A workaround for me was to decrese `split-height-threshold`, since the two windows for diff and commit message were smaller than the allowed height.

But: With `pop-up-frames` set to nil, I expect magit to never open a new frame and instead violate `split-height-threshold` and `split-width-threshold`. Especially since pop-up frames are completely useless in my window manager setup.

**Comment by tarsius** [comment] 2015-09-17 15:31
I intend to dive into the window management mess soonish, but until I have done that, I cannot give any advice here.

**Comment by janesma** [comment] 2016-11-14 18:19
I find the current popup extremely annoying.  I have split-width and split-height thresholds set to limit my windows to a left/right split frame.  When I commit, the buffer for editing the commit message pops up in one of my panes, which is great.  However, the same buffer is opened in a new frame behind my primary frame.  When I finalize the commit, my *primary* frame is closed, leaving the frame that magit popped up in the background.

Running emacs in a terminal with -nw works properly (since there is no way for magit to open a new frame).  The commit action opens the edit commit buffer in one of the 2 existing windows.

**Comment by tarsius** [comment] 2016-11-20 11:27
> However, the same buffer is opened in a new frame behind my primary frame.

That shouldn't happen. Are you using some window management related packages which might be responsible for this?

Magit is very customizable with regards to window management, see https://magit.vc/manual/magit/Switching-Buffers.html.

**Comment by janesma** [comment] 2017-01-06 18:23
Jonas Bernoulli <notifications@github.com> writes:

>> However, the same buffer is opened in a new frame behind my primary frame.
>
> That shouldn't happen. Are you using some window management related packages which might be responsible for this?

It turns out that emacsclient was always opening a new frame,
disregarding the existing frame.  I'm not sure why `emacsclient` behaves
the same as `emacsclient -c` on debian/gnome3/x11/emacs25

> Magit is very customizable with regards to window management, see https://magit.vc/manual/magit/Switching-Buffers.html.

I created a wrapper script to work around the issue:

 #!/bin/bash
 /usr/bin/emacsclient.emacs25  ${@:1:$# - 1} -e "(find-file \"${@:$#}\")"

And set with-editor-emacsclient-executable to call that script.
