### ISSUE TITLE
Push is ignoring global remote.pushdefault and branch-specific pushremote

### ISSUE THREAD

**Issue by fommil** [magit/magit#1767] opened 2015-03-13 09:43 UTC
I recently learnt that it is possible to have a different default push than pull http://stackoverflow.com/questions/29016343/

My workflow is almost always such that my upstream is the official repo and origin is my remote. I always want to automatically pull from upstream (typically master) but push to origin (typically my own named feature branch).

This is working great in the CLI. a git pull -v or git push -v is pointing at the correct repositories.

However, in magit (20150124.930 from MELPA) doing a P -d P (dry run push) is logging that it would go to upstream! (not my default origin).

After searching I found that magit has a few of its own configs for this #e4bcda8381e73760f65d7030ce77c26ae9fd1e2c but even the following in ~/.gitconfig is broken

[magit]
    defaultpushremote = origin
    pushremote = origin

**Comment by fommil** [comment] 2015-03-13 09:59
is this #1485 ? The magit terminology is a bit different to the git terminology, but I think the concept is the same.

**Comment by tarsius** [comment] 2015-03-13 11:07
> is this #1485 ? The magit terminology is a bit different to the git terminology, but I think the concept is the same.

In the sense that that is the primary thing I am going to do to address this, yes. But one of the blog posts linked to their also mentions the approach you are mentioning and why it isn't enough. So not exactly.

> [some git variables are ignored]

That could be considered a bug. But at least it's not a regression and I probably won't get to it until I also implement #1485. Which might be fairly soon after the release.

**Comment by fommil** [comment] 2015-03-13 11:36
Cool. I've read the blog post and I don't see the value in an additional `publish` concept in my workflow, although it may work for others who don't rebase from upstream.

My workflow is (and I am aware the naming of what `origin` or `upstream` means can be confusing):

* actual project lives at `upstream`
* my remote lives at `origin`
* I create a local that pulls from `upstream/release_branch` and pushes to `origin/my_feature_branch`

then I issue a pull request from my origin to the upstream. If I need to rebase off upstream, I just force push to origin. I don't tend to merge from upstream.

**Comment by tarsius** [comment] 2015-04-29 22:39
Since I am going to implement #1485 directly without first fixing this issue. I am closing this one in favor of the former.

**Closed by tarsius** 2015-04-29 22:39 UTC
Labels: 10 feature request
