### ISSUE TITLE
Can not handle credential.helper configuration

### ISSUE THREAD

**Issue by asif-mahmud** [magit/magit#4246] opened 2020-11-11 16:07 UTC
- Problem
I have used this command to store my git credentials for future usage - `git config --global credential.helper store`.  Before today or a few days (i haven't used magit for last 3-4 days), `M-x magit-status` was working fine, it opened the status window on demand. But today i am getting an error message - `Wrong type argument: listp, "store"`. Git from command line is working just fine.

- Environment
Emacs version - 27.1
Magit version - 20201111.1204
Git - 2.29.2

- Expected
When a `projectile` project is opened, if i run `M-x magit-status` it should have opened status window.

- Observed
Instead of status window i got the error message.

- Steps to reproduce
Configure git credential helper using this command -

```
git config --global credential.helper "store"
```
Open emacs, load a project, then enter command - `M-x magit-status`

**Comment by tarsius** [comment] 2020-11-11 16:11
Duplicate of #4245.

**Closed** 2020-11-11 16:11 UTC
Labels: duplicate
