### ISSUE TITLE
git rm merge

### ISSUE THREAD

**Issue by Pitometsu** [magit/magit#3510] opened 2018-07-11 15:47 UTC
```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
```
No options to resolve it via magit for now, error notification only.

**Comment by kyleam** [comment] 2018-07-11 17:54
The file should show up as something like

```
Staged changes (1)
unmerged   foo (deleted by us)
```

in the status buffer.

Move point there and hit <kbd>k</kbd>, which will let you choose "ours"  (`git rm` for my example) or "theirs" (`git add`).

**Comment by kyleam** [comment] 2018-07-11 17:58
Duplicate of #2466.

**Closed by kyleam** 2018-07-11 17:58 UTC
Labels: support
