### ISSUE TITLE
Inhibit revert while rebasing

### ISSUE THREAD

**Issue by rdgreen** [magit/magit#2762] opened 2016-09-07 15:50 UTC
Similar to the issue discussed in #1731, I think it is necessary to inhibit auto-revert-mode while running a rebase, otherwise a rebase can fail occasionally. `git-rebase` is a shell script and therefore does not itself lock the repository.

```
First, rewinding head to replay your work on top of it...
fatal: Unable to create '/home/robin/git/backend/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

**Comment by tarsius** [comment] 2016-09-07 16:06
This is one of those cases where it is very useful to know the Magit and Git versions.

**Comment by tarsius** [comment] 2016-09-07 16:10
This likely is a duplicate of #2708. If you get the index.lock error with a recent Magit version, then please comment on that issue.

**Closed by tarsius** 2016-09-07 16:10 UTC
Labels: duplicate
