### ISSUE TITLE
Wrong type argument: number-or-marker-p, nil 

### ISSUE THREAD

**Issue by knobo** [magit/magit#3714] opened 2019-01-16 09:16 UTC
This is where it happens
I'm right under the first section in magit-status buffer
![image](https://user-images.githubusercontent.com/89921/51238596-8e41f280-1977-11e9-9701-1c210c0a5305.png)

I press "down" or "up" key, and i get  `message: Wrong type argument: number-or-marker-p, nil 
` in the minibuffer. 

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  magit-section-position-in-heading-p()
  magit-previous-line(1 1)
  funcall-interactively(magit-previous-line 1 1)
  call-interactively(magit-previous-line nil nil)
  command-execute(magit-previous-line)
```
https://github.com/magit/magit/blob/master/lisp/magit-section.el#L1513

If i press "left" or "right" key, then up or down. I don't get the error message.

Magit 20190113.1949, Git 2.19.1, Emacs 25.2.2, gnu/linux
and forge-201901112.1437

**Comment by tarsius** [comment] 2019-01-18 19:14
Closing since I am pretty sure this can be fixed by recompiling.

**Comment by knobo** [comment] 2019-01-21 11:56
After upgrading all packages 

``` el
ELISP> forge--db-version
2 (#o2, #x2, ?\C-b)
ELISP> magit-version
"20190119.1742"
ELISP> (byte-recompile-directory package-user-dir nil 'force)
"Done (Total of 818 files compiled, 446 skipped in 215 directories)"
ELISP> 
```

``` el
M-: (list (eq (magit-current-section) magit-root-section)
          (ignore-errors (marker-position (oref section start)))
          (ignore-errors (marker-position (oref section content)))
          (ignore-errors (marker-position (oref section end))))

(t nil nil nil)
```

Problem is still there.

**Comment by tarsius** [comment] 2019-01-21 14:01
The way you have recompiled does not guarantee that obsolete code does not leak into the new byte-code. You even ensure that the old magit byte-code is loaded by first calling `magit-version`. Please try again this time using `magit-emacs-Q-command` as described at https://magit.vc/manual/magit/Debugging-Tools.html. If you can still reproduce after that, then try with no byte-code at all:  `rm ~/.emacs.d -name '*.elc' -exec rm '{}' ';'` (without recompiling anything).

If you can still reproduce after all that, then it is time for a binary-search debug of your init file. I.e. systematically comment out parts of your init file until you have determined the part of it that triggers the issue.

**Comment by basil-conto** [comment] 2019-01-21 14:06
> `rm ~/.emacs.d -name '*.elc' -exec rm '{}' ';'`

That should be `find`, right?

**Comment by phil-s** [comment] 2019-01-22 20:35
Uh, deleting *every byte-compiled file under `.emacs.d`* is an extreme measure!

Perhaps just modify `load-suffixes` ?!

**Comment by tarsius** [comment] 2019-01-30 16:41
The benefit of making sure that there are no byte-code files is that you can be *sure* that no byte-code was loaded. I have asked users enough times to do something, which they then claim they have done only to find out dozens of posts later, that they didn't do it correctly. This is one of those "this cannot possibly happen" issues and with those it is very important to rule out all those weird edge-cases that are beyond my control.

So I would recommend against fiddling with `load-suffixes`. A better compromise would be to only remove magit's byte-code files.

Anyway, I don't think there's anything else I can do here, so I am closing.

**Closed by tarsius** 2019-01-30 16:41 UTC
Labels: unconfirmed

**Comment by knobo** [comment] 2019-02-01 10:05
Stripped out most things. Still a problem though.

![installed-pkgs](https://user-images.githubusercontent.com/89921/52116349-3363f880-2611-11e9-956f-7a588ea8e3b0.png)
![break-on-signals](https://user-images.githubusercontent.com/89921/52116351-37901600-2611-11e9-8fa2-63e17a632182.png)
![dot-emacs](https://user-images.githubusercontent.com/89921/52116354-39f27000-2611-11e9-9667-64f6350cf4d9.png)
![wrong-marker](https://user-images.githubusercontent.com/89921/52116363-3ced6080-2611-11e9-89f2-07888822680e.png)

**Comment by knobo** [comment] 2019-02-01 10:07
And all .elc files deleted.

**Comment by knobo** [comment] 2019-02-01 13:32
If I don't load forge it is no problem.

**Comment by vermiculus** [comment] 2019-02-01 14:21
And if you load it standardly with `(require 'forge)`?

**Comment by knobo** [comment] 2019-02-06 12:45
https://asciinema.org/a/ZhFt2Sy9FIv2VLqxyZptfIGnX

**Comment by tarsius** [comment] 2019-02-06 13:08
After sitting through 3/4 of that I learned that you didn't mention this error before

```
forge-insert-issues: Symbol’s function definition is void: when-let*
```

If you had, then I could have fixed that in a minute or two. I have done that now.

**Comment by knobo** [comment] 2019-02-06 13:13
I'm sorry I did not mention the when-let error. I'm not sure why I missed it.
Great that the video solved it then :) 
And thank you so much for looking in to this and fixing it!  
I have not tried your fix yet.

**Comment by knobo** [comment] 2019-02-06 14:59
It turns out that it was not the main issue. 
I have installed emacs27 now. 
And it works.
I'll send an update when I figure out something more.

**Comment by phil-s** [comment] 2019-02-06 23:52
> Magit 20190113.1949, Git 2.19.1, Emacs 25.2.2, gnu/linux and forge-201901112.1437

`when-let*` was introduced in Emacs 26, so it's not surprising that this was failing in 25.2.2 and working for you in 27.

**Comment by wcy123** [comment] 2020-03-09 12:37
I spent some time to debug this problem, I found `magit-rev-format` cannot retrieve rev string properly.
```
% git "show" "--no-patch" "--format=%h %s" "HEAD^{commit}" "--"
fatal: unrecognized argument: --no-patch
% git --version
git version 1.8.3.1
```

I don't know why `--no-patch` and which version of git supports the option.

**Comment by tarsius** [comment] 2020-03-09 12:48
Magit requires at least Git 2.2.0.
