### ISSUE TITLE
Bumping from 1.2.2 to 1.4.1 breaks rebasing for me

### ISSUE THREAD

**Issue by timvisher** [magit/magit#1827] opened 2015-04-28 14:25 UTC
Thank you _so_ much for the release! I'm super happy with it so far and I think it was a really smart move to make. :)

That said, I use cli emacs without a server and edit files over tramp on a machine that I do git interactions from.

1.4.1 seems to break this flow and I get the following error when attempting to continue a rebase:

```
user-error: Cannot use `magit-with-emacsclient' when accessing repository using tramp
```

Is there something I can tweak to make this work again?

**Comment by timvisher** [comment] 2015-04-28 14:25
FWIW, I was able to work around this issue by issuing `: rebase --continue RET`

**Comment by tarsius** [comment] 2015-04-29 11:37
So what happens if you use `1.2.2` over tramp and git decides to have you edit a commit message? Do you actually get to see that?

**Comment by timvisher** [comment] 2015-04-29 11:48
@tarsius do you have a recommended way of running a temporary emacs instance with 1.2.2 installed?

**Comment by tarsius** [comment] 2015-04-29 11:52
Note really. I would clone the magit repository into an empty .emacs.d, checkout 1.2.2, edit init.el to add the clone to the load-path and require magit.

**Comment by timvisher** [comment] 2015-04-29 12:09
That's essentially what I did. Cloned magit, checked out 1.2.2, launched emacs with `emacs -L magit -Q` and then `(require 'magit)`.

So, the results of my experiment are as follows (I'm attempting to translate my actions to the command line which I almost never use, so forgive any minor inconsistencies):

```bash
mkdir tmp-rebase-experiment && cd tmp-rebase-experiment && git init
touch test
git commit -am 'commit'
git checkout -b feature
echo ohai > test
git commit -am 'commit 2'
git checkout master
echo charnock > test
git commit -am 'commit 3'
git checkout feature
# From emacs with 1.2.2
# M-x magit-status R master RET
# … resolve conflict …
# M-x magit-status R C works
echo piper >> test
git commit -am 'commit 4'
git checkout master
echo whitefield > test
git commit -am 'commit 5'
git checkout feature
# From emacs with 1.4.1
# M-x magit-status R master RET
# … resolve conflicts …
# M-x magit-status R C complains with the error message
# From emacs with 1.2.2
# M-x magit-status R C works
```

**Comment by tarsius** [comment] 2015-04-29 13:12
> # M-x magit-status R C works

How is the commit message buffer presented to you?

**Comment by timvisher** [comment] 2015-04-29 13:20
@tarsius I don't see the commit message buffer. The rebase just happens.

Note I've never been able to rebase interactively except in the old old days (iirc). I don't believe a commit message buffer _should_ be presented to me in this instance because I'm not editing the message of any commit.

**Comment by tarsius** [comment] 2015-04-29 13:32
You are supposed to be given a change to edit the message after resolving a conflict or editing a commit. Maybe you are using an old version of git, which doesn't do that.

If git actually tried to have you edit the message, then this would likely fail because git on the remote cannot start an editor on your local machine.

> I don't believe a commit message buffer should be presented to me in this instance because I'm not editing the message of any commit.

In order to resolve the conflict you might have made changes that need to be reflected in 

I am just trying to figure out whether this is a regression. Because if not then I would rather have you wait for `2.1.0` which handles this properly (need to double check, but am pretty sure).

**Comment by timvisher** [comment] 2015-04-29 13:54
@tarsius In this instance, the version of git is the same for both of them, as is the version of emacs and the version of tramp etc, so I don't think the git part is the problem.

What might have been the problem is that magit maybe had a bug where it didn't show the commit message buffer for some reason and you 'fixed' it and thus broke my 'feature'?

**Comment by timvisher** [comment] 2015-04-29 13:55
Also, definitely not implying that there is never a reason to edit the commit message during a rebase. I was used to magit failing if it had to do that. In most instances it didn't.

**Comment by tarsius** [comment] 2015-04-29 19:34
Apply this patch

```diff
diff --git a/magit.el b/magit.el
index b71948e..49ca780 100644
--- a/magit.el
+++ b/magit.el
@@ -5381,8 +5381,7 @@ (defun magit-rebase-step ()
           (cl-case (read-event)
             ((?A ?a) (magit-run-git-async (if am "am" "rebase") "--abort"))
             ((?S ?s) (magit-run-git-async (if am "am" "rebase") "--skip"))
-            ((?C ?c) (magit-with-emacsclient magit-server-window-for-commit
-                       (magit-run-git-async (if am "am" "rebase") "--continue")))))
+            ((?C ?c) (magit-run-git-async (if am "am" "rebase") "--continue"))))
       (let* ((branch (magit-get-current-branch))
              (rev (magit-read-rev
                    "Rebase to"
```

and it should be back to at least trying but then sometimes failing. It's not possible to make this always work with `1.4.*`, so I am not going to apply this. On `next` I have written a complete new library just to deal with this issue! I have just verified again that it works.

Note that rebasing has been improved considerable on `next` so you might want to update to that. (Else you have to wait a few more weeks and in the meantime use the above patch).

**Closed by tarsius** 2015-04-29 19:34 UTC

**Comment by timvisher** [comment] 2015-04-30 12:36
:+1:

I'd probably feel comfortable bumping to next once it reaches beta. i just really don't like being on the bleeding edge of things. :)
