### ISSUE TITLE
Gravatar halves are put together in reverse order

### ISSUE THREAD

**Issue by dato** [magit/magit#2265] opened 2015-09-16 05:05 UTC
Hello—

On my system, Gravatars are showing top- and bottom- half reversed. Swapping the two `(slice ...)` lines in _magit-insert-revision-gravatar_ fixed the issue.

I don’t use the feature myself, but I can provide debugging information if you can't reproduce.

Thanks.

**Comment by tarsius** [comment] 2015-09-16 11:02
I've seen screenshots of that happening, and asked for an issue to be opened (because on twitter there isn't enough room to figure out what is going on). But was told by one of the users that s/he is perfectly happy with it. :-)

Okay now we can start figuring out what's up (and down) with that. Yes, please post steps that let me reproduce. From looking at the code and the documentation for `slice` I would say I am doing everything right and I am guessing that something like bidirectional text or some Asian coding system triggers a bug in Emacs.

**Comment by tarsius** [comment] 2015-09-25 21:52
Until I have more information, I'm gonna assume this is a bug in Emacs.

**Comment by tarsius** [comment] 2015-10-10 14:53
Note to others who are affected by this and came across this issue: nothing will happen here until someone provides steps to reproduce this, so you might wanna do that.

**Comment by antonio** [comment] 2015-10-13 14:13
> Note to others who are affected by this and came across this issue: nothing will happen here until someone provides steps to reproduce this, so you might wanna do that.

Not sure what the steps could be, since it's happening to me even when loading emacs with `-q` and requiring only magit.

Some environment info:
- I'm using the homebrew version of emacs, configured like this
```
/Users/antonio/.emacs.d at discworld (master)
[16:03] % brew info emacs
emacs: stable 24.5 (bottled), devel 24.5-dev, HEAD
GNU Emacs text editor
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs/24.5 (3923 files, 118M) *
  Built from source with: --with-cocoa --with-gnutls --with-librsvg
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/emacs.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Optional: d-bus ✘, gnutls ✔, librsvg ✘, imagemagick ✘, mailutils ✘, glib ✔
```
- `magit-version` returns `Magit 20151011.1819, Git 2.3.0, Emacs 24.5.1`.
- git config --list (github token filtered out)
```
user.name=Antonio Santos
user.email=antonio@santosvelasco.com
color.diff=auto
color.status=auto
color.branch=auto
color.blame=auto
merge.tool=vimdiff
alias.aa=add .
alias.ci=commit
alias.co=checkout
alias.slog=log --pretty=format:'%C(white)[%C(yellow)%h%C(white)] %C(blue)(%ad) %C(white)%s %C(green)%an' --date=local
alias.st=status -s
alias.blame=blame -w
alias.wtf=blame -w
alias.staged=diff --cached
alias.pr=pull-request
alias.amend=commit -a --amend
core.excludesfile=/opt/boxen/config/git/gitignore
core.preloadindex=true
core.editor=emacs
hub.protocol=https
push.default=current
rerere.enabled=true
credential.helper=/opt/boxen/bin/boxen-git-credential
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=false
```
This is happening to me with any repository, eg https://github.com/antonio/dotfiles

**Comment by tarsius** [comment] 2015-10-14 09:35
So that seems to falsify my theory that this is related to the use of Asian encodings.

**Comment by tarsius** [comment] 2015-10-14 10:02
Can you reproduce the issue using:

```lisp
(progn
  (fundamental-mode)
  (let ((image (find-image '((:type xpm :file "delete.xpm")))))
     (insert "\ntop: ")
     (insert (propertize " " 'display `(,image (slice .0 .0 1.0 0.5))))
     (insert "\nbuttom: ")
     (insert (propertize " " 'display `(,image (slice .0 .5 1.0 1.0))))))
```

(Paste that into the *scratch* buffer and evaluate it there using `C-x C-e`.)

**Comment by antonio** [comment] 2015-10-14 10:03
![screen shot 2015-10-14 at 12 03 01](https://cloud.githubusercontent.com/assets/17516/10480631/8c9938a0-726b-11e5-840f-af7dace35f9a.png)

**Comment by tarsius** [comment] 2015-10-14 10:13
What about these two:

```lisp
(progn
  (fundamental-mode)
  (let ((image (find-image '((:type xpm :file "delete.xpm")))))
     (insert "\ntop: ")
     (insert (propertize " " 'display `(,(copy-sequence image) (slice .0 .0 1.0 0.5))))
     (insert "\nbuttom: ")
     (insert (propertize " " 'display `(,(copy-sequence image) (slice .0 .5 1.0 1.0))))))

(progn (insert "\n")
       (insert-sliced-image
	(find-image '((:type xpm :file "delete.xpm"))) nil nil 2))
```

**Comment by antonio** [comment] 2015-10-14 10:21
Same thing

![image](https://cloud.githubusercontent.com/assets/17516/10481003/21381948-726e-11e5-85c6-26c38c11d551.png)

**Comment by tarsius** [comment] 2015-10-14 10:25
I found this old Emacs bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=7847. Could you please comment there?  (You might want to post my original snippet and should mention that you are using OS X.)

**Comment by antonio** [comment] 2015-10-14 11:38
@tarsius done. Let me know if I can further help with this.

**Comment by tarsius** [comment] 2015-10-14 11:52
Thanks

**Comment by antonio** [comment] 2015-10-15 06:48
I've done some testing and this issue does not exist in the [emacs-mac port]https://github.com/railwaycat/mirror-emacs-mac).

**Comment by tarsius** [comment] 2015-10-15 07:25
I have added a new option `magit-revision-use-gravatar-kludge` which affected users can set to `t` to work around this issue.

I am closing this issue because the alternative would be to keep it open for a decade until every user has updated to an Emacs version which contains a fix for this issue.

**Closed by tarsius** 2015-10-15 07:25 UTC
Labels: 00 bug emacs

**Comment by antonio** [comment] 2015-10-15 07:28
@tarsius thank you, I was planning to open a PR later today since that seemed the most reasonable approach to me as well.

**Comment by johbo** [comment] 2018-01-04 18:10
Just stranded here due to the same problem, the a fix has been added into Emacs meanwhile and it solves the issues for me: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=0fca290ddff9eabcd2e866b1361cd5b5ba868281

**Comment by tarsius** [comment] 2018-01-08 12:50
Thanks for the heads up. I'll add a note to the doc-string.
