### ISSUE TITLE
invalid-function error

### ISSUE THREAD

**Issue by seagle0128** [magit/magit#3704] opened 2019-01-01 09:35 UTC
` Magit 20181229.1434, Git 2.20.1, Emacs 26.1, darwin`

Please refer 
https://github.com/alphapapa/magit-todos/issues/62#event-2049276355

```elisp
Debugger entered--Lisp error: (invalid-function (value (run-hook-with-args-until-success 'magit-section-set-visibility-hook section7)))
  (value (run-hook-with-args-until-success 'magit-section-set-visibility-hook section7))()
  magit-todos--insert-group(:depth 1 :type todos :items (#s(magit-todos-item :filename "./doom-modeline.el" :org-level nil :line 1306 :column nil :position nil :keyword "HACK" :suffix ":" :description "`ace-window-display-mode' should respect the ignore buffers.")) :heading "TODOs (1)")
  magit-todos--insert-groups(:type todos :heading "TODOs (1)" :group-fns nil :items (#s(magit-todos-item :filename "./doom-modeline.el" :org-level nil :line 1306 :column nil :position nil :keyword "HACK" :suffix ":" :description "`ace-window-display-mode' should respect the ignore buffers.")) :depth 0)
  magit-todos--insert-items(#<buffer magit: doom-modeline> (#s(magit-todos-item :filename "./doom-modeline.el" :org-level nil :line 1306 :column nil :position nil :keyword "HACK" :suffix ":" :description "`ace-window-display-mode' should respect the ignore buffers.")))
  magit-todos--scan-callback(#<buffer magit: doom-modeline> "\\(?:^\\(?8:[^:]+\\):\\(?2:[[:digit:]]+\\):\\(?:\\(?1:\\*+\\)[[:blank:]]+\\(?4:\\(?:\\?\\?\\?\\|BUG\\|D\\(?:\\(?:EFEC\\|ON\\)T\\)\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|ISSUE\\|KLUDGE\\|NEXT\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\)\\|WORKAROUND\\|XXXX?\\)\\)[[:blank:]]+\\(?5:.+\\)\\|\\(?:.+\\)?\\(?4:\\(?:\\?\\?\\?\\|BUG\\|D\\(?:\\(?:EFEC\\|ON\\)T\\)\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|ISSUE\\|KLUDGE\\|NEXT\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\)\\|WORKAROUND\\|XXXX?\\)\\)\\(?6:\\(?:([^)]+)\\)?:\\)?\\(?:[[:blank:]]+\\)?\\(?5:.+\\)?\\)\\)" #<process magit-todos--scan-with-rg>)
  apply(magit-todos--scan-callback (#<buffer magit: doom-modeline> "\\(?:^\\(?8:[^:]+\\):\\(?2:[[:digit:]]+\\):\\(?:\\(?1:\\*+\\)[[:blank:]]+\\(?4:\\(?:\\?\\?\\?\\|BUG\\|D\\(?:\\(?:EFEC\\|ON\\)T\\)\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|ISSUE\\|KLUDGE\\|NEXT\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\)\\|WORKAROUND\\|XXXX?\\)\\)[[:blank:]]+\\(?5:.+\\)\\|\\(?:.+\\)?\\(?4:\\(?:\\?\\?\\?\\|BUG\\|D\\(?:\\(?:EFEC\\|ON\\)T\\)\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|ISSUE\\|KLUDGE\\|NEXT\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\)\\|WORKAROUND\\|XXXX?\\)\\)\\(?6:\\(?:([^)]+)\\)?:\\)?\\(?:[[:blank:]]+\\)?\\(?5:.+\\)?\\)\\)" #<process magit-todos--scan-with-rg>))
  #f(compiled-function (&rest args2) #<bytecode 0x43b0e139>)(#<process magit-todos--scan-with-rg>)
  async-when-done(#<process magit-todos--scan-with-rg> "finished\n")
```

**Comment by alphapapa** [comment] 2019-01-01 18:16
This is a configuration error, not a bug in Magit or `magit-todos`..  I've asked you twice to start from a clean `~/.emacs.d` and you still have not done so.  Jonas is busy working on Magit and Forge.  Please close this issue and fix your Emacs configuration.

**Comment by seagle0128** [comment] 2019-01-01 20:36
@alphapapa I tried with a fresh config indeed and did not upgrade from previous version. I don't know the root cause yet since it doesn't occur every time. But it's deserved to investigate. If you don't want to do that, just leave it.

**Comment by alphapapa** [comment] 2019-01-01 20:47
It is *not* a bug in Magit.  Please close this issue and seek help with your configuration elsewhere.

**Comment by tarsius** [comment] 2019-01-02 00:38
I agree with @alphapapa: this is not a bug in Magit and the cause like is outdated byte-code files, which can be fixed by recompiling `magit` and `magit-todo`, in that order.

**Closed** 2019-01-02 00:39 UTC
Labels: invalid

**Comment by seagle0128** [comment] 2019-01-04 17:46
Thank you @tarsius, @alphapapa !
Finally I found the root cause (maybe not). If I enable `async-bytecomp-package-mode` and install `magit-todos` package, the issue occurs. I have to disable it.
