### ISSUE TITLE
Blaming a deleted file in the history causes error

### ISSUE THREAD

**Issue by xuhdev** [magit/magit#2836] opened 2016-10-23 08:38 UTC
To reproduce:

1. `mkdir tmp && cd tmp && git init`
2. `echo "a\nb" > README`
3. `git add README && git commit -m "First commit"`
4. `git rm README && git commit -m "Second commit"`
5. `git checkout HEAD\^ README`
6. `emacs README`, then run `magit-blame`

Expected:

```
fatal: no such path 'README' in HEAD
```

But got the following error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-to-number(nil)
  (list :hash (let ((hash (match-string 1 line))) (if (equal hash (make-string 40 48)) nil hash)) :previous-start (string-to-number (match-string 2 line)) :start (string-to-number (match-string 3 line)) :lines (string-to-number (match-string 4 line)))
  (setq chunk (list :hash (let ((hash (match-string 1 line))) (if (equal hash (make-string 40 48)) nil hash)) :previous-start (string-to-number (match-string 2 line)) :start (string-to-number (match-string 3 line)) :lines (string-to-number (match-string 4 line))))
  (cond ((equal line "")) ((not chunk) (string-match "^\\(.\\{40\\}\\) \\([0-9]+\\) \\([0-9]+\\) \\([0-9]+\\)" line) (setq chunk (list :hash (let ((hash (match-string 1 line))) (if (equal hash (make-string 40 48)) nil hash)) :previous-start (string-to-number (match-string 2 line)) :start (string-to-number (match-string 3 line)) :lines (string-to-number (match-string 4 line))))) ((string-match "^filename \\(.+\\)" line) (let* ((hash (plist-get chunk :hash)) (file (match-string 1 line))) (let ((it (gethash hash magit-blame-cache))) (if it (setq chunk (nconc chunk it)) (plist-put chunk :filename file) (puthash hash chunk magit-blame-cache)))) (magit-blame-make-overlay chunk) (setq chunk nil)) ((string-match "^previous \\(.\\{40\\}\\) \\(.+\\)" line) (plist-put chunk :previous-hash (match-string 1 line)) (plist-put chunk :previous-file (match-string 2 line))) ((string-match "^\\([^ ]+?-mail\\) <\\([^>]+\\)>" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+?-\\(?:time\\|tz\\)\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (match-string 2 line))))
  (let ((line (car --dolist-tail--))) (cond ((equal line "")) ((not chunk) (string-match "^\\(.\\{40\\}\\) \\([0-9]+\\) \\([0-9]+\\) \\([0-9]+\\)" line) (setq chunk (list :hash (let ((hash ...)) (if (equal hash ...) nil hash)) :previous-start (string-to-number (match-string 2 line)) :start (string-to-number (match-string 3 line)) :lines (string-to-number (match-string 4 line))))) ((string-match "^filename \\(.+\\)" line) (let* ((hash (plist-get chunk :hash)) (file (match-string 1 line))) (let ((it (gethash hash magit-blame-cache))) (if it (setq chunk (nconc chunk it)) (plist-put chunk :filename file) (puthash hash chunk magit-blame-cache)))) (magit-blame-make-overlay chunk) (setq chunk nil)) ((string-match "^previous \\(.\\{40\\}\\) \\(.+\\)" line) (plist-put chunk :previous-hash (match-string 1 line)) (plist-put chunk :previous-file (match-string 2 line))) ((string-match "^\\([^ ]+?-mail\\) <\\([^>]+\\)>" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+?-\\(?:time\\|tz\\)\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (match-string 2 line)))) (process-put process (quote chunk) chunk) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((line (car --dolist-tail--))) (cond ((equal line "")) ((not chunk) (string-match "^\\(.\\{40\\}\\) \\([0-9]+\\) \\([0-9]+\\) \\([0-9]+\\)" line) (setq chunk (list :hash (let (...) (if ... nil hash)) :previous-start (string-to-number (match-string 2 line)) :start (string-to-number (match-string 3 line)) :lines (string-to-number (match-string 4 line))))) ((string-match "^filename \\(.+\\)" line) (let* ((hash (plist-get chunk :hash)) (file (match-string 1 line))) (let ((it ...)) (if it (setq chunk ...) (plist-put chunk :filename file) (puthash hash chunk magit-blame-cache)))) (magit-blame-make-overlay chunk) (setq chunk nil)) ((string-match "^previous \\(.\\{40\\}\\) \\(.+\\)" line) (plist-put chunk :previous-hash (match-string 1 line)) (plist-put chunk :previous-file (match-string 2 line))) ((string-match "^\\([^ ]+?-mail\\) <\\([^>]+\\)>" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+?-\\(?:time\\|tz\\)\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" (match-string 1 line))) (match-string 2 line)))) (process-put process (quote chunk) chunk) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- lines)) (while --dolist-tail-- (let ((line (car --dolist-tail--))) (cond ((equal line "")) ((not chunk) (string-match "^\\(.\\{40\\}\\) \\([0-9]+\\) \\([0-9]+\\) \\([0-9]+\\)" line) (setq chunk (list :hash (let ... ...) :previous-start (string-to-number ...) :start (string-to-number ...) :lines (string-to-number ...)))) ((string-match "^filename \\(.+\\)" line) (let* ((hash ...) (file ...)) (let (...) (if it ... ... ...))) (magit-blame-make-overlay chunk) (setq chunk nil)) ((string-match "^previous \\(.\\{40\\}\\) \\(.+\\)" line) (plist-put chunk :previous-hash (match-string 1 line)) (plist-put chunk :previous-file (match-string 2 line))) ((string-match "^\\([^ ]+?-mail\\) <\\([^>]+\\)>" line) (plist-put chunk (intern (concat ":" ...)) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+?-\\(?:time\\|tz\\)\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" ...)) (string-to-number (match-string 2 line)))) ((string-match "^\\([^ ]+\\) \\(.+\\)" line) (plist-put chunk (intern (concat ":" ...)) (match-string 2 line)))) (process-put process (quote chunk) chunk) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (let ((chunk (process-get process (quote chunk))) (lines (split-string string "\n" t))) (if (string-match-p "\n\\'" string) nil (process-put process (quote chunk) chunk) (process-put process (quote partial-line) (car (last lines))) (setq lines (butlast lines))) (let ((--dolist-tail-- lines)) (while --dolist-tail-- (let ((line (car --dolist-tail--))) (cond ((equal line "")) ((not chunk) (string-match "^\\(.\\{40\\}\\) \\([0-9]+\\) \\([0-9]+\\) \\([0-9]+\\)" line) (setq chunk (list :hash ... :previous-start ... :start ... :lines ...))) ((string-match "^filename \\(.+\\)" line) (let* (... ...) (let ... ...)) (magit-blame-make-overlay chunk) (setq chunk nil)) ((string-match "^previous \\(.\\{40\\}\\) \\(.+\\)" line) (plist-put chunk :previous-hash (match-string 1 line)) (plist-put chunk :previous-file (match-string 2 line))) ((string-match "^\\([^ ]+?-mail\\) <\\([^>]+\\)>" line) (plist-put chunk (intern ...) (string-to-number ...))) ((string-match "^\\([^ ]+?-\\(?:time\\|tz\\)\\) \\(.+\\)" line) (plist-put chunk (intern ...) (string-to-number ...))) ((string-match "^\\([^ ]+\\) \\(.+\\)" line) (plist-put chunk (intern ...) (match-string 2 line)))) (process-put process (quote chunk) chunk) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (progn (let ((chunk (process-get process (quote chunk))) (lines (split-string string "\n" t))) (if (string-match-p "\n\\'" string) nil (process-put process (quote chunk) chunk) (process-put process (quote partial-line) (car (last lines))) (setq lines (butlast lines))) (let ((--dolist-tail-- lines)) (while --dolist-tail-- (let ((line (car --dolist-tail--))) (cond ((equal line "")) ((not chunk) (string-match "^\\(.\\{40\\}\\) \\([0-9]+\\) \\([0-9]+\\) \\([0-9]+\\)" line) (setq chunk ...)) ((string-match "^filename \\(.+\\)" line) (let* ... ...) (magit-blame-make-overlay chunk) (setq chunk nil)) ((string-match "^previous \\(.\\{40\\}\\) \\(.+\\)" line) (plist-put chunk :previous-hash ...) (plist-put chunk :previous-file ...)) ((string-match "^\\([^ ]+?-mail\\) <\\([^>]+\\)>" line) (plist-put chunk ... ...)) ((string-match "^\\([^ ]+?-\\(?:time\\|tz\\)\\) \\(.+\\)" line) (plist-put chunk ... ...)) ((string-match "^\\([^ ]+\\) \\(.+\\)" line) (plist-put chunk ... ...))) (process-put process (quote chunk) chunk) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
  (if magit-blame-mode (progn (let ((chunk (process-get process (quote chunk))) (lines (split-string string "\n" t))) (if (string-match-p "\n\\'" string) nil (process-put process (quote chunk) chunk) (process-put process (quote partial-line) (car (last lines))) (setq lines (butlast lines))) (let ((--dolist-tail-- lines)) (while --dolist-tail-- (let ((line ...)) (cond (...) (... ... ...) (... ... ... ...) (... ... ...) (... ...) (... ...) (... ...)) (process-put process (quote chunk) chunk) (setq --dolist-tail-- (cdr --dolist-tail--))))))))
  (save-current-buffer (set-buffer (process-get process (quote command-buf))) (if magit-blame-mode (progn (let ((chunk (process-get process (quote chunk))) (lines (split-string string "\n" t))) (if (string-match-p "\n\\'" string) nil (process-put process (quote chunk) chunk) (process-put process (quote partial-line) (car (last lines))) (setq lines (butlast lines))) (let ((--dolist-tail-- lines)) (while --dolist-tail-- (let (...) (cond ... ... ... ... ... ... ...) (process-put process ... chunk) (setq --dolist-tail-- ...))))))))
  magit-blame-process-filter(#<process git> "fatal: no such path 'README' in HEAD\n")
  read-event(nil t 2)
  sit-for(2)
  execute-extended-command(nil "magit-blame" "magit-bla")
  funcall-interactively(execute-extended-command nil "magit-blame" "magit-bla")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by tarsius** [comment] 2016-10-23 11:26
I cannot reproduce this. Please post the output of `magit-version`.

I am using `Magit 2.8.0-132-ga91eb1a, Git 2.10.0, Emacs 25.1.1, gnu/linux`. Following your instructions results in a new, already staged, file. Blaming that succeeds in that there is no error and a single blame chunk whose revision is shown as "Not Committed Yet" is shown. If I unstage the file and try again, then that is caught in the interactive form of `magit-blame` and results in the error message "Buffer isn't visiting a tracked file".

**Comment by tarsius** [comment] 2016-10-23 11:38
Ah, with an *empty* file I can reproduce this.

**Comment by xuhdev** [comment] 2016-10-23 16:18
My version:

```
Magit 2.8.0-132-gcb97e74f202c, Git 2.1.4, Emacs 25.1.50.1, gnu/linux
```

**Comment by xuhdev** [comment] 2016-10-23 16:20
I expected a fatal error message, but what really happened is the huge error message you saw above.

**Comment by xuhdev** [comment] 2016-10-23 17:21
OK, my guess is that the older version of git does not support blaming in such situation. Do you plan to support older versions?

**Comment by kyleam** [comment] 2016-10-24 02:14
> my guess is that the older version of git does not support blaming in such situation

Right, I reproduced your error with Git v2.1.4.  It should be fixed with a20f33a.

> Do you plan to support older versions?

I belive the earliest version currently supported is v1.9.4 ([FAQ]),
so v2.1.4 should be supported.

[FAQ]: https://magit.vc/manual/magit/I-am-using-a-Git-release-older-than-v194.html#I-am-using-a-Git-release-older-than-v194

**Comment by xuhdev** [comment] 2016-10-24 19:22
I can confirm the fix works.

**Closed** 2016-10-24 20:00 UTC
Labels: fly

**Comment by xuhdev** [comment] 2016-10-24 20:35
You haven't merged the fix yet...

**Comment by tarsius** [comment] 2016-10-24 20:48
Ah... right.
