### ISSUE TITLE
No local branches in magit-refs buffer

### ISSUE THREAD

**Issue by dscole** [magit/magit#3215] opened 2017-10-20 14:36 UTC
I've recently upgraded magit (and all my emacs packages) and the magit-refs buffer stopped showing all my local branches. Instead it showed an empty section for the Branchs: part (the remote branches were showing up fine). After looking through the commit history of magit-refs.el I've noticed that a lot of changes have been recently made and that there is some new feature from git 2.13 that's being used, but some care has been taken to be backwards compatible. 
I was running with:
Magit 20171014.220, Git 2.11.0, Emacs 25.3.2, gnu/linux
So I decided to upgrade git to latest:
Magit 20171014.220, Git 2.14.2, Emacs 25.3.2, gnu/linux
And now the branches are showing up fine.

Note that my previous version, git 2.11.0, is the current version ubuntu zesty is using. 

I think some recent change broke the compatibility with git versions earlier than 2.13.

**Comment by tarsius** [comment] 2017-10-20 14:38
Duplicate of #3203, fixed with #3205.

**Closed by tarsius** 2017-10-20 14:38 UTC
Labels: duplicate

**Comment by dscole** [comment] 2017-10-20 14:51
I downgraded git back to 2.11.0  to double check, and ran the code from that commit:

https://github.com/magit/magit/blob/2360d5b4fab7cb7163a4ed8a8b4300dc4a558c81/lisp/magit-refs.el

```
(magit-insert-section (local nil)
    (magit-insert-heading "Branches:")
    (dolist (line (magit-git-lines "for-each-ref" "--format=\
%(HEAD)%00%(refname:short)%00%(objectname:short)%00%(subject)%00\
%(upstream:short)%00%(upstream)%00%(upstream:track,nobracket)"
                                   "refs/heads"
                                   (cadr magit-refresh-args)))
      (pcase-let ((`(,head ,branch ,hash ,message
                           ,upstream ,uref ,utrack)
                   (-replace "" nil (split-string line "\0"))))
        (magit-insert-branch
         (and (not (string-prefix-p "(HEAD detached" branch)) branch)
         magit-refs-local-branch-format (and (equal head "*") branch)
         'magit-branch-local hash message upstream uref utrack)))
    (insert ?\n)
    (magit-make-margin-overlay nil t))

```
And it still prints an empty Branches: section.

**Comment by tarsius** [comment] 2017-10-20 15:18
@kyleam could you have a look at this please?

**Comment by kyleam** [comment] 2017-10-20 15:18
Please upgrade to the latest magit version.  5c7ad029
(magit-insert-local-branches: don't use ":track,nobracket",
2017-10-15) should work.

**Comment by tarsius** [comment] 2017-10-20 15:19
Ah right!

**Comment by dscole** [comment] 2017-10-20 15:32
OK, yeah that should work.
