### ISSUE TITLE
Status buffer: point gets entangled in invisible text, breaking functionality

### ISSUE THREAD

**Issue by doublep** [magit/magit#4744] opened 2022-08-29 17:07 UTC
Setup: Magit status buffer with staged files, at least two. It looks like this:

```
Staged changes (N)
modified    file1
[invisible diff of file1]
modified    file2
[invisible diff of file2]
```

so essentially a user only sees this in UI:

```
Staged changes (N)
modified    file1
modified    file2
```

Now put the point at the beginning of the third line (`[^]` is the point):

```
Staged changes (N)
modified    file1
[^]modified    file2
```

Press `C-b`, expecting that the point is moved to the end of the previous visible line. But it is not moved there, this is the result:

```
Staged changes (N)
modified    file1
[^]modified    file2
```

In reality, the point is in the invisible (to the user) diff for `file1`, this can be verified e.g. with `M-x describe-char RET`. This is not just a question of appearance, in this position all commands on sections, including `TAB`, `s`, `u` and so on don't work as you'd expect from what you see on the screen

If you press `C-b` again, only now point is moved like it was expected to be moved the first time:

```
Staged changes (N)
modified    file1[^]
modified    file2
```

**Comment by tarsius** [comment] 2022-08-31 13:31
Likely a duplicate of #4739.

**Comment by doublep** [comment] 2022-08-31 13:53
No, it's not the same. It happens also with Emacs 28. I'm the reporter of that bug in Emacs linked from the discussion comments in the other bug. The issue here is similar, but not the same.

**Comment by doublep** [comment] 2022-08-31 14:02
That said, it might turn out to be caused by a long-standing subtle bug in Emacs, would not be the first time. But according to an Emacs developer (see https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-08/msg02517.html):

> (Btw, I think it's a subtle bug in Magit that it assumes cursor motion
> will never end up on invisible text in such buffers.)

**Comment by johanfforsberg** [comment] 2022-09-18 09:39
I am seeing this right now too, I think. I noticed that my collapsed status buffer is behaving in a confusing way where TABbing to reveal diffs will sometimes reveal the previous diff in the list instead of the one the cursor seems to be positioned on, when the cursor is at the beginning of the line. It's like there is an invisible character right at the beginning of the line, which is actually part of the previous line. Moving the cursor one step to the right makes TAB behave as expected.

By experimenting a bit I found that this happens when there are several chunks in a file, some (but not all) of them are "unfolded" (using TAB), and then the entire file is "folded". In this case, moving to the next file and pressing TAB unfolds the wrong thing, and the invisible character is there. Somehow the folding of the chunks gets jumbled up. I could reproduce this by creating a new repo with a couple of plain text files.

I'm on magit 20220916.1716 and emacs 29.0.50 built 2022-08-21

**Comment by johanfforsberg** [comment] 2022-09-18 09:51
I can add that this does not seem to happen if you only use "n"/"p" to move between the headings. It may require some manual cursor movement at the beginning of the line.

**Comment by consoleaf** [comment] 2022-09-18 09:54
I noticed that it seems to behave normally after you mouse-click anywhere in the magit buffer.

(Magit pinned at c1fb53d)

**Comment by kyleam** [comment] 2022-09-18 23:01
@johanfforsberg
> I noticed that my collapsed status buffer is behaving in a confusing way where TABbing to reveal diffs [...]
> I'm on magit 20220916.1716 and emacs 29.0.50 built 2022-08-21

What you're describing sounds like #4739.  That was fixed on the Emacs side after your build date: a2d62456a7b (Fix regression with cursor motion in Magit buffers, 2022-08-27).

**Comment by tangxinfa** [comment] 2023-02-15 02:47
I stash wrong files frequently when i use magit status buffer, because i was use
to C-n/C-p to move the cursor, the following settings make me feel better:

    (use-package magit
      :bind
      (:map magit-status-mode-map
            ([remap next-line] . my/magit-next-line)
            ([remap previous-line] . my/magit-previous-line))
      :config
      (require 'magit-extras)
      (defun my/magit-next-line ()
        "Call `magit-next-line' or `magit-section-forward' according to magit section type at point."
        (interactive)
        (magit-section-case
          (hunk (magit-next-line))
          (t (magit-section-forward))))
      (defun my/magit-previous-line ()
        "Call `magit-previous-line' or `magit-section-backward' according to magit section type at point."
        (interactive)
        (magit-section-case
          (hunk (magit-previous-line))
          (t (magit-section-backward)))))

**Comment by tangxinfa** [comment] 2023-02-15 06:16
I stash wrong files frequently when i use magit status buffer, because i was use
to C-n/C-p to move the cursor, the following settings make me feel better:

    (use-package magit
      :bind
      (:map magit-status-mode-map
            ([remap next-line] . my/magit-next-line)
            ([remap previous-line] . my/magit-previous-line))
      :config
      (require 'magit-extras)
      (defun my/magit-next-line ()
        "Call `magit-next-line' or `magit-section-forward' according to magit section type at point."
        (interactive)
        (magit-section-case
          (hunk (if (oref (magit-current-section) hidden)
                    (magit-section-forward)
                  (magit-next-line)))
          (t (magit-section-forward))))
      (defun my/magit-previous-line ()
        "Call `magit-previous-line' or `magit-section-backward' according to magit section type at point."
        (interactive)
        (magit-section-case
          (hunk (if (oref (magit-current-section) hidden)
                    (magit-section-backward)
                  (magit-previous-line)))
          (t (magit-section-backward)))))

**Comment by sg-qwt** [comment] 2023-04-09 15:26
My emasc version is well beyond a2d62456a7b
But I do hit the same symptom same as in #4739, have to disable trucate-lines or move cursor one off to workaround, not sure why. Maybe there's a regression lately?

```
In GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version
3.24.36, cairo version 1.16.0)
Repository revision: db7e95531ac36ae842787b6c5f2859d0642c78cc
Repository branch: master
System Description: NixOS 23.05 (Stoat)

Configured using:
 'configure
 --prefix=/nix/store/159z3yjad0swhl4mgb90qyb2i7fbbk5p-emacs-pgtk-20230324.0
 --disable-build-details --with-modules --with-pgtk
 --with-native-compilation'

```
Magit 20230402.1342 [>= 3.3.0.50-git], Git 2.39.2, Emacs 30.0.50, gnu/linux
```

**Comment by tarsius** [comment] 2023-04-26 21:21
I cannot reproduce. Could you please pick a commit in magit's repository and tell me exactly what commands I have to invoke to reproduce the issue?

**Comment by doublep** [comment] 2023-04-27 22:04
For what it's worth, I just reproduced it with latest Magit (commit 11370838) and GNU Emacs 29.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.33, cairo version 1.16.0) of 2023-04-08. Exactly like described in the first post.

Here is the simplest way (at least for me) to reproduce, abstracting from dependencies and configuration as much as possible. Install [Eldev](https://github.com/doublep/eldev). In subdirectory `lisp` of your Git directory create file `Eldev-local` with this contents:

    (setf eldev-project-main-file "magit.el")
    (eldev-use-package-archive 'gnu-elpa)
    (eldev-use-package-archive 'melpa)

From the command line  execute:

    ~/git/magit/lisp$ eldev emacs --eval "(magit-status \"PATH-TO-GIT-CHECKOUT-TO-TEST-ON\")"

Then follow the instructions from the first post.

By default it will install stable versions of Magit dependencies. If you want to check with unstable versions, execute:

    $ eldev --unstable upgrade

For me it gave no difference, but is still reproducible.

**Comment by tarsius** [comment] 2023-04-28 12:41
Should be fixed now.

Thanks for the report and patience!

**Closed** 2023-04-28 12:40 UTC
Labels: bug needinfo
