### ISSUE TITLE
Regression with Cygwin

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#2284] opened 2015-09-21 23:28 UTC
After upgrading from `magit-20150724.1231` to `magit-20150918.541` there is now a problem with paths on Windows.  In particular, calling `magit-status` in any repository results in

> apply: Setting current directory: Permission denied, `c:/c/Users/XXX/Projects/XXX/Source/`

Obviously, either `c:` or `/c` should be removed.  Please, let me know if you need some testing.

**Comment by Alexander-Shukaev** [comment] 2015-09-22 00:39
By the way, `unmsys--file-name` will definitely help handling this; you just have to figure out what you've changed since then, and filter those path strings which are returned from `git` with `unmsys--file-name`.

**Comment by johnmastro** [comment] 2015-09-22 00:47
Which `git` are you using (e.g. Cygwin, Git for Windows, etc.)?

**Comment by Alexander-Shukaev** [comment] 2015-09-22 00:54
It's `git` from MSYS2;  `pacman -Ss git-core`:

```
msys/git 2.5.1-1 (VCS) [installed]
    The fast distributed version control system
```

**Comment by npostavs** [comment] 2015-09-22 01:23
We're already doing the needed path manipulations in `magit-expand-git-file-name` (see #1318, and 2b4b366dde1c56496d46e033ff9e00c16aa1e2ed). I suspect we're just missing a call to that function somewhere.

**Comment by tarsius** [comment] 2015-09-22 13:08
The changes to `magit-toplevel` are a good candidate.

**Comment by tarsius** [comment] 2015-09-25 16:00
Does this fix the issue? https://github.com/magit/magit/compare/jb/cygwin-kludge?expand=1

**Comment by tarsius** [comment] 2015-09-27 12:39
@Alexander-Shukaev could you please check whether this fixes the issue for you?

**Comment by Alexander-Shukaev** [comment] 2015-09-27 14:38
Sorry, was busy.  No, unfortunately, the problem remains:

```
Debugger entered--Lisp error: (file-error "Setting current directory" "Permission denied" "c:/c/Users/XXX/Projects/XXX/Source/")
  call-process("c:/Tools/x64/MSYS2/usr/bin/git.exe" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-toplevel")
  apply(call-process "c:/Tools/x64/MSYS2/usr/bin/git.exe" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-toplevel"))
  process-file("c:/Tools/x64/MSYS2/usr/bin/git.exe" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-toplevel")
  apply(process-file ("c:/Tools/x64/MSYS2/usr/bin/git.exe" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-toplevel"))
  magit-process-file("c:/Tools/x64/MSYS2/usr/bin/git.exe" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-toplevel")
  apply(magit-process-file "c:/Tools/x64/MSYS2/usr/bin/git.exe" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-toplevel"))
  magit-git-str("rev-parse" "--show-toplevel")
  apply(magit-git-str "rev-parse" "--show-toplevel")
  magit-rev-parse-safe("--show-toplevel")
  magit-save-repository-buffers(nil)
  magit-maybe-save-repository-buffers()
  run-hooks(magit-mode-setup-hook)
  magit-status-internal("c:/Users/XXX/Projects/XXX/Source/")
  magit-status(nil)
  funcall-interactively(magit-status nil)
  call-interactively(magit-status)
```

I also tried fixing it in the similar way as you did, but it didn't work as well.  The issue is somewhere deeper I assume.

**Comment by tarsius** [comment] 2015-09-27 15:06
Open the directory in question in Dired. What is the buffer-local value of `default-directory` there?

**Comment by Alexander-Shukaev** [comment] 2015-09-27 15:30
```
default-directory is a variable defined in `C source code'.
Its value is
"c:/Users/XXX/Projects/XXX/Source/"
Local in buffer Source; global value is nil
```

**Comment by npostavs** [comment] 2015-09-27 19:54
@Alexander-Shukaev Are you sure you don't have stale elc files or something? I just tried using msys2 git; I see the same stacktrace, but after checking out `jb/cygwin-kludge` it works without error.

**Comment by tarsius** [comment] 2015-09-28 17:18
I've pushed a fix to master now. Let us know if the issue persists.

**Comment by hitswint** [comment] 2015-09-29 02:43
Problem has been fixed on git-status, but still exists when committing.

**Comment by Alexander-Shukaev** [comment] 2015-09-29 16:13
In my case, there is a follow-up problem with `magit-status`:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^\\([^ ]+\\) \\(.*\\)" nil)
  magit-insert-head-header()
  magit-insert-headers((magit-insert-diff-filter-header magit-insert-head-header magit-insert-upstream-header magit-insert-tags-header))
  magit-insert-status-headers()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-status-internal("c:/Users/XXX/Projects/XXX/Source/")
  magit-status(nil)
  funcall-interactively(magit-status nil)
  call-interactively(magit-status)
```

**Comment by npostavs** [comment] 2015-09-29 17:00
> Problem has been fixed on magit-status, but still exists when committing.

Yes, I see this.

---

> In my case, there is a follow-up problem with magit-status:

From the backtrace I guess that `(magit-rev-format "%h %s" (or branch "HEAD"))` is returning nil. What's the output from running `git show --no-patch "--format=%h %s" "master^{commit}"`? (replace `master` depending on what your current branch is).

**Comment by Alexander-Shukaev** [comment] 2015-09-29 17:08
And that's the most funny thing.  I already did this and it does return normal expected output:

```
c02f106 Draft
```

**Comment by npostavs** [comment] 2015-09-29 19:28
@hitswint Does it work after changing `with-editor-emacsclient-executable` using the code below?
```elisp
(setq with-editor-emacsclient-executable
      (format "x() { %s \"$(cygpath -w \"$1\")\"; }; x "
	      (with-editor-locate-emacsclient)))
```

This fixes it for me, although if this is necessary I can't see how it could have ever been working before at all.

---

> it does return normal expected output:

So what about evaluating `(magit-rev-format "%h %s" (or (magit-get-current-branch) "HEAD"))`?

**Comment by Alexander-Shukaev** [comment] 2015-09-29 22:39
Obviously, `nil`...  `;)`  I know it's weird, but it is how it is.  To summarize, running it as a shell command from Emacs does return the expected output, while running it as evaluation of the above forms returns `nil`.

**Comment by npostavs** [comment] 2015-09-29 22:50
> To summarize, running it as a shell command from Emacs does return the expected output, while running it as evaluation of the above forms returns nil.

Maybe the shell is the difference? What about
```elisp
(with-output-to-string
  (with-current-buffer standard-output
    (process-file magit-git-executable
                  nil '(t t) nil "show" "--no-patch" "--format=%h %s" "master^{commit}")))
```
And what are the values of `magit-git-executable` and `shell-file-name`?

**Comment by Alexander-Shukaev** [comment] 2015-09-29 22:57
```
"fatal: ambiguous argument 'master^commit': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
"
```

```
magit-git-executable is a variable defined in `magit-git.el'.
Its value is "c:/Tools/x64/MSYS2/usr/bin/git.exe"
```

```
shell-file-name is a variable defined in `C source code'.
Its value is
"C:/Tools/x64/MSYS2/mingw64/libexec/emacs/25.0.50/x86_64-w64-mingw32/cmdproxy.exe"
```

**Comment by hitswint** [comment] 2015-09-29 23:13
@npostavs That fixes the problem on committing for me too.

**Comment by npostavs** [comment] 2015-09-30 00:26
@Alexander-Shukaev Ah, that looks like #2246. Have you updated since it was fixed? What's the value of `magit-need-cygwin-noglob`? What does `(magit-cygwin-env-vars)` return?

---

@hitswint so which versions magit worked without having to do that?

**Comment by Alexander-Shukaev** [comment] 2015-09-30 00:33
```
magit-need-cygwin-noglob is a variable defined in `magit-process.el'.
Its value is t
```

```
("CYGWIN=noglob" "MSYS=noglob")
```

**Comment by npostavs** [comment] 2015-09-30 01:30
@Alexander-Shukaev oh right, the expression I told you to run doesn't include the fix, so of course it failed it like that. Try `magit-process-file`
```elisp
(with-output-to-string
  (with-current-buffer standard-output
    (magit-process-file magit-git-executable
                        nil '(t t) nil "show" "--no-patch" "--format=%h %s" "master^{commit}")))
```

**Comment by Alexander-Shukaev** [comment] 2015-09-30 13:10
```
"fatal: ambiguous argument '\"--format=%h %s\"': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
"
```

**Comment by johnmastro** [comment] 2015-09-30 17:33
On both my Linux box and my Cygwin box (using `process-file` directly, so without `"noglob"`):

```emacs-lisp
(with-output-to-string
  (with-current-buffer standard-output
    (process-file magit-git-executable
                  nil '(t t) nil "-c" "alias.echo=!echo" "echo" "'\"foo bar\"'")))
;=> "'\"foo bar\"'"
```

But then on my Cygwin box, using `magit-process-file` and thus `"noglob"`:

```emacs-lisp
(with-output-to-string
  (with-current-buffer standard-output
    (magit-process-file magit-git-executable
                        nil '(t t) nil "-c" "alias.echo=!echo" "echo" "'\"foo bar\"'")))
;=> "'foo bar'"
```

So it looks like `"noglob"` is causing the double quotes to be dropped from the arguments to `git`.

In #2246 I mentioned reading a [complaint about this](https://cygwin.com/ml/cygwin/2011-11/msg00225.html) from 2011, but I never actually encountered any problems and forgot about it. I wonder if it's the cause of the error here.

I don't think I'll be able to today, but I'll try to dig into this further tomorrow if no one beats me to it.

**Comment by npostavs** [comment] 2015-09-30 18:27
> So it looks like "noglob" is causing the double quotes to be dropped from the arguments to git.

But the error message that @Alexander-Shukaev reported seems to suggest that double quotes are *not* being dropped when they should be.

---

@johnmastro Does committing work on your Cygwin box? It seems like cygwin git passes a cygwin path to `GIT_EDITOR` which of course a win32 Emacs can't deal with. As far as I can tell, magit never dealt with this, so it's not a regression and cygwin-mount has always been required for this to work?

**Comment by johnmastro** [comment] 2015-09-30 19:28
@npostavs Ah, maybe I had it backwards. Yes, committing works fine, and I've never used cygwin-mount.

One thing that might be a bit different about my setup is that I use `/` as my Cygwin root, so my Cygwin path for git is `/bin/git.exe`, which Emacs translates to `c:/bin/git.exe` without a problem.

**Comment by npostavs** [comment] 2015-10-01 04:22
@Alexander-Shukaev What do you get from
```elisp
(let ((printf "c:/Tools/x64/MSYS2/usr/bin/printf.exe"))
  (with-output-to-string
    (with-current-buffer standard-output
      (let ((magit-need-cygwin-noglob t))
        (magit-process-file printf nil '(t t) nil
                            "[%s]" "a b" "x^{y}"))
      (let ((magit-need-cygwin-noglob nil))
        (magit-process-file printf nil '(t t) nil
                            "[%s]" "a b" "x^{y}")))))
```

---

> One thing that might be a bit different about my setup is that I use / as my Cygwin root, so my Cygwin path for git is /bin/git.exe, which Emacs translates to c:/bin/git.exe without a problem.

Ah, yeah, that would work.

I've pushed [np/cygwin-kludge2][1] to fix the committing issue for the case of `/cygdrive/c/foo/.git/COMMIT_EDITMSG` which is what happens with a normal (i.e. choosing default settings) cygwin install. 

@tarsius There's a bit of duplicated code from `magit-expand-git-file-name` to `git-commit.el`, is that better than having `git-commit` depend on `magit-git`?

[1]: https://github.com/magit/magit/compare/np/cygwin-kludge2

**Comment by Alexander-Shukaev** [comment] 2015-10-01 10:40
```
"[\"a b\"][x^{y}][a b][x^y]"
```

**Comment by npostavs** [comment] 2015-10-01 16:37
I get `"[a b][x^{y}][a b][x^y]"`. @Alexander-Shukaev I think your msys2 and/or your Emacs installation(s) is/are borked. To see which it might be interesting to repeat the experiment with the C program below (compiled in both mingw and msys modes) instead of `printf.exe`. But I don't think there is anything to be done on magit's end.

```c
#include <windows.h>
#include <stdio.h>

int main(int argc, char **argv)
{
    LPTSTR cmd  = GetCommandLine();
    printf("cmdline: %s\n", cmd);

    for (int i = 0; i < argc; i++) {
        printf("arg%d: %s\n", i, argv[i]);
    }
    return 0;
}
```

**Comment by Alexander-Shukaev** [comment] 2015-10-01 18:28
I don't believe that anything can be "broken"; it's all about the configuration.  Let's justify that based on further tests.  I'm also curious what's going on, and if you could give some brief insight into the topic, that would be great.

```
"cmdline: ... [%s] \"a b\" x^{y}
arg0: ...
arg1: [%s]
arg2: a b
arg3: x^{y}
cmdline: .. [%s] \"a b\" x^{y}
arg0: ...
arg1: [%s]
arg2: a b
arg3: x^{y}
"
```

**Comment by Alexander-Shukaev** [comment] 2015-10-01 18:32
I also want to mention that the Magit 2.2.2 from Marmalade has no issues at all.

**Comment by tarsius** [comment] 2015-10-01 18:45
> I don't believe that anything can be "broken"; it's all about the configuration. ... I also want to mention that the Magit 2.2.2 from Marmalade has no issues at all.

That sums it up pretty nicely. The problem is that Cygwin and friends allow configuring things that shouldn't be customizable - instead there should be an enforced convention which can be relied on. So the configuration used by one user causes issues for which we add a work around, which in turn causes issues given the configuration used by another user. It's an uphill battle.

That being said, I would not completely rule out that there is something broken on your system. Especially given #2258, which falls into the "I don't actually think this is possible, but since you see it happening I must be wrong about that" category.

**Comment by Alexander-Shukaev** [comment] 2015-10-01 19:23
With #2258 I eventually figured out what was the problem actually.  It was because Emacs was started through a custom wrapper executable (the purpose of which is to inject the needed environment variables which I don't want to be present globally, but only for Emacs).  Such Emacs invocation indirection caused the failure of abort recognition in terminal (though I still struggle to understand why since I ensured that this wrapper executable returns proper exit status code).  Hence, #2258 was really about configuration, though not an obvious one.  Both, this and the fact that Magit 2.2.2 works normally, give me hope that this is nothing but a configuration issue.

**Comment by tarsius** [comment] 2015-10-01 19:31
Yes, probably, just saying we shouldn't completely rule it out.

> Both, this and the fact that Magit 2.2.2 works normally, give me hope that this is nothing but a configuration issue.

There have indeed been some cygwin related changes since then. (Which apparently fall into the mentioned "one users fix is another users regression" category.) Have you bisected before? If not, this might be a good opportunity to learn how to do it ...

**Comment by tarsius** [comment] 2015-10-01 19:35
> There's a bit of duplicated code from `magit-expand-git-file-name` to `git-commit.el`, is that better than having `git-commit` depend on `magit-git`?

That's okay. And yes, for historic reasons we should try to keep `git-commit.el` usable without magit.

**Comment by npostavs** [comment] 2015-10-01 19:41
> I'm also curious what's going on, and if you could give some brief insight into the topic, that would be great.

The Windows kernel doesn't support multiple command line arguments, there is a single argument that gets parsed by the child process (typically in the libc startup code). So to pass an argument with spaces you actually need to put quotes around it, and the child process is responsible for removing the quotes (see [[1]] for more details).

The MSys runtime does some extra processing to implement some kind of globbing, such that `x{y}` becomes `xy` (and probably some other things, that magit happens not to hit (yet)). Setting the environment variable `MSYS=noglob` prevents this extra processing. But for your system it also prevents quote removal for other arguments; I can't reproduce this, and I have no idea why it happens.

That problem doesn't show in the output above because you compiled with the mingw compiler producing a native Windows binary; if you use msys/gcc I expect you'll see `arg2: \"a b\"` in the first case (though again, I have no idea why that is).

> Such Emacs invocation indirection caused the failure of abort recognition in terminal (though I still struggle to understand why since I ensured that this wrapper executable returns proper exit status code).

Did you wrap emacsclient as well? Can you post the wrapper?

[1]: http://www.daviddeley.com/autohotkey/parameters/parameters.htm

**Comment by npostavs** [comment] 2015-10-02 21:20
> I've pushed np/cygwin-kludge2 to fix the committing issue for the case of /cygdrive/c/foo/.git/COMMIT_EDITMSG which is what happens with a normal (i.e. choosing default settings) cygwin install.

I've now merged this to master.

**Comment by jasminpatry** [comment] 2015-10-03 07:10
@Alexander-Shukaev, the problem that you are having with quotes not getting stripped was addressed in this change: https://github.com/Alexpux/MSYS2-packages/commit/c1b58eb8c71b0e026bb82463183a51dce6ab8e8b . Maybe you need to update msys2?

I'm experiencing problems with magit 20151002.1948 running under MSYS2, but they're a bit different than the ones reported here.  I was previously running 20150911.1633 (with advice around magit-git-insert to add MSYS=noglob to process-environment) successfully.

When I run the following:
```
(let ((printf "c:/MSYS64/usr/bin/printf.exe"))
  (with-output-to-string
    (with-current-buffer standard-output
      (let ((magit-need-cygwin-noglob t))
        (magit-process-file printf nil '(t t) nil
                            "[%s]" "a b" "x^{y}"))
      (let ((magit-need-cygwin-noglob nil))
        (magit-process-file printf nil '(t t) nil
                            "[%s]" "a b" "x^{y}")))))
```
I get `"[a b][x^y][a b][x^y]"` -- so `magit-need-cygwin-noglob` doesn't seem to be working. When I run
```
(let ((printf "c:/MSYS64/usr/bin/printf.exe"))
  (with-output-to-string
    (with-current-buffer standard-output
      (progn
        (let ((process-environment (cons "MSYS=noglob" process-environment)))
          (process-file printf nil '(t t) nil
                        "[%s]" "a b" "x^{y}"))
        (process-file printf nil '(t t) nil
                      "[%s]" "a b" "x^{y}")))))
```
I get `"[a b][x^{y}][a b][x^y]"` -- as expected.

**Comment by npostavs** [comment] 2015-10-03 13:04
@jasminpatry: `magit-process-file` does basically nothing but the let-binding you showed in your working snippet, so this seems impossible. Maybe you have some stale elc files? What do you get from
```elisp
(list
 (let ((magit-need-cygwin-noglob t))
   (magit-cygwin-env-vars))
 (let ((magit-need-cygwin-noglob nil))
   (magit-cygwin-env-vars)))
```

**Comment by jasminpatry** [comment] 2015-10-03 16:27
I get this (`...` in place of a long string of ints):
```
((80 65 ... 105 110 "CYGWIN=noglob" "MSYS=noglob")
 (80 65 ... 105 110))
```
This appears to be because `magit-git-environment` is a string, not a list, but `magit-cygwin-env-vars` calls `append` on it.

**Comment by jasminpatry** [comment] 2015-10-03 17:51
Making `magit-git-environment` a list fixes my problems. I changed the relevant part of `magit-git-executable` to:

                       (setq magit-git-environment
                             (list (buffer-substring-no-properties
                                    (point) (line-end-position))))

**Comment by npostavs** [comment] 2015-10-03 18:14
> Making magit-git-environment a list fixes my problems.

Right, I dropped the list call and when testing I must been running some older code, sorry. Should be fixed now.

**Comment by Alexander-Shukaev** [comment] 2015-10-03 22:01
Sorry for being dumb, but what's the final remedy once again?  Update MSYS2?

**Comment by npostavs** [comment] 2015-10-03 22:39
> what's the final remedy once again? Update MSYS2?

Yes. Also if you update magit make sure it's not from yesterday, since I introduced a bug last night (fixed this morning).

**Comment by jasminpatry** [comment] 2015-10-03 23:27
Thanks @npostavs, seems to be working fine now.

**Comment by Alexander-Shukaev** [comment] 2015-10-05 22:39
Confirmed as well.  Thanks @johnmastro, @npostavs, @tarsius, @hitswint, @jasminpatry

**Comment by npostavs** [comment] 2015-10-05 23:05
Okay that's great news, I think we can call this solved then. :)

**Closed by npostavs** 2015-10-05 23:05 UTC
Labels: 00 bug windows
