### ISSUE TITLE
magit-remote-configure doesn't configure remotes other than 'origin'.

### ISSUE THREAD

**Issue by pietvo** [magit/magit#4582] opened 2022-01-15 20:38 UTC
> Please explain
 >    (1) what behavior you expected

M C (magit-remote-configure) should be able to configure my remote 'clone'.

 >   (2) what behavior you observed

M C displays the remote transient, and prompts for a remote. I type in 'clone' (without quotes), but it displays the variables of remote 'origin'.
However, I can get the variables for remote 'clone in these two ways:
1. C-u M-x magit-remote-configure RET. This prompts for the remote and then displays the proper variables.
2. M-: (magit-remote-configure "clone") RET. This displays (only the variables to this remote.

>    (3) and how we can reproduce the issue.

Open a git directory in dired; C-x g (magit-status), then M C

> Please include a backtrace in your report. 

no backtrace, because the is no emacs error (just wrong behaviour).

> Also post the output of:
>    M-x magit-version RET

Magit 20220115.1530 [>= 3.3.0], Git 2.34.1, Emacs 27.2, darwin
But also 3.3.0 does it wrong.

 >   $ cd /path/to/magit
 >   $ make emacs-Q

This gives the same behaviour

 >   M-x magit-emacs-Q-command RET

> to save a shell command to the `kill-ring` and the system's clip-board, which you can then copy into a shell to run.

This gives the same behaviour

> Finally, if that didn't work and you have installed Magit from Melpa, then run commands similar to the ones above, but use tab completion to replace the various Ns with the correct versions:

    $ cd ~/.emacs.d/elpa/magit-20220115.1530
    $ /Applications/Emacs.app/Contents/MacOS/Emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20210826.1149 -L ../git-commit-20220101.841 -L ../transient-20220112.1305 -L ../with-editor-20220107.1056 -L ../ghub-20220101.1019 -L ../magit-section-20220101.841 -L . -l magit 

Same behaviour

**Comment by tarsius** [comment] 2022-01-15 20:41
Duplicate of https://github.com/magit/transient/issues/187.

**Closed** 2022-01-15 20:41 UTC
Labels: duplicate

**Comment by tarsius** [comment] 2022-01-17 11:26
It's fixed now.
