### ISSUE TITLE
No textual/selectable full commit ID available

### ISSUE THREAD

**Issue by derek-upham** [magit/magit#2033] opened 2015-07-09 19:34 UTC
In the `*magit-log*` buffer for a project, select any commit.  Magit displays a `*magit-rev*` buffer with the commit details.  The details include the full commit ID, but that commit ID is displayed in a buffer header.  Can the `*magit-rev*` buffer also display the full commit ID in the buffer text, to allow for copying and pasting?

**Comment by kyleam** [comment] 2015-07-09 19:37
Press `M-w`.

**Comment by tarsius** [comment] 2015-07-09 19:47
I am actually considering putting it in the buffer *also*:

```
Commit 36b32e415eeacafc7fb14da2756332b0f9941b1f                     <-- the header line
36b32e415eeacafc7fb14da2756332b0f9941b1f                            <-- can be collapsed
References: master origin/master checkout-stage
Author:     Jonas Bernoulli <jonas@bernoul.li>
AuthorDate: Thu Jul 9 19:22:43 2015 +0200
Commit:     Jonas Bernoulli <jonas@bernoul.li>
CommitDate: Thu Jul 9 19:22:43 2015 +0200

    magit-ediff-compare--read-revisions: bugfix

...
```

Looks a bit strange but still. What do others think about this?

**Comment by npostavs** [comment] 2015-07-09 20:06
On the one hand, it does a look a bit strange, and it's not needed because `M-w` works fine. On the other hand, it's not really obvious that `M-w` does what you want unless you've actually read the docs; just copying text from the buffer is the simple and obvious of doing things...

I'm leaning towards putting it in the buffer, it's just the 1 extra line. Probably worth making things simpler.

**Comment by kyleam** [comment] 2015-07-09 20:10
Yeah, I think it's easiest just to insert it.

> I'm leaning towards putting it in the buffer, it's just the 1 extra line. Probably worth making things simpler.

Based on the snippet, it seems like it will replace the "…" under the header, so it's not even an extra line.

**Comment by tarsius** [comment] 2015-07-09 20:16
Oh and one other, slightly related, thing: When only the commit message summary line is being displayed, then one cannot tell whether that's because there's no body, or because it is collapsed. I am considering displaying the summary line in bold when there is a body. Just bold (like filenames) but not in color (like e.g. "Unstaged changes").

And the in-buffer hash should also be just bold. That would make it look a little less strange, but still indicate that it is a section heading.

Thoughts?

**Comment by tarsius** [comment] 2015-07-09 20:32
The reason the commit message is indented is that it comes out of Git like that. Is there any benefit to displaying it that way? If it were not indented, then it would be easier to copy the text. As a compromise `C-w` could be taught to copy without indentation.

**Comment by kyleam** [comment] 2015-07-09 20:44
Hmm, I think the indentation is nice visually for separating it from the other text  (though I guess that could be done other ways and mostly I'm probably just used to always seeing commit message indented).  I like the idea of C-w stripping the indentation (perhaps a prefix argument could be added to always fall back on the plain variant?).

**Comment by kyleam** [comment] 2015-07-09 20:47
> When only the commit message summary line is being displayed, then one cannot tell whether that's because there's no body, or because it is collapsed

What about adding a trailing "...", since a lot of Org users associate that with collapsed content?

**Comment by derek-upham** [comment] 2015-07-09 21:23
For me, `M-w` is `magit-copy-buffer-thing-as-kill`, and that command only ever seems to put the branch name in the kill ring.

It wouldn't work for my use case anyway.  At least half the time I want the commit ID in my clipboard, and ten years ago I deliberately broke the auto-sync between the kill ring and the clipboard.  It slowed down the kill operations during normal editing.  I ended up making a completely separate set of key bindings that work on plain text, hence my interest in having the full commit ID in plain text.

How about putting the short form of the ID in the header, and the long form in the buffer?  That won't look quite as strange.

```
Commit 36b32e4                                         <-- the header line
ID: 36b32e415eeacafc7fb14da2756332b0f9941b1f           <-- can be collapsed
References: master origin/master checkout-stage
Author:     Jonas Bernoulli <jonas@bernoul.li>
AuthorDate: Thu Jul 9 19:22:43 2015 +0200
Commit:     Jonas Bernoulli <jonas@bernoul.li>
CommitDate: Thu Jul 9 19:22:43 2015 +0200
```

**Comment by kyleam** [comment] 2015-07-09 21:30
> perhaps a prefix argument could be added to always fall back on the plain variant?

Nevermind, you could just select a region for that.

**Comment by madscientist** [comment] 2015-07-09 21:50
I vote for removing the indentation.  In txt output it's nice for differentiation but we can use some sort of faces for that and have it look much better.  And I have people committing (not using magit of course) with longer lines that wrap if they're indented but won't if they're not (when they type the line in the editor it's not indented...)  Not a huge deal but it is annoying to read.

**Comment by phil-s** [comment] 2015-07-09 23:59
> I am actually considering putting the hash in the buffer also:
> That looks a bit strange but still. What do others think about this?

Would it be crazy to dynamically add/remove the header depending on whether the first line of the buffer is visible? (using `pos-visible-in-window-p`). Then the header and the first line of the buffer could be the same content, but you could avoid having a visual duplicate.

Less tricky and perhaps more useful to users in general: Just add the text "(M-w to copy)" to the header?

**Comment by npostavs** [comment] 2015-07-10 04:39
> For me, M-w is magit-copy-buffer-thing-as-kill, and that command only ever seems to put the branch name in the kill ring.

Maybe you need to update magit? That should have been fixed in 8273c0e005f2947db726d0da41f1a5fca8a7cfcf (I just used `M-w` to copy that).

> At least half the time I want the commit ID in my clipboard, and ten years ago I deliberately broke the auto-sync between the kill ring and the clipboard. It slowed down the kill operations during normal editing. I ended up making a completely separate set of key bindings that work on plain text

You could add a key binding to transfer from the kill ring to clipboard explicitly.

> Would it be crazy to dynamically add/remove the header depending on whether the first line of the buffer is visible?

I suspect seeing the add/remove would be annoying. Like how I also find it annoying when the minibuffer changes size.

**Comment by tarsius** [comment] 2015-07-10 07:16
> Would it be crazy to dynamically add/remove the header depending on whether the first line of the buffer is visible?

Like in web browsers? Many people seem to hate it there. I don't, I think it is lovely.

Regardless, it's risky to do this here, because the first line isn't just any odd line, it's the heading of the other header lines that follow. So probably not.

> Less tricky and perhaps more useful to users in general: Just add the text "(M-w to copy)" to the header?

Maybe. I wouldn't really want to look at that myself all the time.

**Comment by tarsius** [comment] 2015-07-10 07:23
> What about adding a trailing "...", since a lot of Org users associate that with collapsed content?

I have tried to do that in the past, but we cannot do that, at least not as easily as Org. The problem is that Org hides the body by hiding starting with the newline at the end of the heading to right before the newline at the end of the body, while Magit hides the other newline. Org can use an Emacs feature to insert the "..." but the way Magit hides the body this does not work.

**Comment by tarsius** [comment] 2015-07-10 08:18
> Would it be crazy to dynamically add/remove the header depending on whether the first line of the buffer is visible?

I have started working on this: #2036.

**Comment by tarsius** [comment] 2015-07-10 09:30
I have also started working on not indenting the commentary and making the summary stick out if there's a body, but only then. See #2037.

But the existing code being modified here is so wacky, that really has to be fixed first. So this only serves to demonstrate what making these changes would look like.

**Comment by tarsius** [comment] 2015-07-10 09:30
Lets continue this discussions on these pr's.

**Closed by tarsius** 2015-07-10 09:30 UTC
Labels: 30 support, discussion
