### ISSUE TITLE
Error when trying to delete a branch

### ISSUE THREAD

**Issue by joncol** [magit/magit#3366] opened 2018-02-06 12:40 UTC
Expected behavior: the branch should be deleted.

Actual behavior: Error message: `user-error: nil is ambiguous.  Please cleanup using git directly.`

This happens when trying to delete a local branch in any repository, using the keyboard commands `b k` from `magit-status`.

`magit-version`: `Magit 20180205.311, Git 2.16.1, Emacs 26.0.90, gnu/linux`

**Comment by tarsius** [comment] 2018-02-06 12:41
Duplicate of #3364.

**Closed by tarsius** 2018-02-06 12:41 UTC
