### ISSUE TITLE
Ambiguous parent relationship in `magit-log`

### ISSUE THREAD

**Issue by svenssonaxel** [magit/magit#4545] opened 2021-11-19 17:47 UTC
(1) **Expected**:

Invoking `magit-list` with all references using `l a` shows two commits with an empty line between them to indicate those two commits do not have a parent/child relationship:
```
bb9608d * 2/master 2

b4d5f71 * master 1
```

(2) **Observed**:
Invoking `magit-list` with all references using `l a` shows two commits in such a way that they look like one is the parent of the other:
```
bb9608d * 2/master 2
b4d5f71 * master 1
```

(3) **Steps to reproduce**:
```
mkdir reproduce-magit-ambiguous-parent
cd reproduce-magit-ambiguous-parent
git init
echo 1 > 1
git add 1
git commit -m 1
mkdir 2
cd 2
git init
echo 2 > 2
git add 2
git commit -m 2
cd ..
git remote add 2 2
git fetch --all
```

Also reproducible with `magit-emacs-Q-command`

*M-x magit-version RET*:

```
Magit v3.2.1-75-gf53148a5, Git 2.30.2, Emacs 27.1, gnu/linux
```

**Motivation for why this is important**:

You might think that this is a contrived example and that this bug won't manifest in the wild. Not so; this behavior has confused me more than once in the wild. People merge unrelated histories despite gits attempt at refusing to do so. Others keep documentation in a separate branch in the same repository with history that is unrelated to other branches. Think what you will about those practices, but they are not uncommon, and I don't see a downside in fixing this in magit beyond the effort to do so.

**Comment by kyleam** [comment] 2021-11-19 23:55
This looks like a duplicate of #3602, which was closed after noting the issue in #2989.

Another path forward, with potential for wider benefit, is to improve the rendering on git's end.  Some related threads:

* https://lore.kernel.org/git/xmqqbo0be0hc.fsf_-_@gitster.dls.corp.google.com/T/#u
* https://lore.kernel.org/git/20140709065145.GB14682@sigill.intra.peff.net/T/#u

**Closed** 2021-12-01 13:12 UTC
Labels: duplicate
