### ISSUE TITLE
Empty status buffer but git status reports changes

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3400] opened 2018-03-22 14:57 UTC
The magit status buffer shows that there is no unstaged changes but refuses to rebase because there are un-commited changes. `git status` agrees that 2 files have been modified. I closed and reopened the magit status buffer but this won't solve the issue.

```
Magit 2.11.0-600-g254d5778, Git 2.14.3, Emacs 26.0.91, gnu/linux
```

I have no clue how to reproduce. This already happened once last month. I haven't tried to run with `Emacs -Q` or similar because the bug happens so infrequently.

**Comment by npostavs** [comment] 2018-03-22 15:08
> `git status` agrees that 2 files have been modified.

What does `git diff` say? Perhaps the line endings have changed?

**Comment by DamienCassou** [comment] 2018-03-22 16:11
Noam Postavsky <notifications@github.com> writes:
>> `git status` agrees that 2 files have been modified.
>
> What does `git diff` say? Perhaps the line endings have changed?


when I tried to git add the modified files, I got a message about line
endings but nothing to commit. You are most probably right.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tarsius** [comment] 2018-03-29 01:39
I also think that the issue is that someone committed line endings that don't conform to what the configuration says they should be. This causes git commands to disagree about whether there are changes, so its not an issue that is exclusive to magit. It might be a bit unfortunate that there is no indication at all in the status buffer that such an issue, but because this is a rather rare issue and because I don't have an idea what magit could do here I am closing this.

**Closed by tarsius** 2018-03-29 01:39 UTC
Labels: ., wontfix
