### ISSUE TITLE
Staging with wrong line number

### ISSUE THREAD

**Issue by svenssonaxel** [magit/magit#3924] opened 2019-07-23 23:44 UTC
Version info: Magit 2.90.1, Git 2.20.1, Emacs 26.1, gnu/linux

* Steps to reproduce:
1. Create a file with the following contents (including a newline after the last line):
line1
line2
line3
2. Commit the file
3. Edit the file to have the following contents:
line1
add1
line2
add2
line3
4. Run magit-status
5. Run magit-diff-less-context repeatedly until diffs show with no context.
6. Stage the following diff using magit-stage:
@@ -2,0 +4 @@ line2
+add2

* Expected:
7. The magit-status buffer contains only one unstaged change; the one including add1.
8. The output of ‘git diff --cached’ shows the following staged change:
@@ -1,3 +1,4 @@
 line1
 line2
+add2
 line3

* Actual:
7. The magit-status buffer contains three unstaged changes.
8. The output of ‘git diff --cached’ shows the following staged change:
@@ -1,3 +1,4 @@
 line1
 line2
 line3
+add2

**Comment by kyleam** [comment] 2019-07-24 00:33
When there are no context lines, the function responsible for staging the hunk, `magit-apply-patch`, calls `git apply` with `--unidiff-zero`:

```
--unidiff-zero
    By default, git apply expects that the patch being applied is a
    unified diff with at least one line of context. This provides good
    safety measures, but breaks down when applying a diff generated
    with --unified=0. To bypass these checks use --unidiff-zero.

    Note, for the reasons stated above usage of context-free patches
    is discouraged.
```

I suspect the weirdness you're describing (confirmed on my end) is something that we'll have a hard time avoiding when applying context-free patches.  Note that you can keep the context that `apply` needs but still stage just the "add2" line by selecting it before calling `magit-stage`.

**Comment by tarsius** [comment] 2019-07-25 19:33
I'll file this under "not great but expected".

**Comment by svenssonaxel** [comment] 2019-07-27 19:12
I agree that it's not great, but I don't think it's expected. Let me show why I think so:

1. Create a file with the following contents (13 lines containing "line", including a newline after the last line):
   line
   line
   line
   line
   line
   line
   line
   line
   line
   line
   line
   line
   line

2. Commit the file
3. Edit the file to have the following contents:

   line
   line
   line
   ADD1
   line
   line
   line
   line
   line
   line
   line
   ADD2
   line
   line
   line

4. Run magit-status
5. Set the number of context lines to 3
6. Stage the diff containint "ADD2".

This also exhibits the "not great" behaviour, but **git CLI does not**:
1. Unstage the "ADD2" diff to return to the state in step 4 above.
2. Run `git add --patch`.
3. Answer no to staging the "ADD1" patch
4. Answer yes to staging the "ADD2" patch.
5. Run magit-status.

What is now staged is what I would call the right thing, and different from the "not great" magit behaviour. I believe it is expected that staging a chunk in magit should parrot the good behaviour of staging a chunk with `git add --patch`.

**Comment by npostavs** [comment] 2019-07-27 19:32
>     5\. Set the number of context lines to 3

Did you mean "... to 0" here? If not, then I can't reproduce the problem.

If you did mean 0 context lines, then I don't understand the difference from the initial example. And I don't understand the relevance of `git add --patch`, since it seems to show 3 context lines, not 0.

For reference, steps 1..3 as a shell script:

```sh
git init
yes line | head -n 13 > lines.txt
git add lines.txt 
git commit -m 'initial 13 "lines"'
sed -i -e '3aADD1' -e '10aADD2' lines.txt
```

**Comment by svenssonaxel** [comment] 2019-07-27 20:26
> Did you mean "... to 0" here? If not, then I can't reproduce the problem.

Sorry, my bad. I meant 3, but the reproducing example needs correcting:

```shell
git init
yes line | head -n 17 > lines.txt
git add lines.txt 
git commit -m 'initial 17 "lines"'
sed -i -e '4aADD1' -e '12aADD2' lines.txt
```

**Comment by npostavs** [comment] 2019-07-27 20:32
Okay, I see what you mean with the correct example.

**Comment by svenssonaxel** [comment] 2019-07-27 20:45
I believe it might be fairly doable to fix it.

magit-apply-patch would have to

- parse the chunk headers of the form `@@ -oldstart,oldlen +newstart,newlen @@...`
- calculate sum(newlen-oldlen) for all patches appearing in the same file and before the one being applied
- subtract the result from newstart before applying (which I assume is done with `git apply --cached`).

I assume this is what `git add --patch` is doing (more precely, the sum would be calculated for the non-applied patches appearing before in the same file, but if magit updates the view after every patch application, then all of them would be non-applied).

**Comment by kyleam** [comment] 2019-07-28 04:07
@svenssonaxel OK, thanks for the example that doesn't involve `--unidiff-zero`.

**Comment by svenssonaxel** [comment] 2019-07-28 10:47
OK, so I just realized there's an even easier fix:

When the chunk to be staged comes from an up-to-date diff (which should be the case for `magit-stage`), it's enough to replace `newstart` with `oldstart`. This should have the same effect as the calculation I described above. No need to iterate over preceding chunks. In the example above, `@@ -10,6 +11,7 @@ line` becomes `@@ -10,6 +10,7 @@ line`.

**Comment by kyleam** [comment] 2019-07-29 02:36
@svenssonaxel Please try out the patch from #3927.  It should address your second case, but it still doesn't lead to the intended staged content in the initial context-free  `--unidiff-zero` case.  For that one, I'll fall back to my initial statement that I suspect there's not much more we can do there, but pushback on that is of course welcome.

**Comment by svenssonaxel** [comment] 2019-07-29 09:27
> @svenssonaxel Please try out the patch from #3927. It should address your second case, but it still doesn't lead to the intended staged content in the initial context-free `--unidiff-zero` case.

Confirmed. I'm unable to trigger any unintended behaviour using your patch and at least one context line. Good work!

> For that one, I'll fall back to my initial statement that I suspect there's not much more we can do there, but pushback on that is of course welcome.

I think I've found something here, but it's still a bit of a mystery. It appears that both `diff` and `git diff` will mess up the hunk headers when provided the `-U0` option for no context lines. I'm not saying this is a bug in `diff`, but it sure seems inconsistent and unintended to me. Specifically, `oldstart` seems to be off by one when there are no context lines and `newlen` is missing when it equals 1.

Anyway, it seems that `git patch` behaves in the intended way (at least the way I would expect, which is inconsistent with `diff -U0`), so by altering your calculation just a bit, I think staging for no-context hunks could be fixed. Specifically,

 1. In the case of zero context lines, increase `oldstart` by one before staging and before calculating offset.
 2. Make sure to be able to parse a hunk header with `newlen` missing, e.g. `@@ -2,0 +3 @@ line`. A missing `newlen` defaults to 1.

Let's take the original example:

```
git init
yes line | head -n 3 > lines.txt
git add lines.txt 
git commit -m 'initial 3 lines'
sed -i -e '1aADD1' -e '2aADD2' lines.txt
```

Now, using zero context lines, there are two hunks, both of which have 1 added line, 0 removed and 0 context lines. The second hunk is displayed by `git diff` and `magit-status` as:

```
@@ -2,0 +4 @@ line
+ADD2
```

Increasing `oldstart` by one and then calculate the offset as before (in this case it's 4-3=1), we can apply the second hunk:

```
git apply --cached --unidiff-zero <<EOF
--- a/lines.txt
+++ b/lines.txt
@@ -3,0 +3,1 @@ line
+ADD2
EOF
```

Adding `newlen` as  `,1` seems to be allowed but not required.

For some reason, magit-discard and magit-unstage already works. I have no idea why.

**Comment by kyleam** [comment] 2019-07-29 13:32
Thanks for digging and providing the details.

Stepping back, I wonder whether doing any amount of hunk adjustment is worth the complication for the context-free case.  `magit-apply-region` already aborts if there is no context, telling the user to increase it.  The --unidiff-zero bit that is now in `magit-apply-patch` has existed in one form or another since e66d174f6 (Allow smaller or larger hunks when diffing, 2009-02-12), but I'd guess that this functionality isn't a regular part of anybody's workflow and that making `magit-apply-patch` abort too would be fine.

**Comment by svenssonaxel** [comment] 2019-07-29 14:34
Right. I agree that either a fix or abort logic should be added for --unidiff-zero, but I don't have any strong opinion on which one.

The only thing I've used it for is like a poor man's hunk split. I do think that a (barely) related issue would be a feature request to add hunk splitting and editing. Right now I find myself sometimes falling back to `git add --patch` since (as far as I can tell) this is not present in magit. Is it on the roadmap?

**Comment by npostavs** [comment] 2019-07-29 14:55
> The only thing I've used it for is like a poor man's hunk split.

It sounds like you're unaware of the region support. Try <kbd>C-SPC</kbd> to start selecting the part of the hunk you want to stage.

https://magit.vc/manual/magit/The-hunk_002dinternal-region.html

**Comment by kyleam** [comment] 2019-07-29 16:20
> Try C-SPC to start selecting the part of the hunk you want to stage.

And when that won't do, you can try `magit-ediff-stage`.  There's some related discussion in #2718.

**Comment by svenssonaxel** [comment] 2019-07-30 12:28
> It sounds like you're unaware of the region support. Try C-SPC to start selecting the part of the hunk you want to stage.

That's brilliant! Yes, I was unaware that regions could be part of a hunk, I thought it was limited to several whole hunks. Thanks a ton!

> And when that won't do, you can try `magit-ediff-stage`. There's some related discussion in #2718.

Thank you, works like a charm! Don't know how I missed it when magit-ediff-dwim is bound to e.

--------------------

Anyways, so what about this issue? As I see it, we have two options:

 1. Use @kyleam's patch and add logic to abort staging when there are zero context lines.
 2. Alter @kyleam's patch to correctly handle the case with zero context lines.

**Comment by kyleam** [comment] 2019-07-30 12:54
> Anyways, so what about this issue? As I see it, we have two options:
> 
>     1. Use @kyleam's patch and add logic to abort staging when there are zero context lines.
> 
>     2. Alter @kyleam's patch to correctly handle the case with zero context lines.

I plan to go with 1.  I won't get around to adding the abort logic until tomorrow, which from my POV is fine because it gives people time to object.  If  #3927 is still open, I can add it there, but I don't see any issue with pushing the abort logic commit separately.  With that commit, I'll close this issue.

**Closed** 2019-08-02 05:09 UTC
Labels: bug
