### ISSUE TITLE
magit-status conflicts with global-whitespace-mode if status buffer already open

### ISSUE THREAD

**Issue by chaosite** [magit/magit#4766] opened 2022-09-20 11:04 UTC
Running current Debian emacs-snapshot (20220912+emacs-28.1.91-158879-g1c13ecae662-1), `magit-version` gives:

    Magit 20220919.1308 [>= 3.3.0-git], Git 2.37.2, Emacs 29.0.50, gnu/linux

**To reproduce:**
1) Have `global-whitespace-mode` enabled
2) Open `magit-status`, this should work fine
3) Close (not kill) the `magit-status` buffer, for example using the `q` keybinding
4) Try to open `magit-status` again

**Expected behavior:**
The `magit-status` buffer should pop back up.

**Actual behavior:**
Emacs displays a "Buffer is read only" message, `magit-status` buffer stays hidden.

**Additional notes:**
This also breaks commits, the git command gets a read only buffer warning and can't get the commit message

**Workarounds:**
1. Disable `global-whitespace-mode`
2. [Disable `global-whitespace-mode` only for magit buffers](https://emacs.stackexchange.com/a/38778), as in #3374

**Comment by kyleam** [comment] 2022-09-25 07:13
This issue starts with Emacs's f47a5324f44 (whitespace: Redo BoB/EoB empty line highlighting, 2022-09-11).

I'm out of time tonight to look into it more, but I'd say good next steps would be

  1) pinpoint the specific part of f47a5324f44 that causes it

  2) if it seems like the problem isn't on Magit's side, create a minimal reproducer of the issue that doesn't involve Magit and report it upstream

**Comment by kyleam** [comment] 2022-09-25 23:31
Bug filed upstream: https://debbugs.gnu.org/58082 (<87mtan11ss.fsf@kyleam.com>)

**Comment by kyleam** [comment] 2022-09-26 22:54
Fixed by Emacs's 53af11a2812 (Fix whitespace-mode in read-only buffers, 2022-09-26).

**Closed by kyleam** 2022-09-26 22:54 UTC
Labels: bug emacs
