### ISSUE TITLE
Commit missing from rebase listing of commits; causes removal of commit

### ISSUE THREAD

**Issue by rswgnu** [magit/magit#3289] opened 2017-11-29 22:54 UTC
I count 20 commits down to the one I want to rebase to.  I then try to do an interactive rebase in magit and the listing produced includes only 19 of the commits.  This is from a master branch with all commits pushed to the remote master just FYI.

If I rebase then, as expected, the missing commit is lost.

I am unsure how you can reproduce this unless it happens in all cases in which case many people would probably be pointing it out.  If you let me know some simple things I can look into, I will.

I am using Magit 20171127.435.  The problem exists if I start with 'emacs -Q' as well.

**Comment by tarsius** [comment] 2017-11-29 23:05
> I then try to do an interactive rebase in magit

There are multiple ways of doing that. Please specify the used key sequence exactly.

**Comment by rswgnu** [comment] 2017-11-30 00:11
On Wed, Nov 29, 2017 at 6:05 PM, Jonas Bernoulli <notifications@github.com>
wrote:

> I then try to do an interactive rebase in magit
>
> There are multiple ways of doing that. Please specify the used key
> sequence exactly.
>

​I used 'r' for rebase followed by 'i' for interactive.

**Comment by kyleam** [comment] 2017-11-30 03:38
> I am unsure how you can reproduce this

Can you point to a public repo and a commit range that triggers the
issue for you?

**Comment by phil-s** [comment] 2017-12-03 10:36
rswgnu: Can you confirm that you see *different* behaviour using `git rebase -i REF^` for the REF in question?

**Comment by rswgnu** [comment] 2017-12-04 15:30
On Sun, Dec 3, 2017 at 5:36 AM, phil-s <notifications@github.com> wrote:

> rswgnu: Can you confirm that you see *different* behaviour using git
> rebase -i REF^ for the REF in question?
>

​I do not see a difference other than the rebase listing within magit
includes the REF my cursor was on when I asked to rebase and the
command-line invocation does not include it (presumably because I told it I
want to use that as the picked commit for rebasing).  This is true whether
I add the -i option in the magit rebase or just do 'r i' in magit.

So, I would just look into how to add committer names to the rebase listing
if possible and ignore my issue about the missing commit in the rebase
listing.

Bob

**Comment by phil-s** [comment] 2017-12-04 21:40
> the rebase listing within magit includes the REF my cursor was on when I asked to rebase and the command-line invocation does not include it

The `^` suffix is important. If you used that (as Magit does behind the scenes), then you ought to see the same set of commits in the listing.

**Comment by tarsius** [comment] 2017-12-07 11:25
> I count 20 commits down to the one I want to rebase to. I then try to do an interactive rebase in magit and the listing produced includes only 19 of the commits.

In Git you have to select the commit *before* those that are to be rebased.
In Magit you select the first commit to be rebased.

This apparently surprised you, but I think it makes a lot of sense.

> If I rebase then, as expected, the missing commit is lost.

I very much doubt that. And you haven't really responded to the requests to try to reproduce it. I am going to assume that you were wrong about this and close this.

**Closed by tarsius** 2017-12-07 11:25 UTC
Labels: unconfirmed

**Comment by rswgnu** [comment] 2017-12-07 13:18
On Thu, Dec 7, 2017 at 6:25 AM, Jonas Bernoulli <notifications@github.com>
wrote:

> I count 20 commits down to the one I want to rebase to. I then try to do
> an interactive rebase in magit and the listing produced includes only 19 of
> the commits.
>
> In Git you have to select the commit *before* those that are to be
> rebased.
> In Magit you select the first commit to be rebased.
>
​That was not the issue I saw; it was a commit within the list, not at the
beginning or the end that was missing in magit.
But as you said, I had no good way to reproduce it with other data, so I
suggested you drop this issue as you have just done.
​
​

**Comment by shaktals** [comment] 2020-05-15 18:01
I just found something similar, but I'm now using Magit, so it seems to be an issue with git itself.

**Comment by kyleam** [comment] 2020-05-15 21:46
@shaktals I think it's hard to say much based on that information, but if you're using Git 2.26.{0,1,2} and recently starting noticing issues, it's worth checking whether you still see them after you set `rebase.backend` to `apply`.  Git 2.26 changed the default for `rebase.backend` from `apply` to `merge`.

**Comment by shaktals** [comment] 2020-05-19 01:30
Hi @kyleam! Sorry for the misunderstanding, there was a typo in my comment. I'm NOT using `Magit`, so I am sure the issue is with git itself, just wanted to register. Thanks anyway!

**Comment by Muriel-Salvan** [comment] 2020-06-01 17:37
Hi
I also got this issue, using git version 2.11.0 directly through CLI (git rebase -i <base_branch>).
The commit that was missing from the list was having a comment which I frequently use ("Typo") in some commits of my branches.
I don't know if it's relevant for the investigation, but for sure several other commits having the same comment were already present in the base branch.
Unfortunately the repo on which it happened is not public.
