### ISSUE TITLE
magit-commit-add-log broken

### ISSUE THREAD

**Issue by thierryvolpiatto** [magit/magit#2981] opened 2017-02-01 08:13 UTC
Now when commiting a change in file "foo.el" in the function `my-function', this command adds in commit:

* .git/foo.el:

instead of 

* foo.el (my-function):

magit-version:

Magit 2.10.1, Git 2.11.0, Emacs 24.5.1, gnu/linux

Thanks.

**Comment by tarsius** [comment] 2017-02-01 10:30
I cannot reproduce this. Can you reproduce it using a new repository that doesn't involve any symlinks whatsoever?

> Now [...]

Are you saying this is a regression? This code wasn't touched in over a year. If there is a regression, then that would likely be due to some change involving `magit-diff-visit-file`, that was modified in October.

**Comment by thierryvolpiatto** [comment] 2017-02-01 19:18
Jonas Bernoulli <notifications@github.com> writes:

> I cannot reproduce this. Can you reproduce it using a new repository
> that doesn't involve any symlinks whatsoever?

There is no symlinks here, this is helm where I use about the same magit
commands since months.

> Are you saying this is a regression?

Yes, since last update from melpa-stable.


> This code wasn't touched in over a year. If there is a regression,
> then that would likely be due to some change involving
> magit-diff-visit-file, that was modified in October.

Perhaps, don't know (yet), I will investigate more tomorrow and tell you.

Thanks.


--
Thierry

**Comment by kyleam** [comment] 2017-02-01 19:50
I can reproduce it.  It's caused by 9e0e2a24 (While committing, diff from inside gitdir if necessary, 2017-01-17).  #2963

**Comment by alezost** [comment] 2017-02-01 19:50
I experience a similar problem, and I'm pretty sure it was introduced by 9e0e2a24f25013ab92c20a75134f05d5daabd225.  Particularly, when I comment the line https://github.com/magit/magit/blob/master/lisp/magit-commit.el#L334 (setting `magit-toplevel--force-fallback-to-gitdir` to t) it works again.

The problem is that `default-directory` of *magit-diff* buffer is now `<repo>/.git/` while previously it was `<repo>/`, so when I try to commit the changes in `packages/foo` file I get the following error:

    Setting current directory: No such file or directory, <my-git-tree>/.git/packages/

**Comment by kyleam** [comment] 2017-02-01 23:10
No simple solutions are jumping out at me.

Assuming others don't see an obvious fix, I wonder if the best option
at this point would be to

1. revert 9e0e2a2

2. document that those who use `--separate-git-dir` with `git init` or
   `git clone` should manually set `core.worktree`, as @tarsius
   suggested in #2963

3. ask the Git mailing list if `core.worktree` should be set when
   `--separate-git-dir` is used

If we find out that Git has a reason for not setting `core.worktree`,
we can go back to coming up with a workaround.

While 2 isn't ideal, I think the number of users that regularly set up
a directory with `--separate-git-dir` is likely to be small compared
to those that may visit a diff while committing or that call
`magit-commit-add-log`.  Also, it only needs to be fixed once per
repo.

------------------------------------------------------------------------

It's worth noting that `magit-diff-while-committing` (`C-c C-d`)
doesn't let-bind `magit-toplevel--force-fallback-to-gitdir`, meaning
that it doesn't have the issue reported here but it does have the
problem reported in #2955.

**Comment by kyleam** [comment] 2017-02-02 04:02
> ask the Git mailing list if core.worktree should be set when
> --separate-git-dir is used

I've sent a message about this:
https://public-inbox.org/git/87h94d8cwi.fsf@kyleam.com/T/#u

It seems that `git init --separate-git-dir` used to set
`core.worktree`.  The behavior changed after v2.8.4.

**Comment by thierryvolpiatto** [comment] 2017-02-02 05:44
Setting `magit-toplevel--force-fallback-to-gitdir` to non-nil send the correct filename (foo and not .git/foo) but the function is not added and a buffer .git/foo<2> is created.

**Comment by thierryvolpiatto** [comment] 2017-02-02 06:32
I have installed from git and reverted to e346889a, it is now working
again.

-- 
Thierry

**Comment by kyleam** [comment] 2017-02-04 23:55
> It seems that git init --separate-git-dir used to set
> core.worktree. The behavior changed after v2.8.4.

Which is also reflected in [this 2014 comment] by @tarsius.

But it turns out that `git init --separate-git-dir` setting
`core.worktree` was not by design.

@tarsius I'd prefer to revert 9e0e2a24 for the time being while we
figure out how to handle the --separate-git-dir case.  What do you
think?

[this 2014 comment]: https://github.com/magit/magit/issues/460#issuecomment-36035787

**Comment by tarsius** [comment] 2017-02-04 23:57
Yes, let's do that.

**Closed** 2017-02-05 00:27 UTC
Labels: bug

**Comment by thierryvolpiatto** [comment] 2017-02-05 07:23
Thanks.
