### ISSUE TITLE
a bad gitconfig causes magit to say "not in git repository"

### ISSUE THREAD

**Issue by verhovsky** [magit/magit#4337] opened 2021-03-02 01:00 UTC
I manage my config files with git. My `~/.gitconfig` is a symlink to `~/dotfiles/gitconfig` and `~/dotfiles` is a git repo. I unstashed some changes in my dotfiles that had a merge conflict in my `gitconfig` file, so basically I had `~/.gitconfig` looking something like

```
[color "status"]
<<<<<<< Updated upstream
	added = yellow
=======
	added = green
>>>>>>> Stashed changes
```

Which is an invalid `gitconfig` file. I was still in the magit window for this repo and if I tried any commands like `b b`, magit says `Not inside Git repository` which made it sound like I might've deleted `.git` in my dotfiles repo. Trying to open any hunks also didn't work. When I tried `SPC g g` (doom emacs for `magit-status`) it asks what directory the git repo is in.

Running `git status` from the command line gives a much more sensible error message:

```
$ git status
fatal: bad config line 121 in file /home/boris/.gitconfig
```

It would be better for magit to propogate that error.

PS. I decided halfway through typing this that this isn't a bug but more of a design request, and when I clicked "If this doesn’t look right, choose a different type." it cleared what I typed already.

**Comment by kyleam** [comment] 2021-03-02 03:08
> It would be better for magit to propogate that error.

While I don't disagree, but I don't really see a realistic path forward for making `magit-toplevel` handle corrupt configuration in a more helpful way.  This is a heavily used code path, non-zero exits and stderr happen with regular operation, and, even if inspecting the error code was considered an acceptable cost, the code doesn't distinguish the corrupt config case.

```
not-a-git-repo$ git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
not-a-git-repo$ echo $?
128

a-git-repo-with-corrupt-config$ git rev-parse --show-toplevel
fatal: bad config line 8 in file .git/config             
a-git-repo-with-corrupt-config$ echo $?
128
```

**Comment by kyleam** [comment] 2021-03-11 02:44
Closing, but of course please feel free to continue the discussion.

**Comment by Atemu** [comment] 2021-03-31 17:32
When Magit comes across a dir that it cannot determine to be a git repo (which should be a *very* rare occurance under normal circumstances) it could run those git commands a second time but with user's git config ignored ([this seems to be the only way](https://stackoverflow.com/questions/23400449/how-to-make-git-temporarily-ignore-gitconfig)).  
If the git commands work without the user config, the config must be broken. It could then also trigger a check for the bad config error message to make sure.

Like many people, I use git for my dotfiles and this has bitten me before.  
I think magit should at the very least tell the user about the possibility of a broken config when it can't detect a git repo.

**Comment by Atemu** [comment] 2021-03-31 17:40
Oh, just realised there's a much simpler solution:  
Whenever magit thinks it's outside a git repo, run a bad config check and report that instead if it's bad.

**Comment by kyleam** [comment] 2021-04-04 23:07
Thanks for chiming in.

There are enough spots in the code base that handle the `magit-toplevel` nil case that, looking at this again, I still reach my assessment from above: I don't think it's worth making `magit-toplevel` check for a corrupt config (which, at least for a good number of users, happens very rarely if ever).

Outside of `magit-toplevel`, perhaps something like below would be sufficient.

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index bc9eef27..ddc01f70 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -746,13 +746,25 @@ (defmacro magit-with-toplevel (&rest body)
          (magit--not-inside-repository-error)))))
 
 (define-error 'magit-outside-git-repo "Not inside Git repository")
+(define-error 'magit-corrupt-git-config "Corrupt Git configuration")
 (define-error 'magit-git-executable-not-found
   "Git executable cannot be found (see https://magit.vc/goto/e6a78ed2)")
 
+(defun magit--assert-usable-git ()
+  (if (not (executable-find magit-git-executable))
+      (signal 'magit-git-executable-not-found magit-git-executable)
+    (let ((magit-git-debug
+           (lambda (err)
+             (signal 'magit-corrupt-git-config
+                     (format "%s: %s" default-directory err)))))
+      ;; This should always succeed unless there's a corrupt config (or
+      ;; at least a similarly severe failing state).
+      (magit-git-string "config" "--default=_" "core.bare"))
+    nil))
+
 (defun magit--not-inside-repository-error ()
-  (if (executable-find magit-git-executable)
-      (signal 'magit-outside-git-repo default-directory)
-    (signal 'magit-git-executable-not-found magit-git-executable)))
+  (magit--assert-usable-git)
+  (signal 'magit-outside-git-repo default-directory))
 
 (defun magit-inside-gitdir-p (&optional noerror)
   "Return t if `default-directory' is below the repository directory.
diff --git a/lisp/magit-status.el b/lisp/magit-status.el
index 99ab8f68..de896031 100644
--- a/lisp/magit-status.el
+++ b/lisp/magit-status.el
@@ -266,8 +266,10 @@ (defun magit-status (&optional directory cache)
   (interactive
    (let ((magit--refresh-cache (list (cons 0 0))))
      (list (and (or current-prefix-arg (not (magit-toplevel)))
-                (magit-read-repository
-                 (>= (prefix-numeric-value current-prefix-arg) 16)))
+                (progn
+                  (magit--assert-usable-git)
+                  (magit-read-repository
+                   (>= (prefix-numeric-value current-prefix-arg) 16))))
            magit--refresh-cache)))
   (let ((magit--refresh-cache (or cache (list (cons 0 0)))))
     (if directory
```

**Comment by tarsius** [comment] 2021-04-05 09:03
Looks reasonable. :+1:

**Closed** 2021-04-06 04:55 UTC
Labels: wontfix

**Comment by plumenator** [comment] 2021-04-19 01:05
I think this might have unintentionally caused a regression? Now I get a "Corrupt Git configuration" where I would expect a  "not in git repository". For example, in an empty directory.

**Comment by kyleam** [comment] 2021-04-19 01:21
>Now I get a "Corrupt Git configuration" where I would expect a "not in git repository". For example, in an empty directory.

Trying a few things, I haven't been able to trigger it.  

> Not sure if it's related, but it might also have broken C-u C-x g (the scanning of `magit-repository-directories`)

I usually leave `magit-repository-directories` at a non-nil value, so perhaps I'm missing something, but populating it with a few items, `C-u <magit-status>` works okay on my end.

Could you open a dedicated issue with complete recipes to trigger the problems?

Thanks.

**Comment by plumenator** [comment] 2021-04-20 15:28
Opened #4365

**Comment by createyourpersonalaccount** [comment] 2025-10-03 07:31
This may be unrelated but I will document how I encountered this error and what my fix was.

On Codeberg.org, someone used the AGit workflow that you can contribute a PR without forking & branching. Codeberg instructs you to use this command:

```sh
git fetch -u origin +refs/pull/$N/head:$USER/$BRANCH
```

to obtain a local copy of that PR (where `$N`, `$USER`, and `$BRANCH` are replaced with actual values). After running this command, with magit open, I started getting the "Not in git repository" error when I tried to do things like checkout a branch. The solution was to switch to buffer view with `M-x list-buffers` and then kill all magit related buffers and restart magit.
