### ISSUE TITLE
Unable to revert buffers with magit/diff-hl-flydiff-mode

### ISSUE THREAD

**Issue by seagle0128** [magit/magit#3014] opened 2017-03-02 14:12 UTC
I am experiencing this issue on Emacs 24/25 on Linux/Mac/Windows.

For example,  Emacs 25.1 on macOS 10.12.3
Steps:

```
1. `emacs -Q` and `M-x toggle-debug-on-error`
2. Open ~/.emacs.d/init.el.
3. Load librares: magit, diff-hl.
4. Enable global-diff-hl-mode and diff-hl-flydiff-moe.
5. `M-x revert-buffer`.
```
The buffers is unable to be reverted correctly. High CPU usage, NO debug errors, NO syntax colors and set to fundamental mode :(

Workaround:
1. `(diff-hl-flydiff-mode -1)` or
2. `(magit-auto-revert-mode -1)` 

Messages:
```elisp
Lisp nesting exceeds ‘max-lisp-eval-depth’
```

Refer to: https://github.com/dgutov/diff-hl/issues/85

**Comment by tarsius** [comment] 2017-03-02 16:27
I also cannot reproduce that.

Please turn do `toggle-debug-on-error` and post the output.

**Comment by npostavs** [comment] 2017-03-02 16:31
There was backtrace posted in https://github.com/dgutov/diff-hl/issues/65: https://gist.github.com/rasendubi/39693fadd3ef929af9caa572d8c3d7af

**Comment by seagle0128** [comment] 2017-03-03 01:10
@tarsius There is no output after turn on `toggle-debug-on-error`. What I could see is "High CPU usage, NO debug errors, NO syntax colors and set to fundamental mode".  Again, I found this in the messages: `Lisp nesting exceeds ‘max-lisp-eval-depth’`.

**Comment by seagle0128** [comment] 2017-03-03 01:20
Another workaround:
Changed `magit-turn-on-auto-revert-mode-if-desired` as below, the issue disappears.

```elisp
  (defun magit-turn-on-auto-revert-mode-if-desired (&optional file)
    (if file
        (--when-let (find-buffer-visiting file)
          (with-current-buffer it
            (magit-turn-on-auto-revert-mode-if-desired)))
      (when (and buffer-file-name
                 (file-readable-p buffer-file-name)
                 (magit-toplevel)
                 (or (not magit-auto-revert-tracked-only)
                     (magit-file-tracked-p buffer-file-name)))
        (unless (or auto-revert-mode global-auto-revert-mode)
          (auto-revert-mode)))))
```

**Comment by tarsius** [comment] 2017-03-09 09:08
For the time being I am commenting on dgutov/diff-hl#65. Spreading this across three issues does not help.

**Comment by seagle0128** [comment] 2017-07-27 14:20
There is a new clue here. If enable `global-magit-file-mode` and `diff-hl-flydiff-mode` together, the issue appears.

**Comment by YourFin** [comment] 2017-08-30 01:14
I've run into the same issue as well, although I found this when emacs flatly refused to open some files. The error for me was something along the line of  `max-specpdl-size` exceeded, and with debug enabled there was no backtrace. Disabling either of the plugins solved the issue.

Interestingly, when I attempted to open the afflicted files in vim to try and figure out what was going on, save attempts claimed that the `File exists` (E13), which I have never run into before, and deleting temp files did not stop this behaviour.

Adding the following lines to the end of my `use-package` statement for magit has solved this and kept the relevant functionality, but I'm not sure if this will help @seagle0128. 

Relevant code:

~~~~
(use-package magit
             :config
             (magit-auto-revert-mode -1)
             (global-auto-revert-mode -1)
             (add-hook 'after-init-hook 'magit-file-mode-turn-on))
~~~~

Hopefully this has been helpful.

**Comment by seagle0128** [comment] 2017-08-31 09:29
@YourFin Thanks! It's definitely helpful. The workaround I posted above works well for me, although auto-revert-mode is not disabled globally.

**Comment by tarsius** [comment] 2017-10-06 21:16
I still cannot reproduce that, but have just added a potentially loop-breaking change. For details see https://github.com/dgutov/diff-hl/issues/65#issuecomment-334872105. I am closing this issue - the linked to issue has more information anyway.

**Closed by tarsius** 2017-10-06 21:16 UTC
Labels: unconfirmed
