### ISSUE TITLE
Executing aliased git commands that start with '!'

### ISSUE THREAD

**Issue by rtartler-desres** [magit/magit#2354] opened 2015-10-22 12:55 UTC
I have a git alias called "fixup"

    $ git config alias.fixup
    !git add -uv && git commit --amend -CHEAD

Magit supports executing arbitrary git commands with `magit-git-command` (bound to the key `:`). Trying that on my `fixup` macro results in the following output in the `*magit-process: ...`  buffer:

    128 git … fixup
    fatal: pathspec ':/' did not match any files

`M-x magit` version returns:

    Magit 20151019.443, Git 2.4.4, Emacs 24.5.1

Maybe there is even another shortcut in Magit that achieves something  similar like my `fixup` alias?

**Comment by npostavs** [comment] 2015-10-22 13:20
> Maybe there is even another shortcut in Magit that achieves something similar like my fixup alias?

`S` `c e`

I think `S` (`magit-stage-all`) should be like `git add -uv`, and `c e` (`magit-commit-extend`) should be like `git commit --amend -CHEAD`.

**Comment by tarsius** [comment] 2015-10-22 19:24
I cannot reproduce this.

```lisp
[alias]
	fixup = !git add -uv && git commit --amend -CHEAD
```

works for me just fine.

**Comment by npostavs** [comment] 2015-10-22 21:48
I hadn't actually tried this earlier. 

I can reproduce this using msys2 and cygwin git, it works fine with Git for Windows. It seems that the `--literal-pathspecs` argument causes problems. Just doing `git --literal-pathspecs add -u` from a cygwin or msys2 command line gives the `pathspec ':/' did not match any files` error message.

**Comment by rtartler-desres** [comment] 2015-10-23 19:09
I've been trying the command `git --literal-pathspecs add -u` on my Linux box on various git versions. It works fine on version `1.9.3`, but breaks with git versions `2.0.2`, `2.3.6`, and `2.4.4`.

This problem seems independent of the operating system.

**Comment by npostavs** [comment] 2015-10-23 23:15
> This problem seems independent of the operating system.

Yes, I was confused because I remembered `S` (`magit-stage-modified`) working on my Linux boxes, but that is because it runs `git --literal-pathspecs add -u .` which does work fine.

**Comment by npostavs** [comment] 2015-10-24 18:32
So the `git --literal-pathspecs add -u` bug is on it's way to being fixed in git: http://www.mail-archive.com/git@vger.kernel.org/msg79995.html

From magit's side, I'm thinking `--literal-pathspecs` should not be passed to `magit-git-command`: suppose the user actually wants to use a command with globbing path specs (and if they didn't want globbing they can pass `--literal-pathspecs` themselves).

**Comment by tarsius** [comment] 2015-10-25 14:07
@npostavs If you are suggesting to drop that argument, then yes, we can do that (by let-binding and adjusting `magit-git-default-arguments`). But I think that generally we need this, but unfortunately 17209093b8c5cec7eeba4dffc2912fbdb789f490 does not say why that is so. (Later in 2d29e1a2cc2c6c9b31593b3be81e33c67b0bddaa we switched from `$GIT_LITERAL_PATHSPECS` to `--literal-pathspecs`.

**Comment by npostavs** [comment] 2015-10-25 14:22
> I think that generally we need this, but unfortunately 1720909 does not say why that is so.

I think it's to allow adding files with weird names like `*`. And I suppose Magit doesn't need to use git's globbing because it always computes file list itself.

**Comment by tarsius** [comment] 2015-10-25 14:25
Yes, right.

So we have to add the let-binding and then we close this because it's a Git bug?

**Closed** 2015-10-25 17:57 UTC
Labels: 00 bug git
