### ISSUE TITLE
Magit feels slow

### ISSUE THREAD

**Issue by AshtonKem** [magit/magit#1947] opened 2015-07-02 14:30 UTC
Ever since upgrading to 2.1.0, Magit has run significantly slower in all aspects. Particularly bad can be navigating the status panel (which can lock up Emacs when scrolling to the bottom) and starting magit-status, which can take 2-3 seconds before the buffer is visible and responsive.

**Comment by tarsius** [comment] 2015-07-02 14:35
Please provide more information starting with the output of `M-x magit-version`. What OS are you using? Please provide benchmarks.

`2.1.0` is expected to be *faster* and reports from other users indicate that it generally is. So it is likely that this issue is causes by configuration issues. I can help you with that but need more information.

**Comment by npostavs** [comment] 2015-07-02 14:38
Does sound pretty similar to https://github.com/magit/magit/issues/1907#issuecomment-117228330

**Comment by tarsius** [comment] 2015-07-02 14:40
Yeah, but I installed some code which should prevent that. Unless of course someone turns on `linum-mode` in `magit-mode`-derived modes explicitly.

**Comment by AshtonKem** [comment] 2015-07-02 14:48
# Code Versions
I'm running the dev code branch under emacs-live, which has magit set at c8a131e254fb1da8ea3669d97fee700d476b195b.

magit-version does not work on this revision/setup, I do not know why. Running it returns "Wrong type argument: arrayp, nil" (I can open a separate issue for this if you want).

# Machine
- MacBook pro (Retina): OSX 10.10.3 (14D136)
- Emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57), compiled from homebrew.
- git: 2.4.3


# Metrics
These are hand timed because I don't know how to time actions in Emacs directly.

## Small Change Set (One File)
- magit-status: 2 seconds
- Stage 1 file: 1.5 seconds
- Bring up commit buffer: < 1 second.
- Committing: Effectively Instantaneous.


## Large Change Set (~500 files)
- magit-status: 15 seconds
- stage a file: 27 seconds
- Bring up commit buffer: 2 seconds
- Committing: Effectively instantaneous

**Comment by AshtonKem** [comment] 2015-07-02 14:54
I do not have linum-relative installed, and running ```(global-linum-mode -1)``` had no effect.

**Comment by tarsius** [comment] 2015-07-02 20:20
> I don't know how to time actions in Emacs directly.

Is anyone interested in writing a "How can I profile Magit/Emacs?" FAQ entry (and maybe also a tutorial on the wiki)? :-)

**Comment by tarsius** [comment] 2015-07-02 22:09
See http://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html. I usually use `elp` instead of `profiler` but that might be only because I learned about that first.

**Comment by Silex** [comment] 2015-07-03 07:17
iirc elp is more convenient because it can instrument a specific function, while with profiler you just tell it to start profiling and stop profiling.

**Comment by tarsius** [comment] 2015-07-05 11:03
When you have some information that can help us figure out what is going on, then please reopen.

**Comment by AshtonKem** [comment] 2015-07-10 15:51
Here's the elp-results from a repo with a large number of changes (~4.5k):

```
Function Name                                   Call Count  Elapsed Time  Average Time
magit-wash-sequence                             4849        182.864305    0.0377117560
magit-status                                    1           104.112368    104.112368
magit-status-internal                           1           104.112362    104.112362
magit-refresh-buffer                            1           104.051479    104.051479
magit-status-refresh-buffer                     1           104.050372    104.050372
magit-insert-unstaged-changes                   1           98.606611     98.606611
magit-git-wash                                  4           96.90009      24.2250225
magit-diff-wash-diffs                           2           96.069305     48.0346525
magit-diff-wash-diff                            4846        95.988133999  0.0198077040
magit-diff-insert-file-section                  4846        88.494319999  0.0182613124
magit-diff-wash-hunk                            9489        86.838062999  0.0091514451
magit-delete-line                               28637       6.2685530000  0.0002188969
magit-section-show                              8           3.0162720000  0.3770340000
magit-git-insert                                16          1.8242260000  0.1140141250
magit-section-hide                              4846        1.3801220000  0.0002847961
magit-git-lines                                 4           0.831098      0.2077745
magit-svn-get-ref                               2           0.577336      0.288668
magit-insert-staged-changes                     1           0.413115      0.413115
magit-insert-status-headers                     1           0.36232       0.36232
magit-insert-headers                            1           0.354759      0.354759
magit-insert-head-header                        1           0.354743      0.354743
magit-insert-remaining-headers                  1           0.33832       0.33832
magit-insert-svn-unpulled                       1           0.30789       0.30789
magit-insert-svn-unpushed                       1           0.269472      0.269472
magit-insert-svn-remote                         1           0.255189      0.255189
magit-svn-get-rev                               1           0.255183      0.255183
magit-insert-untracked-files                    1           0.20448       0.20448
magit-git-items                                 1           0.199403      0.199403
magit-git-str                                   26          0.1529470000  0.0058825769
magit-git-string                                7           0.093755      0.0133935714
magit-rev-parse-safe                            15          0.084672      0.0056448
magit-diff-wash-diffstat                        2           0.064761      0.0323805
magit-insert-unpulled-commits                   1           0.059557      0.059557
magit-get-tracked-ref                           2           0.0562359999  0.0281179999
magit-insert-tags-header                        1           0.047502      0.047502
magit-get                                       9           0.046783      0.0051981111
magit-get-current-branch                        4           0.044418      0.0111045
magit-maybe-save-repository-buffers             1           0.041853      0.041853
magit-save-repository-buffers                   1           0.041831      0.041831
magit-insert-unpushed-commits                   1           0.037879      0.037879
magit-insert-upstream-header                    1           0.035589      0.035589
magit-git-dir                                   9           0.034282      0.0038091111
magit-rev-verify                                2           0.033251      0.0166255
magit-get-next-tag                              1           0.029295      0.029295
magit-insert-stashes                            1           0.025732      0.025732
magit-git-exit-code                             1           0.024528      0.024528
magit-insert-heading                            9496        0.0207129999  2.181...e-06
magit-rev-format                                2           0.020107      0.0100535
magit-get-current-tag                           1           0.017981      0.017981
magit-insert-log                                2           0.017664      0.008832
magit-toplevel                                  4           0.017626      0.0044065
magit-diff-expansion-threshold                  9500        0.0173829999  1.829...e-06
magit-bisect-in-progress-p                      3           0.011643      0.0038810000
magit-status-mode                               1           0.0095        0.0095
magit-insert-rebase-sequence                    1           0.008276      0.008276
magit-rebase-in-progress-p                      1           0.008271      0.008271
magit-insert-child-count                        9499        0.0081930000  8.625...e-07
magit-revision-set-visibility                   4654        0.0080220000  1.723...e-06
magit-get-tracked-branch                        1           0.007512      0.007512
magit-load-config-extensions                    1           0.007207      0.007207
magit-log-wash-log                              1           0.007124      0.007124
magit-get-all                                   1           0.007095      0.007095
magit-insert-sequencer-sequence                 1           0.006689      0.006689
magit-decode-git-path                           9692        0.0056240000  5.802...e-07
magit-mode-display-buffer                       1           0.005269      0.005269
magit-mode-get-buffer-create                    1           0.004883      0.004883
magit-mode-get-buffer                           1           0.004873      0.004873
magit-get-boolean                               1           0.004774      0.004774
magit-git-true                                  1           0.004758      0.004758
magit-insert                                    8           0.004442      0.00055525
magit-abbrev-length                             1           0.004425      0.004425
magit-insert-merge-log                          1           0.004357      0.004357
magit-insert-bisect-log                         1           0.003975      0.003975
magit-insert-bisect-output                      1           0.003867      0.003867
magit-insert-bisect-rest                        1           0.003815      0.003815
magit-insert-am-sequence                        1           0.003481      0.003481
magit-am-in-progress-p                          1           0.003475      0.003475
magit-revert-in-progress-p                      1           0.00335       0.00335
magit-cherry-pick-in-progress-p                 1           0.003327      0.003327
magit-log-wash-line                             1           0.002308      0.002308
magit-delete-match                              1           0.000995      0.000995
magit-process-git-arguments                     43          0.0004590000  1.067...e-05
magit-mode                                      1           0.000413      0.000413
magit-section-update-highlight                  2           0.000321      0.0001605
magit-unhighlight-region                        32          0.000229      7.15625e-06
magit-section-highlight                         2           0.00017       8.5e-05
magit-section-make-overlay                      2           0.0001599999  7.999...e-05
magit-format-duration                           6           0.000149      2.483...e-05
magit-expand-git-file-name                      13          0.000139      1.069...e-05
magit-format-log-margin                         1           9.3e-05       9.3e-05
magit-svn-mode                                  1           8.8e-05       8.8e-05
dash--match                                     10          7.3e-05       7.299...e-06
magit-add-section-hook                          3           4.9e-05       1.633...e-05
magit-diff-highlight                            2           4.499...e-05  2.249...e-05
magit-diff-scope                                2           3.999...e-05  1.999...e-05
magit-pre-command-hook                          30          3.500...e-05  1.166...e-06
magit-format-status-tag-sentence                1           3.4e-05       3.4e-05
magit-put-face-property                         10          3.4e-05       3.4e-06
magit-log-format-max-count                      2           2.2e-05       1.1e-05
magit-file-lines                                1           1.6e-05       1.6e-05
magit-diff-type                                 2           1.300...e-05  6.500...e-06
magit-current-section                           4           1.1e-05       2.75e-06
magit-xref-insert-buttons                       2           9.999...e-06  4.999...e-06
magit-make-margin-overlay                       1           9e-06         9e-06
dash--match-symbol                              10          6.999...e-06  6.999...e-07
magit-region-sections                           2           4e-06         2e-06
magit-cancel-section                            1           0.0           0.0```

**Comment by tarsius** [comment] 2015-07-10 15:55
> ~4.5k

files?

**Comment by AshtonKem** [comment] 2015-07-10 16:00
Yes. I just deleted vendor on a ruby project to produce a sufficiently demonstrative example. I understand that this case will always be kind of slow, but I feel that 3 minutes is well outside of what I'd expect.

**Comment by AshtonKem** [comment] 2015-07-10 16:11
I instrumented every package that magit provides with ELP. Same git repo, same change set.

```
Function Name                                   Call Count  Elapsed Time  Average Time
magit-wash-sequence                             4849        714.21395699  0.1472909789
magit-status                                    1           380.345361    380.345361
magit-status-internal                           1           380.345354    380.345354
magit-refresh-buffer                            1           380.271773    380.271773
magit-status-refresh-buffer                     1           379.991121    379.991121
magit-insert-unstaged-changes                   1           374.195191    374.195191
magit-git-wash                                  4           372.85667     93.2141675
magit-diff-wash-diffs                           2           371.959698    185.979849
magit-diff-wash-diff                            4846        371.88197599  0.0767399867
magit-diff-insert-file-section                  4846        345.48839600  0.0712935196
magit-diff-wash-hunk                            9489        342.16807299  0.0360594449
magit-delete-line                               28637       22.044401000  0.0007697873
magit-get-section                               4654        15.106380999  0.0032458919
magit-section-show                              8           3.162959      0.395369875
magit-git-insert                                16          1.8320599999  0.1145037499
magit-section-hide                              4846        1.5678580000  0.0003235365
magit-git-lines                                 4           0.794011      0.19850275
magit-insert-staged-changes                     1           0.762252      0.762252
magit-svn-get-ref                               2           0.542189      0.2710945
magit-section-ident                             18601       0.5229329999  2.811...e-05
magit-insert-status-headers                     1           0.374824      0.374824
magit-insert-headers                            1           0.366978      0.366978
magit-insert-head-header                        1           0.366962      0.366962
magit-insert-remaining-headers                  1           0.347868      0.347868
magit-insert-svn-unpushed                       1           0.27475       0.27475
magit-insert-svn-unpulled                       1           0.267457      0.267457
magit-insert-svn-remote                         1           0.253926      0.253926
magit-svn-get-rev                               1           0.253922      0.253922
magit-insert-untracked-files                    1           0.209762      0.209762
magit-git-items                                 1           0.20557       0.20557
magit-git-str                                   26          0.133954      0.0051520769
magit-git-string                                7           0.081877      0.0116967142
magit-rev-parse-safe                            15          0.071825      0.0047883333
magit-diff-wash-diffstat                        2           0.0585720000  0.0292860000
magit-maybe-save-repository-buffers             1           0.055534      0.055534
magit-insert-tags-header                        1           0.05216       0.05216
magit-insert-unpushed-commits                   1           0.042269      0.042269
magit-insert-upstream-header                    1           0.040157      0.040157
magit-save-repository-buffers                   1           0.038985      0.038985
magit-get                                       9           0.037391      0.0041545555
magit-git-dir                                   9           0.0366950000  0.0040772222
magit-insert-heading                            9496        0.0362589999  3.818...e-06
magit-get-tracked-ref                           2           0.034095      0.0170475
magit-insert-unpulled-commits                   1           0.031856      0.031856
magit-get-current-branch                        4           0.031833      0.00795825
magit-git-exit-code                             1           0.031693      0.031693
magit-get-next-tag                              1           0.028746      0.028746
magit-diff-expansion-threshold                  9500        0.0223020000  2.347...e-06
magit-insert-log                                2           0.021902      0.010951
magit-rev-format                                2           0.021364      0.010682
magit-get-current-tag                           1           0.020454      0.020454
magit-toplevel                                  4           0.0195200000  0.0048800000
magit-insert                                    8           0.017019      0.002127375
magit-insert-child-count                        9499        0.0168539999  1.774...e-06
magit-rev-verify                                2           0.016112      0.008056
magit-bisect-in-progress-p                      3           0.0124        0.0041333333
magit-revision-set-visibility                   4654        0.0114230000  2.454...e-06
magit-log-wash-log                              1           0.010034      0.010034
magit-insert-stashes                            1           0.008295      0.008295
magit-insert-rebase-sequence                    1           0.008268      0.008268
magit-rebase-in-progress-p                      1           0.008263      0.008263
magit-get-tracked-branch                        1           0.007672      0.007672
magit-insert-sequencer-sequence                 1           0.007666      0.007666
magit-status-mode                               1           0.007661      0.007661
magit-decode-git-path                           9692        0.0072950000  7.526...e-07
magit-load-config-extensions                    1           0.005682      0.005682
magit-get-all                                   1           0.005587      0.005587
magit-mode-display-buffer                       1           0.005509      0.005509
magit-mode-get-buffer-create                    1           0.005013      0.005013
magit-mode-get-buffer                           1           0.005006      0.005006
magit-get-boolean                               1           0.004831      0.004831
magit-git-true                                  1           0.00482       0.00482
magit-abbrev-length                             1           0.004763      0.004763
magit-log-wash-line                             1           0.004696      0.004696
magit-insert-merge-log                          1           0.004661      0.004661
magit-insert-bisect-output                      1           0.004604      0.004604
magit-insert-bisect-rest                        1           0.004038      0.004038
magit-revert-in-progress-p                      1           0.003933      0.003933
magit-insert-am-sequence                        1           0.003882      0.003882
magit-am-in-progress-p                          1           0.003877      0.003877
magit-insert-bisect-log                         1           0.003771      0.003771
magit-cherry-pick-in-progress-p                 1           0.003721      0.003721
magit-delete-match                              1           0.002793      0.002793
magit-pre-command-hook                          1099        0.0009850000  8.962...e-07
magit-section-update-highlight                  2           0.000517      0.0002585
magit-section-highlight                         1           0.000462      0.000462
magit-section-make-overlay                      1           0.000452      0.000452
dash--match                                     58          0.0004250000  7.327...e-06
magit-process-git-arguments                     43          0.0003960000  9.209...e-06
magit-mode                                      1           0.000384      0.000384
magit-unhighlight-region                        37          0.0002370000  6.405...e-06
magit-expand-git-file-name                      13          0.0001509999  1.161...e-05
magit-format-duration                           5           9.099...e-05  1.82e-05
magit-format-log-margin                         1           8.7e-05       8.7e-05
magit-svn-mode                                  1           6.4e-05       6.4e-05
magit-section-goto-successor                    1           5.8e-05       5.8e-05
dash--match-symbol                              58          5.299...e-05  9.137...e-07
magit-format-status-tag-sentence                1           3.8e-05       3.8e-05
magit-put-face-property                         10          3.2e-05       3.2e-06
magit-add-section-hook                          3           2.2e-05       7.333...e-06
magit-diff-highlight                            1           2.1e-05       2.1e-05
magit-diff-scope                                1           1.9e-05       1.9e-05
magit-current-section                           5           1.800...e-05  3.600...e-06
magit-file-lines                                1           1.7e-05       1.7e-05
magit-make-margin-overlay                       1           1.5e-05       1.5e-05
magit-log-format-max-count                      2           1.4e-05       7e-06
magit-diff-type                                 1           7e-06         7e-06
magit-xref-insert-buttons                       2           4.999...e-06  2.499...e-06
magit-region-sections                           1           2e-06         2e-06
magit-cancel-section                            1           0.0           0.0
```

**Comment by Silex** [comment] 2015-07-10 16:24
@AshtonKem: what would you say is the easiest to create a repo/situation exhibiting these performance problems?

Maybe we can write a benchmark/test that creates/use such a repo, that way we can easily measure performance enhancements/regressions.

**Comment by AshtonKem** [comment] 2015-07-10 16:33
1. ```git clone git@github.com:rails/rails.git```
2. ```cd rails```
3. ```gem install bundler```
4. ```bundle install --deployment```
5. ```git add vendor```
6. ```git status```

**Comment by tarsius** [comment] 2015-07-11 11:42
Please see #2048.

**Comment by AshtonKem** [comment] 2015-07-11 16:53
The very large example is to make the slowness more obvious. Magit has been performing slowly under what I feel a more common circumstances, like dozens of changes rather than thousands. 

--
Ashton

**Comment by tarsius** [comment] 2015-07-11 17:02
In that case we of course have to do something about it.

When that happens again, with a fairly small number of changes, then please create another benchmark. But this time provide output from `profiler` too. This might be causes by some third-party code, and profiler would make it ~~easier~~ possible to spot that.

**Comment by oldhaapi** [comment] 2015-08-05 16:25
I'm finding magit slow in the case of many refs. We have 10 years of branch history and tags/build, and a branch-per-build policy on team branches, so it adds up. I wonder if this might be a perverse case for magit.

Magit 2.1.0, Git 2.4.3, Emacs 24.5.1

Here's the profiler output:
- command-execute                                               55001  97%
 - call-interactively                                           55001  97%
  - magit-show-refs-popup                                       54694  96%
   - magit-invoke-popup                                         54694  96%
    - call-interactively                                        54694  96%
     - magit-show-refs-head                                     54694  96%
      - magit-show-refs                                         54694  96%
       - let*                                                   54694  96%
        + if                                                    54567  96%
        + magit-mode-display-buffer                               127   0%
  + byte-code

**Comment by tarsius** [comment] 2015-08-13 11:42
@oldhaapi see #2162.

I am closing this issue because

1. When there are thousands of files then the slowdown is expected. (This can be improved but there are already other issues about that.)
2. No slowdown is expected when there are only a few changes - at least not due to parsing diffs. There are other reasons why things could be slow, but they are covered in the manual and other open issues. Besides the tag thing I should also mention that `--graph` is very slow when there are very many commits reachable from `HEAD`.

**Closed by tarsius** 2015-08-13 11:42 UTC
Labels: 30 support

**Comment by tarsius** [comment] 2015-08-13 11:43
Ah and here are some relevant links:

* https://github.com/magit/magit/milestones/2.4.0
* http://magit.vc/manual/magit/Performance.html
* http://magit.vc/manual/magit/Customizing.html

**Comment by tarsius** [comment] 2015-08-13 12:31
Ps: I have added some notes about these things to the manual and will push that in an hour or so.
