### ISSUE TITLE
Diff highlighting broken in emacs 27.0.50

### ISSUE THREAD

**Issue by sdilts** [magit/magit#3986] opened 2019-10-15 20:05 UTC
Emacs 27.0.50 changes the way line highlighting works, which causes cosmetic issues in diff buffers. The highlight now only extends to the end of the text, not to the end of the line. [Here is a Reddit thread that has pictures.](https://www.reddit.com/r/emacs/comments/diahh1/emacs_27_update_changed_how_highlighted_lines/) The relevant paragraph from `emacs/NEWS` reads:

> New face attribute `:extend` to control face extension at EOL. The new face attribute `:extend` controls whether to use the face for displaying the empty space beyond end of 
line (EOL) till the edge of the window. By default, this attribute is non-nil only for `region` and  `hl-line` faces; any other face that crosses end of line will not affect the display of the empty space at EOL.

The change was merged into emacs master at commit https://github.com/emacs-mirror/emacs/commit/3d6075e3ee8c447f8974b37007a1b1ae1af8917c.

**Comment by tarsius** [comment] 2019-10-15 21:45
Was this change discussed anywhere?

I for one won't rush to update all my packages to account for this and will instead wait until the dust has settled. Locally I am resetting to before this was merged for the time being.

**Comment by cireu** [comment] 2019-10-20 11:34
I encounter same issue and just submit a bug here.

https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01809.html

I hope more people can discuss this change and let the maintainers of Emacs hear our voice.

**Comment by thierryvolpiatto** [comment] 2019-10-20 12:31
Zhu Zihao <notifications@github.com> writes:

> I encounter same issue and just submit a bug here.
>
> https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01809.html
>
> I hope more people can discuss this change and let the maintainers of Emacs hear our voice.
>
> cc @thierryvolpiatto , this change also break helm's selection overlay

It doesn't break helm-selection, it just change it, overlay ends at eol
instead of at window-width, is it really a problem?

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cireu** [comment] 2019-10-20 16:22
> Zhu Zihao <notifications@github.com> writes:
> I encounter same issue and just submit a bug here. https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01809.html I hope more people can discuss this change and let the maintainers of Emacs hear our voice. cc @thierryvolpiatto , this change also break helm's selection overlay
> It doesn't break helm-selection, it just change it, overlay ends at eol instead of at window-width, is it really a problem?
> […](#)
> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.*
> -- Thierry Get my Gnupg key: gpg --keyserver pgp.mit.edu --recv-keys 59F29997

Emm, yes, it's not a techonically issue, because no code was broken due to this change, may some one like shorter selection overlay. But I don't think it's a good idea that they push their choice(modifying face behaviour) on user.

**Comment by thierryvolpiatto** [comment] 2019-10-20 17:07
Zhu Zihao <notifications@github.com> writes:

>     Zhu Zihao notifications@github.com writes:
>     I encounter same issue and just submit a bug here. https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01809.html I hope more people can discuss this change and let the maintainers of Emacs hear our voice. cc
>     @thierryvolpiatto , this change also break helm's selection overlay
>     It doesn't break helm-selection, it just change it, overlay ends at eol instead of at window-width, is it really a problem?
>     …
>     — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.*
>     -- Thierry Get my Gnupg key: gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> Emm, yes, it's not a techonically issue, because no code was broken
> due to this change, may some one like shorter selection overlay. But I
> don't think it's a good idea that they push their choice(modifying
> face behaviour) on user.

Agreed, should be at least configurable, don't know yet if it is
possible.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2019-10-20 19:19
For now one can use something like this waiting upstream decide what to do:

```elisp
(when (>= emacs-major-version 27)
  (cl-loop for f in (face-list)
           for face = (symbol-name f)
           when (and (string-match "\\`helm" face)
                     (ignore-errors
                       (face-attribute f :extend t)))
           do (set-face-attribute f nil :extend t)))
```

**Comment by manuel-uberti** [comment] 2019-10-21 09:28
@tarsius could you explain the problem to the Emacs devs here? https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774#254

At the moment I am using @thierryvolpiatto workaround for Magit too, and it works. But of course it'd be better if this was addressed at the root of the problem.

**Comment by tarsius** [comment] 2019-10-21 10:42
I don't have much to add to what Lars said [here along with](https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01832.html) Eli's response.

**Comment by dgutov** [comment] 2019-10-23 20:16
@tarsius I think your presence it requested at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774#269.

**Comment by tarsius** [comment] 2019-10-23 21:19
The problem is that I have to read several hundred messages before I can comment without saying silly things that have already been addressed over and over again. I might try to do that tomorrow. Sight.

**Comment by cireu** [comment] 2019-10-30 10:52
Seems that they change the behaviour again. Now `:extend` was used by default.

Tested on https://github.com/emacs-mirror/emacs/commit/9e10ee754c8ffbe715879b7bba37a4523c8ee59d

**Comment by tarsius** [comment] 2019-10-30 12:26
@cireu I don't think they changed anything.

Also `:extend` is not inherited yet. I just had a stab at this but reverted when I noticed that the branch discussed in https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg00956.html has not been merged yet. (Also I cannot actually find the mentioned branch.)

**Comment by tarsius** [comment] 2019-10-30 12:31
@dgutov I am waiting for the inheritance bug to be fixed before experimenting with this again and before I have experimented with this some more I won't comment.

My main concern is (assuming my initial impression was correct) that each and every theme that styles `magit` (or some other package that has had to add `:extend t`) will have to be adjusted. That will take years to get 90% done and will never be 100% done.

**Comment by peniblec** [comment] 2019-10-31 07:56
@tarsius
> Also `:extend` is not inherited yet. I just had a stab at this but reverted when I noticed that the branch discussed in https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg00956.html has not been merged yet. (Also I cannot actually find the mentioned branch.)

Correct me if I'm wrong, but I think the branch has been merged:

http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=e0bcc25f64da44e3b5e68b66f361cfa73c0f79b2
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8ae2a3a46b9c4cd2126f3c6504c619892ffff6ce

The branch may have been deleted by now, which might explain why it cannot be found anymore.

As for actually fixing this, I've [suggested](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774#278) something that does not require code duplication AFAICT, but maybe this solution has shortcomings I haven't thought of.

**Comment by tarsius** [comment] 2019-10-31 14:16
> Correct me if I'm wrong, but I think the branch has been merged:

You are right. Turns out I did not notice that the built failed for unrelated reasons and I was still using the previous version, which didn't have these commits.

**Comment by dgutov** [comment] 2019-10-31 17:14
https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg01253.html

**Comment by manuel-uberti** [comment] 2019-11-04 08:50
@tarsius FWIW, I rebuilt Emacs `master` this morning (commit: `1d4862e8c18aff5e2a59b9fb37e643a389683047`), and with latest Magit the only thing that I'm seeing "broken" is this:

![Screenshot from 2019-11-04 09-48-21](https://user-images.githubusercontent.com/8199224/68108535-4d0bd680-fee8-11e9-9b05-e9737e4e84ff.png)

Which comes from having hit <kbd>RET</kbd> on a specific commit after <kbd>l l</kbd> from `magit-status`.

**Comment by tarsius** [comment] 2019-11-11 12:25
I have pushed a draft to the `extend-27` branch. Unfortunately that only makes a difference if you don't use a theme, and who does that? I'll try to fix solarized next, but that currently has issues of its own, so that will be based on a version from a few weeks ago.

**Comment by tarsius** [comment] 2019-11-11 12:45
Here's a list of faces that likely have to be extended:

```
magit-section-highlight
magit-section-heading
magit-section-secondary-heading
magit-section-heading-selection
magit-blame-highlight
magit-blame-heading
magit-diff-file-heading
magit-diff-file-heading-highlight
magit-diff-file-heading-selection
magit-diff-hunk-heading
magit-diff-hunk-heading-highlight
magit-diff-hunk-heading-selection
magit-diff-hunk-region
magit-diff-lines-heading
magit-diff-lines-boundary
magit-diff-added
magit-diff-removed
magit-diff-base
magit-diff-context
magit-diff-added-highlight
magit-diff-removed-highlight
magit-diff-base-highlight
magit-diff-context-highlight
```

**Comment by manuel-uberti** [comment] 2019-11-11 13:47
Thank you. I did already add `:extend` support for some faces (included the Magit ones) for [color-theme-sanityinc-tomorrow](https://github.com/purcell/color-theme-sanityinc-tomorrow), so I can check your changes with that theme, if you want me to.

**Comment by dgutov** [comment] 2019-11-11 14:53
> Unfortunately that only makes a difference if you don't use a theme

That sounds like an implementation bug in the core. At least according to the previous discussions in debbugs.

**Comment by dgutov** [comment] 2019-11-11 14:54
Meaning, people shouldn't hurry to change any themes.

**Comment by tarsius** [comment] 2019-11-17 14:25
> That sounds like an implementation bug in the core. At least according to the previous discussions in debbugs.

I brought that up in the debbugs thread and it turns out @dgutov was wrong about this. Themes do have to explicitly repeat `:extend t` for every face for which the official definition does that and which they theme. Its sad but true; as it stands now, each and every theme will have to be adjusted.

I hope we can get Eli to change his mind before the pretest begins, but if we don't, then I am confident that the protests during the pretest will do the trick.

Until then, if you use `solarized-theme`, then get the `extend-27` branch from [my fork](https://github.com/tarsiiformes/solarized-theme).

**Comment by tarsius** [comment] 2019-11-19 09:45
And so it has begun. (This isn't even about the actual issue, just some minor sideshow.)

> I hope we can get Eli to change his mind before the pretest begins, but if we don't, then I am confident that the protests during the pretest will do the trick.

But until that has actually happened I and other maintainers of popular packages have to suffer through it. From the last 24 hours alone:

- https://emacs.stackexchange.com/questions/53827/updating-magit-today-gives-me-invalid-face-attribute/53832#53832
- https://www.reddit.com/r/emacs/comments/dy8eoa/magit_error_on_all_commands_faceattribute_invalid/
- https://github.com/hlissner/doom-emacs/issues/2070
- https://github.com/magit/magit/issues/3986#issuecomment-555391760

-----

@adamkruszewski pull and rebuild Emacs 27.

**Comment by thierryvolpiatto** [comment] 2019-12-16 06:14
From last emacs as of 16 December, setting `:extend` to `t` is no more working, the faces now extend from EOL to end of screen, on some faces only, not all and I can't understand why it's happen on some faces and not others, wonder when this emacs-27 madness will end...
See https://github.com/emacs-helm/helm-ls-git/issues/55 and
https://github.com/emacs-helm/helm/issues/2213.
If somebody know how to retrieve emacs-26 behavior let us know, thanks.
It would have been so much simpler to implement `:noextend` instead of `:extend` to provide same functionality without breaking all packages...

**Comment by thierryvolpiatto** [comment] 2019-12-16 07:02
Seems that the problem is with text with a display text property, faces are extended from EOL to end of screen in such text and without setting extend, only EOL is highlighted, this is the commit introducing this bug:
dd3f2130cf2 * A better fix for extension of overlay string's faces

**Comment by tarsius** [comment] 2019-12-29 13:38
The issue reported by @thierryvolpiatto was fixed in http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=1e240a0ecdcf0eb4653ba57f8daa138ba2a2aab6.

**Comment by tarsius** [comment] 2019-12-29 13:43
Since http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=58fb4c3e68a4a42ad491d0fa2c084e5c39942e2b `:extend' inherited from default spec unless overridden. That means that it is no longer necessary for themes to repeat such settings. Hurray. Thanks @dgutov.

**Closed** 2019-12-29 13:43 UTC
Labels: bug emacs
