### ISSUE TITLE
Updating *magit: …* buffer results in “Variable binding depth exceeds max-specpdl-size”

### ISSUE THREAD

**Issue by hexmode** [magit/magit#3375] opened 2018-02-12 19:26 UTC
Sporadic, but annoying.   I've turned on debug-on-error so I can get you a traceback.

**Comment by hexmode** [comment] 2018-02-12 19:29
Here's one… not sure if this is like the  rest.

Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  (if (not (minibuffer-window-active-p (frame-selected-window))) (progn (setq powerline-selected-window (frame-selected-window)) (force-mode-line-update)))
  powerline-set-selected-window()
  ad-Advice-select-window(#<subr select-window> #<window 100 on *magit: …> norecord)
  apply(ad-Advice-select-window #<subr select-window> (#<window 100 on *magit: ...> norecord))
  select-window(#<window 100 on *magit: ...> norecord)
  #f(compiled-function (it) #<bytecode 0x4217461>)(#<window 100 on *magit: ...>)
  mapcar(#f(compiled-function (it) #<bytecode 0x4217461>) (#<window 100 on *magit: ...>))
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  apply(magit-refresh-buffer nil)
  magit-refresh-buffer()
  magit-refresh()
  funcall-interactively(magit-refresh)
  call-interactively(magit-refresh nil nil)
  command-execute(magit-refresh)

**Comment by tarsius** [comment] 2018-02-12 22:02
> Sporadic, but annoying.

... and new?

>     (minibuffer-window-active-p (frame-selected-window))) (progn (setq powerline-selected-window

Can you reproduce this if you disable powerline? What if you use [`magit-emacs-Q-command`](https://magit.vc/manual/magit/Debugging-Tools.html)?

**Comment by hexmode** [comment] 2018-02-13 03:22
I haven't yet been able to reproduce it, but it happened before I used
powerline, too.

**Comment by tarsius** [comment] 2018-02-16 15:47
Does this still happen? If not then I would like to close this pr. I might close it even if this still happens to you occasionally because I cannot reproduce this and don't see how I can figure out what is going wrong on your machine.

It appears that the code that is responsible for refreshing a buffer calls itself again. If Magit had such a bug built-in, then many more users would be affected. Since that is not the case I suspect that some third-party hook function or advice enters the loop.

So try to figure out what package that is starting with `emacs -Q` and then one by one enabling the other packages until things start blowing up again.

**Comment by hexmode** [comment] 2018-02-16 16:09
Jonas Bernoulli <notifications@github.com> writes:

> Does this still happen? If not then I would like to close this pr. I
> might close it even if this still happens to you occasionally because
> I cannot reproduce this and don't see how I can figure out what is
> going wrong on your machine.

Thanks.  If you think this is something I need to track down, I can do
that.

**Comment by tarsius** [comment] 2018-02-16 18:22
> If you think this is something I need to track down, I can do that.

Well it really depends on if this still happens and how often. I suspect that this is pretty specific to you setup and if it turns out that I am wrong about this, then I will hear about it again from someone else. If you feel like digging into it or you are bothered by the issue much, then by all means try to find the cause.

**Comment by hexmode** [comment] 2018-02-16 20:43
> If you feel like digging into it or you are bothered by the issue
> much, then by all means try to find the cause.

That's the thing, what is the cost/benefit ratio?  It does depend on how
irritated I get by this.

I agree that, from what you've said, this is probably caused by
something in my configuration outside of magit, but it sounds like you
think I'm expecting you to fix it regardless.

I apologize for giving you that impression.

**Comment by tarsius** [comment] 2018-02-16 23:30
> but it sounds like you think I'm expecting you to fix it regardless. I apologize for giving you that impression.

You didn't really give me that impression, but sometimes users do, which is why I worded things the way I did. Sorry about that too.

Am closing this, bu if you look into this some more and need help, then feel free to ask for it on this issue.

I suggest by checking the values of `magit-refresh-buffer-hook`, `magit-pre-refresh-hook` and `magit-post-refresh-hook` and remove everything you find there.

**Closed by tarsius** 2018-02-16 23:30 UTC
Labels: unconfirmed

**Comment by hexmode** [comment] 2018-07-26 23:21
Commenting out the following code seems to have solved this:

``` lisp
;; ;; http://whattheemacsd.com//setup-magit.el-01.html
;; ;; full screen magit-status
;; (defadvice magit-status (around magit-fullscreen activate)
;;   (window-configuration-to-register :magit-fullscreen)
;;   ad-do-it
;;   (delete-other-windows))

;; (defun magit-quit-session ()
;;   "Restores the previous window configuration and kills the magit buffer"
;;   (interactive)
;;   (kill-buffer)
;;   (jump-to-register :magit-fullscreen))

;; (when (boundp 'magit-status-mode-map)
;;   (define-key magit-status-mode-map (kbd "q") 'magit-quit-session))
```

**Comment by tarsius** [comment] 2018-07-26 23:37
Customizing `magit-display-buffer-function` (and keeping the default for `magit-bury-buffer-function`) should give you behavior similar to this advice.

**Comment by hexmode** [comment] 2018-07-27 00:30
I think I may be wrong about the cause because I think it just re-occured.

After some time running, I used `magit-status` to open magit for a directory that already an *magit: ...* status buffer open.

Instead of switching to the already open buffer, it attempted to create a new one and failed saying the existing buffer was read-only.  Trying `magit-status` again opened a new buffer for the same directory with a modified buffer name (_e.g._ *magit: dir*<2>).

Since I'm regularly running `magit-status` to return to the magit buffer, this process repeated.

I'm currently suspecting my `.dir-locals.el` since I notice the above behavior doesn't happen in directories that don't have this particular `.dir-locals.el`.

**Comment by hexmode** [comment] 2018-07-27 00:35
Yep, I think it was a hook I had that didn't test if the buffer was read-only before trying to act on it.

Thank you for the pointer, by the way.

**Comment by tarsius** [comment] 2018-07-27 01:19
You are welcome!
