### ISSUE TITLE
magit-diff-while-committing fails over TRAMP in a worktree

### ISSUE THREAD

**Issue by laurynas-biveinis** [magit/magit#4098] opened 2020-04-24 09:41 UTC
Attempting to use C-c C-d on a git working directory over TRAMP results in (file-missing "Setting current directory" "No such file or directory" "/remote/repo/path/").

Reproduced through magit-emacs-Q-command instance:
- edit a file over TRAMP in some remote repo
- C-x g, stage, c c
- C-c C-d, observe the error. Full stacktrace below.

M-x magit-version:
Magit 20200423.33, Git 2.17.1, Emacs 26.3, darwin

Reproduces with 2.90.1 version too.

```
Debugger entered--Lisp error: (file-missing "Setting current directory" "No such file or directory" "/remote/repo/path/")
  call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "config" "-z" "--get-all" "magit.extension")
  apply(call-process "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "config" "-z" "--get-all" "magit.extension"))
  process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "config" "-z" "--get-all" "magit.extension")
  apply(process-file "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "config" "-z" "--get-all" "magit.extension"))
  magit-process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "config" "-z" "--get-all" "magit.extension")
  apply(magit-process-file "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "config" "-z" "--get-all" "magit.extension"))
  magit-git-insert("config" nil "-z" "--get-all" "magit.extension")
  apply(magit-git-insert ("config" nil "-z" "--get-all" "magit.extension"))
  magit-git-items("config" nil "-z" "--get-all" "magit.extension")
  magit-get-all("magit.extension")
  magit-load-config-extensions()
  run-hooks(change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-diff-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-diff-mode-hook))
  run-mode-hooks(magit-diff-mode-hook)
  magit-diff-mode()
  magit-setup-buffer-internal(magit-diff-mode nil ((magit-buffer-range nil) (magit-buffer-typearg "--cached") (magit-buffer-diff-args ("--stat" "--no-ext-diff")) (magit-buffer-diff-files nil)))
  magit-diff-setup-buffer(nil "--cached" ("--stat" "--no-ext-diff") nil)
  magit-diff-staged(nil ("--stat" "--no-ext-diff"))
  magit-diff-while-committing(("--stat" "--no-ext-diff"))
  funcall-interactively(magit-diff-while-committing ("--stat" "--no-ext-diff"))
  call-interactively(magit-diff-while-committing nil nil)
  command-execute(magit-diff-while-committing)
```

**Comment by tarsius** [comment] 2020-04-24 09:51
> "/remote/repo/path/"

That's not a remote path. Something relevant may be lost in obfuscation here.

**Comment by laurynas-biveinis** [comment] 2020-04-24 09:57
Indeed not a remote path

> > "/remote/repo/path/"
> 
> That's not a remote path. Something relevant may be lost in obfuscation here.

Indeed it's a path on a remote machine that seems to be handled as a local path in the backtrace. I replaced directory components but haven't removed any tramp prefixes in obfuscating.

> > darwin
> 
> And at the other end?

Ubuntu 18.04

**Comment by mpereira** [comment] 2020-05-28 10:12
`M-x magit-diff-while-committing` works for me on TRAMP buffers. Emacs 28.0.50 (and 26.3), macOS, magit 20200526.925.

One question though, @tarsius: do you know off the top of your head how would one configure Emacs so that the same behavior (a diff buffer is opened alongside the commit buffer) is preserved on TRAMP buffers?

**Comment by tarsius** [comment] 2020-06-09 14:20
> (a diff buffer is opened alongside the commit buffer) is preserved on TRAMP buffers?

After 793e387a508984ae2586b93ff78afddf7a1164ac that should now happen automatically.

**Comment by tarsius** [comment] 2020-06-09 14:22
@laurynas-biveinis Sorry for the delay. Tramp didn't work at all for me for a while so I could not experiment with this.

I cannot reproduce this issue, can you still? If so, then I recommend you add some debug statements to functions that appear in the backtrace to print the value of `default-directory` to see where things start going south.

**Comment by mpereira** [comment] 2020-06-09 14:25
> After 793e387 that should now happen automatically.

Sweet. Thank you so much!

**Comment by laurynas-biveinis** [comment] 2020-06-10 09:08
@tarsius , I have just retested and I can no longer reproduce with 2.90.1. The thing that changed between the original report and now was that I updated TRAMP from 26.3-bundled version to the ELPA one, 2.4.3.5, it might have helped here.

Thanks,

**Comment by laurynas-biveinis** [comment] 2020-06-30 12:46
I made a mistake in my previous confirmation and I can still reproduce the issue. I will dump `default-directory` across the backtrace as suggested and will update.

**Comment by laurynas-biveinis** [comment] 2020-06-30 13:01
With 2.90.1, the last good path is at `magit-mode-setup-internal` ('scpx:/host:/path/on/host'), and the the first stripped path is at `magit-load-config-extensions` ('/path/on/host'). Between these two, there is `magit-diff-mode` - I need to figure out how to add `(message ... defaukt-directory) to a `define-derived-mode`. And probably I need to retest with trunk instead of 2.90.1, right?

**Comment by tarsius** [comment] 2020-06-30 13:47
> And probably I need to retest with trunk instead of 2.90.1, right?

Yes please.

**Comment by laurynas-biveinis** [comment] 2020-06-30 14:40
@tarsius, with 20200627.806 I have narrowed it down to `magit-setup-buffer-in-internal`: upon entry, `default-directoryz has the TRAMP prefix, and in the first `with-current-buffer` form it is stripped. The `unless buffer` above it is not executed, so a buffer with stripped `default-directory` must be coming from `(magit-get-mode-buffer mode value)`, but my elisp is lacking to make fast progress there.

**Comment by laurynas-biveinis** [comment] 2020-07-01 13:57
@tarsius debugged it! The missing link in failed repro attempts was that the commit attempt should happen in a worktree. Then, `wtree` in `magit-toplevel` will be resolved remotely and returned without the needed TRAMP prefix.

My fix attempt looks like
```diff
diff --git a/emacs/emacs/elpa/magit-20200627.806/magit-git.el b/emacs/emacs/elpa/magit-20200627.806/magit-git.el
index 6ee11b11..a62f3078 100644
--- a/emacs/emacs/elpa/magit-20200627.806/magit-git.el
+++ b/emacs/emacs/elpa/magit-20200627.806/magit-git.el
@@ -719,7 +719,8 @@ returning the truename."
                      ;; Git bug.  See #2364.
                      (not (equal wtree ".git")))
                 ;; Return the linked working tree.
-                (file-name-directory wtree))
+                (concat (file-remote-p default-directory)
+                        (file-name-directory wtree)))
                ;; The working directory may not be the parent directory of
                ;; .git if it was set up with `git init --separate-git-dir'.
                ;; See #2955.
```

**Comment by tarsius** [comment] 2020-07-02 15:15
Thanks! I've pushed the fix.

**Closed** 2020-07-02 15:15 UTC
Labels: unconfirmed
