### ISSUE TITLE
Speedup log --graph by not using nested repetition in regex

### ISSUE THREAD

**Issue by steabert** [magit/magit#1945] opened 2015-07-02 12:19 UTC
I recently swithed from magit 1.4.2 to magit 2.1.0.

When i show a log with "l l" (i.g. magit-log-current), outputting the graph takes forever, I have to kill it with Ctrl-G.
I read about the problems with showing logs with the "--graph" option, but since in version 1.4.2 everything worked fine, could this actually be some kind of regression?

Profiling indicates that code spends all of the time in "magit-log-wash-line", when calling "looking-at". If I disable that part, the log shows immediately with a graph, but obviously not fully washed (colors are there but sha1 hash and co are located after the graph)

**Comment by Silex** [comment] 2015-07-02 12:42
Do you have a public repo on which we can check the issue?

**Comment by steabert** [comment] 2015-07-02 13:15
Unfortunately not (and I don't control it), but looking through my repos I found that the git repo itself has the same problem, so you could test it on the git repository.

A (initial) log with --graph option using magit 1.4.2 takes about 1-2 s for the git repo, with magit 2.1.0 I'm waiting forever.

**Comment by Silex** [comment] 2015-07-02 13:27
You mean doing it on git@github.com:magit/magit.git? It's very snappy by me so obviously there must be some problem with your installation. I suggest you try to reinstall magit (and all the dependencies), and possibly test with emacs -Q to ensure the problem is not with your other configs.

**Comment by tarsius** [comment] 2015-07-02 13:54
I think he meant git's git repository.

My guess would have been bad commit metadata that causes the washing to cycle forever. But I expect there are no commits with bad metadata in git's own history.

I have increased the value of `magit-log-cutoff-length` you might want to lower that. But that probably won't help. The higher number might cause a delay, but I it would cause the washing to take forever.

**Comment by Silex** [comment] 2015-07-02 13:58
> I think he meant git's git repository.

Oh, ok I just tried and I can confirm it's very slow. The funny thing is that `l a` is fast because there's less graphs on the active branches.

**Comment by steabert** [comment] 2015-07-02 14:48
Sorry for any confusion, I meant indeed the https://github.com/git/git repository.
If I lower the `magit-log-cutoff-length` back to 100, magit 2.1.0 doesn't get stuck.

**Comment by tarsius** [comment] 2015-07-02 14:54
> magit 2.1.0 doesn't get stuck

I wonder what's at play here. What happens if you `git checkout HEAD~412` and then `l l`?

**Comment by tee3** [comment] 2015-07-02 14:56
Magit from MELPA 20150701.1326
GNU Emacs 24.5.1
OS X 10.10.4

I just tried looking at https://github.com/git/git with the magit-2.1.0 and can also confirm that of `l l` runs for a very long time.  Stopping it via `C-g` shows that the process has been progressing slowly.

The git.git repository does have a lot of merge commits on `origin/master`.  Running `git log --oneline --graph > /tmp/tmp` directly completes in about 1 second.  The output of that might give you an idea of why magit doesn't like that input.  The graph looks the same as the partial one obtained via magit.

**Comment by tee3** [comment] 2015-07-02 15:05
Note that the git.git `origin/master` history is basically a **lot** of long-running branches merged into `origin/master`.

**Comment by steabert** [comment] 2015-07-02 19:52
After some digging, I did the following:

* disable any `ansi-color` stuff in `magit-log.el`
* set `magit-log-cutoff-length` to `99999` (my entire history is only ~9000 lines)
* enable profiling for the `magit` package and for the `looking-at` function
* run `magit-current-log`
* press Ctrl-G after a while

it shows almost all time (~8s) spent inside `magit-log-wash-line` (202 calls), and all of it is spent inside `looking-at` (646 calls).

Knowing that git gives me the entire log graph immediately, and the magit log buffer has the entire history in it, just not all of it is washed, this looks like it is a problem with regex matching?

**Comment by tarsius** [comment] 2015-07-02 20:17
That's likely yes. The regex is in `magit-log-oneline-re`.

I intend to improve this and other regexp by using non-printing characters as separators. Currently printing characters are used and then the regexp got complicated over time to avoid matching to much, i guess. Or maybe it's just the graph part of the regexp which performs horribly.

**Comment by steabert** [comment] 2015-07-02 20:19
After reading this: https://lists.gnu.org/archive/html/emacs-devel/2006-05/msg00937.html, it seems that the problem lies in the regex that is trying to match the graph part of the line, and it gets much slower as that part gets longer. I played around with `magit-log-oneline-re` to see if I could simplify the regex match, and with a simpler regular expression I can now display the entire 9000~ line graph log in ~4s. I haven't tried yet to turn color back on.

**Comment by tarsius** [comment] 2015-07-02 20:23
> I haven't tried yet to turn color back on.

I don't expect that this would make a difference.

You should also look at past changes to the regexp to avoid regressions.

**Comment by steabert** [comment] 2015-07-02 20:24
Well, I tested now with `ansi-color` back on, and it takes ~30s for the complete 9000-line log graph. Maybe this is due to the different coloring of each line in the graph?

**Comment by tarsius** [comment] 2015-07-02 20:35
I don't quite understand. Previously aborted - so of course it took less time then. Or am I missing something?

The `ansi-color`ing and Magit's own washing are separate. But of course the `ansi-color`ing also has to find matches and that probably also takes a long time. So yes that might have to take some of the blame (and it might be a good idea to add an option to allow disabling colorful graphs).

**Comment by tarsius** [comment] 2015-07-02 20:39
```
Switches
 -g Show graph [slow] (--graph)
 -G ... in color [slower] (--color)
```

But note that I am considering moving away from Git's `--graph` completely. See #1425.

**Comment by steabert** [comment] 2015-07-02 20:46
With the current regex, i have to abort because it slows down so much it hasn't done much even after minutes. So, initially I always aborted when doing the profiling. With the replaced regex, I don't need to abort, but it still takes ~30s for the entire history with ansi-color, and ~4s for the entire history without ansi-color.

**Comment by tarsius** [comment] 2015-07-02 20:49
Aha! :-)

Well, that gives us something to work with. Good job! By the way, could you please post that magical regexp? :-D

**Comment by steabert** [comment] 2015-07-02 21:02
Sure, I forked the repo and committed my change, but I still need to test it more. There is nothing 'magical' about it I'm afraid :-D
Just followed RMS instructions about avoiding nested repetitions: https://lists.gnu.org/archive/html/emacs-devel/2006-05/msg00959.html and http://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html#Regexp-Special

**Comment by tarsius** [comment] 2015-07-06 11:22
Nothing to see here, move along to #1984 :-)

**Closed by tarsius** 2015-07-06 11:22 UTC
