### ISSUE TITLE
Git shell command completion in git command.

### ISSUE THREAD

**Issue by thierryvolpiatto** [magit/magit#3004] opened 2017-02-26 08:15 UTC
Would be great to have git shell command completion in `magit-git-command`.
One way to achieve this is using `read-shell-command` in `magit-read-shell-command` with bash-completion package installed (works fine here), but perhaps you have a better idea or something is already existing ?

```elisp
(defun magit-read-shell-command (prompt &optional root)
  (let ((dir (if (or root current-prefix-arg)
                 (or (magit-toplevel)
                     (user-error "Not inside a Git repository"))
               default-directory)))
    (list
     (replace-regexp-in-string
      "\\`git " ""
      (read-shell-command
       (format (concat prompt ": ") (abbreviate-file-name dir))
       "git " 'magit-git-command-history))
     dir)))
```

Thanks.

**Comment by tarsius** [comment] 2017-02-26 10:29
I have to admit, I never use this or related commands, exactly because they don't offer any completion yet. But I had the intention to look into this for a while now.

I've tried out our change and installed `bash-completion`, and these seems to work very well. But I'll have to look into this a bit more before applying it. Some things we have to look into:

- Do we still need the `eshell-parse-arguments`?
- Also, it always felt weird that we are using something from `eshell` here, isn't there something equivalent that isn't intended for `eshell`?
- We could remove the git-specific variants and just keep `magit-shell-command{,-topdir}` . Those commands could then insert the "git " initial input, and users who want to run another command could just delete that.
- Since this does depend on a third-party package, we will have to communicate to users that they might want to install that.
- Or should we simply depend on it? Most likely not.
- Alternatives to `bash-completion.el` exist, e.g. [`pcmpl-git`](https://github.com/leoliu/pcmpl-git-el).
- There's even a package whose sole purpose is to read git commands in the minibuffer: [`git-command`](https://github.com/10sr/git-command-el). Unfortunately it doesn't send output to the magit process buffer  though.

So I do think the change you are proposing is a big step in the right decision, but suspect that we will go with another approach eventually.

I would apply your change anyway now, if it did not require inserting "git " as user-editable initial input. I actually tend to like that (because as mentioned above that would allow us to turn four commands into two) but this is something that is likely to change again once we settle for another approach.

Could you please look into make it unnecessary to insert "git "?

**Comment by thierryvolpiatto** [comment] 2017-02-26 18:32
Jonas Bernoulli <notifications@github.com> writes:

> I have to admit, I never use this or related commands, exactly because
> they don't offer any completion yet. But I had the intention to look
> into this for a while now.
>
> I've tried out our change and installed bash-completion, and these
> seems to work very well. But I'll have to look into this a bit more
> before applying it. Some things we have to look into:
>
>   * Do we still need the eshell-parse-arguments?
>   * Also, it always felt weird that we are using something from eshell
>   here, isn't there something equivalent that isn't intended for
>   eshell?

For these two I can't answer yet, I didn't look where you use eshell
code in magit, at first I would say that no eshell-parse-arguments is
not needed.

>   * We could remove the git-specific variants and just keep
>     magit-shell-command{,-topdir} . Those commands could then insert
>     the "git " initial input, and users who want to run another
>     command could just delete that.

Not sure to know what are "the git-specific variants" but I would say
yes here.

>   * Since this does depend on a third-party package, we will have to
>   communicate to users that they might want to install that.

Yes.

>   * Or should we simply depend on it? Most likely not.

Agreed, no, anyway it will work as before if bash-completion isn't
installed.

>   * Alternatives to bash-completion.el exist, e.g. pcmpl-git.
>   * There's even a package whose sole purpose is to read git commands
>     in the minibuffer: git-command. Unfortunately it doesn't send
>     output to the magit process buffer though.
>
> So I do think the change you are proposing is a big step in the right
> decision, but suspect that we will go with another approach
> eventually.

No doubt of that, I just did a quick first shot to provide completion
where I needed.

> I would apply your change anyway now, if it did not require inserting
> "git " as user-editable initial input. I actually tend to like that
> (because as mentioned above that would allow us to turn four commands
> into two) but this is something that is likely to change again once we
> settle for another approach.

I like having "git " as initial input, as I often found myself writing
"git <some command>" instead of "<some command>" and failed miserably,
but it is maybe I am not use to write just directly the command, perhaps
once used to this it is a win ?

> Could you please look into make it unnecessary to insert "git "?

Yes, I will look at this ASAP, for now I don't know where the addition
of "git" to the command line happen.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2017-03-04 15:22
The PR #3004 is fixing this issue, after one week of use I am quite happy with this.

After having tried both pcmpl-git.el and bash-completion.el, I am still prefering bash-completion.el.

- pcmpl-git: 
Pros: Works also with eshell, pcomplete seems more flexible and faster.
Cons: Actually fails to complete subcommands e.g git remote ?
- bash-completion:
Pros: Complete everything.
Cons: Don't work with Eshell, slower (but this is hardly sensible).

**Comment by tarsius** [comment] 2017-04-02 18:16
I am closing this as a duplicate of #2951.

**Comment by tarsius** [comment] 2017-04-02 19:32
Closing in favor of #2951.

**Closed by tarsius** 2017-04-02 19:32 UTC
Labels: feature request
