### ISSUE TITLE
Wrapped magit-commit doesn't show diff

### ISSUE THREAD

**Issue by justmytwospence** [magit/magit#2471] opened 2016-01-09 06:56 UTC
Calling `magit-commit` programmatically doesn't seem to respect `magit-commit-show-diff`. I noticed this while trying to write a hydra that includes the `magit-commit` command, but I can also replicate it simply by comparing the results of `M-x magit-commit` and `M-: magit-commit`. Is this a bug or am I simply daft?

**Comment by tarsius** [comment] 2016-01-09 11:56
No, you're not daft. I had to grep around for various minutes until I found the relevant code - and I wrote it. Here it is:

```lisp
(defun magit-commit-diff ()
  (--when-let (and git-commit-mode
                   magit-commit-show-diff
                   (pcase last-command
                     (`magit-commit
                      (apply-partially 'magit-diff-staged nil))
                     (`magit-commit-amend  'magit-diff-while-amending)
                     (`magit-commit-reword 'magit-diff-while-amending)))
    (let ((magit-inhibit-save-previous-winconf 'unset)
          (magit-display-buffer-noselect t))
      (funcall it (car (magit-diff-arguments))))))

(add-hook 'server-switch-hook 'magit-commit-diff)

(add-to-list 'with-editor-server-window-alist
             (cons git-commit-filename-regexp 'switch-to-buffer))
```

The problem is that the diff is only shown if the `last-command` is one of three hard-coded commit commands.

You might by able to work around the issue by explicitly setting `this-command` (not `last-command`) to the appropriate command in your wrapper command, i.e. to the command you are wrapping. Alternatively using `call-interactively` to call the wrapped command should also work.

----

You're probably wondering why, for example, `magit-diff-staged` isn't called directly inside `magit-commit`.

Answer part 1 (why): The diff buffer has to be displayed in a window *after* the commit buffer. Because otherwise closing the diff (using e.g. `q`) would close the commit window too. That is so because, by default, closing a magit buffer restores the window configuration that was current right before the window was created.

Answer part 2 (how): The commit commands do not display the commit message buffer themselves. Instead they trigger the eventual creation of that buffer by calling `git commit` without providing a commit message. Git then uses the `$GIT_EDITOR` to have the user provide the message. That variable was previously set to a value which cases it to call back to the current emacs instance, in most cases using `emacsclient` with the appropriate arguments.

The emacs server then creates the buffer by visiting the respective file and displays it according option `server-window`. (Actually this is a bit more complicated in our case: we override the potentially customized value of that option by advising `server-switch-buffer` and instead using the entry that we added to `with-editor-server-window-alist`  (see code above).)

Only now that the commit message buffer is being displayed in some window, can we display the diff buffer in some other window (see "why"). The commit buffer was displayed by `server-switch-buffer` which finishes by calling `server-switch-hook`. `magit-commit-diff` is on that hook (see code above) but it is called whenever the `emacsclient` is used for whatever reason. So this function has to make sure it only does anything when appropriate. It does that by checking whether `last-command` is one of the known commit commands.

**Comment by tarsius** [comment] 2016-01-09 14:08
Let me know whether that helped.

**Closed by tarsius** 2016-01-09 14:08 UTC
Labels: support

**Comment by justmytwospence** [comment] 2016-01-09 19:09
Thanks for the thorough explanation. Setting `this-command` worked (`call-interactively` didn't).

**Comment by ccqpein** [comment] 2018-11-14 01:18
I find a familiar problem and find this issue by Google. Sometimes git commit in shell (throw to emacsclient) does not show `magit-commit-show-diff`, I manually open `magit-commit-show-diff` once, then everything is fine now.
