### ISSUE TITLE
magit-insert-remote-branches: Assertion failed: (equal branch (concat remote "/HEAD"))

### ISSUE THREAD

**Issue by michalrus** [magit/magit#4994] opened 2023-08-28 17:11 UTC
`(magit-show-refs)` used to work for me, but I was using a very old version then. Recently, I updated, and I'm now seeing this error often (in all repositories):

```
magit-insert-remote-branches: Assertion failed: (equal branch (concat remote "/HEAD"))
```

A little look at the source code shows that Magit is calling this:

```
git for-each-ref --format='%(symref:short)%00%(refname:short)%00%(refname)%00%(subject)' refs/remotes/origin
```

When I run it in one of the repos (changing `\0` to `\t` and aligning columns), I’m getting:

```
origin/master	origin		refs/remotes/origin/HEAD	Make the adding of another frame instantaneous
		origin/macbook	refs/remotes/origin/macbook	Temporarily comment out IINA.app
		origin/master	refs/remotes/origin/master	Make the adding of another frame instantaneous
```

So you can see that when the first field (`head-branch` ) is set, the 2nd field (`branch`) is just `origin`, while Magit expects `origin/HEAD` then ([source](https://github.com/magit/magit/blob/97a95f70079b6613bf98d2306279d3e03fe51234/lisp/magit-refs.el#L574-L576)):

```elisp
            (if head-branch
                (progn (cl-assert (equal branch (concat remote "/HEAD")))
                       (setq head head-branch))
```

Is my `git` of a wrong version? I didn’t find any recommendations. It is:

```
❯ git --version
git version 2.40.1
```

## Context

Magit version: 97a95f70079b6613bf98d2306279d3e03fe51234.

Backtrace:

```
Debugger entered--Lisp error: (cl-assertion-failed ((equal branch (concat remote "/HEAD")) nil))
  cl--assertion-failed((equal branch (concat remote "/HEAD")))
  magit-insert-remote-branches()
  magit-run-section-hook(magit-refs-sections-hook)
  magit-refs-refresh-buffer()
  magit-refresh-buffer()
  magit-setup-buffer-internal(magit-refs-mode nil ((magit-buffer-upstream "HEAD") (magit-buffer-arguments nil)))
  magit-refs-setup-buffer("HEAD" nil)
  magit-show-refs(nil)
  funcall-interactively(magit-show-refs nil)
  command-execute(magit-show-refs)
```

**Comment by tarsius** [comment] 2023-08-28 19:18
Update Magit to get this updated code:

```elisp
            (if head-branch
                ;; Note: Use `ref' instead of `branch' for the check
                ;; below because 'refname:short' shortens the remote
                ;; HEAD to '<remote>' instead of '<remote>/HEAD' as of
                ;; Git v2.40.0.
                (progn (cl-assert
                        (equal ref (concat "refs/remotes/" remote "/HEAD")))
                       (setq head head-branch))
```

Duplicate of #4903.

**Closed by tarsius** 2023-08-28 19:18 UTC
Labels: obsolete

**Comment by michalrus** [comment] 2023-08-28 20:20
Oops, sorry for not being perceptive enough, and thank you :bow:
